explosion/spaCy

docs/source/index.rst

* Added missing cosine declaration to code listing that already included
imports for `dot` and `norm` function it uses.
Signed-off-by: mr.Shu <mr@shu.io>
----------------------------------------------------
@honnibal Thanks a ton for a great library! 
While reading the index document I kind of skipped the previous declarations of `cosine`. It seemed strange not to find them here since the imports were already in place.

docs: Added missing cosine declaration

---

docs/source/index.rst

It was previously commented out because it wasn't below the `..table` directive.  I'm not sure if this was intentional, but the text "The table above" was very confusing without the table.

Make the accuracy table show up

---

tests/test_tokenizer.py

This tests for what I assume is the correct behaviour for empty strings. Related to Issue #19

Add rokenizer test for zero length string

---

contributors/vsolovyov.md
setup.py

`c_ext()` incorrectly passed `compile_args` twice, both to `extra_compile_args` and to `extra_link_args`. This pull request fixes that.

Correctly pass link_args in c_ext() in setup.py

---

contributors/chrisdubois.md
spacy/matcher.pyx

Each pattern object currently contains two AttrValues rather than just one.
Found this while using spacy in a setting that uses tcmalloc, then building/running with sanitize flags.
No unit tests are included, unfortunately.

Fix size of allocation when creating a pattern

---

bin/init_model.py
bin/ner_tag.py
bin/parser/train.py
bin/prepare_treebank.py
spacy/en/lemmatizer.py
spacy/gold.pyx
spacy/strings.pyx
spacy/util.py
spacy/vocab.pyx
tests/test_parse_navigate.py

@honnibal I am looking for `goodfirstbug` to fix in spaCy as I am picking cython and reading Kurt Smith's book. I caught the deprecated `codecs.open` from the .py code. But if there are any other `goodfirstbug` to fix, esp. from the .pyx code, I will be glad to help out.
P/S: Also, it's great to see that @nltk is replacing the outdated maxent tagger with your perceptron tagger.

Changing deprecated codecs.open to io.open

---

spacy/tokens/doc.pyx
spacy/tokens/spans.pyx
spacy/tokens/token.pyx

Not sure this is a feature everyone needs - I usually play around a lot in ipython when working with a new library, so I made these simple changes clearly for fast visualization purposes based on what str and unicode returned for each of the text representation classes. Text just seems like a reasonable default - it's better than printing an id string for the class.
Example usage from within ipython
```python
>> from spacy.en import English
>> nlp = English()
>> doc = nlp(u'Craig Robinson was denied a sentence. '
'At least so it seemed until Lara Croft came along')
>> doc[0]
Craig
>> doc[0:5]
Craig Robinson was denied a
>> doc.ents
(Craig Robinson, Lara Croft)
>> for sent in doc.sents:
>>     print(sent)
Craig Robinson was denied a sentence.
At least so it seemed until Lara Croft came …
```

add __repr__  print text default for doc, token, and span

---

website/src/jade/home/_installation.jade

Hi all,
I was just doing a clean install of spaCy via pip on a linux VM as well as on my local system, and in both cases, I found that the pip command would install some of the downloads right off the bat.  As a result, I kept getting an error saying the data was already installed when I ran 'python -m spacy.en.download all'!
To fix this for future installs, I went ahead and updated the website tutorial to default to the --force command, which will download everything right off the bat.  Hope this helps!  Spacy is great!
-Kevin Meurer

Add force flag to installation page.

---

spacy/tests/serialize/test_io.py
spacy/tests/website/test_api.py
spacy/tests/website/test_home.py

need a better solution for cleaning up after ```test_efficient_binary_serialization()```, but at least tests pass. See build error here: https://ci.spacy.io/builders/win64-0/builds/28/steps/shell_1/logs/stdio

avoid writing to /tmp (not cross-platform compatible)

---

.appveyor.yml
.travis.yml
MANIFEST.in
README-MSVC.txt
build.py
pip-clear.py
requirements.txt
setup.py
spacy/en/download.py
venv.ps1
venv.sh

This PR aims to fix the headers_workaround kludge:
- setup.py now follows closely numpy/scipy setup (should work with distutils and setuptools)
- setup.py doesn't import cython anymore (see bin/cythonize.py)
- headers for native dependencies (numpy, murmurhash) are now shipped as fallback
- add build.sh and tox for CI
- adds versioning mechanism (from numpy/scipy)
Building spaCy is now more clearly separated between 1) creating an sdist including cythonizing the source (typically performed by the maintainer) and 2) building/compiling the package (typically performed by the user).
Headers from numpy and murmurhash (copied from sdist build-time environment) are now shipped in the sdist (see package ./include dir) and used during installation in case they couldn't be found on the system. …

replace headers_workaround

---

package.json
requirements.txt
setup.py
spacy/en/download.py
spacy/language.py
spacy/lemmatizer.py
spacy/matcher.pyx
spacy/tagger.pyx
spacy/tests/tagger/test_lemmatizer.py
spacy/tokenizer.pyx
spacy/util.py
spacy/vocab.pyx

Sputnik now includes a new DirPackage class that offers a Package interface around a model directory. You can now instantiate spaCy as follows:
```
1) default
nlp = spacy.en.English()
2) model directory without dealing with packages (e.g., for development)
nlp = spacy.en.English('my/directory')
nlp = spacy.en.English(data_dir='my/directory')
3) with a different model
nlp = spacy.en.English('fr_default')
4) with a relocated package base
nlp = spacy.en.English(model='en_default', data_dir='new/root')
5) with an existing package
package = sputnik.package(<app_name>, <app_version>, 'my_model >=1.0.0', data_path='packages')
nlp = spacy.en.English(package)
```
Tokenizer/Tagger/Vocab/etc load() accepts string, directory or package
```

integrate with sputnik

---

requirements.txt
setup.py
spacy/__init__.py
spacy/language.py
spacy/util.py
spacy/vocab.pyx

In case vec.bin is independent of the rest of the models we can simply distribute alternate vec.bin as independent packages. I quickly wired up some code how this could look like, use cases:
1) you only install the "en" package, you'll get the default vec.bin that's included
2) you want to change to alternative vectors (e.g., glove), you install the en_glove_vectors package. The included vec.bin has precedence over the default one shipped via en package.
Now, I haven't fully understood if sth. in vec.bin depends on anything else in spaCy or its models in which case this of course wouldn't work.
Also, don't judge the idea by the API design, I didn't give much thought on this.

initial proposal for ability to switch vectors

---

spacy/syntax/nonproj.pyx
spacy/tests/tokens/test_token_api.py
spacy/tokens/token.pxd
spacy/tokens/token.pyx

change PseudoProjectivity.deprojectivize to use these functions
previously, the deprojectivization was using Doc.from_array to change the head of tokens.
Doc.from_array calls set_children_from_head() which introduces sentence boundaries.
however, this function assumes projective trees which is not true anymore, so it was introducing
incorrect sentence boundaries.
Token.head and Token.dep (and Token.dep_) can now be set from the outside.
deprojectivize doesn't call from_array anymore. from_array is still unsafe if the tree is non-projective.

add function to Token for setting head and dep (and dep_) 

---

spacy/strings.pxd
spacy/strings.pyx

This should generally speed up the `StringStore` class, both for loading and for general usage. It does not change anything about the strings file format, nor does it remove the load/store via JSON.

remove internal redundancy and overhead from StringStore

---

setup.py

Enable OpenMP compiler option for MSVC to support Multi-Threading for nlp.pipe(). Without this option multi-threading done in pipe() method will not work on Windows. MSVC [supports](https://msdn.microsoft.com/en-us/library/fw509c3b.aspx) OpenMP 2.0 which will be enabled by passing this argument to the compiler.

Enable OpenMP compiler option for MSVC

---

spacy/syntax/arc_eager.pyx
spacy/tests/parser/test_parse.py
spacy/tests/parser/test_sbd.py

added the one line that @honnibal suggested to fix issue #322

introduce sentence boundaries for additional root tokens

---

spacy/util.py

We want the get_lang_class to return "en" for both "en" and "en_glove_cc_300_1m_vectors". Changed the split rule to "_" so that this happens. See https://github.com/spacy-io/spaCy/issues/338 for details

Fix get_lang_class parsing

---

spacy/util.py

This is the proper fix for get_lang_class parsing. Previous PR: https://github.com/spacy-io/spaCy/pull/384
Value for `lang` given `en>=1.1.0,<1.2.0`: `en`
Value for `lang` given `en_glove_cc_300_1m_vectors`: `en`
Output from `python -m pytest spacy`: `187 passed, 98 skipped, 5 xfailed, 2 xpassed in 253.32 seconds`

Fix get_lang_class parsing (take 2)

---

spacy/download.py

This very simple PR encompasses the following proposal:
When trying to download data models that already exist locally, the exit code should not be 1 ('error').
This is more inline with other packages which support post-install data download steps, such as NLTK.
This issue came up for me when trying to use spaCy in a production environment: using AWS CodeDeploy with a AfterInstall application lifecycle hook that calls 'python -m spacy.en.download' as part of deployment should succeed the first time, and on subsequent deployments it would be ideal if it would just be a 'no-op' (e.g behave in a more idempotent manner, which is friendlier towards automation generally speaking)

Exit code 0 for when downloading a model that already was downloaded

---

spacy/download.py

Add parameter to download() for application to not exit if a Model exists. The default behavior is unchanged.

Add parameter to download()

---

README.rst

Out of curiosity, I wonder if there's any sort of preferred grammar for alt text when it comes to accessibility.
Like, would someone using a screen reader prefer "Our Gitter chat room" or "Click here for our Gitter" over "spaCy on Gitter"?
Just a random thought.
Possibly fixes #487 (though may make sense to open a separate issue for connecting Gitter to Slack/IRC, if so)

Added Gitter badge, alt text for all badges to README.rst

---

examples/training/train_ner.py

While trying out the save functionality of `train_ner.py` in the `examples` folder, it had some runtime errors. Just thought I'd fix those typos to aid anyone trying out the examples.

Fixed train_ner examples when model_dir isn't None

---

examples/training/train_parser.py

So after pushing #538 I went around playing with trainer_parser.py, which had the same problem. Thought I'd make a pull request to fix it as well.

Fixed train_parser examples when model_dir isn't None

---

README.rst

The ReadMe currently says that Windows Spacy Users should install a full Visual Studio version in order to compile Spacy. Some might prefer to only install the compiler provided by Microsoft (or MinGW if this is confirmed to work?). I added a link to the Wiki that points to the various Microsoft downloads, as these are quite difficult to find otherwise.

Add Windows Compiler installation instructions

---

examples/training/train_ner.py
examples/training/train_parser.py

On spaCy v1.1.2 the `vector` parameter is changed to `add_vector`. I've updated the examples to reflect spaCy v1.1.2.
[x] - `vectors` -> `add_vectors`

updated training examples to v1.1.2

---

examples/training/train_ner.py
examples/training/train_tagger.py

Since v1.1.2, `nlp.tagger` will return `NoneType` if the data directory is not found. This breaks the example file and I've made a change so that `nlp.tagger` will contain the feature_templates from `Tagger` if data directory is not found, should be helpful for people who are just starting out.
I finally for to play around with `train_tagger.py` but was greeted with the following message:
```python
File "train_tagger.py", line 74, in <module>
plac.call(main)
File "/home/kendricktan/.virtualenvs/laice/lib/python3.5/site-packages/plac_core.py", line 328, in call
cmd, result = parser.consume(arglist)
File "/home/kendricktan/.virtualenvs/laice/lib/python3.5/site-packages/plac_core.py", line 207, in consume
return cmd, self.func(*(args + varargs + extraopts), **kwargs)
File "train_tagger.py", …
```

Fixed training examples

---

spacy/matcher.pyx
spacy/tests/test_matcher.py

https://github.com/explosion/spaCy/issues/613
PhraseMatcher wasn't tested at all, I've added a basic test for it.
P.S. Would be cool to have `test` script using makefile or something to easily run them. I had to look into travis scripts to learn how to do it.

Fix PhraseMatcher to work with new Matcher

---

website/docs/usage/rule-based-matching.jade

There are two missing brackets on the `add_pattern` lines. I also suggest you include the `from spacy.tokens.doc import Doc` statement to make it easy for people to copy paste a working example.

Added missing brackets & suggested import statmnt

---

examples/keras_parikh_entailment/keras_decomposable_attention.py

- I removed the theano dependency by using keras backend functions 
- The tests methods failed because in settings we didn't specify the 'gru_encode' param - fixed it
- this will allow us to use the model with tensorflow instead of theano only.
I ran the tests, all passing.
- [x ] Bug fix (non-breaking change fixing an issue)
- [ x] New feature (non-breaking change adding functionality to spaCy)
- [x ] My code follows spaCy's code style.
- [ x] All new and existing tests passed.

Remove theano dependency from parikh model + small bug fix

---

spacy/tagger.pyx

I found this bug when I tried to run `examples/training/train_tagger.py`. I got exceptions like this:
```
File "../train_tagger.py", line 78, in <module>
plac.call(main)
File "/usr/local/lib/python3.5/site-packages/plac_core.py", line 326, in call
cmd, result = parser_from(obj).consume(arglist)
File "/usr/local/lib/python3.5/site-packages/plac_core.py", line 209, in consume
return cmd, self.func(*(args + varargs + extraopts), **kwargs)
File "../train_tagger.py", line 64, in main
tagger.update(doc, gold)
File "spacy/tagger.pyx", line 255, in spacy.tagger.Tagger.update (spacy/tagger.cpp:6857)
self.vocab.morphology.assign_tag(&tokens.c[i], eg.guess)
File "spacy/morphology.pyx", line 42, in spacy.morphology.Morphology.assign_tag (spacy/morphology.cpp:3995) …
```

Fixed bug: eg.guess is a tag id, rather than a tag

---

website/docs/usage/rule-based-matching.jade

I've added an import statement at the top of the `Matcher` example.
First-time users and lazy people like me don't know how to import it. The `spacy.matcher` package is not listed in the autocomplete of PyCharm (not sure about other IDEs), so one either has to remember or look it up in the code or other examples.

Missing import statement for spacy.matcher.Matcher

---

website/docs/usage/dependency-parse.jade

Small typo in dependency parser workflow guide

[DOCS] Typo

---

.gitignore

I noticed this had been generated for me after installing from the local repo with pip using `sudo pip3 install -e .` from within the spaCy folder. I figure it should be ignored.

Add cythonize.json to .gitignore

---

spacy/de/language_data.py

Add a list of stopwords for  German Language.
Fixes Issue #364

Add German Stopwords

---

website/docs/api/doc.jade
website/docs/api/span.jade
website/docs/api/vocab.jade
website/docs/usage/processing-text.jade

Having never touched Jade before, I ran into this annoying syntax trap while writing https://github.com/explosion/spaCy/pull/642/commits/a0c4b29dcbacfa784e7522653e18ca6c78084419 and immediately wondered if there was anywhere in the existing codebase where it had already been screwed up. Sure enough, a regex search in Sublime for `\| [^ ]` turned up these 4 locations, all of which are currently rendered with a missing space on the website (although it's not too noticeable in the cases where there's a code block on either side of a comma).

Fix a bunch of missing spaces of the website

---

.gitignore

Previously only some of its content was ignored, so running `python -m spacy.en.download all` after installing from a local repo would create unstaged changes.

Ignore entire data folder

---

website/docs/usage/index.jade
website/docs/usage/processing-text.jade

There is a typo in the Getting Started guide; this PR fixes it.
This change is required because there is a typo in the Getting Started guide. The problem it solves is that typo.
This change has not been tested, but it is hard to see how adding a single letter to the docs could cause problems!
- [x ] My code follows spaCy's code style.

docs: fix "installaton" typo

---

README.rst
spacy/de/download.py
spacy/download.py
spacy/en/download.py
spacy/language.py
website/docs/usage/index.jade

Adds a `--data-path` (or `-d`) argument to the download.py scripts that lets the path to download to be specified.
Makes downloading to a custom location easier; resolves https://github.com/explosion/spaCy/issues/637
Manually. After `pip install -e .`, I did a `git clean -xdf` to clean my local repo, then, in sequence:
- Checked that 
```
import spacy
spacy.load('en')('Hello, world')[0].pos_
```
gives the empty string
- Ran `python3 -m spacy.en.download all -d ~/some_dir`
- Checked that `spacy.load('en')('Hello, world')[0].pos_` still gave the empty string but that `spacy.util.set_data_path('/home/mark/some_dir'); spacy.load('en')('Hello, world')[0].pos_` didn't.
- Ran `python3 -m spacy.en.download all`
- Checked that `spacy.load('en')('Hello, world')[0].pos_` no longer gave the empty …

Let --data-path be specified when running download.py scripts

---

spacy/syntax/iterators.pyx
spacy/tokens/doc.pyx
spacy/tokens/span.pyx

Add noun_chunks to Span
Support iterating noun_chunks of a Span.  Also add `doc` attribute to `Doc`class for uniformity.  Wasn't sure the best way to remove code duplication between `noun_chunks` in `Doc` and `noun_chunks` in `Span`.
Useful to be able to find noun_chunks in a span, rather than the whole doc.  Eg all noun_chunks in a sentence.

Add noun_chunks to Span

---

website/docs/usage/data-model.jade

The word `motto` was missing the second `t`.
Minor typo in the documentation site.
N/A

Fixed minor typo

---

spacy/symbols.pyx

Reverts explosion/spaCy#676
This patch needs to add the `acl` symbol to the actual `enum`, in the `symbols.pxd` file. Unfortunately, there's an unfortunate problem at the moment.
I made the questionable decision of adding all of these symbols to the `StringStore`, so that when you do `nlp.vocab["NOUN"]` you get back the same integer symbol as `spacy.symbols.NOUN`. That's nice, but the problem is I added these at the *start* of the string table. This means that if we add anything to the symbols list, all of the other strings get pushed back! This means all of the models have to be retrained.
Version 2 will fix this by adding these special symbols towards the *end* of the strings table. Until then we have to just log the changes, because I don't want to make master incompatible with the …

Revert "Add acl to symbols.pyx"

---

examples/training/train_ner.py
examples/training/train_tagger.py

* Add new words to vocab, when training NER model.
* Save vocab when saving NER model.
* Separate save_model method.
* Add load_ner example.
* Nit in train_tagger.
From: https://github.com/explosion/spaCy/issues/664
Tested manually.

train_ner should save vocab; add load_ner example

---

spacy/language_data/tag_map.py

Add PART tag in the UD tag set to the tag set mapping, as it is missing.
Add PART to UD tag set mapping.
16 of the 17 tags in UD tag set are in the mapping; PART is missing.
No tests run.
- [x ] Bug fix (non-breaking change fixing an issue)
- [x ] My code follows spaCy's code style.

Add PART to tag map

---

website/docs/api/doc.jade

Correct the typo "chldren" in doc.jade.
Added an "i" between "h" and "l" in the two instances of this typo
This change improves the documentation's spelling.
I have checked that this is the correct dictionary spelling for the plural form of "child" by referencing the Oxford English Dictionary.
I have neither run nor written any tests.
This change does not affect any code.
- [ x] Documentation (Addition to documentation of spaCy)
- [x ] My change requires a change to spaCy's documentation.
- [x ] I have updated the documentation accordingly.

Correct typo "chldren" in doc.jade

---

website/docs/usage/customizing-tokenizer.jade

- Fix mismatched quotations
- Make it more clear where `ORTH`, `LEMMA`, and `POS` symbols come from
- Make strings consistent (unicode strings)
- Fix lemma_ assertion s/`-PRON-`/`me`/
I ran `harp server` to ensure that the changes appeared correctly and the templates were rendering correctly.

Fix Custom Tokenizer docs

---

website/docs/api/span.jade

Fix the typo in the `start_char` description of the span API in the documentation.
It explains the `end` of the span as the `start_char` description.
This commit fixed this description to the `end` of the span.
This pull request contains a typo fix in the documentation only.

Documentation Typo Fix: start_char description in the span API

---

spacy/tokenizer.pyx

Allow zero-width 'infix' token during the tokenization process, as discussed in #768.

Allow zero-width 'infix' token

---

requirements.txt
setup.py

The required version was specified for plac in requirements.txt but not in setup.py, which could cause a conflicting version error (see issue #771). Similarly, set the version of ujson in requirements.txt to be the same as in setup.py

Specify version number for ujson and plac

---

spacy/sv/language_data.py
spacy/sv/tokenizer_exceptions.py
spacy/tests/conftest.py
spacy/tests/regression/test_issue805.py

Aims to fix issue #805 by importing the Swedish-specific `ORTH_ONLY` and `TOKENIZER_EXCEPTIONS`-exceptions in the `language_data.py`-file. This requires for the `s.`-exception to be removed from the Swedish-specific exceptions to not conflict with global abbreviations.

Fix issue #805

---

website/docs/usage/rule-based-matching.jade

LOWER and IS_PUNCT are members of `spacy` and not of the `Matcher` class.

Fix error in matching documentation

---

website/assets/js/main.js

When browsing the website in Firefox, the header navbar (which disappears when scrolling down) keeps reappearing every time you stop scrolling down. The `scroll` event seems to fire a bit more than on Chrome, leading `scrollUp` to go back to `true` when scrolling ends, when in fact we're not moving any more.
This change just keeps the latest `scrollUp` value if we haven't actually moved.
No tests needed, no documentation change, so the checklist is empty.

Make the website nav header's hysteresis a bit more robust

---

website/docs/usage/language-processing-pipeline.jade

The cell for the `vocab` parameter is not displayed, making it seem as if the explanation belongs to the previous param.

Fix error in pipeline loading documentation

---

spacy/tests/regression/test_issue834.py
spacy/vocab.pyx

load_vectors should accept arbitrary space characters as word tokens

---

website/docs/api/token.jade

There was a typo in the documentation: the ent_iob value for an ent.iob_ value of 'B' should be 3, not B
Just fixing a typo in the documentation.  It's the least I can do for such an amazing project!

Fix typo in IOB integer to letter map

---

spacy/language_data/tokenizer_exceptions.py
spacy/tests/tokenizer/test_tokenizer.py
spacy/tests/tokenizer/test_urls.py

Changed _URL_PATTERN in language/tokenizer_exceptions.py, using url regex validation pattern from: https://mathiasbynens.be/demo/url-regex
This change will screen out a number of patterns that are not URLs as well as picking up some patterns that were missed.
Test cases were added to test_urls to expose the issue and validate the fix.
- [ x] **Bug fix** (non-breaking change fixing an issue)
- [x ] I have added tests to cover my changes.

Fix for Issue #840 - URL pattern too broad

---

.gitignore
spacy/tests/spans/test_span.py
spacy/tokens/span.pyx

Added lower_ and upper_ properties as described in https://github.com/explosion/spaCy/issues/669.
I also added a generic map function to execute on the string representations of each token in a span.
I added some simple features via very minor additions to `spacy/tokens/span.pyx`, and added corresponding tests to `spacy/tests/spans/test_span.py`.
This is my first commit to a major open-source project - please let me know if I should fix/add anything, and apologies ahead of time in case I somehow break something.
- Eric

Add `lower_` and `upper_` properties and `map` fn to `Span` class

---

spacy/lemmatizer.py
spacy/tests/regression/test_issue781.py

I applied the suggested patch of issue #781 
It's unclear whether the line `forms.extend(exceptions.get(string, []))` is anymore needed (also related to #435). I suggest to remove it. The regression test passes with and without that line. It seems redundant, from my current understanding of the code.

#781 Apply suggested patch -- passing regression test added

---

bin/parser/train_ud.py

I encountered various errors while trying to train the parser for French using train_ud.py script.
- the different columns of the CONLLX file were splitted using split function default separators, instead of tabs. It could lead to an error if one field contains space (for instance the token '100 000'), as the number of field is greater than expected.
- use of the LangGlass defined above instead of the base Language class to instanciate the language.
Without this, I got the following error, due to recent change in Spacy Language class (commit 9605cf39cc1c8119535616ebd1df0d011cb4e9f8):
```
File "train_ud.py", line 139, in <module>
plac.call(main)
File "/home/raphael/.virtualenvs/spacy/lib/python3.5/site-packages/plac_core.py", line 328, in call
cmd, result …
```

Split CONLLX file using tabs and not default split separators

---

spacy/__init__.py

Remove definition of `info` from `__init.py__` as it is imported from `cli` module. Removed function caused `RecursionError: maximum recursion depth exceeded`.

Fix infinite recursion in spacy.info

---

spacy/en/morph_rules.py
spacy/fi/tokenizer_exceptions.py

In en and fi data language files, some dictionary keys were duplicated.

Remove duplicate keys in [en|fi] language data dicts

---

spacy/tests/spans/test_merge.py
spacy/tokens/doc.pyx

Small fix for bug described here: https://github.com/explosion/spaCy/issues/862
Issue #862 is due to (from what I could see so I might be wrong) the label argument passed to doc.merge by span.merge, so I simply included a few lines to keep track of a potential 'label' argument.
I appended some relevant assertions to a spans/test_merge test.
- [x ] **Bug fix** (non-breaking change fixing an issue)
- [x ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

Add option to use label=ent_type in doc.merge arguments (Bug fix for issue #862)

---

spacy/language.py

Small typo in language.py caused new train cli to fail when adding the parser to the pipeline and the PseudoProjectivity.deprojectivize method. 
I did not add any test for this issue, as this is a very minor thing. Anyway, I ran all existing tests and they passed.
Testing environment:
```
* **spaCy version:** 1.7.3
* **Platform:** Darwin-16.4.0-x86_64-i386-64bit
* **Python version:** 3.6.0
* **Installed models:**
```

Fixes typo in method calling Pseudoprojectivity method in create_pipeline method of BaseDefaults class

---

examples/keras_parikh_entailment/README.md
examples/keras_parikh_entailment/__main__.py
examples/keras_parikh_entailment/spacy_hook.py

1. Removed model_dir from [evaluate function](https://github.com/explosion/spaCy/blob/master/examples/keras_parikh_entailment/__main__.py#L55) which is not needed and not used inside function too
2. Set [max_length](https://github.com/explosion/spaCy/blob/master/examples/keras_parikh_entailment/spacy_hook.py#L88) to 100 for evaluate and demo. This bug is specified in this [issue comment](https://github.com/explosion/spaCy/issues/767#issuecomment-278651113)
3. Update command to run train in README. The model_dir was removed on this [commit](https://github.com/explosion/spaCy/commit/c031c677ccfcf0c425c4ad838ddf1f795add9b5d) and that change is not updated in README. This PR fixes it.

Fix keras_parikh_entailment example bugs

---

.github/contributors/dvsrepo.md
spacy/es/__init__.py
spacy/es/language_data.py
spacy/es/tag_map.py
spacy/tests/conftest.py
spacy/tests/es/test_exception.py
spacy/tests/es/test_text.py

This pull request prepares spaCy 1.7.x for training the Spanish models. It adds configuration details, a new tag map extracted from current version of UD_esAncora corpus by combining pos tags and morphology.
Using these changes, we have trained the Spanish models internally, reaching satisfying results:
```Results
TOK                100.00
POS                96.70
UAS                87.34
LAS                83.51
```
In order to replicate this model, the following steps can be performed:
* Run init https://github.com/explosion/spacy-dev-resources/blob/master/training/init.py using word_freqs, brown clusters, and GloVe vectors (we have them internally and willing to share them).
* Using https://github.com/explosion/spacy-dev-resources/pull/11 convert UD_esAncora to JSON train cli format.
* …

Prepare Spanish language for training models, including configuration, rich-UD tag map and tests

---

website/docs/usage/entity-recognition.jade

There is an extra closing brace `)` which is creating error while running example.

Extra brace ")" creating error

---

spacy/cli/package.py

When running `python -m spacy package` the package creation failed with an error in Python 2 environments. It was due to `json.dumps` returns `str` not `unicode`. The fix aims to make the CLI work equally well on both python versions.

Fixed python2 issue with the package command

---

examples/keras_parikh_entailment/keras_decomposable_attention.py

The sentences of test data in sentence entailment example should be generated with integers limited to vocab_size.

Corretions for model test example

---

spacy/cli/model.py

Makes effective pruning out the vocabulary when clusters.vocab is larger than the actual vocabulary by not including unseen words in the vocabulary of freqs_data.

Enable pruning out rare words from clusters data

---

website/docs/usage/customizing-tokenizer.jade

Reverse suffix list in `tokenizer_pseudo_code()` so the order of returned tokens matches input order.
This is pseudo-code, and I'm assuming the tokens in the list have character indices, but still? for readability?
No code effect (pseudo-code in doc).

extend suffixes from first-by-character-order to last

---

website/docs/api/token.jade

token.whitespace now raises an AttributeError

Deleting (legacy?) whitespace attribute in doc

---

spacy/lang/hu/punctuation.py
spacy/tests/lang/hu/test_tokenizer.py

The Hungarian tokenizer was not prepared to handle punctuation spelling mistakes, which is quite often in user generated data. This new commit makes the module more robust, in handling such errors.

More robust Hungarian tokenizer.

---

requirements.txt

There's a frequent issue with `six` that occasionally causes spaCy to fail. The solution was found [here](https://stackoverflow.com/questions/39658404/python-cannot-import-name-viewkeys).

Added html5lib==1.0b8 to requirements.txt

---

spacy/lang/fr/__init__.py
spacy/lang/fr/syntax_iterators.py
spacy/syntax/iterators.pyx

Implements noun chunk iterators for French. It is a slightly modified version of the one for English with UD tags and allowing to have parts of the noun chuck after the root token.

Adds function to extract french noun chunks

---

website/docs/usage/customizing-tokenizer.jade

I encountered a small mistake in the example class WhitespaceTokenizer in the documentation, and fixed it. Literally one letter has been changed.

Fixed a minor typo in the documentation

---

spacy/zh/__init__.py

-remove the empty string return from jieba.cut,this will cause the list of tokens cant be pushed and cause an assert error like this [](https://github.com/explosion/spaCy/issues/1150)
- [x ] **Bug fix** (non-breaking change fixing an issue)

Update zh language error

---

examples/training/train_new_entity_type.py
website/docs/usage/training-ner.jade

This simply fixes the error in the documentation for training a new entity type for the NER. It changes it in both the example code and the website documentation. This is a known error and was acknowledged in [this issue](https://github.com/explosion/spaCy/issues/1140), but was closed without being fixed.
I can see that in the tag `v2.0.0-ALPHA` that it has been fixed for the [website](https://github.com/explosion/spaCy/blob/v2.0.0-alpha/website/docs/usage/training-ner.jade) with a new example, but not in the [training example](https://github.com/explosion/spaCy/blob/v2.0.0-alpha/examples/training/train_new_entity_type.py). Maybe it is on the _TODO_ list, making this PR redundant, but might serve as a reminder.

Fixed error training NER documentation and example

---

spacy/ja/__init__.py
spacy/tests/conftest.py
spacy/tests/ja/test_tokenizer.py

I added a basic test for the Japanese tokenizer. I tried to make it work similarly to other tokenizer tests, which required some changes to the way the base Japanese tokenizer was set up. I think it's an improvement since the tokenizer is re-used instead of being recreated every time now, but since no other language seems to work this way, let me know if something should be different.
(sorry, not clear to me which of these adding tests counts as)

Add basic Japanese Tokenizer Test

---

website/docs/api/doc.jade

Frontend displayed: 
```
If start_idx and do not mark[...]
```
Note the missing "end_idx" after 'and'.
- [x ] **Documentation** (addition to documentation of spaCy)

Missing markup char

---

website/docs/usage/models.jade

In [Models](https://spacy.io/docs/usage/models) documentation, the related url to **custom named entities** is broken:
https://spacy.io/docs/usage/train-ner is a 404.
Changed to https://spacy.io/docs/usage/training-ner

Fix url broken

---

spacy/util.py

Don't rely on recent python features to load models
Fixes Issue #1271
- [x ] **Bug fix** (non-breaking change fixing an issue)

Allow loading with python < 3.6

---

spacy/tests/doc/test_doc_api.py
spacy/tests/spans/test_span.py
spacy/tokens/doc.pyx
spacy/tokens/span.pyx

Added functionality to obtain lowest common ancestor matrix.
This was requested in https://github.com/explosion/spaCy/issues/969. I added functionality for spans and docs to get lowest common ancestor matrix by simply calling: doc.get_lca_matrix() or
doc[:3].get_lca_matrix(). 
Corresponding unit tests were also added under spacy/tests/doc and
spacy/tests/spans. The tests were run and passed in a clean Docker Ubuntu container running Python 3.6.1 and Spacy commit dcff10abe98c844f2f66ff22835c9eb8ea8e7138.

Lowest common ancestor matrix for spans and docs

---

spacy/tests/tokenizer/test_customized_tokenizer.py
spacy/tokenizer.pyx

Added a check to the span sub string before push back to the tokens, to avoid a null sub string which may cause Assertion Error.
Tested on python 2.7 with a Ubuntu16.04.

Fix issue #1292 and add test case for the Assertion Error

---

spacy/syntax/iterators.pyx
spacy/tests/parser/test_noun_chunks.py

Capture more noun chunks, specifically appositional modifiers and indirect objects.
Closes #1226 
I added two tests and ran `py.test spacy/tests/parser/test_noun_chunks.py`. (Please inform me if the new tests would be better to go in a file `test_issue1226.py`)
* Improves performance

Capture more noun chunks

---

website/docs/usage/customizing-tokenizer.jade

Closes #835 by explaining `token_match`. All other questions asked in #835 are already addressed on `master` (though not yet live on the website).
Also, in the `tokenizer_pseudo_code` I put the `special_cases` kwarg
before `find_prefix` because this now matches the order the args
are used in the pseudocode, and it also matches spacy's actual code.

Document Tokenizer(token_match) and clarify tokenizer_pseudo_code

---

.appveyor.yml
spacy/_ml.py
spacy/about.py
spacy/cli/train.py
spacy/language.py
spacy/morphology.pyx
spacy/pipeline.pyx
spacy/syntax/_beam_utils.pyx
spacy/syntax/nn_parser.pxd
spacy/syntax/nn_parser.pyx
spacy/tests/parser/test_neural_parser.py
spacy/tests/serialize/test_serialize_tagger.py
spacy/tokens/doc.pxd
spacy/vocab.pyx
travis.sh

This patch-set makes the models in the default spaCy pipeline independent of each other, removing the shared multi-task CNN. We still want to set a `doc.tensor` attribute, which we could do from combining the tensor assigned by the different models.
There are a few reasons I want to experiment with this. First, the multi-task CNN makes training rather more fiddly, as we have to select an epoch where *all* of the models are doing well. Without the multi-tasking, the parser, NER and tagger could all be trained on different devices, which would also be a nice time-saving.
The more important reason is that the shared CNN has proven to be a serious usability problem. Updating the model becomes very inconvenient, and it's hard to mix-and-match different pipeline components.
I expect the …

Make pipeline components independent

---

spacy/syntax/parser.pyx

Fix for the bug #1174.
Simple fix for the bug #1174 due to JSON keys being loaded from the configuration file as strings instead of integers.

Fixed NER model loading bug

---

website/docs/api/index.jade

Links to SyntaxNet are broken as the models moved to a subdirectory in Google's repo (see their changelog for similar fixes to links)
Changed URLs
N/A

Fixing links to SyntaxNet

---

spacy/lemmatizer.py
spacy/tests/regression/test_issue1387.py
spacy/tests/tagger/test_lemmatizer.py

Fix #1387 in the simplest way: don't apply `rules` if we got a lemma from `exc`eptions.
First commit, e81a608, is the regression test; next, ffb50d2, fixes it; in the third commit I copied the regression test to the tests in `tagger/test_lemmatizer.py` but I'm not sure if that's desirable. I thought it might be nice to have a stub there for other tests of exceptions, but at the moment it's purely redundant.

Lemmatizer obey exceptions

---

spacy/matcher.pyx
spacy/tests/test_matcher.py
website/api/token.jade
website/usage/_linguistic-features/_rule-based-matching.jade

Often patterns need to match "any token". A clean way to denote this
is with the empty dict `{}`: this sets no constraints on the token,
so should always match.
The problem was that having attributes `length==0` was used as an
end-of-array signal, so the matcher didn't handle this case correctly.
This patch compiles empty token spec dicts into a constraint
`NULL_ATTR==0`. The `NULL_ATTR` attribute, 0, is always set to 0 on the
lexeme -- so this always matches.

💫 Allow empty dictionaries to match any token in Matcher

---

spacy/structs.pxd
spacy/syntax/_state.pxd
spacy/syntax/arc_eager.pyx
spacy/syntax/nn_parser.pyx
spacy/tests/parser/test_preset_sbd.py
spacy/tokens/doc.pyx
spacy/tokens/span.pyx
spacy/tokens/token.pyx

This patch allows use of separate sentence segmentation and parsing components. Previously this didn't work correctly, because you could add sentence boundaries, but they didn't properly constrain the parser.
The patch fixes the problem by introducing ternary value semantics for the `token.sent_start` attribute. Previously this attribute took two values in `{True, False}`. It now takes values in `{True, False, None}`. In the C data, the mapping is `{1: True, 0: None, -1: False}`.
When `token.sent_start` is set to `None` (default), the parser can predict a sentence starting with that token. If you set it to `True`, the parser *must* predict a sentence on that token. `False` prevents a sentence.
So let's say you get sentence boundaries from some other function you have, that takes text and …

💫 Force parser to respect preset sentence boundaries

---

spacy/_ml.py
spacy/syntax/nn_parser.pyx
spacy/tests/parser/test_add_label.py

This patch allows v2 models to add labels to pre-trained parsing and NER models. This functionality was available in v1 (albeit flakily), but was missing in v2, because there's not really a clean way to resize Thinc models.
The solution here is simply to drop in a replacement for the output layer, copying the sections of weights from the previous one. This seems a bit more robust than trying to fiddle with the internal weights representations.

💫 Allow labels to be added to pre-trained parser and NER modes

---

spacy/language_data/tokenizer_exceptions.py
spacy/tests/tokenizer/test_urls.py

Issue #1078
The regex used to match URL has known performance issues : https://gist.github.com/dperini/729294
These changes allow to:
- avoid catastrophic backtracking
- reduce character range of host name, domain name and TLD identifier
A call on `match` with 'sniffffffffffffffffffffff' now takes 3.10 ms, against 3.2 s before the changes.
As a result, in `test_urls.py`, some URLs that include non-ascii unicode characters don't match anymore.
The `test_urls.py` file has been updated (non-passing tests were converted to xfailed).

Resolve issue #1078 by simplifying URL pattern

---

examples/training/train_ner_standalone.py

Legacy example code uses unused variables `channels` and `loss`, and it printed final epoch's scores twice.  Here I remove the final scoring that included the offending undefined variable names. 
This PR is against the `develop` branch; not sure if I'm following the correct branching strategy for development against 2 alpha.

Bugfix example script train_ner_standalone.py, fails after training

---

spacy/__main__.py
spacy/cli/__init__.py
spacy/cli/validate.py

With our new and more efficient model build system for spaCy v2.0, and more models for more languages in the pipeline, we're also planning on releasing model updates more often.
This can lead to some problems, which have already come up in the alpha tests:
* Updates to spaCy's or Thinc's model architecture often require installing new models. If you're trying to use incompatible models, it can lead to fairly cryptic error messages along the lines of "thinc.foo has no layer bar".
* Checking the model compatibility on load is hard, as models can't know their maximum compatible spaCy version, and we don't want to ship spaCy with the model compatibility – otherwise, every new model release would require a patch to spaCy. (This is the reason the compatibility table lives in …

💫 Add "validate" command to CLI

---

spacy/language.py
spacy/strings.pxd
spacy/strings.pyx
spacy/tests/parser/test_parse_navigate.py
spacy/tokens/doc.pxd
spacy/tokens/doc.pyx
spacy/tokens/token.pxd

This patch follows through on the changes to the StringStore introduced in v2, and fixes by far the longest open bug: #285 Streaming Data Memory Growth
The solution implemented allows a weakref to be created on `Doc` objects, so that we can figure out when it's safe to flush out old strings. A rolling buffer is created using two StringStore objects. One StringStore contains the set of original strings and strings from recent documents. The other string store is the one current on the Vocab object. The only difference between the two `StringStore` objects are in strings created by increasingly old documents. Once we figure out that all of those old documents have passed out of scope and been reference counted, we figure it's safe to flush the obsolete strings.
This logic is only applied in …

💫 Fix streaming data memory growth (!!)

---

setup.py
spacy/language.py
spacy/syntax/nn_parser.pxd
spacy/syntax/nn_parser.pyx
spacy/syntax/transition_system.pyx
website/api/_top-level/_cli.jade

This patch pares down the tangle of options in the parser, in order to improve run-time efficiency. Re #1426 , #1419 
The parser pre-computes feature weights for the hidden states for each token. This is nicely parallel -- we can do a whole batch in one matrix multiplication. However, then we need to step through each state. This portion of the parsing algorithm is done on CPU, and overhead matters a lot.
In order to make things fast and keep the code simple, I've currently hard-coded that there's one hidden layer, and 2 maxout pieces. This allows a nice fused maxpool/dot product, with the maxpool being a simple max of two values. This saves a loop and a temporary array, which is nice.
Benchmarks on my machine (a Dell XPS 13, core i7), with numpy linked to MKL:
|   | After | Before
| --- …

💫 Improve runtime CPU efficiency of parser/NER

---

.github/contributors/johnhaley81.md
examples/keras_parikh_entailment/README.md

The master branch of Keras doesn't work with this example anymore so this pins Keras to version 1.2.2 for this example. This only changes the README.md to get the example to work. I ran `py.test` locally and it's no longer breaking.

Fix Keras install in keras_parikeh_entailment README

---

.github/contributors/ramananbalakrishnan.md
spacy/tests/doc/test_array.py
spacy/tokens/doc.pyx
website/docs/api/doc.jade

- Updates `Doc.to_array(attr_ids)` to accept a single value in `attr_ids`
- Partial fix for discussion in issue https://github.com/explosion/spaCy/issues/1410.

Support single value for attribute list in doc.to_array

---

spacy/compat.py
spacy/pattern/__init__.py
spacy/pattern/parser.py
spacy/pattern/pattern.py
spacy/tests/pattern/__init__.py
spacy/tests/pattern/parser.py
spacy/tests/pattern/pattern.py

Currently, there is no easy way in spaCy to match a complex pattern with respect to a given dependency tree.  Stanford CoreNLP offers this kind of feature with its Semgrex patterns (https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/semgraph/semgrex/SemgrexPattern.html).
This PR contains an implementation of a simple pattern matching algorithm, along with some high level wrapping classes.
A quick demonstration snippet:
```
import spacy
from spacy.pattern import PatternParser, DependencyTree
nlp = spacy.load('en')
doc = nlp("The quick brown fox jumped over the lazy dog.")
tree = DependencyTree(doc)
query = """fox [word:fox]=f
[lemma:quick]=q >/am.*/ fox
[word:/brown|yellow/] > fox"""
pattern = PatternParser.parse(query)
matches = tree.match(pattern)
assert len(matches) == 1 …
```

Implementation of dependency pattern-matching algorithm

---

.github/contributors/uwol.md
spacy/pipeline.pyx

TextCategorizer.predict is expected to return (scores, tensors) as in TextCategorizer.pipe. Hopefully this commit provides a fix.
bug fix
- [] I ran the tests, and all new and existing tests passed. <- currently, no execution environment available

TextCategorizer return parameter fix

---

.github/contributors/ligser.md
spacy/language.py
spacy/strings.pxd
spacy/strings.pyx
spacy/tests/regression/test_issue1506.py

I try to fix #1506 by allowing StringStore to clean up old strings when using it to iterate through many documents in a pipe. I try to do it with little effort on memory or speed, but I might not see all effect of my changes.
Because that method is written as the feature only for `pipe` method of the Language class — the method marked as internal by the underscore.
It's bug fix.

Try to add ability to clean up StringStore in pipe

---

spacy/gold.pyx
spacy/syntax/_beam_utils.pyx
spacy/syntax/arc_eager.pyx
spacy/syntax/ner.pyx
spacy/syntax/nn_parser.pyx
spacy/syntax/stateclass.pxd
spacy/syntax/stateclass.pyx
spacy/syntax/transition_system.pyx

This patch fixes a memory leak and intermittent crash that occurred in the beam parser. This should the implementation. The beam parser is especially useful for assigning probabilities, and will be useful for harder parsing tasks over short texts, e.g. for semantic parsing.

Fix memory leak in beam parser

---

.github/contributors/MartinoMensio.md
website/usage/_linguistic-features/_dependency-parse.jade

The documentation about dependency parsing contained a small typo.
It's only a small change on the docs
- [x ] I ran the tests, and all new and existing tests passed.

small typo on docs

---

.github/contributors/tokestermw.md
spacy/tests/regression/test_issue1207.py
spacy/tokens/span.pyx

Fixes Issue #1207 . 
The `noun_chunks` iterator works on a `Doc` but not a `Span`.
```
doc = nlp(u"Employees are recruiting talented staffers from overseas.")
list(doc.noun_chunks)  # [Employees, talented staffers]
span = doc[0:4]
list(span.noun_chunks)  # ERROR
for sent in doc.sents:
list(sent.noun_chunks)  # ERROR
```
A common use case that I have is I'd like to get the `noun_chunks` of a sentence.
Same fix as https://github.com/explosion/spaCy/commit/9750a0128cf211dac80217eee38e41c38f2c761c
Bug fix

Fixes error when getting `noun_chunks` from `Span`s. (Issue #1207)

---

.github/contributors/sorenlind.md
spacy/lang/da/tokenizer_exceptions.py
spacy/tests/lang/da/test_exceptions.py

I have made some changes to the Danish tokenizer exception. Specifically I've done the following:
* Remove the base exception for `i.` because the letter `i` is a common word in Danish.
* Add multiple exceptions for (relatively) common abbreviations.
* Remove exception for ambiguous abbreviations such as "Jul." for "July" (since "Jul" is a Danish word).
* Add common abbreviations for weekdays.
* Add exceptions for day of month, such as "1.", "10." and "31." (meaning 1st, 10th and 31st).
* Add tests for the above.
Enhancement.

Improve Danish tokenization

---

spacy/language.py

Default spaCy version string in language meta causes error if one tries to install the model package.
I've noticed that by default blank language [creates meta with current spaCy version](https://github.com/explosion/spaCy/blob/master/spacy/language.py#L150). If one packages this model with default meta, a setup file will be created from [this](https://github.com/explosion/spaCy/blob/master/spacy/cli/package.py#L149) template, which builds requirements from meta and expects `==`, `>=`, or `<=` before version number. So after running `setup.py` a wrong requirement `spacy2.x.x` (instead of `spacy>=2.x.x` or smth like that) causes the error.
I'm not sure, I fixed it in the right place, but it works at least.

Fixed spaCy version string in default meta

---

website/usage/_linguistic-features/_rule-based-matching.jade

Changed the index used to add the label because `displacy.render` apparently uses char index

Corrected char index instead of token index

---

.github/contributors/fsonntag.md
spacy/tests/regression/test_issue1494.py
spacy/tokenizer.pyx

See #1494.
Changed behaviour of tokenizer infix search. When infix_start equals the current offset, previously the whole infix tokenization was skipped. Now we add the infix itself, but still ignore the previous tokens (which are basically not there.

Solving #1494

---

spacy/cli/package.py

spacy requirement string for model packages was broken.
It should be `spacy>=2.0.2` instead of `spacy2.0.2`
bug fix

fix setup.py spacy req string for packaging

---

spacy/lang/da/__init__.py
spacy/lang/da/morph_rules.py

I have made some changes to the Danish morph rules. Specifically I've done the following:
* I systematically went through all forms of Danish personal pronouns, adding missing ones and fixing incorrect ones.
* I used the Danish Universal Dependencies for reference in all cases, except 'den'/'det' (Danish for the English word 'it'). I believe  Danish UD contains systematic errors for those words: Case is always specified as 'acc' even when the word refers to the subject (and consequently, Case should be set to 'nom'). I have left Case unspecified for 'den' and 'det'.
* I removed use of 'Masc' and 'Fem' for Gender as Danish only has the genders  'Neut' and 'Com' (common).
Bug fix / enhancement

Add more Danish morph rules and clean up existing ones

---

website/usage/_spacy-101/_lightning-tour.jade

I'm using SpaCy version 2.0.3. If I don't use the *-operator in the example, Python throws an error message. With the operator it works fine. Also according to the documentation of the function `nlp.disable_pipes()`, it expects one or more strings as arguments and not one argument being a list of strings.
Change in documentation in spaCy 101.

doc: Add missing *-operator to nlp.disable_pipes() in Lightning Tour

---

website/usage/_spacy-101/_lightning-tour.jade

Python 3 throws an error message on the original assert statement. Also, according to the Python documentation regarding the assert statement (https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement), `assert` takes at least one argument and at most two. In the two-argument form the second argument is meant as an error message to be displayed when the assertion fails. I don't think this is intended in this case.
Change in documentation in Lighting Tour.

doc: Fix assert statement in Lightning Tour

---

website/usage/_spacy-101/_lightning-tour.jade

The function `dependency_labels_to_root(token)` defined in section *Get syntactic dependencies* does not terminate. Here is a complete example (which doesn't terminate):
import spacy
nlp = spacy.load('en')
doc = nlp("Apple and banana are similar. Pasta and hippo aren't.")
def dependency_labels_to_root(token):
"""Walk up the syntactic tree, collecting the arc labels."""
dep_labels = []
while token.head is not token:
dep_labels.append(token.dep)
token = token.head
return dep_labels
dep_labels = dependency_labels_to_root(doc[1])
dep_labels
Replacing `is not` with `!=` solves the issue:
import spacy
nlp = spacy.load('en')
doc = nlp("Apple and banana are similar. Pasta and hippo aren't.")
def dependency_labels_to_root(token):
"""Walk up the syntactic tree, collecting the arc labels.""" …

doc: Replace 'is not' with '!=' in code example

---

examples/training/train_parser.py

The annotations `heads` and `deps` each contain 6 elements and the last element of `deps` is `'punct'`, so I guess there is a period missing at the end of the example sentence.
Fix in example code.

fix: Add missing period in train data

---

website/usage/_training/_tips.jade

In the first change I added a missing 'that'.
In the documentation words derived from 'to optimize' are written with a 'z' instead of an 's'. I corrected the two usages that were inconsistent with the rest of the text.

doc: Fix minor mistakes

---

website/api/token.jade

Change Span.vector_norm to Token.vector_norm.

Fix typo Span -> Token on Token API page

---

spacy/cli/init_model.py

I have made the following changes to `init-model`:
* When I removed the abbreviation for positional plac args in #1710, I overlooked the fact that the first argument passed is the name of the CLI argument (`init-model`). This caused all arguments to be shifted by one. I've added a dummy-argument called `_cmd`.
* `read_vectors` has two return values, but only one default value was specified when no word vectors were specified.
* `create_model` checked for the existence of word vectors be calling `len` but this caused an exception when no word vectors were specified.
Bug fix.

Fix CLI arguments for init-model

---

spacy/__init__.py
spacy/__main__.py
spacy/cli/convert.py
spacy/cli/download.py
spacy/cli/evaluate.py
spacy/cli/info.py
spacy/cli/init_model.py
spacy/cli/link.py
spacy/cli/package.py
spacy/cli/profile.py
spacy/cli/train.py
spacy/cli/validate.py
spacy/cli/vocab.py
spacy/tests/regression/test_issue1622.py

Running spaCy from the CLI, specifying a command but omitting one or more required arguments, will print a help text. This help text includes names of required and optional arguments. However, it also print both the command name *and* the name of the dummy variable containing the command name.
For example, calling `spacy package` would result in the following output:
```
usage: spacy package [-h] [-m None] [-c] [-f] _cmd input_dir output_dir
spacy package: error: the following arguments are required: input_dir, output_dir
```
Note that the first line contains `spacy package` but it also lists the variable name `_cmd` as one of the arguments. I think that's confusing as it can lead the user to think he or she needs to specify a command *in addition* to the already specified command. 
This …

Don't pass CLI command name as dummy argument

---

.github/contributors/pbnsilva.md
website/api/phrasematcher.jade

Fixes a small type in the PhraseMatcher API docs: `Mamimum` -> `Maximum`.
Documentation change.

Fix to typo in PhraseMatcher API docs

---

.github/contributors/fucking-signup.md
spacy/lang/da/lex_attrs.py
spacy/lang/en/lex_attrs.py
spacy/lang/fr/lex_attrs.py
spacy/lang/id/lex_attrs.py
spacy/lang/nl/lex_attrs.py
spacy/lang/pt/lex_attrs.py
spacy/lang/ru/lex_attrs.py
spacy/tests/regression/test_issue1769.py
website/usage/_adding-languages/_language-data.jade

This PR:
- Fixes issue where `like_num` returned `False` when numeric word was not lowercased (#1769).
- Adds checks for `like_num` in ordinal words lists, where ordinal words were specified but left unused (French, Dutch and Portuguese). Previously, only Danish checked for `like_num` in ordinals words list.
- Updates code example in [Adding Languages](https://spacy.io/usage/adding-languages) in Usage section on the website according to proposed changes.
Bugfix and enhancement

Fix issue #1769

---

spacy/lexeme.pyx
spacy/tests/doc/test_doc_api.py
spacy/tests/doc/test_span.py
spacy/tokens/doc.pyx
spacy/tokens/span.pyx
spacy/tokens/token.pyx

This patch makes the default similarity functions on the `Lexeme`, `Token`, `Doc` and `Span` objects return 1.0 if all of the tokens match by `orth`. For the containers (`Doc` and `Span`), they have to match by length, and then all entries are compared. If containers are length 1, similarity to a matching `Token` or `Lexeme` object is also 1.0.
I'm a bit worried that it will be confusing that non-exact matches will flip back to 0.0 if no word vectors are available. However, this behaviour seems better than any alternative I can think of.

Make .similarity() return 1.0 if all orth attrs match

---

spacy/matcher.pyx
spacy/tests/regression/test_issue1450.py
spacy/tests/regression/test_issue1855.py
spacy/tests/test_matcher_greedy.py
website/usage/_linguistic-features/_rule-based-matching.jade

#1503 
This PR includes fixes and improvements to the pattern matching behavior of spacy.matcher.Matcher.  Specifically, the '*' and '+' operators are not greedy and are inconsistent with the output of standard regular expression libraries.
The PR adds a ADVANCE_PLUS action that behaves as if both ADVANCE_ZERO and REPEAT were the action.  This allows greedy matching to be implemented without backtracking.  Due to the restrictions of the token patterns (i.e. one operator per token), the partial match list can be pruned to never be larger than twice the number of specs in a pattern.
1. Fixed bug in matching state logic preventing '*' from ever being greedy
2. Expanded functionality to allow multiple variable length quantifiers without backtracking 
- [ x] I have submitted the spaCy …

Pattern matcher fixes

---

.github/contributors/thomasopsomer.md
spacy/tests/regression/test_issue1834.py
spacy/tokens/doc.pyx
spacy/tokens/token.pxd

Little fix for issue #1834 - allowing to serialize the `sent_start` token attribute when the document is not parsed, so that sentence boundaries are saved. It also corrects `is_parsed` and `is_tagged` flags after deserialization.
Bug fix

Fix sentence boundaries serialization (issue #1834)

---

website/usage/_install/_instructions.jade

Simple fix for broken github link.  It sent you to `https://github.com/explosion/spacy/blob/master/tests/conftest.py` when it should be `https://github.com/explosion/spacy/blob/master/spacy/tests/conftest.py`

fix broken link to test suite models

---

spacy/lang/nb/__init__.py
spacy/lang/nb/syntax_iterators.py

Added syntax iterator to Norwegian Bokmål (nb)
As suggested [here](https://github.com/explosion/spaCy/pull/1882#issuecomment-361409573) by @ines I added the french syntax iterator as both languages are tagged with universal dependencies.
new feature

Norwegian Language (nb) - Added french syntax iterator with explanation

---

.github/contributors/pktippa.md
website/usage/_spacy-101/_vocab.jade
website/usage/_v2/_migrating.jade

Documentation changes for
* spacy-101 vocab section
* Replacing "like" with "love", coffee suffix should be "fee" but not "ffe"
* v2 - migration - training
* Typo "taining" fixed to "training"
Change to the documenation

Fixing documentation

---

website/usage/_facts-figures/_benchmarks.jade

aclweb.org is throwing a gateway timeout on the URL as `https`+`aclweb.org`, but is fine with `https`+`www.aclweb.org` (also with `http`+`aclweb.org`, but let's keep it in `https`, shall we?
Arguably this is an aclweb server configuration issue, but it's quicker to make a PR to spaCy than to fix aclweb!
Checklist:

update link to Honnibal and Johnson 2015

---

.github/contributors/ursachec.md
spacy/language.py
spacy/pipeline.pyx
spacy/syntax/nn_parser.pyx
spacy/tests/serialize/test_serialize_language.py
spacy/vectors.pyx

Hello everyone! This PR fixes the issue of files not being closed in a timely manner when a spaCy _Language_ object is used in a `unittest` test case  [#1706](https://github.com/explosion/spaCy/issues/1706)
Using the simple test case specified in [#1706](https://github.com/explosion/spaCy/issues/1706), I went through all the _ResourceWarnings_ and removed them one by one in a way which made the most sense to me. After ensuring that all relevant file opens were wrapped in a `with` statement or `util.read_json`, I ran the simple unit test again with positive results.
Specifically, these are the warnings which aren't thrown any more:
```
util.py:521: ResourceWarning: unclosed file <_io.BufferedReader name='SPACY_DIR/data/en/en_core_web_sm-2.0.0/vocab/key2row'>
reader(path / key) …
```

Fix issue #1706

---

spacy/lang/lex_attrs.py
spacy/tests/regression/test_issue1889.py

This PR fixes an issue where `is_stop` returned `False` when a stop word was not lowercased (#1889).
**Before this PR:**
```python
import spacy
nlp = spacy.load('en')
def is_stop(text):
doc = nlp(text)
print(doc[0].is_stop)
is_stop('the') # True
is_stop('The') # False
```
**After this PR:**
```python
import spacy
nlp = spacy.load('en')
def is_stop(text):
doc = nlp(text)
print(doc[0].is_stop)
is_stop('the') # True
is_stop('The') # True
```
Bug fix

Fix issue #1889

---

spacy/tests/doc/test_span.py
spacy/tokens/span.pyx

Hi,
I noticed that the function allowing to retrieve the sentence from a span => `span.sent` works only when the document is parsed. I added the ability to get the sentence using the `sent_start` attribute, by looking on the left and right of the span for the next sentence boundaries.
Don't know if you want that, or if it should belong to a personal `user_span_hooks`, but in case it's here :)
bug fix ?

Make span.sent work when only manual / custom sbd

---

spacy/tokens/token.pyx

`token.lemma` wasn't always returning an integer ! When the lemma wasn't set on the c attribute, the `lemma` property calls the `lemmatizer` lookup table but it returned the unicode instead of the hash.
Small fix, but quite annoying bug ^^.
bug fix

Make token.lemma property return hash instead of unicode

---

spacy/lang/en/lemmatizer/lookup.py

Very minor typo fix
Referencing #2063 , I noticed that  `also` has lemma `conjurer`, I thought it might be a copy paste typo. I mapped it to itself, adverbs has lemma themselves (with some exceptions:) ).
The reason I'm making a one liner pull request is that, "also" is a common adverb and bad lemmatization cause huge shifts at the end.
Very minor change, I only removed one line.
I also made a quick awk to go over adverb and adjective lists and check if any of them exists somewhere else. 

Quick typo fix

---

.github/contributors/calumcalder.md
website/api/_top-level/_displacy.jade

The word_spacing option for the visualizer affects the vertical spacing between the words and arcs, not the horizontal spacing. Documentation has been changed to reflect this.
Documentation

 Fix typo in documentation for displacy Visualizer

---

.github/contributors/justindujardin.md
examples/vectors_tensorboard.py

Add an example script for visualizing spaCy model word vectors in TensorBoard.
Use on the command line:
```bash
python vectors_tensorboard.py en_core_web_lg ./output_folder spaCy_large
```
Documentation, example script

Add example for visualizing word vectors with TensorBoard Projector

---

spacy/_ml.py
spacy/cli/train.py
spacy/language.py
spacy/pipeline.pyx
spacy/syntax/nn_parser.pyx
spacy/tests/conftest.py
spacy/tests/regression/test_issue1660.py
spacy/tests/serialize/test_serialize_language.py
spacy/vectors.pyx
spacy/vocab.pyx

This patch addresses #1660, which was caused by keying all pre-trained
vectors with the same ID when telling Thinc how to refer to them. This
meant that if multiple models were loaded that had pre-trained vectors,
errors or incorrect behaviour resulted.
The vectors class now includes a .name attribute, which defaults to:
{nlp.meta['lang']_nlp.meta['name']}.vectors
The vectors name is set in the cfg of the pipeline components under the
key pretrained_vectors. This replaces the previous cfg key
pretrained_dims.
In order to make existing models compatible with this change, we check
for the pretrained_dims key when loading models in from_disk and
from_bytes, and add the cfg key pretrained_vectors if we find it.

💫 Fix loading of multiple vector models

---

spacy/tests/doc/test_add_entities.py
spacy/tests/doc/test_span_merge.py
spacy/tokens/doc.pyx

Previously the `token.ent_iob` sequence could end up in an inconsistent state, both after `doc.merge()` and after setting `doc.ents`. This patch resolves the problem and improves the error message if we do end up in an inconsistent state.
This should address #1554 , and one of the problems behind #1752

💫 Fix token.ent_iob after doc.merge(), and ensure consistency in doc.ents

---

.github/CONTRIBUTOR_AGREEMENT.md
spacy/tests/vectors/test_vectors.py
spacy/vectors.pyx

Changed python set to cpp stl set #2032 
Changed python set to cpp stl set. CPP stl set works better due to the logarithmic run time of its methods. Finding minimum in the cpp set is done in constant time as opposed to the worst case linear runtime of python set. Operations such as find,count,insert,delete are also done in either constant and logarithmic time thus making cpp set a better option to manage vectors.
Reference : http://www.cplusplus.com/reference/set/set/
Enhancement for `Vectors` for faster initialising of word vectors(fasttext)

[2032] - Changed python set to cpp stl set

---

setup.py
spacy/tokens/_retokenize.pyx
spacy/tokens/doc.pxd
spacy/tokens/doc.pyx

This patch takes a step towards #1487 by introducing the
doc.retokenize() context manager, to handle merging spans, and soon
splitting tokens.
The idea is to do merging and splitting like this:
```python
with doc.retokenize() as retokenizer:
for start, end, label in matches:
retokenizer.merge(doc[start : end], attrs={'ent_type': label})
```
The retokenizer accumulates the merge requests, and applies them
together at the end of the block. This will allow retokenization to be
more efficient, and much less error prone.
A `retokenizer.split()` method will then be added, to handle splitting a
single token into multiple tokens. These methods take `Span` and `Token`
objects; if the user wants to go directly from offsets, they can append
to the .merges and .splits lists on the retokenizer.
The …

Add doc.retokenize() context manager

---

.github/contributors/mollerhoj.md
spacy/lang/da/__init__.py
spacy/tests/lang/da/test_lemma.py

Add's lemmas for Danish
This adds lemmas for Danish to spaCy. The dataset (Den store danske SprogTeknologiske Ordbase, STO) has been made available for public with courtesy of The University of Copenhagen. 
Added lemmas for Danish

Add Danish lemmatizer

---

CONTRIBUTING.md
spacy/tokens/doc.pyx

Fixed typos for #2222,#2223

---

.github/CONTRIBUTOR_AGREEMENT.md
.github/contributors/miroli.md

In modern Swedish, "gäng" is mostly associated with "gang" or "group of people". The removed lemma lookup lemmatized it to the verb "thread".
Just removing one line in the Swedish lemma lookup table, as described above.
Bugfix.

Remove incorrect lemma lookup gäng->gänga

---

.github/contributors/ivyleavedtoadflax.md
website/usage/_spacy-101/_lightning-tour.jade

Add missing comma in spacy-101 docs which prevented example from running.
Also add spaCy Contributor Agreement.
Add missing comma in spacy-101 docs.
Typo fix
Probably a bit overkill for a single comma!:

Add missing comma to NN example in docs

---

.github/contributors/alexvy86.md
website/api/doc.jade

The assertion at the end of the previous sample code for `set_extension` fails because `city_getter`  checked if the whole document text matches any of the city names. Now it checks if any of the city names is contained somewhere in the document text.
Ran the old and new code snippets in a Python 3.6.5 environment, with the expected behaviors (assertion fails for old sample code, passes after fix).
I built and ran the tests for the project and got a bunch of errors (most of them of the form `AttributeError: 'Namespace' object has no attribute 'slow'`), but since I didn't touch the actual project code I imagine these are either issues with my environment...
This is a bug fix to sample code **in the documentation**.

Fix code sample for Doc.set_extension

---

website/api/span.jade

Same fix as [PR 2282](https://github.com/explosion/spaCy/pull/2282) but for `Span._set_extension` this time, didn't notice that this one had the same bug. And I checked that `Token.set_extension` doesn't need a fix :).
This is a bug fix to sample code **in the documentation**.

Fix code sample for span.set_extension

---

.github/contributors/mn3mos.md
README.rst
spacy/cli/download.py

This PR adresses issue #2211 by proposing a patch to the command 'download' which allows users to disable the SSL verification of certificates or to customize the Certificate Authentity file which is used for the validation.
Such options are required in some corporate environments which install proxies and mess with the usual certification processes.
This is my first contribution so I need your help, please :)
I am not able yet to tick the boxes in the checklists, **can you give me pointers to**:
- run the tests manually: I tried to run them but I couldn't find any test relevant to CLI
- propose a change in the documentation **if you consider the README is not enough**
Thanks in advance.
I consider this change an enhancement of the CLI tool.
I updated the README too, but not the manual of …

#2211 - Support for ssl certs config on download command

---

.github/contributors/knoxdw.md
spacy/tests/regression/test_issue2219.py
spacy/tokens/token.pyx

Fixes bug described in issue #2219; regression test demonstrates the problem.
Token similarity was failing when the `other` token happened to be a single letter, apparently because case analysis for span didn't take into account that a token could satisfy `len(other) == 1`. 
Since the problem is that `other[0]` generated an error because the "Token object does not support indexing," adding a check for `hasattr("__getitem__)"` is all that's needed.

Test and fix for Issue #2219: Token.similarity() failed if single letter

---

examples/pipeline/custom_component_countries_api.py

Fix bug in the custom_component_countries_api.py script.
Set a `default` when setting extension to prevent the following `ValueError`:
```
ValueError: [E083] Error setting extension: only one of `default`, `method`, or `getter` (plus optional `setter`) is allowed. Got: 0
```
Fixes bug in example script.

Fix bug in custom_component_countries_api.py script

---

spacy/tests/vectors/test_vectors.py
spacy/vocab.pyx

Implement Fast-Text vectors with subword features #1480 
This commit incorporates subword information to get embeddings for words using fasttext.
For words found in the input vocab model, the vector is returned as it is. For out of vocab words, average of all the subword vectors are computed and returned.
ngram range can be given as optional params. If no range is specified, no subwords are used and the word is used as it is. 
This enables simple and easy integration of subword information and is agnostic of the vocab model supplied.
Usage:
```vocab.get_vector(text,minn,maxn)```

1480 - Implement Fast-Text vectors with subword features

---

spacy/errors.py
spacy/language.py
spacy/util.py

This PR introduces a new mechanism for registering custom pipeline components and their factories and making it easy to define them in a custom model's pipeline.
When you load a model, spaCy will generally use the model's `meta.json` to set up the language class and construct the pipeline. The pipeline is specified as a list of strings, e.g. `"pipeline": ["tagger", "paser", "ner"]`. For each of those strings, spaCy will call `nlp.create_pipe` and look up the name in the [built-in factories](https://github.com/explosion/spaCy/blob/1a4682dd0bdf4d8b7b4c3dd23c3829b1333f2fa5/spacy/language.py#L101). If your model wanted to specify its own custom components, you previously had to write to `Language.factories` *before* loading the model.
```python
pipe = nlp.create_pipe('custom_component')  # …
```

💫 Support pipeline component factories via entry points (with detailed examples)

---

.github/contributors/BigstickCarpet.md
spacy/cli/train.py

Changed to use fixed-spaces rather than tabs to align table headers and data.
```
Itn.    P.Loss  N.Loss  UAS     NER P.  NER R.  NER F.  Tag %   Token %
0       4618.857        2910.004        76.172  79.645  67.987  88.732  88.261  100.000 4436.9  6376.4
1       4671.972        3764.812        74.481  78.046  62.374  82.680  88.377  100.000 4672.2  6227.1
2       4742.756        3673.473        71.994  77.380  63.966  84.494  90.620  100.000 4298.0  5983.9
```
```
Itn.  Dep Loss  NER Loss  UAS     NER P.  NER R.  NER F.  Tag %   Token %  CPU WPS  GPU WPS
0     4618.857  2910.004  76.172  79.645  67.987  88.732  88.261  100.000  4436.9   6376.4
1     4671.972  3764.812  74.481  78.046  62.374  82.680  88.377  100.000  4672.2   6227.1
2     4742.756  3673.473  71.994  77.380  63.966 …
```

Better formatting for `spacy train` CLI

---

.github/contributors/ansgar-t.md
spacy/displacy/render.py
spacy/tests/regression/test_issue2361.py
spacy/util.py

Fix for issue #2361 :
replace &, <, >, " with &amp;amp; , &amp;lt; , &amp;gt; , &amp;quot; in before rendering svg
(As discussed in the comments to #2361)

escape html in displacy.render (#2361)

---

.github/contributors/mpszumowski.md
spacy/gold.pyx
spacy/tests/regression/test_issue2385.py

Fix a bug in iob_to_biluo function in case of labels with a 'b' character and modify _consume_ent for cli.converter to handle tags already in biluo format.
https://github.com/explosion/spaCy/issues/2385
If tags in BILUO format are passed to the CLI converter, the L-flag goes unprocessed and n-word tokens are read as (n-1)-word tokens. This is because the CLI iob and ner 2json converters both presuppose that NER tags are passed in IOB1/2 format and convert them to BILUO in gold.iob_to_biluo. 
This may not always be the case - especially the conll_ner2json converter is not self-evident to accept specifically IOB format. What is more, the currently suggested workflow of preparing the dataset for the isolated NER pipeline component is to convert any offset NER tags into BILUO using …

Fix bug in CLI iob and ner converter

---

.github/contributors/himkt.md
examples/information_extraction/phrase_matcher.py
spacy/tests/conftest.py
website/usage/_models/_languages.jade

This PR is simple document fix.
In my glance, spaCy now uses MeCab for Japanese Tokenizer.
But the documentation still refers Janome, which is confusing for me.
This PR only changes the documentation.
So I create this PR although unittest fails in my environment.
I will further investigate about unittest failing.

replace janome with mecab in the documentation and the test

---

spacy/displacy/render.py

Referring #2452, fixing displacy arrow directions to match the input. 
The fix is simply replacing `direction is 'left'` with `direction == 'left'` to include the case `direction` is a `str` and not a `unicode`.
bug fix

fix issue #2452 - displacy arrow direction is always forward

---

spacy/tests/doc/test_token_api.py
spacy/tokens/token.pyx

Adds token.sent property to fetch the sentence the the token is part of.
This fixes #2518
New feature

Add sent property to token

---

spacy/tests/lang/de/test_lemma.py

I made a quick fix to the issue at #2486 . In this fix I included capitalized versions of the words belonging to the  classes that are likely to occur at the beginning of a sentence. I added capital versions of the words that are risk free i.e. has only one possible lemma. Here are the classes:
Personal pronouns
Relative pronouns
Demonstratives
Indefinite articles
Definite articles
Particles
Auxiliary verbs
Modal verbs
Members of these classes usually have only one possible lemma anyway.
Additions are word-lemma pairs, for instance:
Die:der
Das:der
Welche:welch
- I was very careful not to override any word-lemma pairs that already exists.
- New behavior is as follows: When one of these words is in capital, lemma is the small version i.e. "Die" -> "der". Please see the tests.
- I made a …

German lemmatizer additions

---

website/usage/_install/_troubleshooting.jade

Adds guidance on what to do if users encounter the error described in [1634](https://github.com/explosion/spaCy/issues/1634), which probably only happens in Windows environments.
Change to documentation.
Since this is purely a documentation change I didn't run the project tests.

Guidance to handle binary files in git in Windows

---

.github/contributors/x-ji.md
CONTRIBUTING.md
README.rst
website/usage/_install/_instructions.jade
website/usage/_install/_quickstart.jade

The documentation refers to `venv`, which is native to Python3. However, the command examples are as if they were still using `virtualenv`, which is a package independent of `venv`:
- `venv` doesn't need to be installed via `pip`. In fact `pip install venv` would
return an error.
- The correct way to invoke `venv` is `python3 -m venv`, not `venv`, which would
return command not found.
See https://docs.python.org/3/library/venv.html
I suspect that at some point the documentation simply replaced all occurrences of `virtualenv` with
`venv`. However they are different modules and are used differently. The documentation should either stick with `virtualenv` or correctly use `venv`, which is what this PR tries to do.
(I'm not sure what "or if they do, I've added all …

Fix venv command examples

---

spacy/tokenizer.pyx
spacy/vocab.pxd
spacy/vocab.pyx

This patch improves tokenizer speed by about 10%, and reduces memory usage in the `Vocab` by removing a redundant index. The `vocab._by_orth` and `vocab._by_hash` indexed on different data in v1, but in v2 the orth and the hash are identical.
The patch also fixes an uninitialized variable in the tokenizer, the `has_special` flag. This checks whether a chunk we're tokenizing triggers a special-case rule. If it does, then we avoid caching within the chunk. This check led to incorrectly rejecting some chunks from the cache. 
With the `en_core_web_md` model, we now tokenize the IMDB train data at 503,104k words per second. Prior to this patch, we had 465,764k words per second.
Before switching to the regex library and supporting more languages, we had 1.3m words per second for the tokenizer. …

💫 Small efficiency fixes to tokenizer

---

website/api/doc.jade

Changed 'The index of the first character after the span.' to 'The index of the last character after the span' in description of doc.char_span under field 'end'.

Fixed typo

---

website/usage/_linguistic-features/_tokenization.jade

This pull request is a bug fix to the pseudocode provided in the website of spaCy docs for implementing/customizing spacy tokenizer. 
The pseudocode provided [here](https://spacy.io/usage/linguistic-features#tokenization) slices wrongly the substring when a suffix is spotted. In order to make it write,  the following lines of code
```
suffixes.append(substring[split:])
substring = substring[:split]
```
should be changed to:
```
suffixes.append(substring[-split:])
substring = substring[:-split]
```

Bug fix to pseudocode for spaCy tokenizer

---

spacy/lang/sv/tokenizer_exceptions.py
spacy/tests/lang/sv/test_tokenizer.py

This is part of #2608.
Sentences ending in "i." (as in "... peka i."), "m." (as in "...än 2000 m."), should be tokenized as two separate tokens, not one.
In the corpus there is a single case of "let's call that variable e."; that gets incorrectly tokenized into "e.". But this variable name could be anything, so to fix it in the general case, I'd have to remove all single letter exceptions. There are two ways to do this:
1) In the language specific code, I could override the single letter versions, to make sure they are two different tokens again. This runs into the problem that "s." is an abbreviation in Swedish, which should be one unit. So one option would be "removing everything except s". Doesn't feel like "clean code" to me...
2) I also tried removing the single letter exceptions …

Swedish: Exceptions for single letter words ending sentence

---

.github/contributors/EmilStenstrom.md
spacy/lang/sv/tokenizer_exceptions.py

This is part of #2608. It reduces the tokenization errors from 216 -> 196. The remaining errors has to do with token splitting, I'll handle that in a separate PR. All added abbreviations are from UD_Swedish-Talbanken.
Bug fix.

Add abbreviations from UD_Swedish-Talbanken

---

.github/contributors/njsmith.md
spacy/tests/conftest.py

This is necessary to allow testing an installed spacy by running
`pytest --pyargs spacy`.
Bug fix.

When calling getoption() in conftest.py, pass a default option

---

.github/contributors/pzelasko.md
spacy/tokens/token.pyx

I've removed the redundant vector norm computation in token similarity (was previously computed twice).
Before the change:
```
In [7]: doc = nlp('similar similarities')
In [8]: %timeit doc[0].similarity(doc[1])
38.8 µs ± 576 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
After the change:
```
In [3]: doc = nlp('similar similarities')
In [4]: %timeit doc[0].similarity(doc[1])
23.4 µs ± 131 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
Enhancement/speedup.

Less norm computations in token similarity

---

.github/contributors/grivaz.md
spacy/errors.py
spacy/tests/doc/test_doc_api.py
spacy/tests/doc/test_span_merge.py
spacy/tokens/_retokenize.pyx
spacy/tokens/doc.pyx

Introduces a bulk merge function, in order to solve issue #653
I introduced a bulk merge function in Doc. Most of the changes are in the Retokenizer class, where I replaced the _merge function by a _bulk_merge function. I adapted some unit tests to test the bulk merge (they pass). I tested the implementation on a subset of War and Peace and got the following results:
Before my changes: 165s
With bulk merge: 15s
With bulk merge used sequentially in a for loop: 440s
This is work in progress, depending on feedback, in particular on the following points:
- The bulk merge is slower than the original merge when used sequentially. I could reintroduce the original merge for that case.
- The bulk merge requires the tokens to merge to be given in document order. I could introduce a function that …

Introduces a bulk merge function, in order to solve issue #653

---

.github/contributors/free-variation.md
examples/deep_learning_keras.py

Updated the Keras sentiment analysis example to work with version 2.012 of spaCy.
The fix addresses #2501, #2743 and #2209, and possibly #1917.
The basic problem was that the language model/pipeline used needed to be fixed at `en-vectors-web-1g`, and the pipeline construction process for the validation stage needed to reflect the pipeline used in training.
Also, `config.json` was being written to a *binary* file, which caused an error.
Bug fixes.

Fixed spaCy+Keras example

---

spacy/matcher.pyx
spacy/tests/test_matcher.py

Given a dependency pattern, to output all possible matches on the dependency tree. Uses semgrex syntax.
This has been inspired from https://github.com/explosion/spaCy/pull/1120.
Enhancements to the above are : 
1. All constructs are what spacy is currently using which enables easy understanding of codebase and functionality and allows for good extensibility.
2. Inputs and Outputs are very similar to the existing Matcher.
3. Reuse of `Matcher` within `DependencyTreeMatcher`.
Input : An input pattern which is similar to what `Matcher` takes.
Example :     
`
pattern = [
{'SPEC': {'NODE_NAME': 'fox'}, 'PATTERN': {'ORTH': 'fox'}},
{'SPEC': {'NODE_NAME': 'q', 'NBOR_RELOP': '>', 'NBOR_NAME': 'fox'},'PATTERN': {'LOWER': u'quick'}}
]`
The tree edge is specified using 'SPEC' and the tree node is …

WIP - Dependency Tree Pattern Matcher

---

examples/training/train_intent_parser.py
examples/training/train_ner.py
examples/training/train_new_entity_type.py
examples/training/train_parser.py
examples/training/train_tagger.py

Update the training examples in `/examples/training` to show usage of spaCy's `minibatch` and `compounding` helpers ([see here](https://spacy.io/usage/training#tips-batch-size) for details). The lack of batching in the examples has caused some confusion in the past, especially for beginners who would copy-paste the examples, update them with large training sets and experienced slow and unsatisfying results.
enhancements

💫 Update training examples and use minibatching

---

.github/contributors/jacopofar.md
website/usage/_install/_instructions.jade

As found out in [this issue](https://github.com/explosion/spaCy/issues/2841) the link is broken. The page changed, this is the new landing page.
Update the link in the documentation
Only documentation
- [ X] I have submitted the spaCy Contributor Agreement.
- [ X] I ran the tests, and all new and existing tests passed.
- [X ] My changes don't require a change to the documentation, or if they do, I've added all required information.

Visual C++ link updated

---

spacy/errors.py
spacy/tests/doc/test_add_entities.py
spacy/tests/regression/test_issue242.py
spacy/tokens/doc.pyx

Just added detection of overlapping entities and erroring on setting doc.ents, as described in issue 2550
I also added a unit test, but I had to adapt the unit test for issue 242 which was allowing overlapping entities. I hope this was the desired behavior. I can also change it to something else, if it is preferred.
It's a bug fix
I had to adapt the test for issue 242, so that it passes

raise error when setting overlapping entities as doc.ents to close  #2550

---

spacy/errors.py
spacy/matcher.pyx

Added validation and all major Semgrex operators
1. Added checks to validate input.
2. Added all major Semgrex operator support. Includes support for'<','>','>>','<<','.','$+','$-','$++','$--'.
Details regarding the operators can be found here : https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/semgraph/semgrex/SemgrexPattern.html
Note: The subtree matching code needs to be re-looked at. I guess there are some caveats in the Semgrex pattern matching algorithm that need to be implemented. Unordered subtree matching takes exponential time and the heuristics implemented in Semgrex can be of help.
Enhancement

WIP - Dependency Tree Matcher (Validations + Semgrex operators)

---

spacy/language.py

The name `max_length` implies that input of exactly that length is still valid, so this should be the case.
I encountered this problem when I saw the error message and tried to do `text = text[:nlp.max_length]` to resolve it, but of course it was still too long.
Minor bug fix.

Allow input text of length up to max_length, inclusive

---

spacy/matcher.pyx
spacy/tests/matcher/test_phrase_matcher.py

Related issue: #1971
This PR introduces the ability to match other token attributes in the `PhraseMatcher` – for example, to find sequences of part-of-speech tags that match an example sentence. On initialization, the `attr` keyword argument can specify an attribute string name.
```python
matcher = PhraseMatcher(nlp.vocab, attr='POS')
matcher.add('PATTERN', None, nlp('I love cats'))
doc = nlp('yes, you hate dogs')
assert len(matcher(doc)) == 1  # matched 'you hate dogs' based on token.pos
```
Most useful use case: case-insensitive phrase matches! 🎉
```python
matcher = PhraseMatcher(nlp.vocab, attr='LOWER')
matcher.add('PATTERN', None, nlp('iPhone X'))
doc = nlp('i have an iphone x')
assert len(matcher(doc)) == 1  # matched 'iphone x' based on token.lower
```
It even works for boolean …

💫 Allow matching non-ORTH attributes in PhraseMatcher

---

spacy/displacy/render.py

Resolves #2924.
Fixes problem where multiple visualizations in Jupyter notebooks would have clashing arc IDs, resulting in weirdly positioned arc labels. Generating a random ID prefix so even identical parses won't receive the same IDs for consistency (even if effect of ID clash isn't noticable here.)
bug fix

💫 Create random IDs for SVGs to prevent ID clashes

---

spacy/__main__.py
spacy/cli/__init__.py
spacy/cli/pretrain.py
spacy/cli/train.py

Add support for a new command, `spacy pretrain`:
```
usage: spacy pretrain [-h] [-cw 128] [-cd 4] [-er 1000] [-d 0.2] [-i 1] [-s 0]
texts_loc vectors_model output_dir
Pre-train the 'token-to-vector' (tok2vec) layer of pipeline components,
using an approximate language-modelling objective. Specifically, we load
pre-trained vectors, and train a component like a CNN, BiLSTM, etc to predict
vectors which match the pre-trained ones. The weights are saved to a directory
after each epoch. You can then pass a path to one of these pre-trained weights
files to the 'spacy train' command.
This technique may be especially helpful if you have little labelled data.
However, it's still quite experimental, so your mileage may vary.
To load the weights back in during 'spacy train', you need to ensure
all …
```

💫 Add experimental ULMFit/BERT/Elmo-like pretraining 

---

.github/contributors/cicorias.md
spacy/compat.py
spacy/tests/test_symlink_windows.py

during setup of spacy using command
python -m spacy link en_core_web_sm en
closes #2948
fixes the issues address in #2948 - where the symbolic link isn't being created and the error message indicates permissions, while it is not permissions.
Bug fix

fixes symbolic link on py3 and windows

---

.github/contributors/ALSchwalm.md
spacy/vocab.pyx

Fixes #2976
Currently, it is difficult to use `Vocab.prune_vectors` in some cases because the `batch_size` option is not passed on to the inner `Vectors.most_similar` call. This causes `MemoryError`s when pruning to a smaller but still somewhat large size (e.g., 500K). The PR passes on the option.
Bug Fix

Fix bug where Vocab.prune_vectors did not use 'batch_size'

---

website/api/_annotation/_named-entities.jade

The website for OntoNotes 5 is: https://catalog.ldc.upenn.edu/LDC2013T19, currently the named entity section has it as https://catalog.ldc.upenn.edu/ldc2013T19.
Just noticed this and wanted to submit the fix.  I haven't tested the change or signed the contributor agreement (it's my first PR to SpaCy!), I just figured it wasn't worth creating an issue since the fix is pretty simple.  Let me know if you need me to sign the agreement.
This is a minor fix, just changing the url.  I haven't been able to test the new version of the website, but I imagine it shouldn't cause any issues.
Change tot he documentation
Not sure if these are applicable!

OntoNotes url fix

---

.github/contributors/wxv.md
website/api/token.jade

Proposed in #2933. 
Changes the "equivalent code" of `is_ascii` to return a correct Boolean (previously returning a list with wrong truth value).  
Documentation

Fix is_ascii documentation

---

setup.py

Installing the latest version of spacy `2.0.17` on my MacOS `10.3.6` computer is failing. It seems Apple deprecated the use of `libstdc` a while back.
The install fails with an error similar to this:
```
...
running build_ext
building 'spacy.parts_of_speech' extension
creating build/temp.macosx-10.7-x86_64-3.6
creating build/temp.macosx-10.7-x86_64-3.6/spacy
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/anaconda3/include/python3.6m -I/private/var/folders/q3/j42n3r692gb2yl9cp1ncs3q00000gn/T/pip-install-s3qpnk75/spacy/include -I/anaconda3/include/python3.6m -c spacy/parts_of_speech.cpp -o build/temp.macosx-10.7-x86_64-3.6/spacy/parts_of_speech.o -O2 …
```

fix issue compiling the latest spacy on MacOS 10.3.6

---

.github/contributors/gavrieltal.md
spacy/cli/converters/iob2json.py
website/api/cli.jade

A quick solution for allowing those using the master branch to use IOB or IOB2 formats, and to accept whitespace delimitation on a line other than a pipe.
Fixes the master branch for #2504 and #2970. Fixes for the develop branch are not yet done.

Accept iob2 and allow generic whitespace

---

spacy/structs.pxd
spacy/tests/regression/test_issue2754.py
spacy/tokens/token.pxd
spacy/tokens/token.pyx
spacy/vocab.pyx

See #3028. The solution in this patch is pretty debateable.
What we do is give the `TokenC` struct a `.norm` field, by repurposing the previously idle `.sense` attribute. It's nice to repurpose a previous field because it means the `TokenC` doesn't change size, so even if someone's using the internals very deeply, nothing will break.
The weird thing here is that the `TokenC` and the `LexemeC` both have an attribute named `NORM`. This arguably assists in backwards compatibility. On the other hand, maybe it's really bad! We're changing the semantics of the attribute subtly, so maybe it's better if someone calling `lex.norm` gets a breakage, and instead is told to write `lex.default_norm`?
Overall I believe this patch makes the `NORM` feature work the way we sort of expected it to work. …

Make NORM a token attribute

---

spacy/tests/doc/test_span.py
spacy/tokens/span.pyx

Fixes #3027.
* Allow Span.__init__ to take unicode values for the `label` argument.
* Allow `Span.label_` to be writeable.

💫 Allow Span to take text label

---

examples/training/train_textcat.py
spacy/_ml.py
spacy/pipeline.pyx

Currently the `TextCategorizer` defaults to a fairly complicated model, designed partly around the active learning requirements of Prodigy. The model's a bit slow, and not very GPU-friendly.
This patch implements a straightforward CNN model that still performs pretty well. The replacement model also makes it easy to use the LMAO pretraining, since most of the parameters are in the CNN.
The replacement model has a flag to specify whether labels are mutually exclusive, which defaults to `True`. This has been a common problem with the text classifier.  We'll also now be able to support adding labels to pretrained models again. 
Resolves #2934, #2756, #1798, #1748.

💫 Make TextCategorizer default to a simpler, GPU-friendly model

---

.github/contributors/kbulygin.md
spacy/lang/ja/__init__.py
spacy/tests/regression/test_issue2901.py

The fix is according to https://github.com/explosion/spaCy/issues/2901#issuecomment-447872494. It wouldn't be possible without investigation made by [Paul O'Leary McCann](https://github.com/polm).
The fix itself is the most trivial (just adding `self.tokenizer.parseToNode('')` after `self.tokenizer = MeCab.Tagger()`). To apply the fix and to check that nothing has been broken (at least for Python 3.7.1), the following Dockerfile was used: https://github.com/kbulygin/spacy-dev/blob/master/Dockerfile.
Bug fix.

Fix the first `nlp` call for `ja` (closes #2901)

---

.github/contributors/clippered.md
spacy/tests/regression/test_issue3012.py

Add regression test for issue#3012
Sorry, I can't get this test to run on my environment. I'm getting an error:
```
E           _pytest.warning_types.RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
E           Please use node.get_closest_marker(name) or node.iter_markers(name).
E           Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
``` 
So please feel free to have a look at it too.

issue #3012: add test

---

spacy/cli/package.py
spacy/errors.py
spacy/pipeline.pyx
spacy/syntax/nn_parser.pyx

After creating a component, the `.model` attribute is left with the value `True`, to indicate it should be created later during `from_disk()`, `from_bytes()` or `begin_training()`. This had led to confusing errors if you try to use the component without initializing the model.
To fix this, we add a method `require_model()` to the `Pipe` base class. The `require_model()` method needs to be called at the start of the `.predict()` and `.update()` methods of the components. It raises a `ValueError` if the model is not initialized. An error message has been added to `spacy.errors`.

💫 Raise better error when using uninitialized pipeline component

---

spacy/about.py
spacy/cli/train.py
spacy/syntax/_parser_model.pyx

Resolves #1585.
Previously when we added a new label, the parser might output non-zero
predictions for the new class. This could occur if the output of the
previous layer had non-zero values within it, as zero wouldn't be the
lowest number.
~To fix this, we add a ReLu filter to the output of the parser's maxout
layer, before we apply the output weights. This way, we know that if a
class has zeroed weights, the parser must predict zero probability for
it.~
~This change requires retraining the models, unfortunately.~
Nope, the ReLu idea doesn't work! We still can end up with negative scores,
and very often do, because the output layer may have negative bias.
After thinking some more, I came up with a solution that doesn't require 
retraining the models :tada:. We set nan values for the new …

💫 Prevent parser from predicting unseen classes

---

spacy/displacy/__init__.py
spacy/errors.py
spacy/tests/test_misc.py
spacy/util.py
website/api/_top-level/_displacy.jade

Small fixes to displaCy

---

spacy/language.py
spacy/util.py

Related PR with more details: #2348
Resolves #1816.
This PR introduces the option to add custom `Language` classes via entry points. This allows users to add their own languages without modifying the core library.
To stay with the theme of #2348, the following is now possible:
```python
from spacy.language import Language
from spacy.attrs import LANG
class SnekDefaults(Language.Defaults):
lex_attr_getters = dict(Language.Defaults.lex_attr_getters)
lex_attr_getters[LANG] = lambda text: "sk"
class SnekLanguage(Language):
lang = "sk"
Defaults = SnekDefaults
```
```python
from setuptools import setup
setup(
name="snek",
entry_points={
"spacy_languages": ["sk = snek:SnekLanguage"],
},
)
```
In spaCy, you can then load the custom `sk` language:
```python
from spacy.util import get_lang_class …
```

Improve entry points and allow custom language classes via entry points

---

spacy/cli/convert.py

The keyword argument `n_sents` to the converter functions was misspelled as `nsents`. 
Running `spacy convert -n [...]` resulted in `TypeError: conllu2json() got an unexpected keyword argument 'nsents'`
Bug fix

cli.convert: fix typo in converter arguments

---

spacy/cli/package.py
spacy/cli/train.py

This fixes #3093 for `spacy train`. Still need to check if it fixes `spacy package` for #3067, so it's a WIP.
Bug fix

Set vectors.name when updating meta.json during training

---

spacy/cli/evaluate.py

`spacy evaluate` fails on my system with 
```
File "/Users/fijabakk/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/Users/fijabakk/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/Users/fijabakk/src/spaCy/spacy/__main__.py", line 38, in <module>
plac.call(commands[command], sys.argv[1:])
File "/Users/fijabakk/src/spacy-nb/.venv/lib/python3.6/site-packages/plac_core.py", line 328, in call
cmd, result = parser.consume(arglist)
File "/Users/fijabakk/src/spacy-nb/.venv/lib/python3.6/site-packages/plac_core.py", line 207, in consume
return cmd, self.func(*(args + varargs + extraopts), **kwargs)
File "/Users/fijabakk/src/spaCy/spacy/cli/evaluate.py", …
```

spacy.cli.evaluate: fix TypeError

---

website/usage/_linguistic-features/_named-entities.jade
website/usage/_linguistic-features/_rule-based-matching.jade
website/usage/_linguistic-features/_sentence-segmentation.jade
website/usage/_linguistic-features/_tokenization.jade
website/usage/_visualizers/_ent.jade
website/usage/_visualizers/_html.jade
website/usage/visualizers.jade

Few fixes for typos and small grammatical errors in the documentation
documentation typo fix

Fixing few typos in the documentation

---

spacy/matcher.pyx
spacy/tests/regression/test_issue3009.py

The `?` quantifier indicates a token may occur zero or one times. If the
token pattern fit, the matcher would fail to consider valid matches
where the token pattern did not fit. Consider a simple regex like:
```.?b```
If we have the string 'b', the .? part will fit --- but then the 'b' in
the pattern will not fit, leaving us with no match. The same bug left us
with too few matches in some cases. For instance, consider:
```.?.?```
If we have a string of length two, like 'ab', we actually have three
possible matches here: [a, b, ab]. We were only recovering 'ab'. This
should now be fixed. Note that the fix also uncovered another bug, where
we weren't deduplicating the matches. There are actually two ways we
might match 'a' and two ways we might match 'b': as the second token of the pattern, …

Fix behaviour of Matcher's ? quantifier for v2.1

---

.github/contributors/alvaroabascar.md
spacy/tests/regression/test_issue2396.py
spacy/tokens/doc.pxd
spacy/tokens/doc.pyx
spacy/tokens/span.pyx

This PR fixes issue #2396: `Doc.get_lca_matrix` had a bug in [this line](https://github.com/explosion/spaCy/blob/master/spacy/tokens/doc.pyx#L739) which caused wrong outputs
for some pairs of tokens.
Bug fix
I borrow the following example from @slavi (#2396):
```python3
s = "He created a test for spacy"
doc = nlp(s)
doc.get_lca_matrix()[3][5]
```
- Expected output: 3
- Actual output: 1
The above mentioned line is:
```python3
...
else:
lca_index = __pairwise_lca(token_j.head, token_k.head, lca_matrix)
...
```
Here, for tokens 3 ("test") and 5 ("spacy"), we are calling `__pairwise_lca` recursively with their heads ("created" and "for" respectively). But in doing so, we are skiping "test", which is the actual lowest common ancestor.
The reimplementation consists on [this simple …

Fix issue 2396

---

spacy/tests/regression/test_issue1501-2000.py
spacy/tests/regression/test_issue2396.py
spacy/tokens/_retokenize.pyx

The `doc.retokenize()` context manager wasn't resizing `doc.tensor`, leading to a mismatch between the number of tokens in the doc and the number of rows in the tensor. We fix this by deleting rows from the tensor. Merged spans are represented by the vector of their last token.

💫 Resize doc.tensor when merging spans. Closes #1963

---

spacy/tests/doc/test_span.py
spacy/tokens/span.pyx
website/api/span.jade

Initially `span.as_doc()` was designed to return a view of the span's contents, as a `Doc` object. This was a nice idea, but it fails due to the `token.idx` property, which refers to the character offset within the string. In a span, the idx of the first token might not be 0. Because this data is different, we can't have a view --- it'll be inconsistent.
This patch changes `span.as_doc()` to instead return a copy. The docs are updated accordingly. Closes #1537

💫 Make span.as_doc() return a copy, not a view. Closes #1537

---

website/usage/_processing-pipelines/_multithreading.jade

The joblib link on https://spacy.io/usage/processing-pipelines#multi-processing-example is broken. Changed it to the official site on https://joblib.readthedocs.io/en/latest/parallel.html

Joblib site has moved.

---

.github/contributors/moreymat.md
setup.py
website/usage/_install/_instructions.jade

This PR adds, or rather restores, support for CUDA 10 now that cupy wheels are available : https://pypi.org/project/cupy-cuda100/ .
Support for CUDA 10 was introduced then withdrawn because wheels were not available at the time #2894 .

Support CUDA 10

---

spacy/tokens/span.pyx
spacy/tokens/token.pyx
website/api/span.jade
website/api/token.jade

I've updated the docstrings of `Span.subtree` and `Token.subtree`, to solve issue #3122.
- `Span.subtree` includes tokens within the span, but should not according to the documentation.
- `Token.subtree` includes the token, but should not according to the documentation.
See issue #3122 for more details.
Documentation

Correct docs of `Token.subtree` and `Span.subtree` (issue #3122)

---

spacy/lang/ja/__init__.py
spacy/lang/th/__init__.py
spacy/util.py

After #3065, I tried to reduce the number of skipped tests by installing other optional dependencies. The status of the only test in `lang/th/test_tokenizer.py` switched from `skipped` to `failed` after installing the latest `pythainlp==1.7.1` (or `pythainlp==1.6.0.7` on Python 2). The reason is that the test essentially uses `ThaiDefaults.create_tokenizer`, which falls back to `Language.Defaults.create_tokenizer`. I implemented `ThaiDefaults.create_tokenizer` using code that was previously in `Thai.make_doc`. I used `JapaneseTokenizer` as a reference. While on that, I also did some linting.
There are a couple of things I'm not quite sure about:
- `class Japanese` contained `Tokenizer = JapaneseTokenizer`, but https://spacy.io/api/language#class-attributes doesn't list `Tokenizer` as a …

Making `lang/th/test_tokenizer.py` pass by creating `ThaiTokenizer`

---

.github/contributors/DeNeutoy.md
spacy/cli/init_model.py

- Vectors are optional (as per the docs) but `init-model` crashes if they are not present
- Added a more graceful fallback to strings which are e.g a part of the Python grammar, making "ast.literal_eval(x)" break due to interpretation as code rather than strings.
Bugfix

Allow vectors to be optional in init-model, more robust string counting

---

MANIFEST.in
pyproject.toml
setup.py

The current way you have configured your build system does not comply with PEP 517 or PEP 518, which are very helpful when you have build system dependencies. It is recommended that you add a `pyproject.toml` with `build-system` to describe your build system dependencies, which will allow `pip install .` to "just work" out of the box (I have tested this and it works). Note that I also added it to the `MANIFEST.in` because [it is not currently included by default](https://github.com/pypa/setuptools/pull/1634) with even the latest setuptools.
While I was there, I noticed that you didn't have a `python_requires` in your `setup.py` and added one. This bit of metadata describes exactly which versions of Python are required to run your software. When you drop support for Python 3.4, add …

Build metadata modernization - pyproject.toml and python_requires

---

spacy/cli/ud/conll17_ud_eval.py
spacy/cli/ud/run_eval.py

usage: `run_eval.py out_path ud_dir [-p] [-t] [-m] [-f] [-b] [-l langs] [-c train]`
```
positional arguments:
out_path              Path to output CSV file
ud_dir                Path to Universal Dependencies corpus
optional arguments:
-h, --help            show this help message and exit
-p, --check-parse     Set flag to evaluate parsing performance
-l ar, ca, da, de, el, en, es, fa, fi, fr, ga, he, hi, hr, hu, id, it, ja, no, nl, pl, pt, ro, ru, sv, tr, ur, vi, zh, --langs ar, ca, da, de, el, en, es, fa, fi, fr, ga, he, hi, hr, hu, id, it, ja, no, nl, pl, pt, ro, ru, sv, tr, ur, vi, zh
Enumeration of languages to evaluate (default: all)
-t, --exclude-trained-models
Set flag to exclude trained models
-m, --exclude-multi   Set flag to exclude the multi-language model as
default baseline …
```

Batch UD evaluation script 

---

spacy/lang/fr/lemmatizer/lemmatizer.py
spacy/tests/regression/test_issue3178.py

This branch fixes an error in the handling of some words in French like "je" and "me".
The error is caused by an expected return type by FrenchLemmartizer. This callable class is supposed to return a list of strings but sometimes returns a list of a tuple containing one string.

Fix french lemmatization

---

spacy/displacy/__init__.py
spacy/util.py

Resolves #3208.
Prevent interactions with other libraries (pandas) that also access `get_ipython().config` and its parameters. See #3208 for details. I don't fully understand why this happens, but in spaCy, we can at least make sure we avoid calling into this method.

Don't check for Jupyter in global scope and fix check

---

spacy/lang/ca/__init__.py
spacy/lang/ca/punctuation.py
spacy/lang/fr/tokenizer_exceptions.py
spacy/tests/lang/ca/test_prefix_suffix_infix.py
spacy/tests/lang/ca/test_text.py

Added the same infix rule as in French (`d'une`, `j'ai`) for Catalan (`d'un`, `s'ha`), bringing F-score on `ca_ancora-ud-train.txt` from 93% to 99%. Added unit test to check this behaviour.
Also did a small aestethic clean-up of two French regular expressions.
Enhancement of Catalan tokenization

Improve Catalan tokenization accuracy

---

spacy/lang/it/__init__.py
spacy/lang/it/punctuation.py
spacy/lang/ur/__init__.py
spacy/lang/ur/punctuation.py
spacy/tests/conftest.py
spacy/tests/lang/it/test_prefix_suffix_infix.py
spacy/tests/lang/ur/test_prefix_suffix_infix.py
spacy/tests/lang/ur/test_text.py

1. Added the same infix rule as in French (`d'une`, `j'ai`) for Italian (`c'è`, `l'ha`), bringing F-score on `it_isdt-ud-train.txt` from 96% to 99%. Added unit test to check this behaviour.
2. Added specific Urdu punctuation character as suffix, improving F-score on `ur_udtb-ud-train.txt` from 94% to 100%. Added unit test to check this behaviour.
Enhancement of Italian & Urdu tokenization

Improve Italian & Urdu tokenization accuracy

---

spacy/gold.pyx
spacy/tests/test_gold.py

I was writing examples for a new docs section and noticed that the path from BILUO tags to `doc.ents` was unnecessarily frustrating if you want to set the `doc.ents` as entity spans instead of offsets (unless I'm missing something?).
`gold.spans_from_biluo_tags` takes a `Doc` and a list of tags and returns a list of labeled `Span` objects.`gold.offsets_from_biluo_tags` now delegates to this helper.
On a related note: It should technically be possible to also set `doc.ents` from the offsets returned from `offsets_from_biluo_tags`. However, setting the `doc.ents` from offsets currently requires the labels to be integers, which isn't consistent with the new API. So this should be fixed as well.
(In general, I do prefer instantiating and using `Span` objects to overwrite the `doc.ents`, as …

💫 Add gold.spans_from_biluo_tags helper

---

spacy/errors.py
spacy/matcher/phrasematcher.pyx
spacy/tests/matcher/test_phrase_matcher.py

In most cases, the `PhraseMatcher` will match on the verbatim token text (`ORTH`) or as of v2.1, sometimes the lowercase text (`LOWER`). This means that we only need a tokenized Doc, without any other attributes.
If phrase patterns are created by processing large terminology lists with the full `nlp` object, this easily can make things a lot slower, because all components will be applied, even if we don't actually need the attributes they set (like part-of-speech tags, dependency labels). So this PR adds a suggested feature for validating phrase patterns on `PhraseMatcher.add` by checking the attribute to match on and whether the pattern `Doc` objects are tagged or parsed.  For now, the validation has to be enabled explicitly by setting `validate=True`.
The warning message also includes …

💫 Suggestion: PhraseMatcher pattern validation

---

spacy/cli/debug_data.py
spacy/errors.py
spacy/matcher/_schemas.py
spacy/matcher/matcher.pxd
spacy/matcher/matcher.pyx
spacy/matcher/phrasematcher.pyx
spacy/tests/doc/test_to_json.py
spacy/tests/matcher/test_pattern_validation.py
spacy/tests/test_json_schemas.py
spacy/util.py

If `validate=True` is set on the `Matcher` on intialisation, all patterns that are added will be validated against a JSON schema. If errors are found, a `MatchPatternError` will be raised. The JSON schema produces very helpful hints and errors here – from type checking to additional properties and so on.
**Question:** Should `validate` default to `True` or `False` / should we validate by default and let the user disable it, or should we only validate if explicitly enabled? Always validating seems friendlier to beginners?
```
In [3]: matcher.add('TEST', None, [{"LENGTH": {"IN": [1, 2, "3"]}}, {"POS": {"IN": "VERB"}}], [{"foo": "bar"}])       
---------------------------------------------------------------------------
MatchPatternError                         Traceback (most recent call …
```

💫 Add token match pattern validation via JSON schemas

---

spacy/matcher/phrasematcher.pyx
spacy/tests/regression/test_issue3248.py

@honnibal Is there any problem with keeping the docs on `Phrasematcher` as `PhraseMatcher._docs`?
bug fix

💫 Fix PhraseMatcher pickling and length (resolves #3248)

---

spacy/errors.py
spacy/tests/regression/test_issue2833.py
spacy/tokens/token.pyx

Raises a better error with a more helpful message in `Token.__reduce__`. This should probably also be mentioned in the new "saving and loading" docs.
small enhancement

💫 Raise better error if token is pickled (resolves #2833)

---

spacy/errors.py
spacy/tests/doc/test_doc_spilt.py
spacy/tokens/_retokenize.pyx

Adds the capacity to split tokens
Implemented the feature as described in #2838. I added several error messages, and a new test suite for the functionality.
The tests passed with 554 warnings, but I think this is not related to this change.
Does this change require new documentation?
New feature and new tests.

Add split one token into several (resolves #2838)

---

spacy/cli/ud/ud_run_test.py
spacy/cli/ud/ud_train.py
spacy/displacy/__init__.py
spacy/errors.py
spacy/pipeline/functions.py
spacy/tests/doc/test_doc_api.py
spacy/tests/doc/test_span_merge.py
spacy/tests/lang/test_initialize.py
spacy/tests/matcher/test_matcher_api.py
spacy/tests/parser/test_parse.py
spacy/tests/regression/test_issue1-1000.py
spacy/tests/regression/test_issue1501-2000.py
spacy/tokens/doc.pyx
spacy/tokens/span.pyx

As of v2.1, `Doc.merge` and `Span.merge` will still work, but they'll be officially considered deprecated. Instead, the more efficient and less error-prone `Doc.retokenize` contextmanager should be used. This PR fixes this across the code base and tests.

💫 Replace {Doc,Span}.merge with Doc.retokenize

---

spacy/lang/punctuation.py
spacy/tests/regression/test_issue3277.py

Resolves #3277.
Tested adding dashes to the prefixes and suffixes and it doesn't break anything else.
fix / enhancement

💫  Add en/em dash to prefixes and suffixes 

---

spacy/lang/ca/examples.py

Catalan typo in the examples file. 
Language typo.

Typo error fixed in examples

---

spacy/matcher/matcher.pyx
spacy/tests/matcher/test_matcher_api.py
spacy/tests/regression/test_issue1971.py

* Fix detection of match_id when using extension attributes. The match
ID is stored as the last entry in the pattern. We were checking for this
with nr_attr == 0, which didn't account for extension attributes.
* Fix handling of predicates. The wrong count was being passed through,
so even patterns that didn't have a predicate were being checked.

💫 Fix bugs in matcher extensions. Closes #1971

---

spacy/tests/regression/test_issue3288.py
spacy/tokens/_retokenize.pyx

The code to resize the `doc.tensor` inside `Retokenizer.merge()` assumed the wrong input shape, leading to errors.

Fix issue #3288

---

spacy/errors.py
spacy/tests/doc/test_retokenize_merge.py
spacy/tests/doc/test_retokenize_split.py
spacy/tests/regression/test_issue1971.py
spacy/tokens/_retokenize.pyx
spacy/tokens/underscore.py
website/docs/api/doc.md
website/docs/usage/linguistic-features.md

This PR adds the abilility to override custom extension attributes during merging. This will only work for attributes that are writable, i.e. attributes registered with a default value like `default=False` or attribute that have both a getter *and* a setter implemented.
```python
Token.set_extension('is_musician', default=False)
doc = nlp("I like David Bowie.")
with doc.retokenize() as retokenizer:
attrs = {"LEMMA": "David Bowie", "_": {"is_musician": True}}
retokenizer.merge(doc[2:4], attrs=attrs)
assert doc[2].text == "David Bowie"
assert doc[2].lemma_ == "David Bowie"
assert doc[2]._.is_musician
```
enhancement

💫 Allow setting of custom attributes during retokenization (closes #3314)

---

spacy/lexeme.pxd
spacy/tests/doc/test_retokenize_merge.py
spacy/tests/doc/test_retokenize_split.py
spacy/tokens/_retokenize.pyx
website/docs/api/doc.md
website/docs/usage/linguistic-features.md

`attrs` in `Retokenizer.merge` and `Retokenizer.split` can now also include lexical attributes and binary flags (like `LOWER`, `IS_STOP` or `LIKE_NUM`). Those will be set on the lexeme, so they'll be valid for all entries in the vocabulary, not just that particular token in context.
enhancement

💫 Support lexical attributes in retokenizer attrs (closes #2390)

---

spacy/tests/doc/test_token_api.py
spacy/tokens/doc.pyx
website/docs/api/token.md

We had `doc[0].is_sent_start == None` for reasons, but on the whole, that's dumb. We know the first token should start a sentence, so just set it. We ensure that `doc.is_sentenced` remains `False` if `doc[0].is_sent_start` is the only value set.

Make doc[0].is_sent_start == True (closes #2869)

---

.github/contributors/adrienball.md
spacy/cli/download.py

The egg fragment in the URL must be of the form `#egg=package_name==version` instead of `#egg=package_name-version`.
One of the consequences of specifying wrong egg fragments is that `pip` does not recognize the package and its version properly, and thus it re-downloads the package systematically.
I'm not sure how this should be tested properly. 
Here is what I had before the fix when running the same direct download twice:
```
$ python -m spacy download en_core_web_sm-2.0.0 --direct
Looking in indexes: https://pypi.python.org/simple/
Collecting en_core_web_sm-2.0.0 from https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz#egg=en_core_web_sm-2.0.0
Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2 …
```

Fix egg fragments in direct download

---

spacy/cli/download.py

If a user runs `spacy download en`, we need to resolve it to `en_core_web_sm` and then link the installed model to the shortcut `en` afterwards, so it can be loaded as `spacy.load('en')`. However, if the user runs `spacy download en_core_web_sm`, there's not really a need for an additional symlink. If anything, it makes things more error-prone, because there's a change of an outdated stale symlink. And if the user doesn't have admin permissions and can't write symlinks to `spacy/data`, it shows a warning, even though there's nothing really wrong and the symlink wouldn't have mattered anyways.
This PR fixes this by only symlinking if the specified model name is in the dictionary of shortcuts. It also shows a better success message and fixes the existing messages.
enhancements, small fixes

💫 Only link model after download if shortcut link

---

spacy/syntax/_parser_model.pyx
spacy/syntax/_state.pxd
spacy/syntax/ner.pyx
spacy/syntax/nn_parser.pyx
spacy/tests/regression/test_issue3345.py

Refactor and update constraints that determine which NER transitions are
valid in a given state.
Previously, no valid actions were available if a preset entity crossed
a sentence boundary. Closes #3345.

💫 Fix NER when preset entities cross sentence boundaries

---

spacy/tests/serialize/test_serialize_vocab_strings.py
spacy/vocab.pyx

When deserializing, the vocab did not check whether a lexeme already existed for the data it was loading back in. We'd just save the lexeme into the hash. The vocab wouldn't actually store a duplicate entry, as the key would be there --- but we'd increment the length counter. We'd also allocate a new Lexeme object, so if you kept doing this, you'd waste a bit of memory.

Fix vocab deserialization when loading already present lexemes

---

.github/contributors/tmetzl.md
website/usage/_visualizers/_html.jade

Fixed a typo in the example (changed sentence to sent)
Typo in example causing it to throw an error

Fixed typo in example of html visualizer

---

spacy/tests/doc/test_underscore.py
spacy/tokens/underscore.py
website/docs/usage/processing-pipelines.md

Also see #2581.
Closes #3036.
> When using **mutable values** like dictionaries or lists as the `default` argument, keep in mind that they behave just like mutable default arguments [in Python functions](http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments). This can easily cause unintended results, like the same value being set on _all_ objects instead of only one particular instance. In most cases, it's better to use **getters and setters**, and only set the `default` for boolean or string values.
```python
Doc.set_extension('mutable', default=[])
doc1 = nlp("Hello world")
doc2 = nlp("What's up?")
doc1._.mutable.append("foo")
print(doc1._.mutable)  # ['foo']
print(doc2._.mutable)  # []
```
enhancement

💫 Support mutable default values for extension attributes

---

spacy/tests/doc/test_token_api.py
spacy/tokens/span.pyx
spacy/tokens/token.pyx
website/docs/api/span.md
website/docs/api/token.md

Previously the `token.conjuncts` method was pretty broken (as reported in #795 ), which is a shame because it should be very useful.
The docs say `token.conjuncts` should return the word itself, but I think this will be inconsistent, as if a word has no conjuncts it should return an empty tuple. Therefore the consistent (and probably more useful) behaviour is to return all *other* conjuncts in the chain. This doesn't break backwards compatibility, as the feature was broken anyway, and the example in the docs actually showed the word itself *not* being returned in the set.
I've also added a `span.conjuncts` to keep the token and span APIs aligned. It delegates to `span.root.conjuncts`.

Fix token.conjuncts (closes #795)

---

spacy/displacy/__init__.py
spacy/displacy/render.py
spacy/displacy/templates.py
spacy/tests/test_displacy.py

Closes #2091.
With the new `vocab.writing_system` property introduced in #3390 (exposed via the language defaults), I was able to finally fix this (I think!). Based on the `Doc`, dispaCy now detects whether it's a RTL or LTR language and adjusts the visualization accordingly. Wherever possible, I've also added `direction` and `lang` attributes.
Entity visualization now looks like this:
And dependencies like this (ignore the most likely incorrect tags and dependencies):
enhancement, bug fix

💫 Fix displaCy support for RTL languages

---

spacy/errors.py
spacy/tests/doc/test_span.py
spacy/tokens/span.pyx

Revert part of PR https://github.com/explosion/spaCy/pull/3031 which made `Span.label_` writable. This can get confusing when e.g. running something like 
```
for ent in doc.ents:
ent.label_ = "GPE"
```
Which wouldn't actually write the "GPE" annotation to the underlying `Token` / `doc` objects. With this PR, the above code isn't executable anymore and will throw a `NotImplementedError` similar to the one as implemented for property `ent_id`.
Functionality change

label in span not writable anymore

---

spacy/cli/pretrain.py
website/docs/api/cli.md

Add and document CLI options for batch size, max doc length, min doc length for `spacy pretrain`.
Also improve CLI output.
Closes #3216

Expose batch size and length caps on CLI for pretrain

---

spacy/_ml.py

While developing v2.1, I ran a bunch of hyper-parameter search
experiments to find settings that performed well for spaCy's NER and
parser. I ended up changing the default Adam settings from beta1=0.9,
beta2=0.999, eps=1e-8 to beta1=0.8, beta2=0.8, eps=1e-5. This was giving
a small improvement in accuracy (like, 0.4%).
Months later, I run the models with Prodigy, which uses beam-search
decoding even when the model has been trained with a greedy objective.
The new models performed terribly...So, wtf? After a couple of days
debugging, I figured out that the new optimizer settings was causing the
model to converge to solutions where the top-scoring class often had
a score of like, -80. The variance on the weights had gone up
enormously. I guess I needed to update the L2 regularisation as …

Revert changes to optimizer default hyper-params (WIP)

---

spacy/cli/converters/jsonl2json.py
spacy/gold.pyx

Generation of spaCy's unideal json training format was broken, as we merged work towards replacing it with the jsonl format. However, we didn't want to fully deprecate the json format it 2.1, as it's a breaking change. This patch reverts a minor breakage we introduced during this, to the `spacy.gold.docs_to_json` function.

Fix jsonl to json conversion

---

.github/CONTRIBUTOR_AGREEMENT.md
.github/contributors/Bharat123rox.md
spacy/__init__.py
spacy/errors.py

Fix #3426 by raising a `ValueError` if a narrow unicode build is detected.
A generic `ValueError` has been provided (Is it correct?). The error message is provided with a slight modification from [here](https://spacy.io/usage#narrow-unicode). IMO, I felt a `UnicodeDecodeError` or `UnicodeEncodeError` doesn't fit here. In case the error message has to be improved, do let me know!

Raise Error for a narrow unicode build of Python

---

spacy/lang/en/morph_rules.py
spacy/lang/en/tag_map.py

I wrote a small script to read the UD English training data and check
that our tag map and morph rules were resulting in the best POS map.
This hadn't been done for some time, and there have been various changes
to the UD schema since it has been done. After these changes we should
see much better agreement between our POS assignments and the UD POS
tags.
The following cases were clear-cut misassignments in the tag map. The format here is the previous tag map mapping (of `TAG->POS`) followed by the frequency distribution observed. For instance, we had mapped `MD` to `VERB`, but in the UD data `MD` maps to `AUX` 3294 times, and no other tag ever. 
```
MD->VERB  [('AUX', 3294)]
PRP$->DET  [('PRON', 3063)]
WDT->DET [('PRON', 855), ('DET', 93)]
RP->PART [('ADP', 746), ('ADV', 9)]
EX->ADV …
```

💫 Bring English tag_map in line with UD Treebank

---

spacy/compat.py
spacy/tests/regression/test_issue3356.py
spacy/tokenizer.pyx

spaCy v2.1 switched to the built-in re module, where v2.0 had been using
the third-party regex library. When the tokenizer was deserialized on
Python2.7, the `re.compile()` function was called with expressions that
featured escaped unicode codepoints that were not in Python2.7's unicode
database.
Problems occurred when we had a range between two of these unknown
codepoints, like this:
```
'[\\uAA77-\\uAA79]'
```
On Python2.7, the unknown codepoints are not unescaped correctly,
resulting in arbitrary out-of-range characters being matched by the
expression.
This problem does not occur if we instead have a range between two
unicode literals, rather than the escape sequences. To fix the bug, we
therefore add a new compat function that unescapes unicode sequences
using the `ast.literal_eval()` …

Fix tokenizer on Python2.7

---

examples/training/train_textcat.py
spacy/_ml.py
spacy/pipeline/pipes.pyx
website/docs/api/textcategorizer.md

* Fixed bug in the `"ensemble" architecture that prevented the unigram bag-of-words submodel from working properly.
* Cleaned up redundant code for bag-of-words feature extraction in `spacy._ml`
* Implemented better layer for extracting ngram features
* Added new `"bow"` architecture for text categorizer, to do purely bag-of-words textcat.
* Updated docs with better explanation of textcat architectures, and noted the new options.

Bug fixes and options for TextCategorizer

---

spacy/lang/en/stop_words.py
spacy/tests/regression/test_issue3449.py
spacy/tests/regression/test_issue3521.py

Fixing Issue https://github.com/explosion/spaCy/issues/3521: Contraction `n’t` not tagged as stop word.
- I removed the English stop words with a hyphen from the generic stop list and added a small loop that for each such hyphenated stopword, adds all variants with all potential hyphens.
- I added a relevant unit test that succeeds after implementing above fix
- I added a failing unit test for Issue https://github.com/explosion/spaCy/issues/3449 (an issue I looked into before but can't be fixed generically)
Small fix

Allow English stopwords with any type of apostrophe

---

.github/contributors/xssChauhan.md
spacy/cli/convert.py

`spacy convert` is currently outputting `jsonl` files, and that is creating issues while training new models. The issue is easily subverted by using `json` output format instead of `jsonl`.
This PR changes the default output format from `jsonl` to `json`.
Fixes #3523 

Change default output format from `jsonl` to `json` for cli convert

---

spacy/cli/evaluate.py
spacy/cli/train.py

- early stopping option in `spacy train`
- return scores option in `spacy evaluate`
- fix bug: `spacy train` did not convert output path from string to Path
While I haven't seen any issues related to early stopping or returning evaluation scores,
I have implemented it because I needed it for my own use. The bug I have found obviously needs fixing, as for the two new features:
- Early stoppping stops training after the validation score did not improve for N iterations (a new optional parameter to `spacy train`) - it is much easier to impelment inside `spacy train` than anywhere else, it does not break API nor any conventions mentioned in contributing guide and should be useful for most people.
- `return_scores` option for `spacy evaluate` makes it return a dict of metric values when called …

Improved training and evaluation

---

.github/contributors/BreakBB.md
spacy/compat.py
spacy/tests/test_misc.py

When the creation of symlinks fails on Windows (for example because the user doesn't have the required permissions) the user now correctly sees the corresponding error message. Before the fix the user would simply see the error message of `mklink`, but a success from spaCy, when installing a module with:
`python -m spacy download de`
> Collecting de_core_news_sm==2.1.0 from https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.1.0/de_core_news_sm-2.1.0.tar.gz#egg=de_core_news_sm==2.1.0
>   Downloading https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.1.0/de_core_news_sm-2.1.0.tar.gz (11.1MB)
> Installing collected packages: de-core-news-sm
>   Running setup.py install for de-core-news-sm: started
>     Running setup.py install for …

Fix symlink creation to show error message on failure

---

CONTRIBUTING.md
website/README.md

Minor updates to documentation for building the website locally. This closes #3648.
CONTRIBUTING.md contained instructions for the old harp web server. This was replaced with a reference to website/README.md. In that file the only change was to add a note that Node 10.15 or later is required.
Note: this PR replaces #3649 which was improperly branched off a set of unrelated changes.
Simple doc change only.

Updates to docs for website build

---

.github/contributors/amitness.md
website/docs/usage/101/_serialization.md

On the serialization section of the Spacy 101 docs, the link to the section on pickle protocol in the book 'Dive into Python 3' was broken. I've updated the link to point to the currently working link for the same.
Reproduce steps:
- Goto the section on [Serialization](https://spacy.io/usage/spacy-101#serialization)
- Click on link for 'Pickle protocol'.
- A 404 page is reached.
Changes to the documentation

Fix broken link to Dive Into Python 3 website

---

spacy/lang/de/stop_words.py
spacy/lang/fr/examples.py

I updated the French example sentences as suggested in [this comment](https://github.com/explosion/spaCy/issues/1107#issuecomment-352291273) a while back. And added the two German stop words "anderem" and "ihren" which where missing but similar to the existing ones.
Minor enhancement

Update French example sents and add two German stop words

---

website/UNIVERSE.md
website/src/templates/universe.js

Re-added Universe readme. This fixes a broken link on the website, specifically at the bottom of the [Universe page.](https://spacy.io/universe). This closes issue https://github.com/explosion/spaCy/issues/3680.
Documentation.

Re-added Universe readme

---

spacy/tests/doc/test_span.py
spacy/util.py
website/docs/api/top-level.md

Inspired by #3681.
Filter a sequence of spans and remove duplicates or overlaps. Useful for creating named entities (where one token can only be part of one entity) or when merging spans with `Retokenizer.merge`. When spans overlap, the (first) longest span is preferred over shorter spans.
enhancement

💫 Add util.filter_spans helper

---

.github/contributors/richardpaulhudson.md
website/meta/universe.json

Dear spaCy team, I would be grateful if you would consider my Python library Holmes for inclusion in the spaCy Universe. Holmes transforms the syntactic structures delivered by spaCy into semantic structures that, together with various other techniques including ontological matching and word embeddings, serve as the basis for information extraction. Holmes supports several use cases including chatbot, structured search, topic matching and supervised document classification. I had the basic idea for Holmes around 15 years ago and now spaCy has made it possible to build an implementation that is stable and fast enough to actually be of use - thank you! At present Holmes supports English and German (I am based in Munich) but could easily be extended to support any other language with a spaCy …

Request to include Holmes in spaCy Universe

---

spacy/cli/pretrain.py
website/docs/api/cli.md

As it was discussed in the issue #3694, the PR modifies `pretrain` function a bit to make it possible skip `text` attribute in the JSONL records when `tokens` attribute is provided.
The only change is moving dictionary key access into the `else` branch of conditional logic. Also, the docs were adjusted a bit to reflect the new behavior. Though probably this update should be a bit more clear and verbose than my version. Please let me know if this should be re-written to become more explicit, or if something else should be added.
I didn't run the tests because it seems that the [`test_cli.py`](https://github.com/explosion/spaCy/blob/master/spacy/tests/test_cli.py) doesn't test the function that was modified, and it will not show any changes in behavior even if they were introduced. I can …

Make "text" key in JSONL format optional when "tokens" key is provided

---

spacy/tests/doc/test_underscore.py
spacy/tokens/underscore.py

Resolves #3707.
* Make `Underscore` expose custom `__dir__` that lists the extension attribute names. This enables auto-completion for `doc._` etc.
* Port over docstrings for custom extension methods (previously not available because functions were used as partials).
enhancement

💫 Improve introspection of custom extension attributes

---

spacy/errors.py
spacy/language.py
spacy/tests/pipeline/test_pipe_methods.py

I added a check for the `__call__` attribute of the component to `replace_pipe` just like the `add_pipe` method does it. This prevents to use `replace_pipe` with something that is not a valid pipe/callable.
The test got extended to check for the error when something that is not a callable is handed to the method.
Enhancement

Add check for callable to 'Language.replace_pipe' to fix #3737

---

website/docs/usage/models.md

The URL used to show how to add a model to the requirements.txt had the old release path (excl. explosion).
Change in documentation.

Corrected example model URL in requirements.txt

---

requirements.txt
setup.py
spacy/errors.py
spacy/matcher/matcher.pyx
spacy/util.py

The [`jsonschema`](https://github.com/Julian/jsonschema) library is great, but it also draws in various other [third-party dependencies](https://github.com/Julian/jsonschema/blob/3b8e3da631c5499f20468eb9154df603afbdc2b0/setup.cfg#L28-L33). Since `jsonschema` is only really used in additional validation features (setting `validate=True` on the `Matcher` and `PhraseMatcher`, or in the new and currently experimental/undocumented `debug-data` command), this PR makes it an optional dependency.
If it's not installed, the user will see an error and installation instructions for `jsonschema`.
installation improvement

💫 Make jsonschema dependency optional

---

spacy/gold.pyx
spacy/matcher/phrasematcher.pyx
website/docs/api/annotation.md

The current code base was a mix of BILUO and BILOU when referring to the popular NER annotation format. Was confusing especially when searching for the phrase in the documentation.
Since BILUO is more commonly used across the package, all references to BILOU have been replaced with BILUO.(_also made sense to put O (OUT) at the outside of the abbreviation)_
- Two edits to comments/documentation
- One edit to a function name

Fix all references to BILUO annotation format

---

website/meta/universe.json

Add Baderlab/saber to universe.json

---

.github/contributors/munozbravo.md
spacy/lang/es/__init__.py
spacy/lang/es/lex_attrs.py
spacy/tests/regression/test_issue3803.py

Issue #3803
Added `test_issue3803.py`within *regression/* to test True for spanish num-like tokens.
Added `lex_attrs.py`within *lang/es/* to overwrite default getter for `like_num` and include spanish words for numbers.
Modified `__init__.py` within *lang/es/* to import `LEX_ATTRS` and update `lex_attr_getters` within `SpanishDefaults`.
Added `munozbravo.md` to *.github/contributors/* as specified for Contributor Agreement. 
enhancement
lang/es

Overwrites default getter for like_num in Spanish by adding _num_words and like_num to lex_attrs.py

---

spacy/cli/pretrain.py
website/docs/api/cli.md

Adds resume logic to `spacy pretrain` after some discussion here: https://github.com/explosion/spaCy/pull/3510#issuecomment-478334698
Save this file to `sample_sents.jsonl`
```
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
{"text": "hello there."}
```
Then run `spacy pretrain`.
```bash
spacy pretrain sample_sents.jsonl en_core_web_md here -nw 1 -bs 1 -i 10 -uv -se 2
```
There will be some files in the `here` directory. You can load one of the pre-trained weights by: …

Add resume logic to spacy pretrain

---

spacy/cli/pretrain.py
spacy/errors.py
spacy/tests/test_cli.py
website/docs/api/cli.md

This PR adds some checks for the input of the CLI pretrain command as discussed in #3840. Those are:
- empty input file
- input file contains something else than a JSON object (per line)
- neither the `text` nor the `tokens` key is provided
Moreover empty values for the keys are skipped, counted and logged as a warning after pretrain. The `make_docs` function is also tested now except for the undocumented `heads` key.
Enhancement

Update error raising for CLI pretrain to fix #3840

---

bin/train_word_vectors.py

This changes the vector training script to work with the more recent Gensim Word2Vec interface. 
The old script counted words and built a dictionary of word counts on its own before handing the raw text (not using the spaCy tokenizer) to Gensim directly. I am not exactly sure why that was done and I had trouble getting it to work with the new interface, so I modified the `Corpus` to use the spaCy tokenizer and just let Gensim handle the `min_count` and everything else.
I successfully used this script to train vectors on Japanese Wikipedia.
This is a bug fix.

Change vector training to work with latest gensim (fix #3749)

---

.github/contributors/elbaulp.md
website/docs/usage/training.md

I've been searching for a while how the parameter learning rate was named, with `beta1` and `beta2` its easy as they are marked as code, but learning rate wasn't. I think writing the actual parameter name would be helpful.

Changed learning rate by its param name.

---

spacy/cli/pretrain.py
spacy/errors.py
website/docs/api/cli.md

Some updates and adjustments to the pretrain docs. Also added an error when an unsupported loss_func is handed to `pretrain`.
Improvement

Update pretrain docs and add unsupported loss_func error

---

.github/contributors/kognate.md
spacy/pipeline/entityruler.py
spacy/tests/regression/test_issue3526.py

Added support for serializing `overwrite` and `ent_id_sep`
This PR fixes #3526 and serializes `overwrite` and `ent_id_sep`.   I tried to follow patterns I found in `nn_parser.pyx` and `Sentencizer` for the bytes and file-based serialization changes.  New tests include (similar) example from the issue itself, and a test of the `to_bytes`/`from_bytes` serialization.
The code handles restoring from serialized objects from the previous format and should be fully backwards compatible (serialized elements from before this change can be deserialized).  
This is a bug fix and does not change overall functionality.

Added support for serializing overwrite and ent_id_sep

---

spacy/scorer.py

Now each ent score is tracked individually in order to have its own Precision, Recall and F1 Score.
This issue is discussed here in #3490. 
~~This is an ongoing pull request, there is still a few things to do.~~
This is an enhancement to show scores per entity tag, in addition to the overall scores.

Evaluation of NER model per entity type, closes #3490

---

spacy/cli/pretrain.py
website/docs/api/cli.md

This PR fixes #3859. It tries to parse the epoch number from the given weight file name from `--init-tok2vec`.
For the situation where the weight file has been renamed and does not match the ' modelX.bin' pattern the `--epoch-start` argument was introduced. This is an integer which has to be greater or equal to 0.
Bug fix

Update pretrain to prevent unintended overwriting of weight files

---

spacy/tokens/doc.pyx
website/docs/api/doc.md
website/docs/api/tokenizer.md

This PR:
- updates the documentation examples of the tokenizer creation to fix #3892 
- updates the `Doc.__init__` example in the methods docstring
- fixes the hyperlink to `Doc.to_json`
Documentation changes

Update tokenizer and doc init example 

---

requirements.txt
spacy/errors.py
spacy/pipeline/pipes.pyx

Provide more friendly errors when the `textcat` pipeline was been initialised incorrectly (e.g. no labels were added to the component), cf Issue https://github.com/explosion/spaCy/issues/3912.
* call the new `require_labels` in `begin_training` when initializing a new Model
* call `require_model` in `update`
* upgrade `thinc` in the requirements to `7.0.5` to ensure `test_issue3880` (https://github.com/explosion/spaCy/issues/3880) doesn't fail
small enhancements

more friendly textcat errors

---

spacy/lang/da/punctuation.py
spacy/lang/da/tokenizer_exceptions.py
spacy/tests/lang/da/test_exceptions.py

I've implemented changes to make the Danish tokenizer split on forward slash to make it work properly with terms separated by forward slash, such as "Bus/tog/metro" (busses, trains, metro).  This makes it behave identically to the English tokenizer in this regard. Since there are several abbreviations that contain forward slash (and which should be treated as one token), I've added exceptions for (most of?) these.
Also, I ran Black on the Danish `punctuation.py` to convert a few remaining single quotes to double quotes.
This is an enhancement to the Danish tokenizer.

Make Danish tokenizer split on forward slash

---

spacy/gold.pyx
website/docs/api/goldparse.md
website/docs/usage/linguistic-features.md

Here's a suggested docstring for the `spacy.gold.align` function. Wordpiece tokenization is becoming increasingly popular, now that people are using BERT etc. This makes it worth exposing the alignment utilities in spaCy more prominently.

💫 Document spacy.gold.align

---

website/docs/api/annotation.md

Update annotation docs to match use in Tiger:
- minor formatting fixes
- remove STTS tags not used in Tiger
- update list of dependency relations to match tiger2dep

Update annotation docs for German

---

spacy/tests/regression/test_issue3962.py
spacy/tokens/doc.pyx
spacy/tokens/span.pyx

The `span.as_doc` functionality seems to have some issues (cf. Issue #3962 and Issue #3669) which I think are related to the dependency graph being cut into pieces. Some tokens may still refer to other tokens outside the `span`, thus resulting in an out of bounds error when that token is being accessed.
In `doc.from_array` I have added code that checks the offset of the head for each token, and does not copy the value unless that token is inside the doc : `if (i+value) in range(self.length)`. The token head defaults to 0 (i.e. itself) if the value is not copied/set.
This fix feels a little hacky, so happy to get feedback. Also currently the actual dependency link (e.g. `ccomp`) is being copied even if the head isn't, but I think we need that to ensure other cases keep working where a …

Fix dependency copy for as_doc

---

bin/wiki_entity_linking/kb_creator.py
bin/wiki_entity_linking/training_set_creator.py
bin/wiki_entity_linking/wikipedia_processor.py
examples/pipeline/dummy_entity_linking.py
examples/pipeline/wikidata_entity_linking.py
spacy/_ml.py
spacy/errors.py
spacy/gold.pxd
spacy/gold.pyx
spacy/kb.pxd
spacy/kb.pyx
spacy/pipeline/pipes.pyx
spacy/structs.pxd
spacy/tests/pipeline/test_entity_linker.py
spacy/tests/serialize/test_serialize_kb.py
spacy/tokenizer.pyx

Made some small adjustements that make the NEL functionality resemble the code for the other pipes more closely. This will be followed by another PR which has the (updated) documentation for all this functionality.
* `gold.links` is now a dictionary with `(ent.start_char, ent.end_char)` keys and the values being dicts with `kb_id:value` entries, representing the KB IDs mapped to either 1.0 or 0.0, indicating positive and negative examples respectively. This is similar to the `gold.cats` field for text classification.
* For training, all the `kb_id: value` combinations are used, including the negative cases
* For testing (accuracy measurement), only the positive cases are checked
* `gold.links` now corresponds 1-to-1 to `doc.ents` which allows a more proper chaining of …

API changes for Entity linking functionality

---

spacy/errors.py
spacy/pipeline/pipes.pyx
spacy/syntax/nn_parser.pyx

When Thinc's model.from_bytes() is called with a mismatched model, often
we get a particularly ungraceful error,
e.g. "AttributeError: FunctionLayer has no attribute G"
This is because we're trying to load the parameters for something like
a LayerNorm layer, and the model architecture has some other layer there
instead. This is obviously terrible, especially since the error *type*
is wrong.
I've changed it to raise a ValueError. The error message is still
probably a bit terse, but it's hard to be sure exactly what's gone
wrong.

💫 Improve error message when model.from_bytes() dies

---

website/docs/api/goldparse.md

* add `words`
* update name of entity list to `ner`
I think it might be a bit more consistent to have `ner` named `entities` or `ents` (and `ents` is actually set somewhere to `None`, which is a bit confusing), but it looks like renaming it would be a non-trivial decision.
Documentation.

Update GoldParse attributes in API docs

---

spacy/util.py

This PR adds support for an optional `"lang_factory"` name in the `meta.json` that will be used to initialize the base language class on load (instead of `"lang"`).
For instance, imagine an extension package that implements a custom `Language` subclass (e.g. to integrate another machine learning model or library). Models depending on this package can require it in their `setup.py` and if the custom `Language` class is registered as a `spacy_languages` entry point, it can be initialized automatically on load. For example: `xyz = some_package:CustomLanguage`.
However, `Language` subclass != human language. Given the entry point for `xyz`, the model package would now have to specify `"lang": "xyz"` and be called `xyz_model_name`. If the custom subclass is language-agnostic, you'd have to …

💫 Support custom language factory setting in meta.json

---

spacy/language.py
spacy/tests/test_language.py
website/docs/api/language.md

* Support passing in `(text, annotations)` tuples in `nlp.evaluate` instead of just `(doc, gold)` tuples (to match `nlp.update`).
* Add tests to make sure updating and evaluating with both formats works.
enhancement

💫 Support simple training format in nlp.evaluate and add tests

---

spacy/pipeline/pipes.pyx
spacy/tests/regression/test_issue4030.py

Bugfix for Issue #4030 "TextCategorizer crashes on an empty text".
In `TextCategorizer`.`predict()`, set the `scores` to a matrix of `zeros` when there are no tokens in any `docs`.
Added unit test to test correct behaviour.
Bug fix

Resolve edge case when calling textcat.predict with empty doc

---

.github/contributors/mdaudali.md
website/meta/logos.json

Changed incorrect home page url for AllenAI from appenai.org to allenai.org
Typo fix for website

Correct typo for AllenAI url on homepage

---

website/docs/api/tokenizer.md

On [Gitter](https://gitter.im/explosion/spaCy) @johann-petrak asked about some Tokenizer information which are not linked to from the API docs.
This PR adds 2 links to the Tokenizer API docs so relevant information is a bit more accessible.
Doc change

Add links to tokenizer API docs to refer relevant information.

---

spacy/errors.py
spacy/language.py
spacy/tests/regression/test_issue4054.py

To resolve an edge case decribed in Issue #4054, I added some additional checks to make sure the `lang` of `nlp` and `vocab` remain consistent across serialization of the different objects.
* If `vocab` does not have a `lang`, write the `lang` of `Language` to `meta`, to ensure it ends up correctly in the `meta.json`  
* unit test to check this behaviour
* When providing a `vocab` to a `Language`, throw an error if they are conflicting (just for robustness)
* some random formatting by `black`
bug fix / enhancement

ensure the lang of vocab and nlp stay consistent

---

pyproject.toml

There was a typo in pyproject.toml.  This patch fixes the issue.

Fix typo in requirements section of pyproject.toml

---

spacy/tests/regression/test_issue4002.py
spacy/tokens/doc.pyx

Fix for Issue #4002 , where the `PhraseMatcher` was not correctly matching `norm` attributes.
The `Token` property `norm` either returns `self.c.norm`, or `self.c.lex.norm` if the former equals `0`, cf [`token.pyx`](https://github.com/explosion/spaCy/blob/master/spacy/tokens/token.pyx#L301).
For consistency, the `get_token_attr` from `Doc` then needs to implement a similar logic when querying the `NORM` attribute.
This fixes the failing unit test previously implemented by @ines, and hopefully also fixes the original issue described in #4002.
Bug fix

Fix get_token_attr for NORM

---

spacy/cli/download.py

Resolves #3923.
This PR attempts to resolve an inconvenience of the `download` command. If a model is downloaded and then loaded within the same process, our `is_package` check currently fails, because `pkg_resources.working_set` is not refreshed automatically (see #3923). This can commonly happen in Jupyter notebooks if you do something like:
```
In [1]: !python -m spacy download de_core_news_sm
In [2]: import spacy
nlp = spacy.load("de_core_news_sm")
```
To work around this, we can try and require the newly installed package explicitly using `pkg_resources.working_set.require`. 
The following test case works without the code proposed in this PR (if you want to try it, make sure the model isn't installed):
```python
from spacy.cli import download
from spacy.util import is_package
import …
```

💫 Require downloaded model in pkg_resources so it can be used in same session

---

spacy/tests/regression/test_issue3540.py
spacy/tokens/_retokenize.pyx

This PR fixes two related bugs that happened after running `retokenizer.split`:
* The `lemma` information was not updated and was still referring to the old `token.text` attributes. This is fixed/reset by calling `token.lemma = 0` on the split tokens.
* The `vector` attributes were left unchanged, causing an out-of-bounds error as described in Issue #3540. This is fixed by extending the `doc.tensor` and setting the vectors of the split tokens to an array of zeros (not sure what else to do).
bug fix

Update lemma and vector information after splitting a token

---

spacy/displacy/render.py

This PR was inspired by a nice little feature I first saw in @ICLRandD's [Blackstone project](https://github.com/ICLRandD/Blackstone). The library ships with a [custom color theme for displaCy](https://github.com/ICLRandD/Blackstone#visualising-entities) to highlight the new entity types it adds.
This PR adds the ability for third-party packages (including models) to expose `spacy_displacy_colors` [entry points](https://spacy.io/usage/saving-loading#entry-points) to add to or overwrite the built-in color scheme.
Imagine a package setup like this:
```python
displacy_colors = {"SNEK": "#3dff74"}
```
```python
from setuptools import setup
setup(
name="snek",
entry_points={
"spacy_displacy_colors": ["colors = snek:displacy_colors"],
},
)
```
The key `colors` here doesn't matter, but it needs …

💫 Support displaCy user colors via entry point

---

spacy/errors.py
spacy/gold.pyx

Provide the tokens in the cycle and the first 50 tokens from document in the error message so it's easier to track down the location of the cycle in the data.
Addresses feature request in #3698.
The error message now looks like this:
```
ValueError: [E069] Invalid gold-standard parse tree. Found cycle between word 
IDs: {0, 1} (tokens: 'In'  'the') in the document starting with tokens: In the 
summer of 2005 , a picture that people have long been looking forward to started 
emerging with frequency in various major Hong Kong media . With their unique charm 
, these well - known cartoon images once again caused Hong Kong to be a focus 
of worldwide attention.
```
The document ID could be added to GoldParse at some point, but with the current training format you really need a non-existent …

Provide more info in cycle error message E069

---

website/meta/universe.json

Adding negspacy to universe.json. This is a spaCy pipeline object that checks if Named Entities are negated using the NegEx algorithm. This is particularly useful in the medical domain, so it pairs well with the ScispaCy UMLS linker.
Change of documentation

Update universe.json to include negspacy

---

spacy/lang/tokenizer_exceptions.py

While working on an unrelated task I got warnings about an unsupported
escape sequence (`"\("`) in the tokenizer exceptions. Making the
tokenizer exceptions a raw string makes this warning go away.
The specific string that triggered this is `¯\(ツ)/¯`.
I guess this is a minor bug fix?

Make the emoticon list a raw string

---

website/docs/usage/visualizers.md

To avoid a commonly reported error, make the enabling/disabling of `jupyter` mode more explicit in the docs + in the longer example code snippet.

Make enabling/disabling jupyter mode more explicit

---

spacy/errors.py
spacy/matcher/matcher.pxd
spacy/matcher/matcher.pyx
spacy/tests/matcher/test_matcher_api.py

Check for relevant components in the pipeline when Matcher is called, similar to the checks for PhraseMatcher in #4105.
* Matcher keeps track of attributes seen in added patterns
* when Matcher is called on a doc, check for is_tagged for LEMMA, TAG, POS and for is_parsed for DEP
Addresses issues like #4156.
Enhancement.

Check for is_tagged/is_parsed for Matcher attrs

---

spacy/tests/regression/test_issue3959.py
spacy/tests/regression/test_issue4133.py
spacy/tokens/doc.pyx

Bugfix for Issue #3959 : Ensure `pos` attributes are serialized (and not just `tags`).
The current fix only works when `doc.is_tagged` is `True`, but I think that makes sense.
bug fix

Serialize POS attribute when doc.is_tagged

---

spacy/matcher/matcher.pxd
spacy/matcher/matcher.pyx
spacy/tests/regression/test_issue4120.py

In the matching code, there was no explicit reasoning for when the pattern has a final `{OP: ?}` token, as reported by @adrianeboyd in Issue #4120.
To remedy this, I added a new type of matching `MATCH_DOUBLE` for when we're matching (`is_match`) at the end of the string (`is_final`) for this type of quantifier `ZERO_ONE`.
When this happens, two matches are added to the results: one with the last token, and one without. We need to specifically check that the length of the match is not zero though, otherwise the [unit test](https://github.com/explosion/spaCy/blob/master/spacy/tests/regression/test_issue2001-2500.py#L127) for Issue #2464 will include 0-0 and 1-1 matches and thus fail with a total count of 5 instead of 3 (hooray for that unit test!).
bug fix

Adding double match for optional operator at the end

---

spacy/tokens/_retokenize.pyx

This doesn't address a current bug, but it's a patch to avoid future problems.
The `_split()` function in `_retokenize.pyx` doubles the length of a `doc` and then moves tokens to create space for the new tokens. When it does, it accesses `doc.c[token_to_move]` in a loop, but the `token_to_move` variable was being defined on the **new** length of the `doc` - meaning that it was occassionally accessing data out of memory. I patched it here by making sure it's only reading tokens that actually existed in the original `doc` by introducing a new variable `orig_length`.
small fix

Small retokenizer fix

---

spacy/cli/train.py
spacy/pipeline/pipes.pyx
spacy/syntax/arc_eager.pyx
spacy/syntax/nn_parser.pyx
spacy/tests/regression/test_issue3830.py

As reported in #3830, the v2.1 models include the label "subtok", which is an internal control symbol used to tell the parser to merge tokens. The `learn_tokens` setting was not being passed through correctly, and even if disabled, the parser was still adding the subtok label.
The other part of the bug in 3830 was that, even if we *did* want to learn the tokens, the `merge_subtokens` pipeline component wasn't necessarily being added to the pipeline. This process is better handled in the `postprocesses` list that the parser and entity recognizer can define.

Fix #3830: 'subtok' label being added even if learn_tokens=False

---

website/docs/api/top-level.md

There were two broken links in the displaCy docs which are fixed with this PR.
Docs

Fix visualizer options linking for displaCy.

---

spacy/cli/train.py

You need both settings, otherwise there is no noise.
(The train command ran into some morphology-related error, so I couldn't really test it, but I think the option is okay.)
Bugfix.

Add separate noise vs orth level to train CLI

---

spacy/tests/regression/test_issue4190.py
spacy/tokenizer.pyx

On initialization, the tokenizer defines a set of default rules (exceptions) and populates an internal cache. If a custom tokenizer with custom rules is loaded `from_disk`, those default rules were not entirely removed from cache. This bugfix addresses that issue as reported in Issue #4190 .
bug fix

Bugfix for serializing tokenizer rules/exceptions

---

spacy/syntax/ner.pyx

* Fix check of valid ent_type for B
* Add valid L as preset-I followed by not-I
Fixes #4229.
Bugfix.

Fix handling of preset entities in NER

---

spacy/tests/regression/test_issue1001-1500.py

Add regression test for #1061 back to test suite.
(Apparently lost in merge for 2.0.0rc1?)
Enhancement?

Add regression test for #1061 back to test suite

---

spacy/lang/de/__init__.py

Add guillemets/chevrons to German orth variants with both German/Austrian
and Swiss conventions.
I noticed that a number of people mentioned them in tokenizer/tagger bug reports.
Enhancement.

Add guillemets/chevrons to German orth variants

---

spacy/lang/ko/__init__.py
spacy/tests/lang/ko/test_tokenizer.py

Fixed check_spaces method to return a generator of length 0 instead of 1 on empty string.
This fixes the following error issue. 
> File ".../spacy/lang/ko/__init__.py", line 72, in \_\_call\_\_
doc = Doc(self.vocab, words=surfaces, spaces=list(check_spaces(text, surfaces)))
File "doc.pyx", line 209, in spacy.tokens.doc.Doc.\_\_init\_\_
ValueError: [E027] Arguments 'words' and 'spaces' should be sequences of the same length, or 'spaces' should be left default at None. spaces should be a sequence of booleans, with True meaning that the word owns a ' ' character following it.
Bug fix

Fix ValueError exception on empty Korean text.

---

website/docs/usage/101/_pos-deps.md
website/docs/usage/linguistic-features.md

* Moved the "Part-of-speech tag scheme" infobox up on the page https://spacy.io/usage/linguistic-features
* Corrected one link to the dependencies doc (was pointing to POS doc)
Change to the documentation, closes #4242

Make pos/tag distinction more clear in docs

---

website/docs/api/top-level.md

Corrected small typo in the docs

Docs: bufsize instead of buffsize

---

spacy/tests/doc/test_retokenize_merge.py
spacy/tokens/_retokenize.pyx

* tag/pos/morph are set to root tag/pos/morph initially (can be overridden by attrs later)
* lemma and norm are reset and end up as orth (not ideal, but better than orth of first token)
Fixes #4051.
Bugfix.

Modify retokenizer to use span root attributes

---

spacy/lang/hr/__init__.py
spacy/lang/hr/lemma_lookup_license.txt
spacy/tests/conftest.py
spacy/tests/lang/hr/test_lemma.py

This PR adds a list of Croatian lemmas adapted from the reldi-tagger.
The PR adds lemma_lookup.json for Croatian, its licence and registers it. It also adds the corresponding test for the lemmatizer as well as setting up the test fixture for a Croatian tokenizer.
The list of lemmas was adapted from the reldi-tagger repository (https://github.com/clarinsi/reldi-tagger) which is licensed under Apache 2.0. I also made a fork of the repo on my account to cover future changes, if necessary.
This is an enhancement for the Croatian language module of spaCy.

Adding a Croatian lemmatizer from Apache 2.0 source reldi-tager

---

spacy/tests/regression/test_issue1001-1500.py
spacy/tokenizer.pxd
spacy/tokenizer.pyx

Flush tokenizer cache when affixes, token_match, or special cases are
modified.
Fixes #4238, same issue as in #1250.
Bugfix.

Flush tokenizer cache when necessary

---

spacy/lang/punctuation.py
spacy/tests/lang/en/test_prefix_suffix_infix.py

Addresses rare cases (such as `_MATH_.`, see #1061) where the final period was not recognized as a suffix following punctuation.
Enhancement.

Allow period as suffix following punctuation

---

spacy/pipeline/pipes.pyx
spacy/tests/parser/test_add_label.py

`DependencsParser.labels` would fail because some of the labels don't include a `-`.
bugfix

💫 Fix bug in Parser.labels and add test

---

spacy/lang/ja/__init__.py
spacy/lang/ja/tag_map.py
spacy/tests/lang/ja/test_tokenizer.py

Before this change, half-width spaces in Japanese text were simply discarded. This wasn't immediately noticed because most Japanese text doesn't use spaces at all.
This is a bug fix.

Fix handling of spaces in Japanese

---

spacy/errors.py
spacy/pipeline/pipes.pyx

If `incl_prior` is False, the `prior_probs` was built incorrectly with wrong dimensions.
Added a check to ensure an error is thrown if this occurs (instead of happily continuing to do matrix multiplications).
bugfix

Bugfix for dimensions in el_pipe

---

spacy/lang/char_classes.py

Add Kannada, Tamil, and Telugu unicode blocks to uncased character classes so that period is recognized as a suffix during tokenization.
(I'm sure a few symbols in the code blocks should not be ALPHA, but this is mainly relevant for suffix detection and seems to be an improvement in practice.)
Part of a fix for #4269.
Bugfix.

Add Kannada, Tamil, and Telugu unicode blocks

---

spacy/pipeline/pipes.pyx
spacy/tests/pipeline/test_sentencizer.py

Most of these characters are for languages / writing systems that aren't supported by spacy, but I don't think it causes problems to include them. In the UD evals, Hindi and Urdu improve a lot as expected (from 0-10% to 70-80%) and Persian improves a little (90% to 96%). Tamil improves in combination with #4288.
The punctuation list is converted to a set internally because of its increased length.
Sentence final punctuation generated with:
```
unichars -gas '[\p{Sentence_Break=STerm}\p{Sentence_Break=ATerm}]' '\p{Terminal_Punctuation}'
```
See: https://stackoverflow.com/a/9508766/461847
Fixes #4269.
Enhancement.

Extend default punct for sentencizer

---

spacy/lang/el/lemmatizer/__init__.py
spacy/lang/fr/lemmatizer/__init__.py
spacy/lang/nl/lemmatizer/__init__.py
spacy/lang/ru/lemmatizer.py
spacy/lang/uk/lemmatizer.py
spacy/lemmatizer.py
spacy/lookups.py
spacy/morphology.pyx
spacy/tests/lang/lt/test_lemmatizer.py
spacy/tests/lang/nl/test_lemmatizer.py
spacy/tests/vocab_vectors/test_lookups.py
spacy/tokens/token.pyx
website/docs/api/lemmatizer.md
website/docs/api/lookups.md

* Make getter/setter methods take both strings and integers and convert strings to hashes automatically and remove now unused methods.
* Use `strings.get_string_id` instead of `hash_string` to account for "special" strings (e.g. built-in symbols) and ensure hashes are always the same as what `StringStore` produces.
* Include serialized `self.bloom`.
* Ensure `from_bytes` clears existing dict contents and bloom filters.
* Add more `Table` API tests.
* Make `orth` argument in `Lemmatizer.lookup` optional (and fall back to string, which is now handled in `Table.__contains__` ouf-of-the-box).
* Tidy up and auto-format.

💫  Adjust Table API and add docs

---

spacy/tests/doc/test_add_entities.py
spacy/tests/pipeline/test_entity_linker.py
spacy/tokens/doc.pyx

When setting `doc.ents`, the KB identifiers were not preserved. Fixed + unit test. 
bug fix

Ensure that doc.ents preserves kb_id annotations

---

.github/contributors/seanBE.md
spacy/matcher/matcher.pyx

Adding `return_matches` and `as_tuples` back into `Matcher.pipe`. They were added in 1cf774bdc17b9f60e53c008d67fabfb164e84353 but were removed in issue https://github.com/explosion/spaCy/pull/3236.
I was following the documentation on the website when I ran into some unexpected keyword arguments when using `Matcher.pipe`. The alternative solution is updating the documentation but since I'm using `Matcher` in my implementation, I went for the code change. 
I could not find any tests on the pipe implementation for either `PhraseMatcher` or `Matcher`. I can create some if necessary. I also couldn't find an issue on this surprisingly. Maybe I'm missing something here. I can create an issue to link to this PR as well if wanted.
"new" feature

add return_matches and as_tuples back to Matcher.pipe

---

spacy/errors.py
spacy/morphology.pyx
spacy/syntax/transition_system.pyx
spacy/util.py

Move messages to `spacy.errors` and add more information to the "Unknown feature" error. This is one that users may hit if they forget to upgrade a model to v2.2, so we might as well mention that in the message.
Example that produces the error if run with spaCy v2.2 and the v2.1 model:
```python
import spacy
nlp = spacy.load("de_core_news_sm")
doc = nlp("Some text hello world")
```
enhancement, ux

Improve Morphology errors

---

spacy/cli/init_model.py
website/docs/api/cli.md

The `init-model` command had hard-coded the name of the word vectors, leading to incorrect vector names being threaded through training, and ultimately the wrong names ending up in the metadata.

Allow vectors name to be set in init-model

---

spacy/cli/debug_data.py

Initialize low data warning for debug-data parser, which resulted in an error if you only checked `-p parser` rather than all components.
Bugfix.

Initialize low data warning for debug-data parser

---

spacy/tests/doc/test_retokenize_merge.py
spacy/tokens/_retokenize.pyx

Closes #3687.
> Duplicate spans can easily happen when you combine matches or things like entities and noun chunks. Because two identical spans are also "overlapping" in theory, an error is also raised when you try to merge them
enhancement

Skip duplicate spans in Doc.retokenize

---

spacy/errors.py
spacy/pipeline/pipes.pyx
spacy/tests/pipeline/test_tagger.py

Raises a warning if a new tagger is trained and the vocab has no lemma data.
enhancement, ux

Warn in Tagger.begin_training if no lemma tables are available

---

spacy/pipeline/pipes.pyx
spacy/tests/regression/test_issue3001-3500.py
spacy/tests/regression/test_issue4348.py

When providing an empty batch of training data, down the line `thinc` would throw an error. This is prevented by catching the empty batch early on and not do any training/prediction on it.
Fixes #4348. Also wrote a unit test for Issue #3456 which was kind of related.
bug fix

Ensure training doesn't crash with empty batches

---

spacy/lang/hu/punctuation.py
spacy/lang/tokenizer_exceptions.py
spacy/tests/tokenizer/test_urls.py
spacy/tokenizer.pyx

Move prefix and suffix detection for `URL_PATTERN` into the tokenizer. Remove associated lookahead and lookbehind from `URL_PATTERN`.
Fix tokenization for Hungarian given new modified handling of prefixes and suffixes.
And since I'm already looking at the details, correct/simplify a few parts of the pattern and match a wider range of URI schemes. If you don't want these changes, the second commit can be reverted.
It would be nice to match IDNs, too, but I decided it looks too complicated for now.
Fixes #4362.
Bugfix and enhancement.

Improve URL_PATTERN and handling in tokenizer

---

spacy/_ml.py
spacy/cli/pretrain.py
spacy/pipeline/pipes.pyx

This PR has a few small improvements to the spacy pretrain and cloze multitask objective.
* Use cosine loss in the cloze multitask objective
* Ignore zero vectors in the objective
* Support bilstm depth CLI argument
The big improvement that needs to happen is reading the hyper-parameters off the pretrained weights. We do something like that in Prodigy, I'll see if I can port the logic over. I want to overhaul the hyper-parameter system in spaCy though, so maybe it should wait.

Improve spacy pretrain

---

spacy/cli/converters/jsonl2json.py

Add a dummy kwargs to the jsonl2json converter, so that options that don't apply don't break it.

Fix ner_jsonl2json converter (fix #4389)

---

spacy/matcher/phrasematcher.pyx
spacy/tests/matcher/test_matcher_api.py
spacy/tests/matcher/test_phrase_matcher.py

* Fix callback lookup in PhraseMatcher (string key rather than hash key)
* Add callback tests for Matcher and PhraseMatcher
Fixes #4397.
Bugfix.

Fix PhraseMatcher callback and add tests

---

spacy/__init__.py
spacy/errors.py
spacy/tests/test_register_architecture.py
spacy/util.py

Components have a `Model` class method, that's used to instantiate their statistical model. This `Model` classmethod hard-codes the architecture. This makes it pretty awkward to plug in a different model architecture --- you have to subclass. Technically you can work around this, but it's messy.
This PR brings in a technique we experimented with in `spacy-pytorch-transformers`, that seems to be working pretty well. The idea is to register creation functions, so that the component config can fetch the creation function by name. This avoids the problem of passing in a function --- if you pass a function in you can't serialise it, leading to all sorts of trouble.
I've introduced a new term, **architecture**, for the types of functions we're registering. The problem is that *model* is too …

Add registry for model creation functions ('architectures')

---

spacy/errors.py
spacy/matcher/matcher.pyx
spacy/tests/matcher/test_matcher_logic.py

Create more user-friendly error when trying to remove a match pattern that doesn't exist + unit test
enhancement

Error when removing a matcher rule that doesn't exist

---

spacy/matcher/phrasematcher.pyx
spacy/tests/matcher/test_phrase_matcher.py

Fix PhraseMatcher.remove() for overlapping patterns:
* Remove patterns in order of reverse length
* Reset stored path through trie between multiple removes for the same match ID
* Add test
Fixes #4435.
Bugfix.

Fix PhraseMatcher.remove for overlapping patterns

---

spacy/gold.pyx
website/docs/api/goldparse.md

Update documentation for the docs_to_gold function.
The
The `docs_to_json` function returns a dict not a list - i've updated the description to reflext the actual function of the code.
This is a PR for: https://github.com/explosion/spaCy/issues/4452

Fix documentation for the docs_to_json function

---

spacy/matcher/phrasematcher.pxd
spacy/matcher/phrasematcher.pyx
spacy/structs.pxd
spacy/syntax/_state.pxd
spacy/syntax/stateclass.pxd

Create more general `SpanC` to replace `Entity` (used by NER) and `MatchStruct` (used by PhraseMatcher).
(Intended for future use in one general `filter_spans()` so that there are not duplicate functions in `util` and the updated tokenizer in #4259.)
Enhancement.

Replace Entity/MatchStruct with SpanC

---

spacy/language.py

Also see #4426: Because the attributes like `lemma_lookup` are still available on the base defaults, user code that writes to them still works, even though they're not used anymore (and have been replaced by the lookups via `nlp.vocab.lookups`).
Open questions: Should we raise an error here instead, and if so, how should this be implemented? Should we make the attributes properties with a setter that raises an error?
enhancements

Remove lemma attrs on BaseDefaults

---

.github/contributors/pberba.md
spacy/vocab.pyx
website/docs/api/vocab.md

I've updated the documentation for `vocab.get_vector` to include changes for support of Fasttext ngrams.
Although support for Fasttext ngrams have been added since spaCy `v2.1`, this features are not reflected in the documentation.
Update of documentation.

Update `vocab.get_vector` docs to include features on Fasttext ngram 

---

spacy/tests/regression/test_issue3001-3500.py
spacy/vectors.pyx

Prevent division by zero when calling the `most_similar()` function in `Vector` if either the original `data` or the `query` contains an all-zero vector. Fixes #3412 
bug fix

prevent division by zero in most_similar method

---

spacy/syntax/_parser_model.pxd
spacy/syntax/_parser_model.pyx
spacy/syntax/nn_parser.pyx

Free the remaining pointers in the `ActivationsC` activations at the end of `_parseC()` in `Parser`.
This is the only definite spacy-related memory leak I found with valgrind using examples from #3618. (I think there may be some remaining issues related to cython/numpy.)
Bugfix.

Free pointers in parser activations

---

spacy/cli/train.py
spacy/language.py
spacy/pipeline/entityruler.py
spacy/tests/pipeline/test_pipe_methods.py
spacy/tests/regression/test_issue3611.py
spacy/tests/regression/test_issue4030.py
website/docs/api/language.md

Another small API qurik that I've been meaning to fix. The suggestion here is to "softly" introduce it asap and then make it official in the next minor/major version. (We can still keep a fallback with a deprecation warning to not break people's training code.)
```diff
- nlp.disable_pipes("tagger", "parser")
+ nlp.disable_pipes(["tagger", "parser"])
```
This example is especially nice because it avoids spreading in a list (which isn't supported inline in 2.7 and maybe even 3.5, not sure).
```diff
- other_pipes = [p for p in nlp.pipe_names if p != "textcat"]
- nlp.disable_pipes(*other_pipes)
+ nlp.disable_pipes([p for p in nlp.pipe_names if p != "textcat"])
```
enhancement

Also support passing list to Language.disable_pipes

---

spacy/errors.py
spacy/matcher/dependencymatcher.pyx
spacy/matcher/matcher.pyx
spacy/matcher/phrasematcher.pyx
spacy/pipeline/entityruler.py
spacy/tests/matcher/test_matcher_api.py
spacy/tests/matcher/test_matcher_logic.py
spacy/tests/matcher/test_pattern_validation.py
spacy/tests/matcher/test_phrase_matcher.py
spacy/tests/regression/test_issue1-1000.py
spacy/tests/regression/test_issue1001-1500.py
spacy/tests/regression/test_issue1501-2000.py
spacy/tests/regression/test_issue2001-2500.py
spacy/tests/regression/test_issue2501-3000.py
spacy/tests/regression/test_issue3001-3500.py
spacy/tests/regression/test_issue3549.py
spacy/tests/regression/test_issue3555.py
spacy/tests/regression/test_issue3839.py
spacy/tests/regression/test_issue3879.py
spacy/tests/regression/test_issue3951.py
spacy/tests/regression/test_issue3972.py
spacy/tests/regression/test_issue4002.py
spacy/tests/regression/test_issue4120.py
website/docs/api/matcher.md
website/docs/api/phrasematcher.md

Another not so great API. Managed to implement the new syntax in a backwards-compatible way.
```diff
patterns = [[{"TEXT": "hello"}, {"text": "world"}], [{"TEXT": "hi"}]]
- matcher.add("KEY", None, *patterns)
+ matcher.add("KEY", patterns)
- matcher.add("KEY", on_match, *patterns)
+ matcher.add("KEY", patterns, on_match=on_match)
```
enhancement, matcher

Implement new API for {Phrase}Matcher.add (backwards-compatible)

---

spacy/syntax/nn_parser.pyx

The `GoldParse` init constructor has a catch-all `**_` which seems to have led to a subtle bug in `nn_parser.pyx`.
Personally I would prefer removing `**_` from the constructor, but this may break people's scripts (though the breaking might be informational). We can also remove it as part of the v.3.0 release. Unless there is a reason to keep this?
bug fix

Fix GoldParse init

---

spacy/_ml.py
spacy/ml/__init__.py
spacy/ml/_wire.py
spacy/ml/common.py
spacy/ml/tok2vec.py
spacy/util.py

Our hyper-parameter config stuff is a mess, which makes it very difficult to customize the models. The architecture registry is a good step forward. Now we just have to progressively refactor everything to use it.
This PR starts with the `Tok2Vec` builder, which had accumulated a rats-nest of different options. We refactor these into different architecture functions, and start building up the new `spacy.ml`.

Refactor Tok2Vec to use architecture registry

---

spacy/gold.pyx
spacy/tests/test_gold.py

from #4525 
- Fixed the bug described in #4525
- Made the `gold.align` code simpler and more efficient
bug fix and refactor.

[#4525] fix gold.align

---

examples/training/ner_multitask_objective.py
spacy/gold.pyx
spacy/language.py
spacy/pipeline/pipes.pyx
spacy/syntax/arc_eager.pyx
spacy/syntax/ner.pyx
spacy/syntax/nn_parser.pyx
spacy/syntax/nonproj.pyx
spacy/tests/regression/test_issue4402.py

PR #4226 added a `cats` field to the training format, which needs to be `pop()`'d off before iterating over the sentences and their annotations. Afterwards however, the field needs to be added back in with `append`, in case multiple pipeline components would process the same `TRAIN_DATA`. If we don't do this, we could be losing training data throughout the pipeline.
Caught this error while trying to run `ner_multitask_objective.py`, which was crashing. It runs again now, though I'm not sure whether it's still functional OK? I think it's been a while since this script was tested :-)
EDIT: Also now fixes #4402
Meanwhile, I'm working on rewriting the training tuple-format (as discussed) which would be quite an overhaul (+ not backwards compatible). But I thought this quick fix would be good …

Match pop with append for training format

---

spacy/cli/train.py
spacy/gold.pyx

After #4525, we're seeing some alignment failures on our OntoNotes data. I think we actually have fixes for most of these cases.
In general it's better to fix the data, but it seems good to allow the GoldCorpus class to just skip cases where the raw text doesn't
match up to the gold words. I think previously we were silently ignoring these cases.

Flag to ignore examples with mismatched raw/gold text

---

requirements.txt
setup.cfg
spacy/_ml.py
spacy/cli/pretrain.py
spacy/ml/tok2vec.py
spacy/syntax/nn_parser.pyx
website/docs/api/cli.md

We can't merge this until we release Thinc 7.3, but I had this on a branch anyway.
Thinc 7.3 adds a new activation function that performs pretty well. This PR adds support for using it in the Tok2vec layer, instead of maxout.

Support Mish activation (requires Thinc 7.3)

---

spacy/gold.pyx
spacy/tests/test_gold.py

Please see https://github.com/explosion/spaCy/pull/4526#issuecomment-546739757
This bug is due to space normalized to `""` and `string.startswith("")` returning `True`.
So I changed the `gold.align` to just consume `""`.

modified gold.align to handle space tokens

---

spacy/gold.pyx
spacy/tests/test_gold.py

I merged @tamuhey 's alignment changes from #4525  to master, but we probably shouldn't make that change on a point release, especially before we've done more testing. I've re-added the previous function, and added a feature flag to `spacy.gold` that can be toggled to enable the new alignment.
We can switch over to the new alignment on v2.3 or v3.0.

Put new alignment behind flag for v2.2.2 release

---

requirements.txt
spacy/syntax/_parser_model.pxd
spacy/syntax/_parser_model.pyx
spacy/syntax/nn_parser.pyx

Backport 3dfc764 to v2.1.x:
* Free pointers in ActivationsC
* Restructure alloc/free for parser activations
* Rewrite/restructure to have allocation and free in parallel functions
in `_parser_model` rather than partially in `_parseC()` in `Parser`.
* Remove `resize_activations` from `_parser_model.pxd`.
Fixes #4538.

Free pointers in parser activations (#4486)

---

spacy/analysis.py
spacy/errors.py
spacy/tests/pipeline/test_analysis.py

While it doesn't really make sense to have the `@component` decorator specify attributes like `span.label_` as requirements, user may still want to set extension attributes like `span._.custom_label`. This PR allows this.
bug fix

Support span._. in component decorator attrs

---

spacy/_ml.py
spacy/ml/_legacy_tok2vec.py
spacy/ml/tok2vec.py
spacy/tests/test_tok2vec.py

The refactor to the `spacy._ml.Tok2Vec` function is too risky for a point release, so for v2.2.2 we should keep the old implementation and have the new behind a feature flag.

Put Tok2Vec refactor behind feature flag

---

spacy/displacy/templates.py
website/docs/images/displacy-ent-custom.html
website/docs/images/displacy-ent-snek.html
website/docs/images/displacy-ent1.html
website/docs/images/displacy-ent2.html

Background: https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break
Looks nice, but makes it difficult to display entity spans consistently for RTL languages:
Also, the more I think about it: the effect is kind of undesirable, because it removes the clear visual indicator that a span is "cut off" and continued on the next line (especially if only the label is cut off). This can falsely give the impression of two spans.
enhancement

Remove box-decoration-break from entities in displacy

---

spacy/language.py

We weren't passing the `n_process` setting through when we have `nlp.pipe(as_tuples=True)`.

Fix multiprocessing for as_tuples=True

---

requirements.txt
setup.cfg
spacy/__init__.py
spacy/compat.py
spacy/displacy/render.py
spacy/lang/en/__init__.py
spacy/language.py
spacy/ml/common.py
spacy/ml/tok2vec.py
spacy/tests/test_architectures.py
spacy/util.py

This PR replaces our function registries (e.g. `@register_architecture`) and entry point handling with our new library, [`catalogue`](https://github.com/explosion/catalogue) that was designed for exactly this purpose.
We're able to remove a lot of code and helper functions, and streamline the way users can register custom functions. 
```python
@registry.architectures.register("xy")
class my_custom_architecture():
@registry.languages.register("xy")
class MyCustomLanguage(Language):
registry.displacy_colors.register("colors", func={"XY": "green"})
```
```python
all_architectures = registry.architectures.get_all()
custom_architecture = registry.architectures.get("custom_architecture")
```

Replace function registries with catalogue

---

bin/ud/ud_train.py

`run_eval.py` uses the `write_conllu()` function from `ud_train.py` by itself, so it needs to set the token extensions if necessary.
Bugfix.

Set extensions when write_conllu() is called in UD train script

---

spacy/tests/doc/test_retokenize_split.py
spacy/tokens/_retokenize.pyx

Always realloc to a size larger than `doc.max_length` in `retokenizer.split()` (or cymem will throw errors).
Fixes #4604.
Bugfix.

Fix realloc in retokenizer.split()

---

.github/contributors/questoph.md
spacy/lang/lb/__init__.py
spacy/lang/lb/punctuation.py
spacy/lang/lb/tokenizer_exceptions.py
spacy/tests/lang/lb/test_text.py

- Added "punctuation.py" to the language package for Luxembourgish. 
- Changes to "__init__.py" and "tokenizer_exceptions.py" to match the new setup.
With these changes it is now possible to split tokens like "d'Kanner" correctly into 2 tokens [d'] and [kanner]. The "punctuation.py" file is a replication of the version for Italian.
Changed the long text in "test_text.py" because all tests were failing. Had to keep the text in one line to successfully pass the tests.
Fix for the basic language support for Luxembourgish

Fix basic language support for Luxembourgish (by adding punctuation.py)

---

spacy/cli/converters/conllu2json.py

Make sure that the last batch of sentences is output when `-n` is greater than 1.
Bugfix.

Fix conllu2json converter to output all sentences when n > 1

---

spacy/language.py
spacy/tests/test_language.py

The arguments were swapped, so evaluating components without `.pipe` would fail.
bug fix

Fix bug in Language.evaluate for components without .pipe

---

spacy/tests/regression/test_issue3001-3500.py
spacy/tests/regression/test_issue3880.py
spacy/tests/regression/test_issue4348.py
spacy/tests/test_gold.py
spacy/tests/tokenizer/test_urls.py

This PR checks whether xpassing tests can be un-xfailed (e.g. because the underlying problem was fixed) or whether the xfail marker was used to  disable them (e.g. because the test was unreliable). In that case, we should skip the test with a `reason` instead of using xfail (which can easily get confusing, because it's later unclear whether the test was actually expected to fail and if so, where etc.)
I also added warning filters to the tests that currently raise our own warnings (for legitimate reasons, just expected in those cases).
tests

Fix xpassing tests

---

spacy/syntax/_state.pxd
spacy/syntax/nn_parser.pyx
spacy/tests/parser/test_ner.py

The parser and NER components use transition-based models, that build a state representation by combining the vectors from some tokens in the context. The previous NER feature set was:
* Current word
* Next word
* Previous word
* First word of the current entity
* Word before first word of the current entity
* Word after first word of the current entity
This PR adds a feature set that seems to perform a bit better, while using fewer tokens:
* Current word
* First word of current entity, if it exists
* Last word of current entity, if it exists
This is less redundant, and runs faster. It also prepares us better for the wider token vectors we'll be expecting from transformer models.
You can change the feature set by passing `nr_token_features` to the `begin_training` method. Care should be …

Add option for improved NER feature extraction

---

spacy/syntax/_parser_model.pyx
spacy/syntax/nn_parser.pyx
spacy/util.py

The parser and NER components use transition-based models that build a hidden representation by combining information from the token vectors of several features in the context. Previously, this information was always mixed using a hidden layer with a maxout activation.
This PR gives the option to skip this hidden layer, so that the token vectors are used as features directly in a linear model. This is faster, and may be a more appealing option when the token vectors are wide, as with pretrained transformer models.
You can set the option by passing `"hidden_depth": 0` in the component cfg to begin_training, e.g.:
```
nlp.begin_training(component_cfg={"ner": {"hidden_depth": 0}})
```
Currently setting `hidden_depth=0` automatically sets the maxout pieces to 1 as well.

Support no hidden layer in parser and NER

---

spacy/vectors.pyx

`vectors.find()` accepts several input types. One of them is a sequence of rows, which are mapped into a sequence of corresponding keys. This function returned the keys out of order.

Make vectors.find() return keys in correct order

---

setup.cfg
spacy/lang/ja/__init__.py
spacy/tests/conftest.py
website/meta/languages.json

Currently Japanese uses python-mecab3 as a wrapper of MeCab for tokenization. However we use an old version of python-mecab3 because the latest versions make using Unidic (required by Universal Dependencies) tricky, in addition to having [an unresolved issue](https://github.com/SamuraiT/mecab-python3/issues/34) around memory usage. 
This change replaces python-mecab3 with [fugashi](https://github.com/polm/fugashi), a Cython wrapper for MeCab I wrote recently, which doesn't have the above issues. The API was also written with spaCy in mind, which allowed for simplifying the tokenizer code here a bit.
This is an enhancement.

Replace python-mecab3 with fugashi for Japanese

---

spacy/cli/train.py
spacy/gold.pxd
spacy/gold.pyx
spacy/pipeline/pipes.pyx
spacy/syntax/nn_parser.pyx
spacy/tests/test_gold.py

Various fixes to get the new `Example` API working with the train CLI and for all pipeline components. Main changes:
* Training examples are projectivized correctly (including a new test)
* Head of `0` is a valid value, not treated as unset
* `pipe()` in all components is updated to accept `as_examples` argument and to yield the annotated examples without clobbering the provided data
* Use `Example.goldparse` in `iter_gold_docs()` instead of `Example.gold` because a `None` `GoldParse` is generated with `ignore_misaligned` and generating it on-the-fly can raise an unwanted `AlignmentError`
Bugfix.

Fix Example details for train CLI / pipeline components

---

.github/contributors/mmaybeno.md
spacy/vocab.pyx

Fixes a bug where we were not getting the correct array module when returning a vector in Vocab.
Fixes issue related to #4673. This issue causes a `TypeError` when trying to do any calculations related to the vectors where a word is not in the Vocab list. This leads to mixed array types (in our case `numpy` and `cupy` arrays). 
The change is doing what is done in other parts of the code where we first get the appropriate array module prior to any calculations. Removing `numpy` with `get_array_module`.

Agnostic vocab array fix

---

spacy/errors.py
spacy/tests/parser/test_parse.py
spacy/tokens/doc.pxd
spacy/tokens/doc.pyx

Iterate over lr_edges until all heads are within the current sentence. Instead of iterating over them for a fixed number of iterations, check whether the sentence boundaries are correct for the heads and stop when all are correct. Stop after a maximum of 10 iterations, providing a warning in this case since the sentence boundaries may not be correct.
Fixes #4688.
Bugfix.

Iterate over lr_edges until sents are correct

---

spacy/tests/regression/test_issue4707.py
spacy/util.py

Fixes #4707.
When you `disable` a component when loading a model, it should also be excluded when calling `nlp.from_disk` afterwards to load the individual components (especially the tokenizer, which will otherwise raise an error).
bug fix

Auto-exclude disabled when calling from_disk during load

---

spacy/lang/lb/norm_exceptions.py
spacy/lang/lb/punctuation.py
spacy/lang/lb/tokenizer_exceptions.py
spacy/tests/lang/lb/test_exceptions.py
spacy/tests/lang/lb/test_text.py

The changes cover some issues with tokenization for Luxembourgish, including the correct handling of the definite article "d'", the abbreviation "'t" for "et" (it), and words with hyphen infixes (should not be split). I have
- rewritten the "punctuation.py" file defining language-specific rules for infixes (mostly by reusing the code for German);
- corrected an error in the "norm_exceptions.py" file (mapping of norm and variants);
- added some tokenization tests to test data processing;
- smaller changes to the list of norm & tokenizer exceptions.
enhancement

Tokenization fixes & new tests for Luxembourgish

---

spacy/pipeline/pipes.pyx

Fixed typo bug in the EntityLinkers's `predict` function - hopefully by fixing this the EL results will become more meaningful (will run experiments to test this hopeful hypothesis).
Fixes #4772 - thanks to @lilysikes  for the report and fix!
bug fix

fix bug in EL predict

---

spacy/matcher/matcher.pyx

Add `int` values (for `LENGTH`) in `_get_attr_values()` instead of treating `int` like `dict`.
(The validation fix in #4444 was incorrect.)
Fixes #4717.
Bugfix.

Fix int value handling in Matcher

---

spacy/cli/convert.py
spacy/cli/converters/conllu2json.py
spacy/tests/test_cli.py

Instead of a hard-coded NER tag simplification function that was only intended for NorNE, map NER tags in CoNLL-U converter using a dict provided as JSON as a command-line option.
Map NER entity types or new tag or to "" for 'O', e.g.:
```
{"PER": "PERSON", "BAD": ""}
=>
B-PER -> B-PERSON
B-BAD -> O
```
Enhancement.

Add NER map option to convert CLI

---

spacy/errors.py
spacy/kb.pyx
spacy/tests/regression/test_issue4674.py

Make `set_entities` in the `KnowledgeBase` more robust to input lists that define the same KB ID more than once. While this shouldn't really happen, the method now recovers by ignoring the duplicate entry and throwing a user-friendly warning. 
Before this PR, this specific method would cause a crash if you attempted IO later, because the KB would think it had more entities than it did (counting the duplicate ones instead of only the unique set).
Fixes #4674 - added unit test.
bug fix

More robust set entities method in KB

---

spacy/tests/doc/test_span.py
spacy/tokens/span.pyx

Add `char_span` method into `Span` like `Doc`.
Now `Span` has new method `char_span`, almost same as `Doc.char_span`:
```python
doc = nlp("This is a sentence. This is another sentence. And a third.")
sent = list(doc.sents)[1]
assert sent.text == "This is another sentence."
assert sent.char_span(0, 4) == "This"
assert sent.char_span(0, 1) is None
```
new feature

[New feature] add `char_span` to Span

---

bin/ud/ud_train.py
bin/wiki_entity_linking/entity_linker_evaluation.py
bin/wiki_entity_linking/wikipedia_processor.py
examples/training/conllu.py
examples/training/pretrain_textcat.py
examples/vectors_tensorboard.py
requirements.txt
spacy/cli/init_model.py
spacy/cli/profile.py
spacy/cli/train.py

Issue #4200 revealed a [bug](https://github.com/tqdm/tqdm/issues/678) in `tqdm` that was messing up colors for Windows users in Jupyter. We made an ugly temp hack [fix](https://github.com/explosion/spaCy/pull/4263) by moving our `tqdm` imports to their respective functions. Meanwhile, the original has been [fixed](https://github.com/tqdm/tqdm/commit/ae6de71c3460123944aa7bb80d7cb0b5bdcafb7b) over at `tqdm`, so we can revert our hack as well.
`tqdm`==4.38.0 is the first version with the fix, so I pinned that in our dependencies.
enhancement

Restore tqdm imports

---

spacy/errors.py
website/docs/api/phrasematcher.md

The tabular [documentation of the PhraseMatcher constructor](https://spacy.io/api/phrasematcher#init) left out the deprecated argument `max_length`, which can result in subtle bugs when calling this constructor with positional arguments. Even though a warning is thrown about the deprecated `max_length`, users may still not realise that `attrs` is not parsed correctly, as the pipeline still runs (with the default `attrs`=`ORTH`). This happened in Issue #4825.

Documentation for PhraseMatcher constructor

---

spacy/errors.py
spacy/gold.pyx

Facilitate large training file, but also throw a warning to point towards the possibility of splitting up into multiple files.
Fixes #4703
Fixes #4823 
enhancement

facilitate larger training files

---

.github/contributors/iechevarria.md
spacy/errors.py
website/docs/api/language.md

The tabluar documentation for Language.pipe leaves out the argument `n_process` which was introduced in v2.2.2. In addition, warning W016 says that a "future version" will introduce `n_process` while it was introduced in v2.2.2.

Add n_process to Language.pipe documentation (#4842) [ci skip]

---

spacy/displacy/__init__.py

By default, Jupyter renders MathJax between any two dollar signs. When running displacy through some news documents I was seeing very odd rendering due to this behavior. Using this [SO answer](https://stackoverflow.com/questions/16089089/escaping-dollar-sign-in-ipython-notebook), I added a span tag to stop rendering mathjax when `jupyter=True`.
signed contributor agreement: https://github.com/explosion/spaCy/pull/4839
bug fix

stop rendering mathjax by default in displacy

---

spacy/attrs.pxd
spacy/attrs.pyx
spacy/language.py
spacy/symbols.pxd
spacy/symbols.pyx
spacy/tests/regression/test_issue4849.py
spacy/tests/serialize/test_serialize_extension_attrs.py
spacy/tokens/doc.pyx
spacy/tokens/span.pyx
spacy/tokens/token.pxd

Allow `token.ent_id` to be serialized through the attr `ENT_ID`, which wasn't defined yet in the symbols or attrs list.
Fixes #4849 + unit test
bug fix ?

serialize ENT_ID

---

spacy/cli/debug_data.py
spacy/errors.py

When training with noise, punctuation may be [converted](https://github.com/explosion/spaCy/blob/master/spacy/gold.pyx#L480) into whitespace which can then crash the training process as this may result in invalid entities. 
This is a quick fix in the `debug_data` script that alerts the user to this potential issue.
Fixes #4830 
enhancement

Warn for punctuation in entities when training with noise

---

bin/wiki_entity_linking/README.md
bin/wiki_entity_linking/entity_linker_evaluation.py
bin/wiki_entity_linking/wikidata_train_entity_linker.py
bin/wiki_entity_linking/wikipedia_processor.py
spacy/pipeline/pipes.pyx

Optimizing the EL pipeline to be less memory-heavy. In practice this means that the same documents will have to be reprocessed with `nlp()` in each epoch, but storing in memory or on file seems worse. There's always a memory/cpu/disk trade-off but this change should hopefully make the pipeline runnable on most machines.
Additional minor edits:
- provide more informative progress bars
- warn up-front if output directory is not specified
- limit train/dev data in number of articles instead of number of entities (more intuitive)
enhancement

Reduce mem usage in training Entity Linker

---

examples/training/pretrain_textcat.py
examples/training/rehearsal.py
examples/training/train_entity_linker.py
examples/training/train_intent_parser.py
examples/training/train_ner.py
examples/training/train_new_entity_type.py
examples/training/train_parser.py
examples/training/train_textcat.py

The current example training scripts don't work with the transformer models, as they need [access](https://github.com/explosion/spacy-transformers/blob/master/spacy_transformers/language.py#L81) to their `tok2vec` component during `nlp.update()` but that component gets [disabled](https://github.com/explosion/spaCy/blob/master/examples/training/train_textcat.py#L71) in the train script.
If we want to support this use-case, we can specifically prevent disabling this component as in this PR. I know we have [specific train scripts](https://github.com/explosion/spacy-transformers/tree/master/examples) for the transformer models, but on the other hand we also claim they can be used like normal spaCy models, so it's not a strange expectation that the example scripts would work with the …

run normal textcat train script with transformers

---

spacy/pipeline/entityruler.py
spacy/tests/pipeline/test_entity_ruler.py

When using the "id" attribute in EntityRuler patterns right now, the labels property gives different strings for the same label because of the way patterns are stored.
Currently labels returns something like:
e.g. 
```python
[
...
"TECH_ORG||apple",
"TECH_ORG||microsoft",
"TECH_ORG||google",
...
]
```
This PR fixes this so that the labels property only includes
```python
[
...
"TECH_ORG",
...
]
```
and the ent_ids property has
```python
[
...
"apple",
"microsoft",
"google",
...
]
```

Fix ent_ids and labels properties when id attribute used in patterns

---

spacy/gold.pyx
spacy/tests/regression/test_issue4924.py

From #4924.
I found `nlp.evaluate` fails with empty `doc` and `gold`.
This seems to be unintended, because the error is somewhat confusing:
```
gold_deps = set()
gold_deps_per_dep = {}
gold_tags = set()
>       gold_ents = set(tags_to_entities([annot[-1] for annot in gold.orig_annot]))
E       TypeError: 'NoneType' object is not iterable
spacy/scorer.py:239: TypeError
```
I thought the following three ways to correct this:
1. Informs the users that `nlp.evaluate` will not accept an empty `gold`, and fails.
2. Modify `GoldParse` to set `gold.orig_annot = []` instead of `None`, if `gold` is empty.
3. Modify `nlp.evaluate` to properly handles empty `gold`
I adopted the second way.
In the first way, users should write a boilerplate to check `gold` is empty.
In the third way, it is necessary …

fix nlp.evaluate (#4924)

---

website/docs/api/phrasematcher.md

Stolen from here: https://stackoverflow.com/questions/47638877/using-phrasematcher-in-spacy-to-find-multiple-match-types
Change to documentation.

Adding a note on retrieving the string rep of the match_id

---

spacy/tokens/doc.pyx

Ensure we get a float when calling `doc1.similarity(doc2)`:
* Before this PR (printing value & type):
* cupy: 0.9182048, <class 'cupy.core.core.ndarray'> 
* numpy: 0.9182046417319748, <class 'numpy.float64'>
* After this PR:
* cupy: 0.9182047843933105, <class 'float'>
* numpy: 0.9182046417319748, <class 'float'>
Fixes #4896
We may need to mention this in the breaking-backwards-compatibility notes for spaCy 3.

Ensure doc.similarity returns a float (on develop)

---

spacy/cli/train.py

The `train` CLI script had a `try`-`finally` block, not sure why the `except` was missing?
If there wasn't a particular reason, I just added a quick log message to avoid confusion as in Issue https://github.com/explosion/spaCy/issues/4719.
enhancement

add message when cli train script throws exception

---

spacy/cli/pretrain.py
spacy/cli/train.py

`pretrain` allows setting various parameters such as `cnn_pieces` and `bilstm_depth`. If you want to use those results in the `train` script with `init_tok2vec`, it needs to take the same parameters to build an initial `Tok2Vec` component, because the two need to match exactly before `tok2vec.from_bytes()` is called. 
Obviously this should be fixed more cleanly in spaCy 3...
Fixes #4819
Fixes #4871
Fixes #3979
bug fix

add tok2vec parameters to train script

---

spacy/tests/doc/test_doc_api.py
spacy/tokens/doc.pyx

Modify flag settings so that `DEP` is not sufficient to set `is_parsed` and only run `set_children_from_heads()` if `HEAD` is provided.
Then the combination `[SENT_START, DEP]` will set deps and not clobber sent starts with a lot of one-word sentences.
Fixes #4440.
Bugfix.

Require HEAD for is_parsed in Doc.from_array()

---

spacy/vectors.pyx

Cast all keys and rows to `int` in `vectors.key2row` for more efficient access and serialization.
After pruning vectors, `key2row` ended up as `Dict[numpy.uint64, Union[int, numpy.int32]]` instead of `Dict[int, int]`, which is much larger when serialized with msgpack for (4x larger for English `md` vs. `lg`) and much slower to load and access.

Use int only in key2row for better performance

---

spacy/tests/doc/test_span.py
spacy/tests/util.py
spacy/tokens/span.pyx

Use the same tuple for `__eq__` and `__hash__`, including all attributes except `vector` and `vector_norm`.
Fixes #4965.

Sync Span __eq__ and __hash__

---

spacy/language.py
spacy/pipeline/pipes.pyx

Fixes #4009
Refactor https://github.com/explosion/spaCy/commit/95a96152213a0c3e4827c00ab396357d3abf02d2 started using `pretrained_vectors` instead of `pretrained_dims` in the `cfg`, but [`build_text_classifier`](https://github.com/explosion/spaCy/blob/2c107f02a4d60bda2440db0aad1a88cbbf4fb52d/spacy/_ml.py#L638) still needs that `pretrained_dims` parameter. This is a quick hack to make sure that setting is there, so that the TextCategorizer actually does use the pretrained vectors when available. This will be much more cleanly fixed in spaCy 3.
To use pre-trained vectors in the `textcat` component, either call 
```
nlp.begin_training()
```
or  
```
textcat.begin_training(pretrained_vectors=nlp.vocab.vectors.name, pretrained_dims=nlp.vocab.vectors.data.shape[1])
```
bug fix

Fix using pre-trained vectors in textcat

---

spacy/lang/ro/__init__.py
spacy/lang/ro/punctuation.py
spacy/lang/ro/tokenizer_exceptions.py

Modifications to Romanian tokenization to improve tokenization for UD_Romanian-RRT.
The modifications are based entirely on the RRT train subcorpus. Evaluated on the dev corpus the tokenizer accuracy is 99.625%.
For each prefix / suffix / exception, variants are generated with all combinations of the variants for the characters  `Ă Â Î Ș Ț` with cedilla instead of comma and without diacritics in upper case, lower case, and title case.
Caveats:
* some affixes or some parts of some paradigms may be missing
* the orthography variants may be incomplete or may overgeneralize
* the tokenizer exceptions are currently not case-specific
* because of the way spacy prioritizes prefixes over suffixes, some tokenizations are incorrect, e.g., `și-ți` will be tokenized as `și- ți` not as `și -ți`

Improved Romanian tokenization for UD RRT

---

spacy/displacy/__init__.py
spacy/displacy/render.py
spacy/displacy/templates.py
spacy/tests/test_displacy.py
spacy/tests/util.py
website/docs/api/top-level.md

Support `add_lemma` (default `False`) option for `dep` visualisation with `displacy`. Just adds an additional row of lemma's below the `token.text`. Made sure all combinations with `fine_grained` (for POS) work well. 
Also changed the documentation.
enhancement

add lemma option to displacy 'dep' visualiser

---

.github/contributors/MisterKeefe.md
spacy/attrs.pxd
spacy/attrs.pyx
spacy/symbols.pxd
spacy/symbols.pyx
spacy/tests/doc/test_array.py
spacy/tokens/doc.pyx

Closes 5029. Make a token's idx property as one of the things that can be included in the output of a `Doc`'s `to_array` method. 
- Add `IDX` as an entry in `attrs.pxd` 
- Add clause in `elif` chain to make `IDX` result in `token.idx` lookup
- Add unit test
Minor enhancement
- [ x ] I ran the tests, and all new and existing tests passed.
- [ x ] My changes don't require a change to the documentation, or if they do, I've added all required information.

Add `idx` as an attribute available via to_array

---

setup.cfg

Conda is complaining that it can't parse that line otherwise.

Add missing comma in a dependency specification

---

spacy/language.py
spacy/tests/doc/test_underscore.py
spacy/tests/matcher/test_matcher_api.py
spacy/tests/regression/test_issue4849.py
spacy/tests/regression/test_issue4903.py
spacy/tests/regression/test_issue4924.py
spacy/tokens/underscore.py

Fixes https://github.com/explosion/spaCy/issues/4903
- Define a `state` for the `Underscore` class
- Load that state when creating multiple works with `n_process`>1.
On Linux the current state is transferred as `fork` is being called (by default, can be changed), but this is not the case on Windows or macOS, where `spawn` is called instead. So it's always safer to make sure the necessary state is defined explicitely. See also https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
If we have other global variables/state that should be retained when multiprocessing, we should make a similar fix for them.
bug fix

load Underscore state when multiprocessing

---

spacy/lang/lb/punctuation.py
spacy/lang/lb/tokenizer_exceptions.py

This update fixes some special cases for the Luxembourgish tokenizer, i.e., the correct handling of apostrophe infixes in words. Forms like "d'Saach" (definite article + word) should be split while others should remain as one token "entsche'den" (indication of long vowel in old orthography).
- Fix for tokenizer rules in punctuation.py
- Addition to exceptions in tokenizer_exceptions.py

Optimizing tokenization for Luxembourgish (dealing with apostrophe infixes)

---

bin/wiki_entity_linking/wikidata_train_entity_linker.py
spacy/cli/train.py

Found a few bugs introduced from porting bug fixes from `master` to `develop` (PR #5027), mostly related to the refactor of using a batch of training `examples` (on `develop`) versus the old `golds, docs` (on `master`) as argument for `nlp.update()`.
Also reverted the additional parameters in the `train` script from https://github.com/explosion/spaCy/pull/5021 as this fix was really intended for `master` only and should probably be done more properly with config files for v.3 onwards.
bug fix

Fix sync between master and develop

---

.gitignore
Makefile

Various improvements to building the .pex standalone executable.
* Create versioned files, e.g. `dist/spacy-2.2.3.pex` instead of using the Git sha.
* Build wheels with `pip wheel` into a directory `wheelhouse/`, so that we can disable pex's cache.
* Add `make test` command that runs the tests using the built artefact.
It should also now be easier to change the Python version. In summary, writing something like:
```
make PYVER=3.7 test
```
Should build and test a file `dist/spacy-2.3.3.pex`, if 2.2.3 is the current library version (according to the `about.py`). The executable will be self-contained, except that it will require the Python3.7 interpreter to be installed.

Improve Makefile

---

spacy/_ml.py
spacy/language.py
spacy/tests/regression/test_issue4725.py
spacy/tests/regression/test_issue4849.py
spacy/tests/regression/test_issue4903.py

Fixes #4725
Should not be ported to `develop` - is a quick fix for 2.x.
Similar to https://github.com/explosion/spaCy/pull/5006 where the global data for `Underscore` needed to be passed on to the child processes, here we pass on the global vectors data.
bug fix

take care of global vectors in multiprocessing

---

spacy/syntax/nn_parser.pyx

Fixes #4934
Should not be ported to `develop` - is a quick fix for 2.x.
When calling `ner.begin_training()` on a pretrained component with `cfg` parameters such as `conv_depth`, that parameter will be ignored because there already is a `Model`. As discussed in https://github.com/explosion/spaCy/issues/4934, alternative routes should be taken to accomplish creating a new model and/or resume training.
The current code did store the new `cfg` values though, making the model inconsistent for IO, resulting in a crash. This PR resolves that by only storing the config parameters that are relevant.
bug fix

prevent updating cfg if the Model was already defined

---

spacy/errors.py
spacy/tests/doc/test_array.py
spacy/tests/doc/test_token_api.py
spacy/tokens/doc.pyx
spacy/tokens/token.pyx

Improve the verification for valid token heads when heads are set:
* in `Token.head`: heads come from the same document
* in `Doc.from_array()`: head indices are within the bounds of the document
Addresses segfault in #5075 by making it impossible to create invalid heads in a document with `Doc.from_array()`.
Bug fix.

Improve token head verification

---

spacy/pipeline/functions.py
spacy/tests/regression/test_issue5082.py
spacy/tokens/_retokenize.pyx

Closes #5082 
When using the `merge_entities` pipe, the vector of the merged `token` is now appropriately set to the vector of the original `span` (i.e. the average of the original tokens). Before it was just a zero vector.
enhancement

set vector of merged entity

---

.github/contributors/dhpollack.md
website/src/images/logos/allenai.svg

fixed a typo (space went was supposed to be outside quotes, but it was inside)
This error caused a Gatsby build error when I tried to build the documentation locally
bug fix
Can I sign the contributor agreement electronically somehow?

fix typo in svg file - caused documentation build error

---

spacy/language.py

Remove iterator over `raw_texts` with `iterator.tee()` in `Language.pipe` that is never consumed and consumes memory unnecessarily.
Addresses part of issue in #5083. I think the use of `iterator.tee()` may still be causing memory problems with multiprocessing, but this should be an improvement for `.pipe(n_process=1)`.

Remove unnecessary iterator in Language.pipe

---

spacy/tests/regression/test_issue5141.py
spacy/tokens/_serialize.py

Fixes #5141.
Calling `to_bytes()` on an empty `DocBin` would crash because `numpy`'s `vstack` can not deal with empty input.
bug fix

Fix serialization of empty doc

---

spacy/language.py

I stumbled upon these unnecessary lines and found that this already got fixed in `master` (https://github.com/explosion/spaCy/pull/5101), but we need it on `develop` as well. And for some reason cherry-picking didn't work.
bug fix

remove unnecessary itertools call

---

examples/streamlit_spacy.py

Fixes #5089 - thanks to @shovalsa for submitting the bug report ánd the fix !
Dependency labels were not showing up properly with the example streamlit script. By rendering through SVG, this is fixed.
bug fix

fix showing dep arcs in streamlit script

---

.github/contributors/guerda.md
examples/information_extraction/phrase_matcher.py

The PhraseMatcher example currently contains a deprecated use of `max_length`.
The parameter max_length is deprecated in PhraseMatcher, as stated here: https://spacy.io/api/phrasematcher#init
I removed the defaulted attribute in `get_matches` and in the initialization of `PhraseMatcher`.
Improvement of documentation

Remove max_length parameter in PhraseMatcher example

---

pyproject.toml
requirements.txt
setup.cfg
spacy/about.py
spacy/cli/train.py
spacy/syntax/_parser_model.pyx

`_load_vectors` accidentally got removed in the refactor... 
+ bump thinc to 8.0.0a3 (which includes the rename of `_init` to `init`, and a fix for static vectors)
bug fix

Bugfix linking vectors

---

spacy/cli/train.py

* Omit per_type scores from model-best calculations:
The addition of per_type scores to the included metrics (#4911) causes errors when they're compared while determining the best model, so omit them for this `max()` comparison.
* Add default speed data for interrupted train CLI:
Add better speed meta defaults so that an interrupted iteration still produces a best model.
Fixes #5200.
Bug fix.

Minor bugfixes for train CLI

---

spacy/pipeline/pipes.pyx
spacy/syntax/nn_parser.pyx
spacy/tests/regression/test_issue4725.py
website/docs/usage/saving-loading.md

Pickling of the parser got broken by changing the arguments of `__init__`. Fixed now by adjusting the `__reduce__` arguments and setting the `moves` object through `__get_state__`.
Fixes #4725 which got broken in the v3.0 refactor, see also PR #5213 (where we first noticed the hanging test).
bug fix

Fixing pickling of the parser

---

spacy/ml/_layers.py
spacy/syntax/_parser_model.pyx
spacy/tests/parser/test_ner.py

The parser/ner was broken on GPU. This could be tested by adding `require_gpu` to the `overfitting_IO` test in `test_ner`.
This PR includes several fixes to make sure the parser again runs correctly on GPU. To ensure also IO works, it needs the additional fix from https://github.com/explosion/thinc/pull/332.
bug fix

Fix parser @ GPU

---

spacy/errors.py
spacy/tests/vocab_vectors/test_vectors.py
spacy/vectors.pyx

Modify `Vectors.resize` to work with cupy. Modify behavior when resizing to a different vector dimension so that individual vectors are truncated or extended with zeros instead of having the original values filled into the new shape without regard for the original axes.
Bug fix.

Modify Vector.resize to work with cupy and improve resizing

---

spacy/tests/regression/test_issue5152.py
spacy/tokens/doc.pyx
spacy/tokens/span.pyx

There was a bug when calculating the similarity of a `Span` of X tokens ("`self`"), to a `Token` with X characters ("`other`"), because of this line:
``` elif hasattr(other, "__len__") and len(self) == len(other)```
which would be `True` in that case, and then `other[i]` would crash because a `Token` can't be indexed.
I rewrote the check to actually look at the class of the instance instead (like it is in the implementation in `doc.pyx`, I found out afterwards).
Also, I thought there was a bit of a weird construct with an `else` statement with an unmatched `if`. I rewrote it for clarity.
Fixes #5152
bug fix

bugfix in span similarity

---

spacy/pipeline/pipes.pyx

Ran [`test_overfitting_IO`](https://github.com/explosion/spaCy/blob/develop/spacy/tests/pipeline/test_entity_linker.py#L264) in `test_entity_linker.py` with `require_gpu`.
It looks like only this one little change is needed to make it run properly?
@honnibal : I'm a little surprised by this. Considering [your original comment](https://github.com/explosion/spaCy/pull/3864#issuecomment-504370194) I was assuming I'd need to do more work. But perhaps I still should, to make it more efficient on GPU? Or do you think it's fine if it runs (which it does) ?
enhancement

fix NEL overfitting test for GPU

---

.github/contributors/jacse.md
spacy/lang/da/examples.py

Fixes two examples, adds additional examples translated from the english version, and adds punctuation.
The two changed examples are:
* "fortov" changed to "fortovet", which is more [used](https://www.google.com/search?client=firefox-b-d&sxsrf=ALeKk0143gEuPe4IbIUpzBBt-oU10OMVqA%3A1585549036477&ei=7I6BXuvJHMGOrwSqi46oCQ&q=l%C3%B8behjul+p%C3%A5+fortov&oq=l%C3%B8behjul+p%C3%A5+fortov&gs_lcp=CgZwc3ktYWIQAzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQR1DT8xZY0_MWYK_0FmgAcAZ4AIABAIgBAJIBAJgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwjr7964xsHoAhVBx4sKHaqFA5UQ4dUDCAo&uact=5) and more natural. The Swedish and Norwegian examples also use this version of the word.
* "stor by" changed to "storby". In Danish we have a specific noun to describe a large, metropolitan city which is …

Extend and fix Danish examples

---

spacy/about.py
spacy/tests/pipeline/test_senter.py
spacy/util.py

As discussed, setting optimizer defaults back to the values from Thinc 7 (for now).
Bump to 3.0.0.dev6
a feature? a fix? a random experiment?

Optimizer defaults

---

spacy/lang/fr/tokenizer_exceptions.py
spacy/lang/tokenizer_exceptions.py
spacy/tokenizer.pyx

Use inline flags in `token_match` patterns so that serializing does not lose the flag information.
Bug fix.

Use inline flags in token_match patterns

---

spacy/lang/es/tokenizer_exceptions.py

As I understand it, `pala` is a proper noun in Spanish and `para la` or `pa la` should be written with a space. So removing this tokenizer exception that would always split up the token `pala` into two.
Fixes #5255
fix

Remove `pala` tokenizer exception

---

.github/contributors/umarbutler.md
spacy/cli/train.py

Fixed a typo in the warning in cli/train.py for the provision of exactly two labels to textcat, which have not been specified to be binary. The new code now correctly reads the name of the argument (--textcat-positive-label) for specifying a positive label. I have also added my contributor agreement.
Changed static string.
Fixes #5283

Fixed Typo in Warning

---

.github/contributors/chopeen.md
website/docs/api/cli.md

This PR fixes a typo at https://spacy.io/api/cli#pretrain, by replacing an underscore with a dash.
Bug #5292 
Minor documentation fix.

[Closes #5292] Fix typo in option name "--n-save_every"

---

website/docs/api/cli.md

Fixes #5285
The documentation contained the wrong version number for a new feature.
doc fix

Docs: tag-map-path since 2.2.4 instead of 2.2.3

---

.github/contributors/elben10
bin/wiki_entity_linking/wikipedia_processor.py
spacy/tests/regression/test_issue5314.py

(Fixes #5314 )
Fixes change of format `{lang}wiki-latest-pages-articles.xml.bz2` which makes the `bin.entity_linking.wikipedia_processor._process_wp_text` not parse any article.
The code removes everything within the `<text >` tag before extracting the text.
Bug fix

Fixes  #5413

---

spacy/lang/zh/__init__.py
spacy/language.py
spacy/tests/conftest.py
spacy/tests/lang/zh/test_serialize.py
spacy/tests/lang/zh/test_text.py
spacy/tests/lang/zh/test_tokenizer.py

Add support for [pkuseg](https://github.com/lancopku/PKUSeg-python) (currently `pkuseg==0.0.22`) alongside jieba:
* Specify tokenizer configuration through `Language` `meta`:
* split on characters (default if no word segmentation packages are installed)
```
Chinese(meta={"tokenizer": {"config": {"use_jieba": False, "use_pkuseg": False}}})
```
* jieba (remains the default tokenizer if installed)
```
Chinese()
Chinese(meta={"tokenizer": {"config": {"use_jieba": True}}}) # explicit
```
* pkuseg (only used if a model is specified explicitly)
```
Chinese(meta={"tokenizer": {"config": {"pkuseg_model": "default", "use_jieba": False, "use_pkuseg": True}}})
```
`"pkuseg_model"` can be a named model provided by pkuseg or the path to a model directory. 
pkuseg could be configured to load its default …

Add pkuseg and serialization support for Chinese

---

website/src/components/landing.js
website/src/styles/landing.module.sass
website/src/widgets/landing.js

Resolves #5311.
Should fix the visual alignment of landing page boxes on certain platforms by making text box and button flex column elements so button is always at the bottom and text box takes up remaining space, regardless of how full it is. 
docs / website

Tidy up and fix alignment of landing cards

---

.github/contributors/Mlawrence95.md
.github/contributors/mlawrence95.md
website/docs/usage/examples.md

The first link in this sentence looks great, but the second link does not work due to a 404. I'm not sure what the original link contained, so I don't feel comfortable replacing it.
Minor documentation/website change. Replaces link with base text

[minor doc change] embedding vis. link is broken in `website/docs/usage/examples.md` 

---

spacy/errors.py
spacy/gold.pyx
spacy/tests/test_gold.py
spacy/util.py

Improve GoldParse NER alignment by including all cases where the start and end of the NER span can be aligned, regardless of internal tokenization differences.
To do this, convert BILUO tags to character offsets, check start/end alignment with `doc.char_span()`, and assign the BILUO tags for the aligned spans. Alignment for `O/-` tags is handled through the one-to-one and multi alignments.
Fixes #4791.
Bug fix / enhancement.

Improve GoldParse NER alignment

---

setup.py

Update `is_new_osx` according to discussions [here](https://github.com/explosion/spaCy/issues/5310) and [here](https://github.com/hajimes/mmh3/pull/22). @honnibal : the assumption is that the comment incorrectly mentioned `OSX >= 10.10`, and it should have been `OSX >= 10.7` instead?
Putting this on the `develop` branch where support for Python 2 is dropped, as apparently some behaviour may be different across Python 2 and 3.
(Hopefully) fixes #5310
bug fix

update is_new_osx function

---

spacy/tests/regression/test_issue5137.py
spacy/util.py
website/docs/usage/saving-loading.md

Fixes Issue #5137 + unit test
As described in the [documentation](https://spacy.io/usage/saving-loading#advanced-cfg), 
```
nlp = spacy.load("en_core_snek_sm", snek_style="cute")
```
should pass on the custom configuration (`snek_style`) all the way down to the `init` `**cfg` of a custom component.
This was not actually happening though. Added a quick fix by putting `config.update(overrides)` to pass that `config` on to `create_pipe`.
bug fix

Fix passing of component configuration

---

spacy/gold.pyx

* Initialize lower flag explicitly
* Handle whitespace words from GoldParse correctly when creating raw
text with orth variants
* Return the text with original casing if anything goes wrong
Bug fix.

Fix problems with lower and whitespace in variants

---

spacy/lang/en/tokenizer_exceptions.py

Instead of treating `'d` in contractions like `I'd` as `would` in all cases in the tokenizer exceptions, leave the tagging and lemmatization up to later components.
Fixes #5373.
Bug fix.

Improve exceptions for 'd (would/had) in English

---

spacy/vocab.pyx

Modify indices array type in `Vocab.prune_vectors` to accommodate OOV_RANK index as max(uint64).

Modify array type to accommodate OOV_RANK

---

spacy/lang/da/tokenizer_exceptions.py
spacy/lang/sv/tokenizer_exceptions.py

Remove `TAG` value from Danish and Swedish tokenizer exceptions because it may not be included in a tag map (and these settings are problematic as tokenizer exceptions anyway).

Remove TAG from da/sv tokenizer exceptions

---

spacy/gold.pyx
spacy/tests/parser/test_ner.py

cf Issue #5181 (which discusses two bugs, so shouldn't be closed just yet)
If a training text was empty, `gold.ner` was `None`, throwing an error when training the NER pipeline
bug fix

prevent None in gold fields

---

.github/contributors/ilivans.md
spacy/errors.py
spacy/tests/test_errors.py

Fix `ErrorsWithCodes().__class__` value - it should be a class rather than a string like `"[__class__] .."` before.
It's critical for functions which try to inference the class of an object, i.e. `isinstance`
I personally encountered the issue using `rollbar` which collects all the visible variables and tries to serialize those. In case of ErrorsWithCodes() it failed during `isinstance(o, collections.abc.Mapping)` check.
I ran all the tests using Python 3.8, Ubuntu 19.04, no spacy models preinstalled.
`spacy` is installed with `pip install -e path_to_repo`.
```
FAILED spaCy/spacy/tests/lang/fa/test_noun_chunks.py::test_noun_chunks_is_parsed_fa - Failed: DID NOT RAISE <class 'ValueError'>
======================== 1 failed, 1709 passed, 890 skipped, 49 xfailed, 1 xpassed, 4 warnings in …
```

Fix ErrorsWithCodes().__class__ return value

---

examples/experiments/tok2vec-ner/multihashembed_tok2vec.cfg
examples/training/train_ner.py
pyproject.toml
spacy/cli/train_from_config.py
spacy/gold.pyx
spacy/language.py
spacy/ml/_biluo.py
spacy/ml/_iob.py
spacy/ml/_precomputable_affine.py
spacy/ml/models/__init__.py
spacy/ml/models/defaults/__init__.py
spacy/ml/models/defaults/simple_ner_defaults.cfg
spacy/ml/models/parser.py
spacy/ml/models/simple_ner.py
spacy/ml/models/tagger.py
spacy/ml/tb_framework.py
spacy/pipeline/__init__.py
spacy/pipeline/pipes.pyx
spacy/pipeline/simple_ner.py
spacy/syntax/_parser_model.pyx
spacy/syntax/nn_parser.pyx
spacy/tests/parser/test_add_label.py
spacy/tests/parser/test_neural_parser.py
spacy/tests/pipeline/test_simple_ner.py
spacy/tests/regression/test_issue2001-2500.py
spacy/tests/regression/test_issue3001-3500.py
spacy/tests/serialize/test_serialize_config.py
spacy/tests/serialize/test_serialize_pipeline.py
spacy/tests/test_misc.py
spacy/util.py

The parser and NER models use a transition-based approach that's rather more intricate and indirect than the most obvious way people implement something like an NER model on top of a transformer. The most obvious way is more analogous to a tagger, with either a minimal modification to ensure valid sequences are produced, or perhaps a more involved CRF layer doing viterbi decoding with previous-tag features.
This PR adds a new component, provisionally titled `SimpleNER`, that uses this more baseline-ish strategy. The logic of applying the validity constraints is performed in a Thinc layer named `BILUO`.
Bug-fixes and some tweaks are also made to the existing parser model to make it more suitable for usage with transformers. In particular, the option to not use an output hidden layer …

Adapt parser and NER for transformers

---

spacy/cli/train_from_config.py
spacy/gold.pxd
spacy/gold.pyx

When we're reading in the gold data, we had a nested loop where
we looped over the brackets for each token, looking for brackets
that start on that word. This is accidentally quadratic, because
we have one bracket per word (for the POS tags). So we had
an O(N**2) behaviour here that ended up being pretty slow.
To solve this I'm indexing the brackets by their starting word
on the TokenAnnotations object, and having a property to provide
the previous view.

 Fix accidentally quadratic runtime in Example.split_sents

---

spacy/lang/de/syntax_iterators.py
spacy/lang/el/syntax_iterators.py
spacy/lang/en/syntax_iterators.py
spacy/lang/es/syntax_iterators.py
spacy/lang/fa/syntax_iterators.py
spacy/lang/fr/syntax_iterators.py
spacy/lang/id/syntax_iterators.py
spacy/lang/nb/syntax_iterators.py
spacy/lang/sv/syntax_iterators.py
spacy/matcher/matcher.pyx

Mostly internals, but I don't think we want to have argument names like `doc_or_span`, because this just makes it messy. Maybe it's just personal preference but I do think it's more consistent with our overall code style.
code style

Rename argument: doc_or_span/obj -> doclike

---

spacy/errors.py
spacy/lang/pl/lemmatizer.py

Tests currently fail on Python 2.7, which we still officially support on the spaCy v2.x line.
fix, compat

Use backwards-compatible super() for v2.x branch

---

spacy/tests/test_misc.py
spacy/util.py

Using `"blank:en"` as a shortcut for a blank model is a convention we've been using in Prodigy for a while and it's also come up in our examples in this repo. I keep writing conditionals to resolve this to `spacy.load` vs. `spacy.blank`, so I'm proposing making this part of the official API for `util.load_model` and `spacy.load`.
```python
nlp = spacy.util.load_model("blank:en")
nlp = spacy.load("blank:en")
nlp = spacy.blank("en")
```
⚠️ This is mostly intended to allow creating blank models and loading model packages programmatically based on string input, e.g. a command-line argument. The main recommended user-facing API is still `spacy.load` with a model path/package name and `spacy.blank` with a language code.
enhancement

Add blank:{lang} shortcut support to util.load_model

---

.github/contributors/lfiedler.md
spacy/kb.pyx
spacy/language.py
spacy/pipeline/pipes.pyx
spacy/tests/regression/test_issue5230.py
spacy/vectors.pyx

This PR fixes the issue where files were not closed in a timely manner, after some objects were writing to them during tests using `unittest`  #5230 
I ran through possible sources for the `ResourceWarnings` being raised. Classes directly pointed out by the warnings were `Language`, `Tagger`, `Vectors`. There the methods `to_disk` used write functions that did not close properly after write when used within tests (`unittest` and `pytest` as it turned out). Tests were implemented by catching the warnings and checking whether they still occur.
Having had a closer look, the classes `Pipes` and `EntityLinker` seemed to have implemented similar versions of `to_disk`, so I took care of them as well.
For each case I wrote unit tests (`unittest`, `pytest`) and fixed the affected code in a minimal …

Fix ResourceWarnings during unittest

---

requirements.txt
setup.cfg
spacy/cli/info.py
spacy/cli/package.py
spacy/cli/train.py
spacy/cli/validate.py
spacy/language.py
spacy/util.py

Better model compatibility and validation

---

spacy/analysis.py
spacy/language.py
spacy/tests/pipeline/test_analysis.py
spacy/tests/pipeline/test_pipe_methods.py

During `nlp.update`, components can be passed a boolean set_annotations
to indicate whether they should assign annotations to the `Doc`. This
needs to be called if downstream components expect to use the
annotations during training, e.g. if we wanted to use tagger features in
the parser.
Components can specify their assignments and requirements, so we can
figure out which components have these inter-dependencies. After
figuring this out, we can guess whether to pass set_annotations=True.
We could also call `set_annotations=True` always, or even just have this
as the only behaviour. The downside of this is that it would require the
`Doc` objects to be created afresh to avoid problematic modifications.
One approach would be to make a fresh copy of the `Doc` objects within
`nlp.update()`, so …

Support training of connected components

---

.github/contributors/JannisTriesToCode.md
website/docs/usage/adding-languages.md

Change 'realize' to 'realise'
Nothing but a minor fix of a typo.
documentation change

Documentation Typo Fix

---

spacy/cli/download.py
spacy/tests/test_misc.py
spacy/util.py

Turns out this works as well, and correctly returns `True`, even if the package was installed in the same Python session 🤷‍♀️ (This wasn't the case for the `pkg_resources.working_set` approach, so it needed the `require` workaround, which in turn would do very strict requirement resolution and lead to `is_package` returning `False` if the current environment was in a bad state and had incompatible dependencies installed.)

Simplify is_package check for installed model packages

---

examples/training/pretrain_textcat.py
spacy/cli/train.py
spacy/errors.py
website/docs/api/cli.md

- prevent using both pretrained components (from `base_model`) as well as a pretrained Tok2Vec layer (from `init_tok2vec`) in the `train` CLI command: throw custom error
- fix naming of `conv-depth` in CLI docs
- fix description of train iterations in docs
enhancement & doc fix

Pretrain fixes

---

spacy/vectors.pyx

The pretrain command didn't work anymore when giving it a vectors model:
`spacy pretrain my_data.jsonl en_vectors_web_lg my_output -i 20`
gave a
```
File "vectors.pyx", line 420, in spacy.vectors.Vectors.from_disk.load_keys
File "vectors.pyx", line 309, in spacy.vectors.Vectors.add
ValueError: [E197] Row out of bounds, unable to add row 0 for key 64.
```
It looks like the order of deserialization was wrong - the vectors (`self.data`) needs to be loaded first?
This code hasn't changed in ages though, so why did it stop working? My best guess is that this edit https://github.com/explosion/spaCy/pull/5430/files#diff-2e6a697a4ce7f5268000e28254546b00L306 in a recent PR by @adrianeboyd fixed a bug that was hiding the current bug ?
bug fix

fix deserialization order

---

requirements.txt
setup.cfg
spacy/cli/download.py
spacy/cli/package.py
spacy/cli/train.py
spacy/cli/validate.py
spacy/errors.py
spacy/language.py
spacy/tests/test_misc.py
spacy/util.py

```
UserWarning: [W095] Model 'en_model' (0.0.0) requires spaCy >=3.1.0,<3.2.0 and 
is incompatible with the current version (3.0.0.dev9). This may lead to 
unexpected results or runtime errors. To resolve this, download a newer 
compatible model or retrain your custom model with the current spaCy version. 
For more details and available updates, run: python -m spacy validate
```
ehnancement

Improve model version dependency handling

---

spacy/lang/es/examples.py
spacy/lang/es/tokenizer_exceptions.py

Fixes #5530  Adds to #3056 
File: spacy/lang/es/tokenizer_exceptions.py
Currently the lines 7-10 contain
```
_exc = {
"pal": [{ORTH: "pa", LEMMA: "para"}, {ORTH: "l", LEMMA: "el", NORM: "el"}],
"pala": [{ORTH: "pa", LEMMA: "para"}, {ORTH: "la", LEMMA: "la", NORM: "la"}],
}
```
These normalizations are "lunfardo" (slang) used in certain regions, but they can create errors in tokenization due to the actual meaning of the words, which follow:
From dle.rae.es (Real Academia Española)
"pal"
Del fr. pal, y este del lat. palus 'palo'.
1. m. Heráld. Palo o partición y mueble del escudo.
2. m. Mar. Linguete grande, y en especial, el del cabrestante.
It is basically a big stick
"pala" means shovel
I propose to put these two exceptions in another variable that can be selectively used if needed or …

Spanish tokenizer exception and examples improvement

---

spacy/errors.py
spacy/tests/test_misc.py
spacy/util.py

Show a warning if a model specifies a "loose" version constraint / unconstrained version / however we want to call it. Basically things like `>=3.0.0`, which means that the model will inevitably become incompatible (while still officially reporting that it is compatible). This case should only happen if a user manually edits the `meta.json` or if the version is old (v2.x). 
Wording could be improved here... communicating the point is a bit difficult.
```
UserWarning: [W094] Model 'en_model' (0.0.0) requires a spaCy version with very 
loose constraints: >=2.1.0. This can lead to compatibility problems as new 
spaCy versions are released, because the model may say it's compatible when it's 
not. Consider changing the "spacy_version" in your meta.json to a version range, 
for example: …
```

Add warning for loose version constraints

---

spacy/lang/ja/__init__.py
spacy/tests/lang/ja/test_serialize.py
spacy/tests/lang/ja/test_tokenizer.py

* Use `config` dict for tokenizer settings
* Add serialization of split mode setting
* Add tests for tokenizer split modes and serialization of split mode setting
Based on #5561
Enhancement.

Update Japanese tokenizer config and add serialization

---

.github/workflows/issue-manager.yml

Adding bot by @tiangolo to follow up on issues that got the label `answered`
* Currently runs at midnight
* Removes the label when someone (anyone) replies
* Automatically closes after 3 days 
* Writes a message "_This issue has been automatically closed because it was answered and there was no follow-up discussion_."
All of these parameters can be changed. Though the bot currently can't make a distinction between anyone replying, or restricting to only the original poster for instance.
This bot can be generalized to manage multiple labels. If we want it to cover also `more-info-needed` for instance, we could have a .yml file like this one: https://github.com/svlandeg/TestRepo/blob/master/.github/workflows/issue-manager.yml
Let's merge-squash these commits - JSON as a string in YAML …

bot for answered issues

---

.github/contributors/MartinoMensio.md
website/meta/universe.json

This PR adds to the spaCy Universe the wrapper I created for using in spaCy the Universal Sentence Encoder hosted on Tensorflow Hub https://tfhub.dev/google/collections/universal-sentence-encoder/1
It uses pipeline components to substitute the vector of documents, spans and tokens with a hook that computes the vector from the TensorFlow Hub model.
For more details, see https://github.com/MartinoMensio/spacy-universal-sentence-encoder-tfhub/

adding spacy-universal-sentence-encoder

---

spacy/cli/train_from_config.py
spacy/gold/__init__.py
spacy/gold/align.py
spacy/gold/annotation.py
spacy/gold/corpus.py
spacy/gold/example.py
spacy/gold/gold_io.pyx
spacy/language.py
spacy/pipeline/morphologizer.pyx
spacy/pipeline/pipes.pyx
spacy/scorer.py
spacy/syntax/gold_parse.pyx
spacy/syntax/nn_parser.pyx
spacy/tests/parser/test_add_label.py
spacy/tests/parser/test_ner.py
spacy/tests/parser/test_neural_parser.py
spacy/tests/parser/test_preset_sbd.py
spacy/tests/test_gold.py
spacy/tests/test_language.py

This shouldn't be merged, it's just a checkpoint where the tests are passing while I continue working. It might be useful in reviewing the changes later or if we decide to take a different approach.
These changes remove the `GoldParse` object from the library API, and hide it as an internal detail of the `spacy.syntax` module. Things pass around the `Example` object, which does not have any support for `GoldParse` directly.
~This currently doesn't support all previous functionality, e.g. the `ignore_misaligned` isn't working here. While the tests pass, training would probably break for some reason.~
Update: It should be fully working now, e.g. training works, tests pass, etc.

More steps on reforming spacy.gold

---

spacy/lang/ja/__init__.py
spacy/tests/lang/ja/test_tokenizer.py

The current sentence segmentation algorithm seems to perform poorly and having problematic sentence segmentation set by the tokenizer can cause unexpected behavior in following components, in particular for the parser in the default provided models.
I think it would be better to implement this as a separate pipeline component like a custom `JapaneseSentencizer` that can be included if desired. (Overall the behavior is very similar to the `Sentencizer` except that it additionally keeps track of paired punctuation.)
Bug fix.

Disable sentence segmentation in ja tokenizer

---

.github/contributors/theudas.md
spacy/pipeline/pipes.pyx

I am dealing with a lot of short sentences. For disambiguation, it is sometimes needed to also include the neighbor sentences.
I changed the predict method of NEL to include n_sents neighbour sentences when generating the vector for the model. There was no change to the training needed, since training ignores sentence scopes.
Enhancement

Added Parameter to NEL to take n sentences into account

---

spacy/cli/train_from_config.py

Add `--code-path` option to training CLI to allow importing arbitrary code from a Python file, like custom registered functions referenced in the config, before training. Will also allow training "templates" to consist of `config.cfg` and `code.py`.
The method of doing it (see `util.import_file`) should be very solid, it's also how we're loading custom recipes from a file in Prodigy.
enhancement

Add --code-path option to train CLI

---

spacy/lexeme.pyx
spacy/tests/vocab_vectors/test_vectors.py
spacy/tokens/token.pyx

Fix `Token.is_oov` and `Lexeme.is_oov` so they return `True` when the lexeme does **not** have a vector.

Fix polarity of Token.is_oov and Lexeme.is_oov

---

spacy/util.py

Allowing `vocab` in overrides leads to duplicate vocab arguments when initializing components since the vocab is already configured through overrides for `nlp`, so remove it before initializing individual components.
Fixes #5620.
Bug fix.

Skip vocab in component config overrides

---

spacy/pipeline/pipes.pyx
spacy/tests/pipeline/test_tagger.py

In `Tagger.begin_training()` check for new tags aside from `_SP` in the new tag map initialized from the provided gold tuples when determining whether to reinitialize the morphology with the new tag map.
This fixes a regression introduced by #5527 when `Tagger.begin_training()` is called without gold tuples.
Fixes #5648.
Bug fix.

Disregard special tag  _SP in check for new tag map

---

.github/contributors/PluieElectrique.md
spacy/lookups.py

When loading a model's vocab, `Lookups` creates several `Table`s. Each `Table` creates a `BloomFilter` with a default size of 1 million items. For small models, this size is too big. (This is assuming that the lookup tables are read-only and that we don't need to allocate extra space--I may be wrong about this.)
For example, here are the sizes (`len(data)`) of `en_core_web_sm-2.3.0`'s vocab:
```
lookups.bin
lemma_lookup: 41582
lexeme_norm: 3506
lemma_rules: 5
lemma_index: 4
lemma_exc: 4
lookups_extra.bin
lexeme_cluster: 0
lexeme_prob: 0
lexeme_settings: 0
```
With a default error rate of `1e-4`, a `BloomFilter` of 1 million items takes up about 18.3 MiB, which results in a total of 146.4 MiB for the eight tables above. If we instead use the sizes of the data to hint the `BloomFilter`, we …

Reduce memory usage of Lookup's BloomFilter

---

spacy/lang/ja/__init__.py
spacy/tests/lang/ja/test_tokenizer.py

Convert the user_data values so that they can be loaded as custom token extensions for `inflection`, `reading_form`, `sub_tokens`, and `lemma`.

Convert custom user_data to token extension format for Japanese tokenizer

---

spacy/cli/project.py
spacy/errors.py
spacy/util.py

Some small fixes:
- `shlex.split` needs the `posix` flag to work on Windows
- added some more informative Error messages here and there, because debugging wasn't always straightforward
- cloning a project in the working dir (no `dest` parameter) didn't work for me, because it would always say the working dir already exists. I added 
```
if dest == Path.cwd():
dest = dest / name
```
so that it would create the new dir in the subdir of the working dir. Hopefully that doesn't break anything on Linux?
After cloning the GH repo in the temp dir and moving it, on my system (running as admin), the script can't clean up the temp directory:
>  UserWarning: [W091] Could not clean/remove the temp directory at ...\Temp\tmp889ccvy9: [WinError 5] Access is denied: …

Fixes to project CLI

---

.github/contributors/hertelm.md
website/docs/usage/rule-based-matching.md

The result of the code example at https://spacy.io/usage/rule-based-matching#adding-patterns is `15578876784678163569 HelloWorld 0 3 Hello, world`, which does not match with the text below, where the span is (0, 2). I think the code outcome is the expected result, since the pattern comprises three tokens (_Hello_, _,_, and _world_).
A change to the website.

Website: fixed the token span in the text about the rule-based matching example

---

website/docs/api/phrasematcher.md

Very minor fix in docs, specifically in this part:
```
matcher = PhraseMatcher(nlp.vocab)
>   for doc in matcher.pipe(texts, batch_size=50):
>       pass
```
`texts` suggests the input is an iterable of strings. I replaced it for `docs`.
Minor change in documentation
- [Does not apply] I ran the tests, and all new and existing tests passed.
- [ x ] My changes don't require a change to the documentation, or if they do, I've added all required information.

Minor fix in PhraseMatcher api docs: pipe(docs) instead of pipe(texts)

---

spacy/cli/project.py

Bugfix following PR #5679
EDIT: also added `try`-`except` because the `git` commands otherwise exit unelegantly. e.g. when the subfolder in the default repo doesn't exist, it would say
> error: Sparse checkout leaves no entry on working directory
and nothing more. Now it gives a full stack trace, including messages such as 
> ✘ Could not clone 'woopsie' in the repo
'https://github.com/your-anon-repo'.
> FileNotFoundError: [Errno 2] No such file or directory: '...\\Temp\\tmpcx81e311\\woopsie'
bug fix

bugfix exec usage in dvc.yaml

---

.github/contributors/tiangolo.md
bin/spacy
requirements.txt
setup.cfg

This PR does the following:
* Pin Typer to a version range safe from breaking changes (there could be breaking changes between `>=0.3.0` and `>=0.4.0`).
* Add `shellingham` as a dependency, a small library used by Typer to detect the current shell and be able to install completion automatically with:
```console
$ spacy --install-completion
```
Without `shellingham` it would have to be:
```console
$ spacy --install-completion zsh
// or
$ spacy --install-completion bash
// or
$ spacy --install-completion fish
// etc.
```
* Update the way the standalone `spacy` command is created, from an integrated shell script to a pure Python "entrypoint" in setuptools:
* This fixes shell completion because with the current shell script the actual command called ends up being `python -m spacy some-args` …

♻ Refactor CLI setup for completion

---

spacy/tokens/doc.pyx
spacy/tokens/span.pyx

These have been deprecated for a while and shouldn't be used anymore, so we might as well remove them for v3.
enhancement

Remove deprecated methods: Doc.print_tree, Doc.merge, Span.merge

---

.gitignore
MANIFEST.in
setup.py
spacy/language.py

Include git commit in package and model meta
* save current git commit in `spacy/git_info.py`
* include current git commit in `meta.json` when models are saved
* git version code in `setup.py` is adapted from numpy, add `licenses/3rd_party_licenses.txt` with relevant license
Enhancement

Include git commit in package and model meta

---

spacy/cli/pretrain.py

At some point, `util.minibatch_by_words` was only taking `Example`'s, which is why we started using `Example` in the `pretrain` script, just to wrap the raw text in an object and get it back out. A little silly.
As `util.minibatch_by_words` has been generalized, we can just stick to batches of texts here.
This runs for me like so:
```
spacy_develop>python -m spacy init-model "en" output_init_dev -j lexemes.jsonl -v vectors.npz -V 20000
spacy_develop>python -m spacy pretrain examples\training\textcat_example_data\jigsaw-toxic-comment.jsonl output_init_dev output_pretrain examples\experiments\onto-joint\pretrain.cfg
```
bug fix

fix to pretrain script

---

spacy/cli/convert.py
spacy/gold/converters/json2docs.py
spacy/gold/corpus.py
spacy/gold/example.pyx
spacy/tests/serialize/test_serialize_doc.py
spacy/tokens/_serialize.py
spacy/tokens/doc.pxd
spacy/tokens/doc.pyx

Now that we don't have the `GoldParse`, it's important that the `Doc` object be able to track whether it was created from actual text, or whether we filled in the `spaces` variable with just `True`. This addresses a bug in the conversion where incorrectly spaced text was being tokenized.
The name of the field is kind of janky, but I don't know what else to call it.
We should create a flags variable on the `Doc` to hold these flag values, it's getting a bit bad to have all this cruft on the object. We can just have accessors in Python.

Record whether Doc objects are built from known spacing

---

.github/contributors/mikeizbicki.md
spacy/lang/ko/__init__.py

**The Bug:** The original code in the `Korean` class called the `MeCab` constructor once for each document being parsed.  This code has a large overhead, however, because it must launch and kill a system process for each document.  (Each `MeCab` class communicates with the `mecab` executable via a system process).
**The Fix:** This pull request changes the behavior so that the `MeCab` constructor is called exactly once when the `Korean` class is executed, and the constructor is reused for each of the documents.  This is how `MeCab` was intended to be used, and the reduced overhead results in a 100x speedup.  On the original code, running
```
>>> import timeit
>>> import spacy.lang.ko
>>> nlp = spacy.lang.ko.Korean()
>>> timeit.timeit(lambda: nlp('이거은 테스트 케이스를 생성하기 위해 Google Translate에 넣은 …
```

fix bug in Korean language, resulting in 100x speedup by reducing overhead of mecab

---

.github/contributors/jbesomi.md
website/meta/universe.json

Add [texthero](https://github.com/jbesomi/texthero) to SpaCy Universe. Texthero is a python toolkit to work with text-based dataset quickly and effortlessly. It provides capabilities to preprocess, represent, and visualize any text-dataset quickly and effortlessly.
[texthero.nlp.named_entities](https://texthero.org/docs/api/texthero.nlp.named_entities) and [texthero.nlp.noun_chunks](https://texthero.org/docs/api/texthero.nlp.noun_chunks) are Pandas wrapper around SpaCy. 
- changed universe.json only

Add texthero to universe.json

---

website/meta/universe.json

Fix quote issue in spaczz universe.json

---

spacy/ml/models/textcat.py
spacy/ml/models/tok2vec.py
spacy/tests/regression/test_issue5551.py
spacy/tests/test_models.py

Testing reproducibility for `Tok2Vec` and `textcat` - this works when hard-coding the seeds for the `HashEmbed` layers.
Fixes #5551 
bug fix

Fixing reproducible training

---

spacy/errors.py
spacy/gold/example.pyx
spacy/language.py
spacy/pipeline/pipes.pyx
spacy/pipeline/simple_ner.py
spacy/pipeline/tok2vec.py
spacy/syntax/nn_parser.pyx
spacy/tests/regression/test_issue4001-4500.py
spacy/tests/test_gold.py
spacy/tokens/doc.pyx

Some further clean up of the v.3 code:
* consistently return `losses` dict after `update` call of `language` & pipe components 
* `update` functions of components now have a keyword separator to avoid passing in wrong things after the v.3 refactor
* removed `tensors` as return value from `predict` and as input from `set_annotations` - was never used
* added few more `Example` tests
* bugfix around `W028`
The docs are updated on the nightly docs branch.
enhancement & bugfix

cleanup components API

---

spacy/cli/__init__.py
spacy/cli/debug_model.py
spacy/cli/train.py
spacy/tests/test_models.py

On Matt's suggestion, I implemented a script that will hopefully help us debug ML models easier in the future. I think over the past few months, we've all written many versions of this, so probably a good idea to make this a central tool/script.
I think this may also really help users understand how their model is built, and what happens internally when initializing / training.
The idea is that you feed it with a model config and it'll run on some toy data. By default, it only shows you the final predictions:
```
python -m spacy debug-model entity_linker_defaults.cfg
ℹ Using CPU
ℹ Analysing model with ID 52
ℹ Prediction:
[[ 6.06358    5.3513675 14.997823 ]  [ 7.18159    8.246782  18.731634 ]  [
6.0793247  7.8958707 15.619816 ]  [ 4.023115   4.7302594 14.28684  ]]
```
You can check for …

debug-model script

---

spacy/cli/train.py

The meta serialized in the _final_ model in `cli/train.py` is actually the model's meta, not the meta provided via the commandline. This overwrites the meta in the `final-model` directory before reading it in again, so it is up to date.
bug fix

fix meta serialization in train

---

spacy/ml/_character_embed.py

Fix `doc.to_utf8` for usage of `CharacterEmbed` on GPU (was already fixed on `master`)
Together with https://github.com/explosion/thinc/pull/365, makes `CharEmbed` / the morphologizer work again on GPU.
bug fix

fix doc.to_utf8 on GPU

---

spacy/errors.py
spacy/lang/zh/__init__.py
spacy/tests/conftest.py
spacy/tests/lang/zh/test_serialize.py
spacy/tests/lang/zh/test_tokenizer.py
website/docs/usage/models.md

Refactor `ChineseTokenizer` configuration so that it uses a single `segmenter` setting to choose between character segmentation, jieba, and pkuseg.
* replace `use_jieba`, `use_pkuseg`, `require_pkuseg` with the setting `segmenter` with the supported values: `char`, `jieba`, `pkuseg`
* make the default segmenter plain character segmentation `char` (no additional libraries required by default)
Enhancement.

Refactor Chinese tokenizer configuration

---

spacy/lang/en/__init__.py
spacy/lang/en/punctuation.py
spacy/lang/punctuation.py
spacy/tests/lang/en/test_text.py
spacy/tests/lang/fr/test_exceptions.py

Currently, splitting on a hyphen as infix happens only when the hyphen is inbetween `ALPHA` characters. This PR extends that to also include cases where the previous word ends with a number `0-9`.
This solves a case like `6,000-year` which makes it 3 tokens (instead of 1).
Funnily enough, checking the test suite, we previously were testing that "11-septembre" would also be one token in French. I don't see the rationale for this? With the current edit, this would be 3 tokens and I think that's fine?
enhancement?

Hyphen infix
