docs/source/quickstart.rst

Fix import typo in docs

---

spacy/en/download.py

It would also be nice to have a checksum for this.

Force SSL for downloading English language data.

---

requirements.txt
setup.py
spacy/en/download.py
spacy/en/uget.py

get rid of wget dependency (and its pypi/conda naming confusion)
uget supports partial downloads and checksums
by default dest_dir is not remove anymore (see --force flag)

add custom download tool (uget), replace wget with uget

---

spacy/tokenizer.pxd
spacy/tokenizer.pyx
tests/test_pickle.py
tests/tokenizer/test_tokenizer.py

- Add tests to test_pickle and test_tokenizer that save to tempfiles.

Add __reduce__ to Tokenizer so that English pickles.

---

spacy/tests/print/test_print.py
spacy/tokens/doc.pyx
spacy/tokens/spans.pyx
spacy/tokens/token.pyx

Should now be py[23] compatible - tested it locally. Used six to check python versions.

fixed error in python2 when printing unicode

---

.appveyor.yml
.travis.yml
setup.py
spacy/__init__.py
spacy/about.py
spacy/en/download.py
spacy/language.py
spacy/lemmatizer.py
spacy/matcher.pyx
spacy/tagger.pyx
spacy/tests/conftest.py
spacy/tests/serialize/test_packer.py
spacy/tests/tagger/test_lemmatizer.py
spacy/tests/website/conftest.py
spacy/tests/website/test_home.py
spacy/tokenizer.pyx
spacy/util.py
spacy/vocab.pyx

```
a model can be specified:
1) by calling a Language subclass
- spacy.en.English()
2) by calling a Language subclass with via (previously: data_dir)
- spacy.en.English('my/model/root')
- spacy.en.English(via='my/model/root')
3) by package name
- spacy.load('en_default')
- spacy.load('en_default==1.0.0')
4) by package name with a relocated package base
- spacy.load('en_default', via='/my/package/root')
- spacy.load('en_default==1.0.0', via='/my/package/root')
```

refactored data_dir->via, add zip_safe, add spacy.load()

---

examples/parallel_parse.py

There's probably a better default value....

added batch_size as keyword argument

---

.gitignore
examples/InventoryCount/Instructions.md
examples/InventoryCount/inventory.py
examples/InventoryCount/inventoryCount.py
examples/InventoryCount/main.py

Added an example of reusing the English() object through using module reloading. On top of that, added an example of determining inventory counts for a few test sentences, and the way to interact with Doc objects, finding wether they're a noun with descriptive compound objects ('fresh ground beef' VS 'beef')

Added reloadable English() example for inventory counting

---

spacy/gold.pyx

changed gold.pyx:read_json_file so it doesn't expect any annotation levels when reading in data files

German ner

---

bin/parser/train.py
spacy/de/__init__.py

overwrites the default_vocab function in `class German` to install a dummy lemmatizer until a proper one is built

German lemmatizer dummy

---

spacy/symbols.pxd
spacy/symbols.pyx
spacy/syntax/iterators.pyx
spacy/syntax/parser.pyx
spacy/tests/conftest.py
spacy/tests/integration/test_model_sanity.py
spacy/tests/parser/test_base_nps.py
spacy/tests/unit/test_parser.py

This merges from a branch where I actually redo the tests, but I found a bug in the German noun chunker that I fixed. The merge also includes tests for the noun chunker behaviour and some small changes to the tests.

Fix German noun chunker

---

spacy/util.py

Revert "Fix get_lang_class parsing"

---

requirements.txt

current new version of plac(0.9.3) is creating problem but it is working <0.9.3

plac version in requirements

---

website/blog/sense2vec-with-spacy.jade

it was not working - variable `tokens` does not exist; now it is fine

fixed sense2vec blog post code

---

setup.py

Noticed after updating to latest spaCy I got breakage due to missing ujson - added this dependency in setup.py here

added ujson dependency to setup.py

---

website/docs/tutorials/rule-based-matcher.jade

Hi everybody,
I added the merge_phrases function to the tutorial and fixed a minor bug. Let me know if something should be restructured.

Working version of rule matcher tutorial

---

website/docs/usage/data-model.jade

removed typo

---

website/docs/usage/dependency-parse.jade

Fixed some typos and errors on the page.

Fixing typos and errors!!

---

spacy/tests/spans/test_merge.py
spacy/tokens/span.pyx

span.merge bugfix

---

examples/keras_parikh_entailment/__main__.py
examples/keras_parikh_entailment/keras_decomposable_attention.py

Also added import of `build_model()` in __main__.py

PR to fix Issue #623

---

examples/nn_text_class.py

This PR makes two improvements. First, it fixes an `AttributeError` that comes from running `examples/nn_text_class.py`, which rises out of [lexeme.pyx](https://github.com/explosion/spaCy/blob/master/spacy/lexeme.pyx#L159).
``` python
File "nn_text_class.py", line 272, in <module>
#s.strip_dirs().sort_stats("time").print_stats(100)
File "/Users/kyle/tensorflow_kj/venv/lib/python3.5/site-packages/plac_core.py", line 328, in call
cmd, result = parser.consume(arglist)
File "/Users/kyle/tensorflow_kj/venv/lib/python3.5/site-packages/plac_core.py", line 207, in consume
return cmd, self.func(*(args + varargs + extraopts), **kwargs)
File "nn_text_class.py", line 251, in main
for batch in minibatch(train_data, bs=batch_size):
File "nn_text_class.py", line 87, in …
```

Fix attribute error in nn_text_class.py, add module docstring

---

spacy/matcher.pyx

As already declared on line 211.

Remove duplicated line of vocab declaration

---

website/docs/usage/deep-learning.jade

Fixed a minor typo in deep learning tutorial docs.

---

website/docs/usage/language-processing-pipeline.jade

Fix another typo on the website

---

spacy/language.py

Fixes https://github.com/explosion/spaCy/commit/618ac36093e64bdc26e5d023c50feedbf4f53706#commitcomment-19939319. Completely untested; hastily wrote this in the GitHub editor whilst at work.

Fix syntax mistake

---

website/docs/usage/entity-recognition.jade

Just some typo fixes in the docs.

Minor typos Fix

---

website/docs/usage/entity-recognition.jade

Load English language model in example for updating the NER model
added 'en' to spacy.load(..) in example for https://spacy.io/docs/usage/entity-recognition#updating
changed
nlp = spacy.load(entity=False, parser=False)
to 
nlp = spacy.load('en', entity=False, parser=False)
the example was not executable without loading the English language model

added 'en' to spacy.load(..)

---

spacy/symbols.pyx

Add acl to symbols.pyx
Add acl to symbols.pyx

Add acl to symbols.pyx

---

examples/training/load_ner.py

Hi Matt! Sorry I actually missed the load_ner.py file (didn't git add). This shows how to actually load the model. Thanks again for your quick response!

actually commit load_ner.py

---

.github/contributors/magnusburton.md
setup.py
spacy/__init__.py
spacy/sv/__init__.py
spacy/sv/language_data.py
spacy/sv/stop_words.py

Base commit for Swedish. Added stop words and the contributor agreement.

Initial commit for Swedish

---

website/docs/usage/training.jade

Updated Training Documentation
Import of tagger from spacy.pipeline failed, so switched to spacy.tagger, and update required a goldparse object, not a list of tags, so updated as well.
In description 
NA
NA
- [ x] Documentation (Addition to documentation of spaCy)
- [ x] My code follows spaCy's code style.

update to training doc

---

spacy/sv/morph_rules.py

I added morph rules based on the ones over at the [Swedish Wiktionary (See the table)](https://sv.wiktionary.org/wiki/deras). Any questions about how I thought when creating these rules are appreciated. Thanks guys!

Added Swedish morph rules

---

README.rst

fixed minor typo

---

website/docs/usage/rule-based-matching.jade

Tiny code typo

---

spacy/sv/tokenizer_exceptions.py

I added abbreviations for januari (January) and the abbreviations for the two biggest cities in Sweden (Stockholm & Göteborg)

Added Swedish abbreviations as token exceptions

---

spacy/vocab.pyx

Minor change, maintains code semantics.

Avoid "True if ... else False"

---

website/docs/usage/rule-based-matching.jade

Make it clear that Matcher attributes live in spacy.matcher.attrs.
Explain where the variables used in the example code (LOWER, IS_PUNCT) are data attributes of spacy.matcher.attrs.
See above.
It's not clear where these are found without looking through the code.
I proofread the sentence.

Clarify Rule-Based Workflow Docs

---

spacy/fr/__init__.py
spacy/fr/language_data.py
spacy/fr/punctuation.py
spacy/tests/conftest.py
spacy/tests/fr/__init__.py
spacy/tests/fr/test_exceptions.py
spacy/tests/fr/test_text.py

Add the custom rules necessary to correctly tokenize French (elision rules mostly). Some rare tokenization exceptions are not covered for the moment.

Add French tokenization support

---

spacy/tests/regression/test_issue792.py

Added file providing regression tests for issue #792.

Added regression test for Issue #792.

---

spacy/tokens/doc.pyx

Small fix for provided example

Small `Doc.count_by` documentation update

---

spacy/fr/language_data.py

Adds a few more tokenizer exceptions

Adds more French tokenizer exceptions

---

spacy/sv/lemma_rules.py
spacy/sv/tokenizer_exceptions.py

I added some swedish lemma rules and some more verb contractions including a loop for `fattaru` etc.
I have a question about how I've go ahead with implementing the last two adjective categories [here](http://www.worddive.com/grammar/sv/svensk-grammatik/5-komparation-av-adjektiv/). Since the base word is for example `god` (nice or kind) and it's an irregular adjective. What's the best approach to words like this?

Added swedish lemma rules and more verb contractions

---

website/docs/usage/entity-recognition.jade

(Seems to have solved it for me -- but would be happy if it were tested somewhere else)
See issue #832 (I believe it is simple enough)
- [ x ] **Documentation** (addition to documentation of spaCy)
- [ x ] My change requires a change to spaCy's documentation.     ***(not sure if applicable)***
- [ x ] I have updated the documentation accordingly.

Fixes example 3 of entity recognition (see issue #832)

---

website/docs/api/token.jade

There was a typo in the Token class documentation: the description for suffix_ attribute mentions start of sentence when it should mention end of sentence.

Updated Token class documentation

---

spacy/tests/bn/__init__.py
spacy/tests/bn/test_tokenizer.py
spacy/tests/conftest.py
spacy/tests/tokenizer/test_tokenizer.py

This adds a few tests for the Bengali tokenizer.

Add tests for Bengali

---

website/docs/usage/entity-recognition.jade

The original code forget to import the `random` module and the `EntityRecognizer` module.

**Documentation**： Edit example code

---

spacy/attrs.pyx
spacy/de/tag_map.py
spacy/en/tag_map.py
spacy/language_data/tag_map.py
spacy/morphology.pxd
spacy/morphology.pyx
spacy/parts_of_speech.pxd
spacy/parts_of_speech.pyx
spacy/symbols.pxd
spacy/symbols.pyx
spacy/syntax/nonproj.pyx
spacy/tagger.pyx
spacy/tokens/doc.pyx
spacy/tokens/token.pyx

I'm working on Russian language support. This commit is a prerequisite (Russian UD corpus uses UD v2.0).
I looked at UD v2.0 documentation and added some symbols. To keep old code working, I didn't remove old symbols, even if it was required by new standard.

Add support for Universal Dependencies v2.0

---

spacy/cfile.pyx
spacy/gold.pyx
spacy/language.py
spacy/matcher.pyx
spacy/morphology.pyx
spacy/pipeline.pyx
spacy/tagger.pyx
spacy/tokenizer.pyx
spacy/util.py

Clean many unused import statement across the project.

Remove unused import statements

---

website/docs/usage/training.jade

Fix doc typo

---

spacy/cli/link.py

For Python 2 on Windows, pathlib's symlink capability doesn't work. Instead, we shell out to mklink

Possible solution to #909

---

spacy/cli/package.py

correction of package.py (encoding on open instead of write)

---

spacy/pt/stop_words.py

Fixing typos in Portuguese stop words.
- [ x ] **Bug fix** (non-breaking change fixing an issue)

Fix typos in Portuguese stop words

---

spacy/pt/stop_words.py
spacy/pt/tokenizer_exceptions.py

Improve the Portuguese language word lists.
Let me know if I can help with something PT related.

Portuguese improvements

---

spacy/cli/model.py

Fixed typo in `spacy model` CLI

---

website/docs/usage/deep-learning.jade

This is a great tutorial, but I think it is weirdly explained in the current form. The largest part of the code is about implementing the actual sentiment analysis model, not about counting entities. (which is not even present in the `deep_learning_keras.py` script in `examples`)

Make object of the deep learning tutorial clearer

---

website/docs/usage/adding-languages.jade

tried to google about connlu format. Saw there is conll format, not connlu.

fix typo, CONLL format

---

website/docs/usage/language-processing-pipeline.jade

Turn the generator expression into a list comprehension before printing

Print list comprehension

---

website/docs/api/token.jade

Add Token.orth and Token.orth_ description in doc

---

spacy/tokens/doc.pyx

Fix issue #1069 with custom hook `Doc.sents` definition

---

website/docs/api/doc.jade

Span as written gives empty text.
(Is there a way to produce one pull request for cross-file doc updates? I feel like I'm cluttering your queue)

Fixed span example error

---

website/docs/usage/deep-learning.jade

link to Doc API documentation fixed

Fixed link

---

spacy/lang/hu/punctuation.py
spacy/tests/tokenizer/test_exceptions.py

Fixed emoji handling for Hungarian
Fixes https://github.com/explosion/spaCy/issues/1088

Fixed emoji handling for Hungarian

---

spacy/es/tokenizer_exceptions.py
spacy/syntax/iterators.pyx

This PR :
- Fix the spanish sentence segmentation by reconfiguring tokenizer exceptions
- Add a spanish nouns chunker

Spanish model features

---

spacy/cli/package.py

Fixed typo in cli/package.py

---

website/docs/api/doc.jade

docs - Update doc.jade (Just remove a duplicate 'doc =')

---

website/docs/usage/lightning-tour.jade

docs - Add read() method when opening file (Lightning tour)

---

website/docs/usage/visualizers.jade

docs - Fix url error for Displacy Ent visualizer

---

website/docs/usage/word-vectors-similarities.jade

Hi,
There is a typo about the capital of Lithuania.
Vilnius is the capital of Lithuania https://en.wikipedia.org/wiki/Vilnius
Ljubljana is the capital of Slovenia https://en.wikipedia.org/wiki/Ljubljana

Changed the capital of Lithuania to Vilnius

---

spacy/cli/converters/conllu2json.py

Fixed conllu converter
@ines I still not managed to use my data, but it looks like there is a bug in the converter. Can you confirm it?

Fixed conllu converter

---

website/docs/usage/_spacy-101/_tokenization.jade

Changed the typo _fist_ -> _first_ in the sentence:
> Fist, the raw text is split on whitespace characters [...]

Fix small typo in the new spaCy 101 guide

---

website/docs/api/vocab.jade

This document describes the `Vocab` class, not the `Span` class.
Just a documentation typo fix.

fix confusing typo

---

website/docs/usage/lightning-tour.jade

make this work in python2.7

---

website/docs/usage/saving-loading.jade

https://spacy.io/docs/usage/cli/#package is a 404.  
Changed to https://spacy.io/docs/usage/cli#package 
Definitely a larger fix possible to deal with trailing slashes

.../cli/#foo is 404

---

spacy/fr/stop_words.py

Minor change maybe not even operative
Pretty easy to understand.
I'd be pleased to have @Gregory-Howard opinion ?

French NUM_WORDS and ORDINAL_WORDS

---

website/docs/usage/processing-text.jade

Use an example from an old issue https://github.com/explosion/spaCy/issues/172#issuecomment-183963403.
- [x ] **Documentation** (addition to documentation of spaCy)

improve pipe, tee, izip explanation

---

website/docs/usage/adding-languages.jade

Fix small typo in documentation

---

website/docs/usage/_data.json

I've replaced the dead URL with a link from the Wayback Machine

Fix broken tutorial link on website

---

spacy/__main__.py
spacy/cli/__init__.py
spacy/cli/model.py

Ported Model CLI for v2
Took the model cli from the master branch, and adapted it for the v2 workflow. (Probably needs to be reviewed)

Ported model cli from v1

---

spacy/cli/model.py

Added vector loading to model cli
This changeset enables the model cli to store word vectors in the vocabulary (extends the functionality of https://github.com/explosion/spaCy/pull/1276). However I have not managed to figure out where and how to store the `oov_prob` in the `Vocab` object.

Added vector loading to model cli

---

spacy/zh/__init__.py

Set the "cut_all" parameter in jieba.cut() to False, or jieba will return ALL POSSIBLE word segmentations.
For example, with cut_all=True, a single name "清华大学" will be segmented into four possible words and returned (i.e., "清华", "清华大学", "华大", "大学").

Set the "cut_all" parameter in jieba.cut() to False, or jieba will return ALL POSSIBLE word segmentations.

---

.github/contributors/mdcclv.md

Contributor agreement for Orion Montoya @mdcclv

---

examples/training/train_textcat.py
spacy/gold.pyx
spacy/pipeline.pyx

The TextCategorizer class is supposed to support multi-label
text classification, and allow training data to contain missing
values.
For this to work, the gradient of the loss should be 0 when labels
are missing. Instead, there was no way to actually denote "missing"
in the GoldParse class, and so the TextCategorizer class treated
the label set within gold.cats as complete.
To fix this, we change GoldParse.cats to be a dict instead of a list.
The GoldParse.cats dict should map to floats, with 1. denoting
'present' and 0. denoting 'absent'. Gradients are zeroed for categories
absent from the gold.cats dict. A nice bonus is that you can also set
values between 0 and 1 for partial membership. You can also set numeric
values, if you're using a text classification model that uses an …

💫 Fix multi-label support for text classification

---

.github/contributors/polm.md

This just adds my contributor agreement.

Contributor agreement

---

spacy/ja/__init__.py

Before this commit, the Mecab tokenizer had to be called twice when
creating a Doc- once during tokenization and once during tagging. This
creates a JapaneseDoc wrapper class for Doc that stashes the parsed
tokenizer output to remove redundant processing. 
I originally tried doing this without a Doc wrapper class by handling the shared info in the `Japanese.make_doc` function. However, it seems `make_doc` isn't used the way I thought... I expected it to be called in the below code:
import spacy
ja = spacy.load('ja')
doc = ja("日本語だよ")
But it seems it wasn't, and as a result it couldn't handle sharing information between the Tokenizer and Tagger.
Except for adding the one attribute to store Mecab output `JapaneseDoc` is a pass-through class, so I think this is OK, but if there's a better …

[ja] Stash tokenizer output for speed

---

.github/contributors/jerbob92.md

Added my contributor agreement.

Add myself to contributors

---

examples/training/train_new_entity_type.py

Fix #1444: fix training new entity type example

---

website/docs/usage/rule-based-matching.jade

Fixes #1104 rather than leaving it broken which seemed to be the executive decision.

DOC "OP" key in token spec

---

.github/contributors/ramananbalakrishnan.md
spacy/tests/doc/test_array.py
spacy/tokens/doc.pyx
website/api/doc.jade

Following PR: https://github.com/explosion/spaCy/pull/1435 , this a PR to port to v2 (on the `develop` branch)

Support single value for attribute list in doc.to_array

---

spacy/tests/doc/test_doc_api.py
spacy/tests/spans/test_span.py
spacy/tokens/doc.pyx
spacy/tokens/span.pyx

Port of PR https://github.com/explosion/spaCy/pull/1298 to v2.
Added functionality to obtain lowest common ancestor matrix.

Add LCA matrix for spans and docs

---

.github/CONTRIBUTOR_AGREEMENT.md
website/usage/_adding-languages/_language-data.jade

I was going through the `adding_languages` page and noticed a tiny typo :)
- [ x] My changes don't require a change to the documentation, or if they do, I've added all required details.

Minor typo [ nad => and ]

---

.github/contributors/IamJeffG.md

Contributing agreement to `master` branch.
This supports my open PR on `develop` branch (https://github.com/explosion/spaCy/pull/1479)

Contributing agreement - IamJeffG

---

.github/contributors/MathiasDesch.md
CONTRIBUTING.md
website/usage/_spacy-101/_similarity.jade

* I just changed the condition on similarity to display similar icon when similarity is > 0.5
* I also fixed a broken link to SCA template that I saw when I filled it
Small bug fix

Fix Doc mistake, showing visual of similarity when dissimilar

---

.github/contributors/DuyguA.md

Contributor file for a first pull request
This file:)

added contributor agreement for DuyguA

---

website/api/span.jade

trivial typo in docs

---

examples/vectors_fast_text.py

loading english fast text giving error because line contains new line at the end and rsplit is splitting it incorrectly

Add rstrip after reading line from  vec file #1582

---

website/usage/_vectors-similarity/_basics.jade

Fix typo in documentation

---

.github/contributors/bdewilde.md
spacy/tests/regression/test_issue1612.py
spacy/tokens/span.pyx

See Issue #1612.
Bugfix. Changed `span.orth_` property to simply return `span.text`, guaranteeing that they're always the same as the docs suggest should be the case.

Make span.orth_ = span.text, as advertised

---

.github/contributors/markulrich.md
website/usage/_processing-pipelines/_custom-components.jade

Documentation typo fix
Typo fix and added contribute agreement

Use local parameter in example MyComponent

---

.travis.yml

Use flake8 to look for syntax errors, undefined names

---

spacy/cli/model.py

I'm not sure that this command should be added, but since I have already written it for myself, why not share it :smile:
I've merged v1.x `model` cli command with v2.x `vocab` command into a new one, which helps to create models from raw data: words counts, brown clusters and vectors.
The command requires the following parameters:
- `lang`: model language
- `output_dir`: model output directory to store to
- `freqs_loc`: path to word counts file, should be in format, which described [here](https://spacy.io/usage/adding-languages#training)
- `clusters_loc`: [optional] location of Brown clusters data in format produced by [this](https://github.com/percyliang/brown-cluster) script
- `vectors_loc`: [optional] location of [word vectors](https://spacy.io/usage/adding-languages#word-vectors) file …

Added model command to create models from raw data

---

examples/training/train_textcat.py

Fix typo in comment

---

.github/contributors/IsaacHaze.md
spacy/cli/train.py
spacy/tests/regression/test_issue1622.py

Fix exception while trying to save the final trained model when training a new model with cli/train.py
Bugfix

Fix Issue 1622

---

spacy/cli/init_model.py

When running `spacy init-model` I get an exception from plac:
```
File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/Users/sorenlind/Documents/Developer/spacy-init/spacy/__main__.py", line 31, in <module>
plac.call(commands[command])
File "/Users/sorenlind/.virtualenvs/spacy-init/lib/python3.6/site-packages/plac_core.py", line 324, in call
parser = parser_from(obj)
File "/Users/sorenlind/.virtualenvs/spacy-init/lib/python3.6/site-packages/plac_core.py", line 133, in parser_from …
```

Remove abbreviation for positional plac argument

---

.github/contributors/Bri-Will.md
spacy/lang/lex_attrs.py
spacy/tests/regression/test_issue1698.py

Fixes issue #1698
Checks token text for presence of "@" symbol in order to prevent LIKE_URL from matching on e-mail addresses.
Bug fix
- [ x ] My changes don't require a change to the documentation, or if they do, I've added all required information.

Update lex_attrs.py. Fix like_url from matching on e-mail

---

website/usage/_training/_tagger-parser.jade

Fix minor mistakes in documentation.

doc: Fix minor mistakes

---

.github/contributors/mdda.md
website/usage/_linguistic-features/_dependency-parse.jade

(similar change to #1689, it seems).  
Also the assertion needs to include the case subject==descendant, since it appears possible to be in its own subtree, without being its own ancestor. 
Documentation fix

Documentation example fix : token.head needs '==' rather than 'is'

---

CONTRIBUTING.md

doc: Fix typo

---

.github/contributors/cbilgili.md
CONTRIBUTORS.md
spacy/lang/tr/__init__.py
spacy/tests/conftest.py
spacy/tests/lang/tr/test_lemmatization.py

- Ported Turkish lemmatization lookup dictionary from Turkish dictionary site http://st2.zargan.com/duyuru/Zargan_Linguistic_Resources_for_Turkish.html
- Adds simple Turkish test suite and lemmatization test

Adds Turkish Lemmatization

---

.github/contributors/kimfalk.md
spacy/lang/da/examples.py
spacy/lang/da/tokenizer_exceptions.py

Corrected what seems to be a automatic translation error in the examples file and added a tokenizer exception, which is used often in Danish. 
change to the documentation.

Two corrections in the da lan.

---

.github/contributors/zqhZY.md
spacy/lang/zh/__init__.py

fix No valid 'lang' setting found in model meta.json issue when pickling zh lang model 
bugfix

fix issue #1774

---

examples/keras_parikh_entailment/README.md

typos corrected

---

spacy/cli/convert.py
spacy/cli/download.py
spacy/cli/evaluate.py
spacy/cli/info.py
spacy/cli/link.py
spacy/cli/package.py
spacy/cli/profile.py
spacy/cli/train.py
spacy/cli/validate.py
spacy/cli/vocab.py

As suggested in https://github.com/explosion/spaCy/pull/1789#issuecomment-354997281, I have prefixed dummy argument names in the CLI commands with an underscore. This makes it more clear that they are dummy variables.
Enhancement.

Prefix dummy argument names with underscore

---

.github/contributors/kwhumphreys.md
CONTRIBUTING.md
spacy/lang/en/tokenizer_exceptions.py
spacy/tests/regression/test_issue1758.py

bug fix for https://github.com/explosion/spaCy/issues/1758

english tokenizer: handle "would've"

---

website/usage/_training/_basics.jade

Fixed an incorrect word order.

Small Grammar Fix to _basics.jade

---

spacy/tests/regression/test_issue1769.py

This PR finally adds tests for issue #1769 which don't cause build errors on Windows.
Adds tests

Add tests for issue #1769

---

.github/contributors/azarezade.md
spacy/lang/char_classes.py

Add Persian characters and the following:
- `٪` used instead of `%`
- `؟` used instead of `?`
- `﷼` used instead of `$`
- `،` used instead of `,`
- `؛` used instead of `;`
Enhancement

Add Persian character and symbols

---

.github/contributors/Kimahriman.md
spacy/cli/download.py
spacy/tests/regression/test_issue1904.py

Fixes #1904, removing dummy command argument from the link call after a download.
I added a quick and dirty test that just looks at the console output. Not sure if this is necessary/too fragile if the messages change in the future.
Bug fix

Fixed auto linking after download and added simple test to check

---

spacy/cli/init_model.py

Fixing issue described in #1928 
bug fix

Fix init_model issue

---

.github/CONTRIBUTOR_AGREEMENT.md
website/usage/_install/_instructions.jade

Fix typo in the installation docs.

---

README.rst

Missing the "sm" in the en_core_web_....load() call.

Typo correction in Readme file

---

.github/contributors/emulbreh.md
spacy/cli/evaluate.py
spacy/cli/train.py
spacy/util.py

Fixes https://github.com/explosion/spaCy/issues/1974

Don't fix random seeds on import

---

.github/contributors/enerrio.md
spacy/language.py
spacy/tests/regression/test_issue1959.py

This PR fixes issue #1959 where calling nlp.pipe won't modify text using a custom component. Here is some example code:
```python 
nlp = spacy.load('en')
texts = ['Apple is looking at buying U.K. startup for $1 billion.']
def clean_component(doc):
""" Clean up text. Make lowercase and remove punctuation and stopwords """
doc = [tok.text.lower() for tok in doc if (not tok.is_stop
and tok.pos_ != 'PUNCT' and
tok.pos_ != 'SYM')]
doc = ' '.join(doc)
return doc
nlp.add_pipe(clean_component, name='cleaner', after='ner')
for doc in nlp.pipe(texts):
print(doc)
```
This is the output before this PR:
``` 'Apple is looking at buying U.K. startup for $1 billion.'```
After this PR:
```'apple looking buying u.k. startup 1 billion'```
Big Fix

Fix Issue #1959

---

spacy/morphology.pxd
spacy/morphology.pyx

fix typo/missing here too

---

spacy/attrs.pyx

missing PrepCase attribute

---

.github/contributors/willismonroe.md
CONTRIBUTING.md
website/usage/spacy-101.jade

Broken github link to NLTK

---

.github/contributors/alldefector.md
spacy/lang/es/__init__.py
spacy/lang/es/syntax_iterators.py

Fix Spanish noun_chunks failure caused by typo

---

.github/contributors/doug-descombaz.md
website/usage/_processing-pipelines/_pipelines.jade

Fix typo ditectory -> directory

---

spacy/lang/en/stop_words.py
website/usage/_v2/_features.jade

Minor enhancements
I fixed a typo in website , referenced in #2054 
I added contracted forms of some auxiliary verbs:
```
'd              as in   He'd
'll             as in   I'll
'm              as in   I'm
n't             as in   don't
're             as in   You're
's              as in   She's or Let's
've             as in   could've 
```
One `C` letter addition :)
1 more line to stopwords list for contacted forms

Minor enhancements

---

website/api/pipe.jade

drop should be a float
Doco change

drop should be a float

---

website/api/doc.jade
website/usage/_spacy-101/_similarity.jade

Minor Issues in documentation I observed while going through
- [] I have submitted the spaCy Contributor Agreement.

Docs patch

---

.github/contributors/howl-anderson.md
spacy/cli/ud_train.py

This PR try to fix #2133 
Put global variable change operations to main() method to keep it from auto execute during importing
bug fix

bugfix for global-variable-change-in-runtime related issue

---

.github/contributors/ottosulin.md
spacy/lang/fi/lex_attrs.py
spacy/lang/fi/stop_words.py

Added my contributor agreement.

My contributor agreement

---

spacy/lang/fi/stop_words.py

Few stop words were words for numbers, which should be later included in lex_attrs.py. Gonna work on that later.

Fixed few Finnish stop words

---

spacy/lang/fi/lex_attrs.py
spacy/lang/fi/stop_words.py

Added Finnish numbers. Please advise if I didn't get the use of lex_attrs.py correctly :)

Finnish numbers

---

.github/contributors/ottosulin.md
spacy/lang/fi/examples.py
spacy/lang/fi/lex_attrs.py
spacy/lang/fi/stop_words.py

Added examples as translated equivalents of those in 'en' language.

Finnish examples

---

spacy/lang/pl/tokenizer_exceptions.py

more exceptions

---

spacy/tokens/doc.pyx

This PR try to fix #2194 
Check `Doc.noun_chunks_iterator` before `Doc.noun_chunks` call it.
bug fix

bugfix: `Doc.noun_chunks` call `Doc.noun_chunks_iterator` without checking

---

website/usage/_spacy-101/_vocab.jade

website documentation changes

---

.github/CONTRIBUTOR_AGREEMENT.md
.github/contributors/miroli.md

Just removing one row in the Swedish lemmatizer lookup table, år > åra.

Fixes #2238

---

.github/contributors/therealronnie.md
spacy/tests/doc/test_doc_api.py
spacy/tokens/doc.pyx

This PR addresses the issue #2228. This issue produces a `KeyError` when running:
```
Doc(nlp.vocab).from_bytes(nlp('This is a test').to_bytes(tensor=False), tensor=False)
```
or 
```
Doc(nlp.vocab).from_bytes(nlp('This is a test').to_bytes(sentiment=False), sentiment=False)
```
Bug fix.
- [*] I have submitted the spaCy Contributor Agreement.
- [*] I ran the tests, and all new and existing tests passed.
- [*] My changes don't require a change to the documentation, or if they do, I've added all required information.

Addresses Issue #2228 - Deserialization fails when using tensor=False or sentiment=False

---

spacy/gold.pyx

Fixes https://github.com/explosion/spaCy/issues/2269
bug fix
- [ x ] My changes don't require a change to the documentation, or if they do, I've added all required information.

Fixing KeyError by renaming SP to _SP

---

.github/contributors/bellabie

This time hopefully created in the right spot. (Sorry about that!)
Adding a NEW instance of the Contributor Agreement, instead of overwriting the template 🙇🏼‍♂️

B Cavello's signed Contributor Agreement v2

---

.github/contributors/mauryaland.md
spacy/lang/fr/stop_words.py

Add contraction forms of common French stop words such as articles ("le" ->  "l'").
Enhancement. All the stopwords added contain the apostrophe" ' "or " ’ ".

Update stop_words.py for French language

---

.github/contributors/LRAbbade.md

Just adding my contributor agreement.

Adding my contributor agreement

---

spacy/compat.py

* Use __in__ to avoid the nested _ands_ and _ors_.
* Dict comprehension directly tracks with the doc string
Simplifications

Simplify is_config() and normalize_string_keys()

---

website/usage/_linguistic-features/_rule-based-matching.jade

changed **interpretted** to **interpreted**
Corrected a simple spelling mistake. No testing required.

corrected spelling

---

.github/contributors/idealley.md

Added agreement

---

website/usage/_spacy-101/_lightning-tour.jade

adding a missing apostrophe

---

website/api/cli.jade

In source code [train.py](https://github.com/explosion/spaCy/blob/master/spacy/cli/train.py#L40) default Number of iterations  is `30`
Documentation

Train model command n_iteration 20 -> 30

---

.github/contributors/btrungchi.md
spacy/tokenizer.pyx

Fix loading tokenizer with custom prefix search.
This is a bug fix.

Fix loading tokenizer with custom prefix search

---

spacy/lang/ja/__init__.py
spacy/tests/conftest.py
spacy/tests/lang/ja/test_lemma.py

Japanese lemmas now work correctly. 
ja("新しく")[0].lemma_ # "新しい"
ja("なった")[0].lemma_ # "成る"
Includes tests.
I suppose this counts as a bug fix? Prior to this `.lemma_` would just be the string representation of the token.

Add Japanese lemmas

---

spacy/lang/ja/stop_words.py

List created by taking the 2000 top words from a Wikipedia dump and
removing everything that wasn't hiragana.
This is an enhancement, previously there were no Japanese stop words.

Add Japanese stop words

---

website/universe/universe.json

Hi @ines and @honnibal,
Continuing the https://github.com/explosion/spaCy/pull/2572
Updated:
- Import config from JSON/YML/XLSX/etc, keen to do the Prodigy integration if you provide me some dataset example.
- Training with PDF, DOCX, PNG as sources
- Better training phases and well defined data definition
Next, I will do some blogging on this. :)
Change to documentation

Universe update - ExcelCy

---

.github/contributors/sammous.md
website/universe/universe.json

Updating the description and the code snippet for the custom pipeline package *spacy-lefff*.
Website

Updating description and code snippet spacy-lefff

---

spacy/cli/download.py

I just noticed what looked like an extra `)` when going through the CLI and thought to fix it. That said, if this was intentional then please let me know.

Remove ')' for clarity

---

.github/contributors/mbkupfer.md

added contributor agreement for mbkupfer

---

.github/contributors/tyburam.md
spacy/lang/pl/lex_attrs.py

This PR is first step into better support for polish language. It is just a polish version of lex_attrs.py based on english one and signed contribution agreement. 
Enhancement

Lex _attrs for polish language

---

.github/contributors/filipecaixeta.md
spacy/lang/pt/lex_attrs.py

Add words that were missing in _num_words for portuguese

Add words to portuguese language _num_words

---

website/usage/_visualizers/_jupyter.jade

Fix minor typo in doc
Documentation fix

Add jupyter=True to displacy.render in documentation

---

spacy/lang/si/examples.py

Adding the Sinhala translation for "This is a sentence" as an example.
New example sentence

Adding "This is a sentence" example to Sinhala

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/05_other.md
.github/contributors/BramVanroy.md
CONTRIBUTING.md
README.rst
website/_harp.json
website/usage/_spacy-101/_community-faq.jade
website/usage/examples.jade

Some documentation improvements
1. Fixed the dead URL to joblib
2. Fixed Stack Overflow brand name (with space)
Documentation

Documentation improvement regarding joblib and SO

---

spacy/lang/th/__init__.py

Change PyThaiNLP Url from https://github.com/wannaphongcom/pythainlp/ to https://github.com/PyThaiNLP/pythainlp

Change PyThaiNLP Url

---

.github/contributors/frascuchon.md
website/universe/universe.json

Include universe spec for spacy-wordnet component
Universe spec for spacy-wordnet pipeline component
An universe component proposal

Include universe spec for spacy-wordnet component

---

spacy/lang/fr/lemmatizer/lemmatizer.py

On the previous PR ([#2818](https://github.com/explosion/spaCy/pull/2818)), I forgot to add the code to check if the word is in the regular lists of words for each part of speech. That leads to lemmas taken from the lookup table while the word is already in its lemma form. Consequently, bad results were occurring.
Bug fix/enhancement

Check if the word is in one of the regular lists specific to each POS for French Language

---

.github/contributors/svlandeg.md
spacy/lang/fr/tokenizer_exceptions.py
spacy/tests/lang/fr/test_exceptions.py

- corrected typo in regexp for French which was not working properly
- expanded unit test for French which was already testing similar regexps
- small bug/typo fix

Fix small typo bug in French regexp + relevant unit test

---

.github/contributors/gavrieltal.md
examples/training/train_textcat.py

Fixes #2942 
quick value initialization fix
- [x ] I ran the tests, and all new and existing tests passed.

Initialize trues to 0.0 in training example

---

website/usage/_models/_languages.jade

This addresses #3001. 
This just adds a note, with link, to the documentation. 
This is a documentation fix.

Add note that Unidic is required for Japanese

---

spacy/tokens/token.pyx

Simple docstring update.
Changed "left" to "right".
Documentation.

Fix docstring for is_right_punct().

---

.github/contributors/ozcankasal.md
spacy/lang/tr/lex_attrs.py

Turkish name for trillion is added.

trilyon forgotten

---

.github/contributors/willprice.md
spacy/displacy/render.py

See issue #2924 for details of issue that this PR improves the fix of https://github.com/explosion/spaCy/commit/02fc73ca53effae501c97879e1e95dc156d24f0d (#2927)
As per issue #2924, I have updated the random prefix generation to be more unique by using a UUID. IDs are now similar in form to `<type>-7135b3c80f544f30b060362966d60704-0-1`. Tested locally.

Improve random prefix generation in displaCy arcs

---

.github/contributors/jarib.md
spacy/lang/nb/tag_map.py

Add three tags from the UD/NORNE dataset that was missing in the `nb` tag map. Relates to #3082.
Bug fix.

Add three missing tags from the `nb` tag map

---

spacy/lang/ru/lemmatizer.py
spacy/tests/lang/ru/test_lemmatizer.py

See #3079. Here I'm merging into `develop` instead of `master`.
Bug fix.

Enabling `tests/lang/ru/test_lemmatizer.py`, fixing a `unicode` issue

---

.github/contributors/retnuh.md
examples/training/train_textcat.py

- Update the call to `output_dir.mkdir()` to also create the parents if needed
Very minor enhancement to hopefully save someone else the pain of half an hour training only to have it bomb out when saving :(

Update call to `mkdir()` to create the parents

---

spacy/tokens/printers.py

Fix issue #3150 - Doc.print_tree(flat=True) broken

---

website/universe/universe.json

Because the original code of spaCy2CoNLLU [does not provide the correct CoNLL format](https://github.com/rgalhama/spaCy2CoNLLU/issues/3), and because the maintainer of that code does not respond to issues, I have forked the original code and fixed and improved it. This PR reflects those changes.
Documentation

Updated spacy_conll information

---

examples/information_extraction/phrase_matcher.py

Updated main to make use of language variable when initializing spacy.

Updated main to make use of lang variable

---

.github/contributors/amperinet.md
spacy/lang/fr/lemmatizer/lemmatizer.py

Similar error as corrected in #3180 ; a tuple is returned instead of a string. 
We had this error with the phrase "Les moyens définis". 
bug fix

add small fix for French lemmatizer

---

contributer_agreement.md
examples/training/training-data.json

I have changed the type of the `id` from a string to an int. According to the [json input spec ](https://spacy.io/api/annotation#json-input) the `id ` needs to be an `int` not a string. Using a string as `id` results in a `TypeError` when calling `spacy.gold.read_json_file()`.
change to the documentation.

Update Example input JSON file to adhere to specification.

---

spacy/lang/sv/__init__.py
spacy/lang/sv/tag_map.py

Added tag map to map for UD Swedish Talbanken.
Enhancement to Swedish Language

Fixed tag map for Swedish Talbanken

---

website/universe/universe.json

Added spacy-langdetect plugin to universe.json

added spacy-langdetect to universe.json

---

.github/contributors/roshni-b.md
spacy/lang/bn/examples.py
spacy/lang/bn/morph_rules.py

- submitted my contributor's agreement,
- added example sentences in Bengali,
- added pronouns in Bengali,
- added grammatical nuances

updates for Bengali language

---

examples/training/train_tagger.py

- Json fix in comment

---

.github/contributors/danielkingai2.md
spacy/lexeme.pyx
spacy/tokens/doc.pyx
spacy/tokens/span.pyx
spacy/tokens/token.pyx

Replace calls to `numpy.dot` (and one call to `numpy.zeros`) to work on GPU
Fixes #3348 
Bug fix

Don't use numpy directly for similarity

---

spacy/lexeme.pyx
spacy/syntax/arc_eager.pyx
spacy/syntax/ner.pyx
spacy/tokens/doc.pyx
spacy/tokens/span.pyx
spacy/tokens/token.pyx
spacy/vocab.pyx

Use `@property` decorator if properties only have a getter and existing syntax if there's getter and setter.
enhancement

💫 Tidy up property syntax

---

spacy/cli/train.py
spacy/language.py
spacy/syntax/_beam_utils.pxd
spacy/syntax/_beam_utils.pyx
spacy/syntax/_parser_model.pyx
spacy/syntax/nn_parser.pyx

* Add flag in `spacy train` to evaluate the model at multiple beam-widths
* Make small tweaks to model to learn better mixed global/greedy models

Improve beam search support

---

README.md
website/docs/styleguide.md
website/gatsby-node.js
website/meta/site.json
website/src/components/search.js
website/src/templates/index.js

Various updates to make once v2.1 is up.
enhancement

💫 v2.1.0 launch updates (only merge on launch!)

---

spacy/tokens/doc.pyx
spacy/tokens/span.pyx
spacy/tokens/token.pyx

More fixes for `doc.similarity()` on GPU. Closes #3431

💫 Fix similarity calculation if vectors are on GPU

---

website/src/widgets/landing.js

>In 2015, independent researchers from Emory University and Yahoo! Labs showed that spaCy offered **thefastest** syntactic parser in the world
should be
>In 2015, independent researchers from Emory University and Yahoo! Labs showed that spaCy offered **the fastest**  syntactic parser in the world

Add missing space in website's landing page

---

examples/training/train_textcat.py
spacy/syntax/nn_parser.pyx
spacy/tests/parser/test_add_label.py

v2.1 introduced a regression when deserializing the parser after
parser.add_label() had been called. The code around the class mapping is
pretty confusing currently, as it was written to accommodate backwards
model compatibility. It needs to be revised when the models are next
retrained.

💫 Fix class mismap on parser deserializing (closes #3433)

---

.github/contributors/wannaphongcom.md
spacy/lang/th/tag_map.py

Update Thai tag map
Update Thai tag map. Add VERB.
enhancement

Update Thai tag map

---

spacy/tokenizer.pyx
website/docs/api/tokenizer.md

Include the default value of 1000 in `spacy.Tokenizer` docs [here](https://github.com/explosion/spaCy/blob/master/spacy/tokenizer.pyx) and [here](https://github.com/explosion/spaCy/blob/master/website/docs/api/tokenizer.md)

DOC: Include default value for batch_size in tokenizer pipe in docs

---

.github/contributors/graus.md
website/meta/universe.json

Adds textpipe to spaCy's universe

adds textpipe to universe

---

.github/contributors/ivigamberdiev.md
README.md

Just update links in main README
Enhancement

Update links and http -> https

---

website/docs/api/cli.md

Fixes a typo in [this](https://github.com/explosion/spaCy/blob/master/website/docs/api/cli.md) doc which may benefit users still using SpaCy v2.0.18 or lower.

Fix typo in the web documentation of cli.md

---

.github/contributors/celikomer.md

Signed agreement

---

website/docs/usage/visualizers.md

although the text indicates the entity types should be in lowercase, the sample code shows uppercase, which is the correct format.

entity types for colors should be in uppercase

---

.github/contributors/bjascob.md
website/meta/universe.json

Update the website to include the "pyInflect" spaCy extension information.  Specifically the page for https://spacy.io/universe is altered.  
Issue#3171 is the request to add inflection capability through a spaCy extension.  PyInflect is a separate project and all code and details can be found at https://github.com/bjascob/pyInflect.  This closes #3171.
**1 - There are no code changes with this PR.  I manually verified the changes to the universe.json file by running the webserver locally and visually checking the modified page.

Update Universe Website for pyInflect

---

website/docs/usage/rule-based-matching.md

Make documentation code more pythonic.
Documentation

Improve redundant variable name

---

website/docs/usage/spacy-101.md

I assume this is a typo. Sorry if it has a meaning that I'm not aware of.

Remove dangling M

---

.github/contributors/henry860916.md
website/docs/usage/processing-pipelines.md

component:print_info is appened in the last, so need show it at the end of  pipeline
Types of change
- [X ] I have submitted the spaCy Contributor Agreement.
- [ X] I ran the tests, and all new and existing tests passed.
- [] My changes don't require a change to the documentation, or if they do, I've added all required information.

update response after calling add_pipe

---

.github/contributors/F0rge1cE.md
spacy/cli/init_model.py

Resolve https://github.com/explosion/spaCy/issues/3667 . Fix bug in loading new pre-trained word2vec.
Bug fix.
- [x ] I ran the tests, and all new and existing tests passed.

Fix offset bug in loading pre-trained word2vec.

---

spacy/lang/th/__init__.py

fix word tokenize for PyThaiNLP 2.0+
Update api for PyThaiNLP 2.0+
bug fix

fix ThaiTokenizer bug

---

.github/contributors/aaronkub.md
website/docs/usage/rule-based-matching.md

Small change to the rule-based-matching documentation to resolve #3708.

Fixing Regex Matcher Examples (#3708)

---

website/meta/universe.json

Added following packages: NLPArchitect, NLPRe, Chatterbot, alibi, NeuroNER

Add multiple packages to universe.json (#3809) [ci skip]

---

spacy/cli/pretrain.py

Corrected type of seed parameter.
Changed type of seed parameter for cli `pretrain` from `float` to `int`
Bug fix

Fix for #3811

---

website/docs/usage/processing-pipelines.md

Minor fix to broken link in documentation
Fix broken link in website documentation

Minor fix to broken link in documentation

---

.github/contributors/demongolem.md
website/docs/api/tokenizer.md

Self contained example.  You should really say what nlp is so that the example will work as is

Update tokenizer.md for construction example

---

.github/contributors/askhogan.md
examples/information_extraction/entity_relations.py

Update example and sign contributor agreement

---

.github/contributors/ameyuuno.md

@ines hi! 
I asked to change my username (yuukos -> ameyuuno). So I added a new contributor agreement.

added contributor agreement ameyuuno.md

---

.github/contributors/yashpatadia.md
spacy/lang/char_classes.py
spacy/tests/regression/test_issue3625.py

- Fix default punctuation rules for Hindi text
- Add Hindi Unicode character range to the character class
Please see issue #3625 for more details.
- Bug fix

Fix default punctuation rules for splitting Hindi text

---

bin/train_word_vectors.py
spacy/tests/regression/test_issue3869.py
spacy/tokens/doc.pxd
spacy/tokens/doc.pyx

Using Python's `Counter` instead of `PreshCounter` fixes a bug described in Issue https://github.com/explosion/spaCy/issues/3869.
Added a unit test to check this behaviour.
bug fix

Fix doc.count_by functionality

---

website/docs/api/entityruler.md

Fixed example for creating a new EntityRuler in API docs.

Fix initial example in EntityRuler API docs

---

spacy/lang/nb/__init__.py

Norwegian used to borrow from French but that doesn't appear to have
been true for a while now, so the comment that was here is no longer
relevant.
comment fix

Remove old comment about using French parser in Norwegian

---

website/docs/api/goldparse.md

The example showed an incorrected import
Only on the documentation, the example showed an incorrect import

Corrected imported function

---

spacy/cli/init_model.py

Fix init_model if there's no vocab (closes #4048)

---

spacy/pipeline/entityruler.py
spacy/tests/pipeline/test_entity_ruler.py
website/docs/api/entityruler.md
website/docs/usage/rule-based-matching.md

* Add validate option to EntityRuler
* Add validate to usage and API docs
Bug fix for #4069

Add validate option to EntityRuler

---

.github/contributors/ICLRandD.md
website/meta/universe.json

Add an entry for the Blackstone project on the spaCy universe page. Checked JSON is valid.
Changes to `universe.json`
- [x ] I ran the tests, and all new and existing tests passed.
This spaCy Contributor Agreement (**"SCA"**) is based on the
[Oracle Contributor Agreement](http://www.oracle.com/technetwork/oca-405177.pdf).
The SCA applies to any contribution that you make to any product or project
managed by us (the **"project"**), and sets out the intellectual property rights
you grant to us in the contributed materials. The term **"us"** shall mean
[ExplosionAI GmbH](https://explosion.ai/legal). The term
**"you"** …

Add entry for Blackstone in universe.json

---

.github/contributors/ryanzhe.md
spacy/gold.pyx
spacy/tests/test_gold.py

#4020 
biluo_tags_from_offsets used to return a malformed biluo tag sequence even if the passed in entites parameters have overlaps.
- biluo_tags_from_offsets now checks whether passed in entities have overlaps and throw E107 if they do
- also added unit tests for the exception

biluo_tags_from_offsets throw exception for overlapping entities

---

.github/contributors/yanaiela.md
spacy/displacy/render.py

This PR is in response to the proposal suggested at #3850.
Now one can supply a custom html template for the entities displayer, along with custom arguments to have more control on the display.
This is a new feature for displacy, specifically for the entities renderer.
Still not sure about this, so after the feature logic will be approved, will change also documentation

Custom entity render

---

.github/contributors/isaric.md
spacy/lang/hr/examples.py

I am submitting the spaCy contributor agreement for myself and adding examples.py for Croatian language.
Two files are added - isaric.md - the contributor agreement, and examples.py for Croatian
language
This is an enhancement - please see issue #1107

Issue #1107 - adds examples.py for Croatian language

---

website/docs/api/entityruler.md

/api/phtasematcher -> /api/phrasematcher

fix PhraseMatcher link typo in docs

---

.github/contributors/avramandrei.md
website/meta/universe.json

This module offers a named entity recognition model for Romanian Language. The model has been
trained on a  corpus that holds 5127 sentences, annotated with 16 classes. More information about the corpus can be found at https://github.com/dumitrescustefan/ronec/blob/master/README.md.
We used a script to transform the corpus from CoNLLU-Plus format to spaCy's json. The training has been done using the cli.
We would like to integrate this model with spaCy download interface and easily load with with `spacy.load("ro_ner")`, as described in the sample code.
We have seen [here](https://github.com/explosion/spaCy/issues/2935) that the models must be trained by you. The pipeline of training can be found at https://github.com/dumitrescustefan/ronec/blob/master/spacy/README.md.

Added RONEC to spaCy Universe

---

spacy/tests/regression/test_issue3879.py

Failing unit test for Issue #3879

Unit test for Issue 3879

---

spacy/matcher/matcher.pyx
spacy/tests/regression/test_issue3879.py
spacy/tests/regression/test_issue3951.py

Bugfix in matcher that addresses issues #3879 and #3951 (but not yet #4120)
bug fix

fix retry loop in matcher

---

website/docs/api/pipeline-functions.md

DOC Fix pipeline functions examples

---

setup.py

Add Thai Language tokenizers (pythainlp)
Add Thai Language tokenizers
enhancement

Add Thai Language tokenizers

---

website/meta/universe.json

the numeric fused-head universe project description

new universe project - the numeric fused-head

---

README.md
spacy/gold.pyx
spacy/lang/de/__init__.py
spacy/lang/en/__init__.py
spacy/language.py
website/docs/api/top-level.md
website/meta/languages.json
website/meta/universe.json

Filtering by orth and tag, create variants of training docs with alternate orth variants, e.g., unicode quotes, dashes, and ellipses.
The variants can be single tokens (dashes) or paired tokens (quotes) with left and right versions.
Enhancement.

Add train_docs() option to add orth variants

---

spacy/matcher/_schemas.py
spacy/tests/matcher/test_matcher_api.py

Add token attributes with tests to token pattern schema.
Fixes #4165.
Bugfix.

Add more token attributes to token pattern schema

---

bin/ud/ud_run_test.py
bin/ud/ud_train.py
examples/training/conllu.py
examples/training/pretrain_textcat.py
examples/vectors_tensorboard.py
spacy/cli/init_model.py
spacy/cli/profile.py
spacy/cli/train.py

This is an ugly, temporary fix to avoid a Windows bug with Jupyter notebooks when importing `tqdm`, cf Issue #4200 
I will monitor the original issue https://github.com/tqdm/tqdm/issues/678 and revert these changes when the underlying issue is fixed.
"external bug workaround"

pulling tqdm imports in functions to avoid bug

---

spacy/lang/uk/__init__.py

Allow Ukrainian create_lemmatizer to accept lookups kwarg.
Bugfix.

Update Ukrainian create_lemmatizer kwargs

---

website/meta/universe.json

Update code example for neuralcoref + caveat for spaCy > 2.1.0
documentation fix

update neuralcoref example

---

website/meta/universe.json

update sense2vec version

---

website/meta/universe.json

typo fix for wordnet_annotator

---

.github/CONTRIBUTOR_AGREEMENT.md
.github/contributors/jaydeepborkar.md
spacy/lang/hi/stop_words.py

I've added more stop words in Hindi in stop_words.py file, have linked up the resource to the same at the beginning. And as well have added my name in the contributors!

Update stop_words.py and add name in contributors

---

.github/contributors/EARL_GREYT.md
examples/training/training-data.json

The head of 'in' is review which has an offset of 4 and not 44

fix typo in first token

---

spacy/language.py

The function to format `docs` and `golds` in `Language.update` method has been separated into another function.
I did this for the following reasons:
1. Code refactor
1. To make it easier to reuse the format part, when create custom Language.
refactor

Refactor language update

---

spacy/matcher/phrasematcher.pyx

Fix PhraseMatcher to remember attr on pickling.
Bugfix.

Fix PhraseMatcher to remember attr on pickling

---

spacy/tests/test_misc.py

Background: https://twitter.com/_inesmontani/status/1177941471632211968
This test checks all files in the package directory and asserts that their file names only consist of ASCII characters.
tests

Add test for ASCII filenames

---

spacy/lang/uk/__init__.py
spacy/lang/uk/lemmatizer.py

Update Ukrainian lemmatizer with new lookups (copied from Russian)
Bugfix.

Update Ukrainian lemmatizer with new lookups

---

examples/streamlit_spacy.py

Make the default NER labels less model-specific
Bugfix.

Make the default NER labels less model-specific [ci skip]

---

.github/contributors/bintay.md
spacy/tests/vocab_vectors/test_vectors.py
spacy/vectors.pyx
spacy/vocab.pyx

Modified the `most_similar` method of `Vectors` so that it returns the top `n` most similar vectors rather than the single most similar vector.
The new value returned looks like `(keys, best_rows, scores)` where `keys`, `best_rows`, and `scores`  are arrays containing an array for each query. So `scores[0]` would be an array of scores corresponding to the `n` vectors most similar to the `0`th query.
In theory, performance should not be impacted much — `argmax` is replaced by `argpartition`, both of which run in linear time with respect to the number of elements. If the user chooses to sort the `n` most similar entries by setting the `sort` parameter to true, it will add an `O(n lg n)` step to sort the entries. However, I haven't tested the performance in practice yet and I might be …

most_similar() return the k most similar vectors

---

spacy/vectors.pyx

Consider batch_size when sorting similar vectors
This is my best guess at a fix and needs to be reviewed by someone who's more familiar with this part of the code.
Fixes #4386.
Bugfix.

Consider batch_size when sorting similar vectors

---

spacy/matcher/matcher.pyx

This is basically stabbing blindly at the ghost match problem, but it at
least seems like there was a bug previously here --- so this should
hopefully be an improvement, even if it doesn't fix the ghost match
problem.

Unify matcher get_ent_id and get_pattern_key

---

spacy/matcher/matcher.pyx
spacy/tests/matcher/test_pattern_validation.py

Allow int values in token patterns
* Add missing int value option to top-level pattern validation in Matcher
* Adjust existing tests accordingly
* Add new test for valid pattern `{"LENGTH": int}`
Fixes #4442 .
Bugfix.

Allow int values in token patterns

---

spacy/tests/vocab_vectors/test_vectors.py
spacy/vectors.pyx

Fixes #4443
In https://github.com/explosion/spaCy/blob/2d249a9502bfc5d3d2111165672d964b1eebe35e/spacy/vectors.pyx#L340, the first element of the tuple needs to have the correct shape relative to the batch size, so should be replaced by `sorted_index = xp.arange(scores.shape[0])[:,None][i:i+batch_size],xp.argsort(scores[i:i+batch_size], axis=1)[:,::-1]`. Also there is no need to run the sorting code if only one most similar vector is requested.
Bug fix

Most similar bug

---

website/docs/api/lemmatizer.md

Removing extra o in the lookups = Loookups()

Misspelling on Lemmatizer Example #4406

---

spacy/cli/debug_data.py

Check for docs with 2+ sentences in debug-data.
The suggested threshold here is more of a guess than anything.
Enhancement.

Check for docs with 2+ sentences in debug-data

---

spacy/cli/convert.py
spacy/cli/converters/conll_ner2json.py
spacy/cli/converters/iob2json.py

Suppress convert output if writing to stdout.
Fixes #4470.
Bugfix.

Suppress convert output if writing to stdout

---

website/docs/usage/linguistic-features.md

Add Entity Linking to menu on website

Add Entity Linking to menu on website

---

spacy/cli/debug_data.py
spacy/errors.py
spacy/gold.pyx
spacy/tests/test_gold.py

Check for empty label in iob_to_biluo(), which can result from ill-formed input.
Check for empty NER label in debug-data.
Addresses #4385.

Checks/errors related to ill-formed IOB input in CLI convert and debug-data

---

website/meta/universe.json

Rasa has been updated and rasa core and rasa nlu have been merged.
Change website link
Change image link
Change pip package link
Change description
Update universe.json file.

Update information about Rasa

---

spacy/gold.pyx

Remove unused variable in iob_to_biluo.

refactor: remove unused variable

---

website/meta/universe.json

Adding cookiecutter-spacy-fastapi to universe
Adding cookiecutter-spacy-fastapi to universe
Documentation change to universe

Add cookiecutter-spacy-fastapi to spacy universe

---

spacy/tests/vocab_vectors/test_vectors.py
spacy/vectors.pyx

Clip most_similar to range [-1, 1] (fixes #4506)

---

website/docs/usage/rule-based-matching.md

Fixes #4475. 
Documentation bugfix.

Fix logic in rules+model entity example

---

spacy/gold.pyx
spacy/tests/regression/test_issue4529.py

[#4529] fix: gold pyx

---

spacy/syntax/_parser_model.pyx

The previous version worked with previous thinc, but only
because some thinc ops happened to have gpu/cpu compatible
implementations. It's better to call the right Ops instance.

Fix GPU training for Thinc 7.2+

---

spacy/pipeline/functions.py
spacy/tests/pipeline/test_functions.py

The `Matcher` in `merge_subtokens()` returns all possible subsequences of `subtok`, so for sequences of two or more subtoks it's necessary to filter the matches so that the retokenizer is only merging the longest matches with no overlapping spans.
Bugfix.

Filter subtoken matches in merge_subtokens()

---

spacy/ml/tok2vec.py

The model registry refactor of the Tok2Vec function broke loading models
trained with the previous function, because the model tree was slightly
different. Specifically, the new function wrote:
concatenate(norm, prefix, suffix, shape)
To build the embedding layer. In the previous implementation, I had used
the operator overloading shortcut:
( norm | prefix | suffix | shape )
This actually gets mapped to a binary association, giving something
like:
concatenate(norm, concatenate(prefix, concatenate(suffix, shape)))
This is a different tree, so the layers iterate differently and we
loaded the weights wrongly.

Fix tok2vec structure after model registry refactor

---

bin/ud/ud_run_test.py
bin/ud/ud_train.py
spacy/util.py

Setting the encodings when opening files specifically to UTF-8 in case that's not the default (as on Windows).
bug fix

UTF-8 encodings

---

.github/contributors/neelkamath.md
website/meta/universe.json

**Rationale behind making a new project**
I _really_ wanted to use one of the existing two HTTP APIs for spaCy, but they didn't fit my needs due to poor documentation and lacking infrastructure. I had thought for several days about patching the original repositories or forking them, but they had serious issues such as security and poor routing (e.g., used an HTTP GET request for large text which may not fit in the URL instead of an HTTP POST request where the request body can have arbitrarily large amounts of text which doesn't require percent encoding) which made it faster and more sustainable to make my own solution.
Added a project to the spaCy Universe JSON file

Add "spaCy Server" to spaCy Universe

---

spacy/language.py
spacy/tests/pipeline/test_analysis.py

Validate *after* component is removed, not before.
bug fix

Fix pipeline analysis on remove pipe

---

spacy/scorer.py
spacy/tests/test_scorer.py

Add LAS per dependency to Scorer
Enhancement.

Add LAS per dependency to Scorer

---

website/meta/universe.json

Adding Dframcy (spacy dataframe plugin) to spacy universe.
Adding Dframcy to spaCy universe.
Documentation change to universe.

Add dframcy to spacy universe

---

website/docs/usage/101/_named-entities.md

I fixed a typo in the documentation.
Docs

Fixed typo: Added space between "recognize" and "various"

---

website/docs/api/docbin.md

Fix DocBin.merge() example
Docs.

Fix DocBin.merge() example

---

spacy/lang/es/examples.py
spacy/lang/nb/examples.py
spacy/lang/xx/examples.py

* Add sentence-final punctuation to `es` and `nb`
* Concatenate all relevant language examples for `xx`
(This will be needed for some new `spacy-models` tests.)
Enhancement.

Minor updates to language example sentences

---

spacy/lang/zh/__init__.py
spacy/lang/zh/tag_map.py
spacy/tests/conftest.py
spacy/tests/lang/zh/test_text.py
spacy/tests/lang/zh/test_tokenizer.py

Rework Chinese language initialization and tokenization:
* Create a `ChineseTokenizer` class
* Modify jieba post-processing to handle whitespace correctly
* Modify non-jieba character tokenization to handle whitespace correctly
* Add a `create_tokenizer()` method to `ChineseDefaults`
* Load lexical attributes
* Update Chinese tag_map for UD v2
* Add basic tests
* Test tokenization with and without jieba
* Test `like_num` attribute
Enhancement, mostly.

Rework Chinese language initialization and tokenization

---

website/docs/api/sentencizer.md

Fix an assert in sentencizer documentation.

Fix assert in sentencizer documentation

---

spacy/cli/debug_data.py

Update check for at least one evaluation document for `GoldCorpus` / `Example` updates and ignore misaligned `None` label in NER checks.
Bugfix.

Fix minor issues in debug-data

---

spacy/gold.pyx

Initialize all values in `a2b` and `b2a` since `numpy.empty()` otherwise results in unspecified integers (and the previous version only initialized values up to the minimum length of `a` and `b`).
Bugfix.

Fix initialization of token mappings in new align

---

website/docs/usage/linguistic-features.md

Update pseudo-code and algorithm description to correspond to current tokenizer behavior.
Add more examples for customizing tokenizers while preserving the existing defaults.
Minor edits / clarifications.
Fixes #4573, fixes #4645.
Documentation.

Update tokenization usage docs

---

.github/contributors/erip.md
spacy/lang/char_classes.py
spacy/lang/ko/lex_attrs.py

This PR introduces initial Korean language-specific support.
A new feature.

Add initial Korean support

---

website/meta/universe.json

Hi there, I released Holmes v2.1.0 yesterday and would like to update the Universe entry. Thanks and best wishes from Munich, Richard

Update to Holmes Universe entry

---

spacy/errors.py
spacy/pipeline/pipes.pyx
spacy/tests/pipeline/test_tagger.py
spacy/tests/pipeline/test_textcat.py

Add error when attempting to add non-string labels to `Tagger` or `TextCategorizer`.
Fixes #4654.
Enhancement.

Add error for non-string labels

---

spacy/cli/converters/conllu2json.py

Fix conllu2json converter to output all sentences
Make sure that the last batch of sentences is output if n_sents > 1.
Bugfix.

Fix conllu2json converter to output all sentences

---

spacy/cli/converters/conllu2json.py
spacy/tests/test_cli.py

Update converter to handle various things in MISC column:
* `SpaceAfter=No` and set raw text accordingly
* plain NER tag
* name=NER (for NorNE)
Enhancement.

Update conllu2json MISC column handling

---

spacy/pipeline/pipes.pyx
spacy/tests/pipeline/test_sentencizer.py

Restructure Sentencizer to follow Pipe API so that it can be scored with `nlp.evaluate()`.
Enhancement.

Restructure Sentencizer to follow Pipe API

---

spacy/cli/evaluate.py
spacy/cli/train.py
spacy/gold.pxd
spacy/gold.pyx
spacy/pipeline/__init__.py
spacy/pipeline/pipes.pyx
spacy/scorer.py
spacy/tests/serialize/test_serialize_pipeline.py

Add a tagger-based `SentenceRecognizer` component that segments sentences by tagging tokens with two tags: beginning of a sentence or not.
* Add `sent_starts` to `GoldParse`
* Add sentence segmentation evaluation to `Scorer` (also works for the parser and other components)
* Add the same evaluation to CLI evaluate
* Add metrics/scoring to train CLI
Evaluating on English OntoNotes, this component has higher precision and lower recall than the parser, but with these model settings the f-score is only 0.5% less than the parser and it's ~10x faster. It could be 10-20% faster and ~1% worse with even more minimal model settings. With these settings it's 275K on disk.
| Model | P | R | F | Words/Sec |
|---|---|---|---|---|
| en_core_web_sm parser | 93.86 | 95.10 | 94.48 | 5656 |
| senttagger | …

Add a tagger-based SentenceRecognizer

---

spacy/gold.pxd
spacy/gold.pyx
spacy/tests/test_gold.py

Add lemmas to GoldParse / Example / docs_to_json
Enhancement.

Add lemmas to GoldParse / Example / docs_to_json

---

spacy/cli/converters/conllu2json.py

Update conllu2json converter to include raw text in final batch.
(The changes got out of sync across a few PRs.)
Bugfix.

Fix conllu2json n_sents and raw text

---

spacy/tests/serialize/test_serialize_doc.py
spacy/tokens/_serialize.py
spacy/tokens/doc.pyx

* Include `Doc.cats` in `Doc` serialization
* Include `Doc.cats` in `DocBin` serialization
* Add tests for `Doc.cats` in `Doc` and `DocBin` serialization
Fixes #4770.
Bugfix.

Include Doc.cats in serialization of Doc and DocBin

---

examples/training/pretrain_kb.py
examples/training/train_entity_linker.py
spacy/errors.py
spacy/pipeline/pipes.pyx

The Entity Linking example scripts needed an update after a previous refactor. Also added a few more user-friendly errors.
Fixes #4723
bug fix & enhancement

Update EL example 

---

spacy/cli/debug_data.py
spacy/cli/train.py

Add `--tag-map-path` argument to CLI `debug-data` and `train`: Add an argument for a path to a JSON-formatted tag map, which is used to update and extend the default language tag map.
Enhancement. (Intentionally not added to docs yet.)

Add tag map argument to CLI debug-data and train

---

spacy/pipeline/pipes.pyx

NEL requires doc.sents

---

.github/contributors/AlJohri.md

sign contributor agreement for AlJohri (#4839) [ci skip]

---

website/docs/usage/rule-based-matching.md

remove extra word typo

---

spacy/lang/tokenizer_exceptions.py
spacy/tests/tokenizer/test_urls.py

* match domains longer than `hostname.domain.tld` like `www.foo.co.uk`
* expand allowed characters in domain names while only matching lowercase TLDs so that "this.That" isn't matched as a URL and can be split on the period as an infix (relevant for at least English, German, and Tatar)
Fixes #4862.
Bugfix and enhancement.

Fix and improve URL pattern

---

spacy/tests/lang/hu/test_tokenizer.py

Mark most Hungarian tokenizer test cases as slow to reduce the runtime of the test suite in ordinary usage:
* for normal tests: run default tests plus 10% of the detailed tests
* for slow tests: run all tests
Enhancement.

Mark most Hungarian tokenizer test cases as slow

---

website/docs/usage/vectors-similarity.md

These links are broken on the website, due to quotes around the URLs.

Update vectors-similarity.md to fix broken URLs

---

spacy/lang/char_classes.py
spacy/tests/tokenizer/test_urls.py

* Add CJK character class as uncased
* Incorporate Chinese URL test case
Enhancement.

Add CJK to character classes

---

spacy/language.py

Add sentrec shortcut to `Language`. (I still think it needs to be renamed.)
Enhancement.

Add sentrec shortcut to Language

---

spacy/cli/debug_data.py

Report length of dev dataset correctly
Bugfix.

Report length of dev dataset correctly

---

spacy/cli/train.py

* reorder to metrics to prioritize F over P/R
* add sentrec to model metrics
Bugfix mostly.

Improve train CLI sentrec scoring

---

spacy/syntax/nn_parser.pyx

bugfix typo conv_window

---

website/meta/universe.json

Updates the information about the `spacy_conll` package in spaCy universe.
Documentation change in the Universe.

Changes to spacy_conll in universe

---

spacy/cli/train.py

Improve train CLI with a provided base model so that you can:
* add a new component
* extend an existing component
* replace an existing component
When the final model and best model are saved, disabled components are reenabled and the meta information is merged to include the full pipeline and accuracy information for all components in the base model plus the newly added components if needed.
Fixes #4342.
Enhancement.

Improve train CLI with base model

---

spacy/pipeline/pipes.pyx
spacy/tests/pipeline/test_sentencizer.py

Add `as_example` to `Sentencizer pipe()`.
Bug fix.

Add as_example to Sentencizer.pipe()

---

spacy/gold.pxd
spacy/gold.pyx
spacy/tests/test_gold.py

Add support for pos/morphs/lemmas throughout `GoldParse`, `Example`, and `docs_to_json()`.
Enhancement.

Add support for pos/morphs/lemmas in training data

---

spacy/pipeline/pipes.pyx
spacy/tests/pipeline/test_sentencizer.py

Fix Sentencizer.pipe() for empty doc
Fixes issue mentioned in #4935.
Bug fix.

Fix Sentencizer.pipe() for empty doc

---

.github/contributors/ceteri.md
website/meta/universe.json

Added a new entry for `PyTextRank` into `website/meta/universe.json` and verified the JSON format with a checker.
This is a proposed new entry for the spaCy uniVerse.
Many thanks. I hope the formatting, description, category, and tags fit for the directory.

Submitting `PyTextRank` for inclusion in the spaCy uniVerse

---

spacy/attrs.pxd
spacy/attrs.pyx
spacy/symbols.pxd
spacy/symbols.pyx
spacy/tests/doc/test_retokenize_merge.py
spacy/tests/doc/test_retokenize_split.py
spacy/tokens/_retokenize.pyx
spacy/tokens/token.pxd

Add MORPH attr / symbol for get/set in Token and add new morphs in retokenizer.
Enhancement.

Add MORPH attr, add support in retokenizer

---

website/meta/universe.json

Added a new reference in `universe.json` to Presidio Research, a toolbox for creating NER models for PII data detection
Link to repo: https://github.com/microsoft/presidio-research/

Added presidio-research to universe.json

---

.github/contributors/onlyanegg.md
spacy/cli/converters/conllu2json.py
spacy/tests/regression/test_issue4665.py

Allowing the HEAD field in CoNLL-U format to be an underscore
Added a check for underscores and added a regression test
Fixes #4665 
Bug Fix

Fix for Issue 4665 - conllu2json

---

requirements.txt
setup.cfg

Update lower pin for srsly to 1.0.1
Fixes #4975.
Bug fix.

Update lower pin for srsly to 1.0.1

---

spacy/util.py

Fixing new optimizer attribute names
bug fix

fix grad_clip naming

---

MANIFEST.in

add pyx and pxd files to the distribution

---

spacy/cli/train.py

Set the GPU before loading any existing models in the train CLI so that you can start with a base model and train on GPU.

Set GPU before loading any models in train CLI

---

spacy/cli/debug_data.py
spacy/cli/train.py

Backport: Add tag_map argument to CLI debug-data and train (#4750)
Add an argument for a path to a JSON-formatted tag map, which is used to
update and extend the default language tag map.
Enhancement.

Add tag_map argument to CLI debug-data and train

---

spacy/gold.pyx

Initialize all values in a2b/b2a in new align

Initialize all values in new align

---

spacy/tests/serialize/test_serialize_tokenizer.py
spacy/tokenizer.pyx

Preserve empty tokenizer properties by using language defaults for missing properties but loading empty properties as is.
Addresses problem mentioned in #4991.
Bugfix.

Restore empty tokenizer properties

---

spacy/matcher/_schemas.py
spacy/matcher/matcher.pyx
spacy/tests/matcher/test_pattern_validation.py

Support `IS_SENT_START` and `SENT_START` as `Matcher` attributes using `SENT_START` internally.
Fixes #5073.
Bug fix.

Normalize IS_SENT_START to SENT_START for Matcher

---

spacy/tokens/doc.pyx

Break out of infinite loop as intended, fixing bug originating in #4702.
Bug fix.

Break out of infinite loop when setting children from heads

---

spacy/cli/train.py

* include speed and accuracy from final iteration in initial version of `model-final/meta.json`
* combine with speeds from base model if necessary
* include `token_acc` metric for all components

Fix model-final/model-best meta from train CLI

---

requirements.txt
setup.cfg

Require srsly >=1.0.2
Bug fix?

Require srsly >=1.0.2

---

spacy/pipeline/pipes.pyx
spacy/tests/pipeline/test_entity_linker.py

* Add a unit test to ensure the NEL component works well (can overfit on a small example).
* Fixed a bug with respect to NEL IO: make sure `entity_width` is written in the `cfg`
bug fix

Unit test for NEL functionality

---

spacy/cli/train.py
spacy/language.py
spacy/ml/models/defaults/__init__.py
spacy/ml/models/defaults/senter_defaults.cfg
spacy/pipeline/pipes.pyx
spacy/tests/pipeline/test_senter.py
spacy/tests/serialize/test_serialize_pipeline.py

* rename `sentrec` to `senter`
* use `spacy.HashEmbedCNN.v1` by default
* update to follow `Tagger` modifications
* remove component methods that can be inherited from `Tagger`
* add simple initialization and overfitting pipeline tests
Enhancement

Update sentence recognizer

---

bin/wiki_entity_linking/README.md

Fix typo in bin/wiki_entity_linking/README.md

fix typo in bin/wiki_entity_linking/README.md

---

.github/contributors/mabraham.md
spacy/tokenizer.pyx

Fixes #5115
used util.ensure_path like other parts of the code
Bug fix

Tokenizer to_disk and from_disk now ensure paths

---

.github/contributors/merrcury.md
LICENSE

It fixes the LICENSE. This will keep the copyright to the original developers who have worked hard in 2020 as well. 

DOC : Update LICENSE Year

---

website/docs/usage/rule-based-matching.md

small typo in code sample

---

spacy/tests/util.py

Due to changes to `Span` (#5005), spans from different documents are now
never equal. Check `Token.is_sent_start` values instead.
Fixes #5144.
Bug fix.

Fix sents comparison in test util

---

website/docs/usage/saving-loading.md

link was broken, now it matches other links to that page
docs fix

Fix broken link in docs

---

.github/contributors/sloev.md
website/meta/universe.json

Add pipeline component [spacy_syllables](https://github.com/sloev/spacy-syllables) to universe list.
`spacy_syllables` adds multilingual syllable annotations to Tokens.
documentation change

add spacy_syllables to universe

---

azure-pipelines.yml

`macos-10.13` was discontinued on March 23, 2020, so update to `macos-10.14`.

Update from macOS-10.13 to macOS-10.14

---

.github/contributors/Baciccin.md
spacy/lang/lij/__init__.py
spacy/lang/lij/examples.py
spacy/lang/lij/punctuation.py
spacy/lang/lij/stop_words.py
spacy/lang/lij/tokenizer_exceptions.py
website/meta/languages.json

This PR adds basic support for the [Ligurian language](https://en.wikipedia.org/wiki/Ligurian_(Romance_language)).
* Adds my contributor agreement.
* Adds example sentences, punctuation, stop words and tokenizer exceptions.
* Updates `website/meta/languages.json` with the new language.
This PR adds support for a new language.

Add Ligurian language

---

spacy/lang/de/punctuation.py

Minor improvements German tokenizer settings style
Code style.

Improve German tokenizer settings style

---

spacy/lang/fr/__init__.py
spacy/lang/fr/punctuation.py
spacy/lang/fr/tokenizer_exceptions.py

Improve French tokenization for UD_French-Sequoia.
Enhancement.

Improve French tokenization

---

spacy/lang/pt/tokenizer_exceptions.py

Modifications to Portuguese tokenization for UD_Portuguese-Bosque.
Instead of splitting contactions as exceptions, they are kept as merged
tokens.
Enhancement.

Modifications/updates to Portuguese tokenization

---

spacy/lang/it/__init__.py
spacy/lang/it/punctuation.py
spacy/lang/it/tokenizer_exceptions.py

Improve Italian tokenization for UD_Italian-ISDT.
Enhancement.

Improve Italian tokenization

---

spacy/lang/ro/__init__.py
spacy/lang/ro/punctuation.py
spacy/lang/ro/tokenizer_exceptions.py

Modifications to Romanian tokenization to improve tokenization for
UD_Romanian-RRT.
Enhancement.

Improved Romanian tokenization for UD RRT

---

spacy/vectors.pyx
website/docs/api/vectors.md
website/docs/usage/vectors-similarity.md

Remove `Vectors.from_glove`. It doesn't do what a user might expect (load vectors from a binary format produced by glove) and isn't used anywhere internally, either. Instead, a user should use `spacy init-model` to load vectors from the text word2vec/glove format.
Closes #5086.

Remove Vectors.from_glove

---

spacy/scorer.py

Fix the `GoldParse` initialization when the number of tokens has changed (due to merging subtokens with the parser).

Fix GoldParse init in Scorer when token count differs

---

.github/contributors/Tiljander.md
website/docs/api/entityruler.md
website/docs/usage/rule-based-matching.md

Describing priority rules for overlapping matches in API and usage section.

Describing priority rules for overlapping matches

---

spacy/_ml.py

Pass the `exclusive_classes` setting to the bow model within the ensemble textcat model.
Bugfix.

Fix exclusive_classes in textcat ensemble

---

spacy/gold.pyx
spacy/tests/regression/test_issue4924.py
spacy/tests/test_gold.py

When creating docs to pair with gold parses, modify test to check whether a doc is unset rather than whether it contains tokens.

Check whether doc is instantiated in Example.get_gold_parses()

---

spacy/errors.py
spacy/vectors.pyx

Raise an error if there is an attempt to resize the vectors in place with
a different vector dimension.
Bug fix.

Raise error for inplace resize with new vector dim

---

.github/contributors/leicmi.md
spacy/lemmatizer.py

This will remove a duplicated if/else-if branch.
Refactor/Quickfix

Remove duplicated branch in if/else-if statement

---

bin/wiki_entity_linking/wikipedia_processor.py

Small fix in NEL script, fixes #5131 
Avoid enumerate and read training file line by line. This should avoid long waiting at 0% in the beginning of processing a huge training file.
enhancement

avoid enumerate to avoid long waiting at 0%

---

website/docs/usage/linguistic-features.md
website/meta/universe.json

Two small fixes in the documentation
closes #5245
doc fix

Small doc fixes

---

.github/contributors/koaning.md
website/meta/universe.json

We're releasing it on our side officially on the 16th of April. If possible, let's announce around the same time :)
This adds "whatlies" to the spaCy universe json.
This adds "whatlies" to the spaCy universe json.

add "whatlies" to spaCy universe

---

spacy/vocab.pyx

Set `Lexeme.rank` for vectors added with `Vocab.set_vector` so that the lexeme `ID` accessed by a model points the right row for the new vector.
Fixes #5170.

Set rank for new vector in Vocab.set_vector

---

.github/contributors/paoloq.md
spacy/matcher/matcher.pyx
spacy/tests/matcher/test_matcher_api.py

Comparison predicate handling for `!=` 

---

spacy/errors.py
spacy/tests/doc/test_creation.py
spacy/tokens/doc.pyx
spacy/util.py

Add an option to initialize a `Doc` from a text and list of words where the words may or may not include all whitespace tokens. If the text and words are mismatched, raise an error.
This makes it possible to address #4791 and to create docs more easily from external tokenizers that do not preserve whitespace.
Enhancement.

Add Doc init from list of words and text

---

.github/contributors/thomasthiebaud.md
website/meta/universe.json

Hi! I would like to add `spacy_fastlang` to the universe. We are using something very similar in production at Trustpilot

Add spacy_fastlang to universe

---

.github/contributors/sebastienharinck.md

Add contributor agreement for user `sebastienharinck` from the [bot message](https://github.com/explosion/spaCy/pull/5312#issuecomment-614105720)

contrib: add contributor agreement for user sebastienharinck

---

.github/contributors/laszabine.md
website/docs/api/language.md

The documentation of `Language.evaluate` was unclear to my understanding. It did not specify whether the `Doc`s and `GoldParse`s that are passed to this method should contain predictions or correct annotations. This information was only present in the documentation of `Scorer.score`. (The code example to `Language.evaluate` does not specify the correct usage either, and there are also no examples of model evaluations in the usage documentation.) It was conceivable that the model would be applied to `Doc.text` to generate the predictions, and that the `Doc` argument needed to be supplied for comparison purposes. 
I amended the documentation of `Language.evaluate` to make it clear that the `Doc` argument should contain the predicted annotations and the `GoldParse` argument the correct …

Amend documentation to Language.evaluate

---

spacy/cli/train_from_config.py
spacy/ml/_precomputable_affine.py
spacy/syntax/nn_parser.pyx
spacy/util.py

* Activate GPU properly from `train-with-config`
* Fix some GPU training issues
* Improve performance in the precomputable affine backprop padding

Improve GPU usage for train-with-config

---

spacy/lang/zh/__init__.py

Modify jieba install message to instruct the user to use `ChineseDefaults.use_jieba = False` so that it's possible to load pkuseg-only models without jieba installed.
Bug fix.

Modify jieba install message

---

website/docs/api/vectors.md

Update `nlp.vectors` to `nlp.vocab.vectors`
Docs

Update nlp.vectors to nlp.vocab.vectors

---

spacy/tests/regression/test_issue5152.py
spacy/tokens/doc.pyx
spacy/tokens/span.pyx

* bugfix in span similarity
* also rewrite doc.pyx for clarity
* formatting
Fixes #5356.

Backport: bugfix in span similarity (#5155)

---

.github/contributors/michael-k.md
setup.cfg

Prevent pip from installing spaCy on Python 3.4 (which is unsupported since v2.2.0) by extending `python_requires`.
Missed in 80d554f2e2813aea41b0889b39d8f30f648af1ad
enhancement

Prevent pip from installing spaCy on Python 3.4

---

setup.cfg
website/docs/usage/index.md

Add cuda101 and cuda102 options to setup
Enhancement?

Add cuda101 and cuda102 options to setup

---

spacy/__init__.py
spacy/_ml.py
spacy/analysis.py
spacy/cli/init_model.py
spacy/displacy/__init__.py
spacy/errors.py
spacy/gold.pyx
spacy/kb.pyx
spacy/language.py
spacy/lexeme.pyx
spacy/matcher/matcher.pyx
spacy/matcher/phrasematcher.pyx
spacy/pipeline/pipes.pyx
spacy/tests/doc/test_doc_api.py
spacy/tests/doc/test_span.py
spacy/tokenizer.pyx
spacy/tokens/doc.pyx
spacy/tokens/span.pyx
spacy/tokens/token.pyx
spacy/util.py

Simplify warnings

---

spacy/matcher/matcher.pyx
spacy/tokens/doc.pxd
spacy/tokens/doc.pyx

Normalize TokenC.sent_start values to booleans for the `Matcher`.
Fixes #5287.
Bug fix.

Normalize TokenC.sent_start values for Matcher

---

.github/contributors/vondersam.md
spacy/lang/sv/__init__.py
spacy/lang/sv/lex_attrs.py
spacy/tests/lang/sv/test_lex_attrs.py

Added the numerical lexical attributes for Swedish, so that the Token attribute `like_num` works. Tests are included.
Enhancement

Swedish like_num

---

spacy/cli/train.py

Run CPU timing in first iteration only
Bug fix.

Fix logic in train CLI timing eval on CPU/GPU

---

spacy/tests/lang/sv/test_exceptions.py

Some tests for Swedish were actually written in Danish. I have fixed them.
Fix test

Fixed tests for Swedish that were written in Danish.

---

website/docs/api/token.md

Fix Token API docs from #5375
Docs.

Fix Token API docs from #5375

---

spacy/lang/zh/__init__.py
spacy/tests/lang/zh/test_tokenizer.py

Add method to update / reset pkuseg user dict
Enhancement.

Add method to update / reset pkuseg user dict

---

.github/contributors/thoppe.md
website/meta/universe.json

Hi! I'm the author of [NLPre](https://github.com/NIHOPA/NLPre) and I wanted to update the author information for the app on the "Universe" page on the website. Thanks for highlighting this program and all the others!
Only added links in /website/meta/universe.json
Change to documentation only.

Added author information for NLPre

---

examples/training/train_entity_linker.py
website/docs/usage/training.md

Small fixes to EL docs
updates to the documentation

Few more updates to the EL documentation

---

spacy/cli/init_model.py
spacy/errors.py
spacy/tests/vocab_vectors/test_vectors.py
spacy/vectors.pyx
spacy/vocab.pyx

Check that row is within bounds for the vector data array when adding a vector.
Don't add vectors with rank OOV_RANK in `init-model` (change is due to shift from OOV as 0 to OOV as OOV_RANK).
Bug fix.

Check that row is within bounds when adding vector

---

spacy/lang/fa/__init__.py

Set syntax iterators in Persian defaults and add missing `__init__.py` in new test dir.
Bug fix.

Fix syntax iterators for Persian

---

spacy/tokens/span.pyx

Use `Token.sent_start` for sentence boundaries in `Span.sent` so that `Doc.sents` and `Span.sent` return the same sentence boundaries.
Fixes #5435.
Bug fix.

Use Token.sent_start for Span.sent

---

setup.cfg
spacy/lang/pl/__init__.py
spacy/lang/pl/lemmatizer.py

Contributed by @ryszardtuora
Enhancement

Add Polish lemmatizer

---

spacy/_ml.py
spacy/language.py

Skip duplicate lexeme rank setting within `_fix_pretrained_vectors_name()`. Otherwise for a typical model load the ranks are set twice.
Enhancement.

Skip duplicate lexeme rank setting

---

azure-pipelines.yml
pyproject.toml
requirements.txt
setup.cfg
spacy/about.py
spacy/errors.py
spacy/language.py
spacy/ml/_precomputable_affine.py
spacy/tests/parser/test_add_label.py

- requires thinc 8.0.0a8 (https://github.com/explosion/thinc/pull/347)
- fix refactoring of `fan_in` to `mean` in `normal_init`
- remove `ops` from `Adam()`
- raise warning when `model_cfg` can not be found in `create_pipe`
- bump to 3.0.0.dev7
enhancement & bug fix

Update to latest thinc

---

spacy/syntax/nn_parser.pyx

Inspect all instances in `Parser.begin_training` rather than only the first 1000.
(Reported in #4912.)
Bug fix.

Remove peeking from Parser.begin_training

---

spacy/cli/init_model.py

Add option for base model in init-model CLI in order to include a custom tokenizer that can't be initialized as a simple blank model.
Enhancement.

Add option for base model in init-model CLI

---

spacy/lemmatizer.py

Extend lemmatizer rules for all UPOS tags
Allow rules for any UPOS.
Fixes #5459.
Enhancement.

Extend lemmatizer rules for all UPOS tags

---

spacy/cli/converters/conllu2json.py
spacy/tests/test_cli.py

Improve matching by splitting on separator properly, allow `name=B-TAG` and `NE=B-TAG`, allow O tags to be omitted.
Enhancement.

Improve handling of NER in CoNLL-U MISC

---

website/meta/languages.json

Update website models for v2.3.0
Docs.

Update website models for v2.3.0

---

website/docs/usage/models.md

Docs for Chinese word segmentation
Docs.

Docs for Chinese word segmentation

---

spacy/errors.py
spacy/tests/doc/test_retokenize_merge.py
spacy/tokens/_retokenize.pyx

Disallow merging 0-length spans because it leads to invalid docs with inserted empty tokens and other problems.
Fixes #5450.
Bug fix.

Disallow merging 0-length spans

---

spacy/tests/regression/test_issue5152.py
spacy/tests/regression/test_issue5230.py
spacy/tests/regression/test_issue5458.py
spacy/tests/serialize/test_serialize_vocab_strings.py
spacy/tests/vocab_vectors/test_vectors.py

Another round of cross-Python compat fixes for v2.3.
compat

Fix compat for v2.x branch

---

Makefile
requirements.txt
spacy/tests/package/test_requirements.py

Remove jsonschema from dependencies

---

spacy/language.py
spacy/pipe_analysis.py
spacy/tests/pipeline/test_analysis.py

Hopefully makes it more obvious it's about (static) pipeline analysis rather than... any actual analysis performed by the package.
enhancement

Rename spacy.analysis to spacy.pipe_analysis

---

spacy/matcher/phrasematcher.pyx
spacy/tests/matcher/test_phrase_matcher.py

Switch to new add API in PhraseMatcher unpickle
Bug fix.

Switch to new add API in PhraseMatcher unpickle

---

pyproject.toml
requirements.txt
setup.cfg
spacy/about.py

* spacy to v2.3.0
* thinc to v7.4.1
* spacy-lookups-data to v0.3.2

Bump version and deps for v2.3.0

---

Makefile

Update Makefile for v2.3.0

---

Makefile

Handle spacy.pex renaming in Makefile

Handle spacy.pex renaming in Makefile

---

spacy/lang/pl/lemmatizer.py

Restructure Polish lemmatizer not to depend on lookups data in `__init__` since the lemmatizer is initialized before the lookups data is loaded from a saved model. The lookups tables are accessed first in `__call__` instead once the data is available.
Bug fix.

Fix Polish lemmatizer for deserialized models

---

spacy/lang/zh/tag_map.py

Map NR to PROPN in Chinese tag map (according to https://repository.upenn.edu/cgi/viewcontent.cgi?article=1039&context=ircs_reports).
Bug fix?

Map NR to PROPN

---

spacy/language.py

Improve vector name loading from model meta
Don't depend on `bool(nlp.vocab)` for running the `_fix_pretrained_vectors_name` hack on deserialization (since the lexemes are no longer preloaded) and set the vectors name directly since the `Language.meta` property always accesses the current values from `nlp.vocab.vectors` so it can't be set by updating the meta dict.
Bug fix.

Improve vector name loading from model meta

---

spacy/morphology.pyx

If `_SP` is already in the tag map, use the mapping from `_SP` instead of `SP` so that `SP` can be a valid non-space tag. (Chinese has a non-space tag `SP` which was overriding the mapping of `_SP` to `SPACE`.)
Bug fix.

Prefer _SP over SP for default tag map space attrs

---

spacy/tokens/morphanalysis.pyx

The current version raises an error because `to_json()` returns a list, so remove it for v2 for now.
Bug fix.

Remove MorphAnalysis __str__ and __repr__

---

.github/contributors/leomrocha.md

Added and Signed Contributor Agreement

contributor agreement signed

---

spacy/pipeline/pipes.pyx

To allow "SP" as a tag (for Chinese OntoNotes), preserve "_SP" if present as the reference `SPACE` POS in the tag map in `Tagger.begin_training()`.
Bug fix.

Preserve _SP when filtering tag map in Tagger

---

spacy/errors.py
spacy/tests/test_misc.py
spacy/util.py

Since v2.2 models will be loadable but with degraded performance for v2.3, add a rudimentary version check that tries to compare the major.minor version in `meta['spacy_version']` to the current spacy version. If there is a version mismatch or the meta can't be parsed to determine compatibility, show warnings.
Enhancement.

Add rudimentary version checks on model load

---

spacy/lexeme.pyx

Use hard-coded value for `MAX_UINT64` instead of definition from `libc.stdint`
Bug fix.

Avoid libc.stdint for UINT64_MAX

---

spacy/lang/ja/__init__.py
spacy/tests/lang/ja/test_tokenizer.py

Handle empty and whitespace-only docs in the custom alignment method used by the Japanese tokenizer.
Bug fix.

Handle empty and whitespace-only docs for Japanese

---

spacy/about.py

Bump version to 2.3.0.dev1

---

spacy/tests/conftest.py

Switch pytest test from `fugashi` to `sudachipy`, too.
Bug fix.

Update pytest conf for sudachipy with Japanese

---

spacy/lang/ja/__init__.py

Include explicit install instructions in Japanese requirements warning.
Enhancement.

Expand Japanese requirements warning

---

spacy/errors.py
spacy/pipeline/pipes.pyx
spacy/syntax/nn_parser.pyx
spacy/tests/parser/test_ner.py
spacy/tests/test_lemmatizer.py

* Fix warning message for lemmatization tables
* Add a warning when the `lexeme_norm` table is empty. (Given the relatively lang-specific loading for `Lookups`, it seemed like too much overhead to dynamically extract the list of languages, so for now it's hard-coded.)
Enhancement.

Fix and add warnings related to spacy-lookups-data

---

spacy/gold.pyx
spacy/vocab.pyx

Updates to docstrings for `GoldParse` and `Vocab`.

Updates to docstrings

---

website/docs/usage/101/_pos-deps.md
website/docs/usage/adding-languages.md
website/docs/usage/linguistic-features.md
website/docs/usage/rule-based-matching.md

Minor v2.3.0 doc updates, mostly related to examples
Docs.

Minor v2.3.0 doc updates

---

website/docs/usage/models.md

Warning for sudachipy 0.4.5
Docs

Warning for sudachipy 0.4.5

---

website/docs/usage/v2-3.md

Add warnings example in v2.3 migration guide
Originally suggested by  @MartinoMensio in #5614.
Docs.

Add warnings example in v2.3 migration guide

---

.github/contributors/richardliaw.md

Contributor Agreement: richardliaw

---

website/docs/usage/v2-3.md

Extend what's new in v2.3 with vocab / is_oov
Docs

Extend what's new in v2.3 with vocab / is_oov

---

website/docs/usage/v2-3.md

Fix backslashes in warnings config diff in v2.3 migration section.
Docs.

Fix backslashes in warnings config diff

---

website/docs/usage/v2-3.md

Extend migration guide for preloaded vocab, prob tables, and tag maps.
Docs.

Extend v2.3 migration guide

---

spacy/gold/example.pyx
spacy/tests/test_gold.py

Haven't gotten around to actually fixing all of them yet - perhaps let's first make sure we agree on what the ideal result should be ;-)

NER align tests

---

spacy/lang/en/__init__.py
spacy/language.py
spacy/lemmatizer.py
spacy/tests/regression/test_issue1-1000.py
spacy/tests/test_lemmatizer.py

Move `Lemmatizer.is_base_form` to the language settings so that each language can provide a language-specific method as `LanguageDefaults.is_base_form`.
The existing English-specific `Lemmatizer.is_base_form` is moved to `EnglishDefaults`.
Bug fix.

Move lemmatizer is_base_form to language settings

---

bin/ud/ud_train.py
examples/training/conllu.py
examples/training/train_ner.py
pyproject.toml
spacy/cli/debug_data.py
spacy/errors.py
spacy/gold/corpus.py
spacy/gold/example.pyx
spacy/gold/gold_io.pyx
spacy/morphology.pyx
spacy/pipeline/simple_ner.py
spacy/tokens/_serialize.py
spacy/tokens/doc.pyx
spacy/tokens/morphanalysis.pyx

Various fixes related to the refactor from PR #5555
& clean-up of unused Error messages
(bug) fix

refactor fixes

---

spacy/lang/ja/__init__.py
spacy/tests/lang/ja/test_tokenizer.py

Revert "Convert custom user_data to token extension format for Japanese tokenizer"

---

examples/training/rehearsal.py
examples/training/train_ner.py
examples/training/train_new_entity_type.py

Fix multiple context manages in examples
Bug fix.

Fix multiple context managers in examples

---

spacy/cli/init_model.py

Two small bugs crept in, probably from refactoring/merging.
- `vectors_loc` was not passed through from the CL arguments
- `prune_vectors` was not passed through to `read_vectors`
bug fix

Fixing init_model

---

spacy/tests/doc/test_doc_api.py
spacy/tokens/doc.pyx

* Add strings for all writeable Token attributes to `Doc.to/from_bytes()`.
* Add ENT_KB_ID to default attributes.
Fixes #5643.
Bug fix.

Add strings and ENT_KB_ID to Doc serialization

---

spacy/tokens/_serialize.py
website/docs/api/docbin.md

* Add version number to DocBin
* Add POS to all attributes in DocBin
* Add morph string to strings in DocBin
* Add ent_kb_id string to strings in DocBin

DocBin: add version number, missing attributes and strings

---

.github/contributors/hertelm.md
examples/training/train_entity_linker.py

Fixes #5668 for the entity linker training example, according to the first comment by @adrianeboyd .
documentation

Fixed vocabulary in the entity linker training example

---

.github/contributors/hertelm.md
.gitignore
MANIFEST.in
examples/training/rehearsal.py
examples/training/train_entity_linker.py
examples/training/train_ner.py
examples/training/train_new_entity_type.py
netlify.toml
setup.py
spacy/language.py
spacy/tests/doc/test_doc_api.py
spacy/tokens/doc.pyx
website/docs/api/phrasematcher.md
website/docs/usage/rule-based-matching.md

Update v2.3.x from master

---

spacy/cli/convert.py
spacy/gold/converters/__init__.py
spacy/gold/converters/conllu2docs.py
spacy/tests/test_cli.py

Add conllu2docs converter adapted from conllu2json converter
Enhancement?

Add conllu2docs converter

---

spacy/about.py

Set version to 2.3.1

---

spacy/tests/regression/test_issue2501-3000.py

(I hope I don't need to submit the spaCy Contributor Agreement for this fix. If I do, feel free to remove this PR.)

Fix typo in test function docstring

---

spacy/cli/convert.py
spacy/gold/gold_io.pyx

* In `spacy convert -t json` output the JSON docs wrapped in a list
* Add back token-level `ner` alongside the doc-level `entities`
Bug fix?

Make docs to JSON conversion backwards-compatible with v2

---

spacy/errors.py
spacy/gold/example.pyx
spacy/tests/parser/test_nonproj.py
spacy/tests/test_gold.py

* unit tests for `test_aligned_spans_y2x`, `test_aligned_spans_x2y`, `get_aligned_parse`
* some clean up
enhancement

Few more Example unit tests

---

.github/contributors/gandersen101.md
website/meta/universe.json

Adding spaczz package to universe.json

---

spacy/morphology.pyx
spacy/pipeline/morphologizer.pyx
spacy/pipeline/pipes.pyx

Update `get_loss` for senter and morphologizer to keep them similar to tagger.
Enhancement.

Update get_loss for senter and morphologizer

---

spacy/about.py
spacy/cli/download.py

No need to fetch an additional JSON file anymore, we might as well hard-code the previous shortcuts so we can still support them and show users a warning.

Deprecate model shortcuts and simplify download

---

spacy/pipeline/pipes.pyx
spacy/tests/pipeline/test_senter.py

When converting the `sent_start` values back to `SentenceRecognizer` labels, handle `None` alignments.
Bug fix.

Fix get_loss for values outside of labels in senter

---

spacy/cli/convert.py

Minor refactor of conversion of docs to output format to avoid duplicate conversion steps.
Enhancement.

Minor refactor to conversion of output docs

---

spacy/lang/fr/lemmatizer.py

Remove English-specific is_base_form from French lemmatizer.
Fixes #5728.
Bug fix.

Remove is_base_form from French lemmatizer

---

spacy/lang/en/__init__.py
spacy/lemmatizer.py
spacy/tests/regression/test_issue3001-3500.py

Fix lemmatizer is_base_form for python2.7
Fixes #5729.
Bug fix.

Fix lemmatizer is_base_form for python2.7

---

spacy/cli/project/assets.py
spacy/cli/project/clone.py
spacy/cli/project/dvc.py
spacy/cli/project/run.py
spacy/cli/project/util.py
spacy/errors.py
spacy/schemas.py
spacy/util.py

Update project CLI hashes, directories, skipping

---

spacy/cli/pretrain.py
spacy/displacy/render.py
spacy/errors.py
spacy/language.py
spacy/lemmatizer.py
spacy/lookups.py
spacy/matcher/matcher.pyx
spacy/ml/models/multi_task.py
spacy/pipeline/entityruler.py
spacy/pipeline/hooks.py
spacy/pipeline/pipes.pyx
spacy/scorer.py
spacy/tests/parser/test_ner.py
spacy/tests/pipeline/test_analysis.py
spacy/tests/regression/test_issue5137.py
spacy/tests/regression/test_issue5230.py
spacy/tests/test_errors.py
spacy/tokens/_serialize.py
spacy/tokens/underscore.py
spacy/util.py
spacy/vectors.pyx
website/docs/usage/linguistic-features.md
website/docs/usage/processing-pipelines.md
website/docs/usage/rule-based-matching.md
website/docs/usage/saving-loading.md

Not needed anymore for Python 3 only.
compat

Remove object subclassing

---

spacy/about.py

Set version to 2.3.2

---

spacy/tests/doc/test_doc_api.py
spacy/tests/test_gold.py
spacy/tokens/doc.pyx

Add morphological analyses to morphology table in `Doc.from_array`.
Bug fix.

Add morph to morphology in Doc.from_array

---

spacy/errors.py

Clarify warning W030 for misaligned BILUO tags.
Resolves #5727.
Enhancement.

Clarify warning W030 for misaligned BILUO tags

---

Makefile
spacy/lang/zh/__init__.py
website/docs/usage/models.md

* Update pkuseg version in Chinese tokenizer warnings
* Update pkuseg version in `Makefile`
* Remove warning about python3.8 wheels in docs
Enhancement.

Update pkuseg version

---

bin/ud/run_eval.py
bin/ud/ud_train.py

Upgraded UD eval script for v.3, including the recent new languages & models.
enhancement

Upgrade of UD eval script

---

spacy/cli/debug_data.py
spacy/cli/train.py
spacy/morphology.pyx

Generalize tag map initialization and updating so that a provided tag map can be loaded correctly in the CLI.
* normalize provided tag map as necessary
* use the same method for initializing and overwriting the tag map
Bug fix.

Improve tag map initialization and updating

---

.github/contributors/abchapman93.md
website/meta/universe.json

This pull request adds a project to spaCy Universe: [VA COVID-19 NLP BSV](https://github.com/abchapman93/VA_COVID-19_NLP_BSV) is a rule-based spaCy pipeline which was used for [COVID-19 surveillance at the Department of Veterans Affairs](https://openreview.net/forum?id=ZQ_HvBxcdCv).
Change to `universe.json`

Add VA COVID-19 NLP project to spaCy Universe

---

spacy/cli/evaluate.py

Very minor bug fix if you're calling `evaluate` from `spacy.cli.evaluate` separately.
Bug fix.

Provide default output for evaluate in CLI

---

spacy/morphology.pyx
spacy/tests/morphology/test_morph_pickle.py

Pickle exceptions in the MORPH_RULES format instead of the internal format after the recent `Morphology.__init__` changes.
Bug fix.

Fix exceptions for Morphology.__reduce__

---

spacy/errors.py
spacy/pipeline/pipes.pyx
spacy/syntax/nn_parser.pyx

Provide more customized normalization table warnings when training a new model. Only suggest installing `spacy-lookups-data` if it's not already installed and it includes a table for this language (currently checked in a hard-coded list).
Possibly the first warning about the empty normalization table could be removed, it's kind of a lot of warnings in the end.
Enhancement.

Improve warnings around normalization tables

---

website/docs/api/morphologizer.md

Initial draft of Morphologizer API docs
Docs.

Initial draft of Morphologizer API docs

---

.github/contributors/solarmist.md
spacy/lang/ja/__init__.py

Mark the document as tagged before returning it to the user from the JapaneseTokenizer.
Fixes #5802
Bug fix

Mark Japanese documents as tagged.

---

spacy/cli/pretrain.py

Remove hard-coded GPU ID from pretrain
Fixes #5799.
Bug fix.

Remove hard-coded GPU ID from pretrain

---

spacy/morphology.pyx
spacy/tests/doc/test_morphanalysis.py
spacy/tests/morphology/test_morph_converters.py
spacy/tokens/morphanalysis.pyx

* `MorphAnalysis.get` returns only the field values
* Move `_normalize_props` inside `Morphology` as `Morphology.normalize_attrs` and simplify
* Simplify POS field detection/conversion
* Convert all non-POS features to strings
* `Morphology` returns an empty string for a missing morph to align with the FEATS string returned for an existing morph
* Remove unused `list_to_feats`
Enhancement

Minor refactor for Morphology and MorphAnalysis

---

spacy/tests/lang/ja/test_tokenizer.py

* Update POS tests to reflect current behavior (it is not entirely clear whether the AUX/VERB mapping is indeed the desired behavior?)
* Switch to `from_config` initialization in subtoken test
Bug fix in tests, so ... ???

Update Japanese tests

---

website/meta/universe.json

About:
https://spacy.io/universe/project/python-sentence-boundary-disambiguation
Have been receiving typo reports on project repo.
https://github.com/nipunsadvilkar/pySBD/issues/72#issue-664000944
Please merge to update the pysbd code example.

✏️  typo in pysbd code example

---

examples/training/train_textcat.py
examples/training/train_textcat_config.cfg
spacy/cli/debug_model.py
spacy/errors.py
spacy/tests/test_util.py
spacy/util.py

* `dot_to_object` as a `util` function instead of only in `debug_model`
* additional unit test, also testing default config + config fill behaviour
* some updates to the `train_textcat` script (should probably be retired at some point, but still useful for quick benchmarks right now)
enhancement

dot notation to object - util function

---

spacy/cli/evaluate.py
spacy/cli/train.py
spacy/language.py

Move timing into `Language.evaluate` so that only the processing is being timed, not processing + scoring. `Language.evaluate` returns `scores["speed"]` as words per second, which should be identical to how the speed was added to the scores previously. Also add the speed to the evaluate CLI output.
Enhancement.

Move timing into Language.evaluate

---

spacy/cli/train.py

Fix score_weights typo in train CLI
Bug fix.

Fix score_weights typo in train CLI

---

.github/contributors/leyendecker.md
spacy/displacy/render.py
spacy/tests/regression/test_issue5838.py

Fix on EntityRendered to support break lines (after last entity) (closes #5838)

---

spacy/pipeline/entityruler.py
spacy/tests/pipeline/test_entity_ruler.py

Similar to #4414, update the sorting in EntityRuler to prefer the first span in overlapping spans.
Fixes #5840.
Bug fix.

Prefer earlier spans in EntityRuler

---

spacy/errors.py
spacy/language.py
spacy/pipe_analysis.py
spacy/tests/pipeline/test_analysis.py
website/docs/api/language.md
website/docs/usage/processing-pipelines.md

* Simplify pipe analysis, remove global, don't auto-analyze when pipe is added or removed.
* Add `Language.analyze_pipes` that prints/returns overview and problems.
* Allow user to change keys that are shown in overview (assigns, requires, scores etc.)
enhancement

Integrate and simplify pipe analysis

---

spacy/lang/es/syntax_iterators.py

Fix span boundary handling in Spanish noun_chunks.
Fixes #5853.
Bug fix.

Fix span boundary handling in Spanish noun_chunks

---

spacy/errors.py
spacy/tests/doc/test_span.py
spacy/tokens/span.pyx

Add Span index boundary checks
Bug fix

Add Span index boundary checks

---

spacy/gold/example.pxd
spacy/gold/example.pyx
spacy/tests/test_gold.py

Recalculate alignment if tokenization differs from tokenization at the point when the saved alignment was created.
Bug fix.

Recalculate alignment if tokenization differs

---

spacy/errors.py
spacy/matcher/matcher.pyx
spacy/tests/matcher/test_pattern_validation.py

* Add a warning when a subpattern is not processed and discarded
* Normalize subpattern attribute/operator keys to upper case like top-level attributes
Fixes #5870.

Add warning when Matcher subpattern is discarded

---

spacy/default_config.cfg
spacy/errors.py
spacy/language.py
spacy/schemas.py
spacy/tests/test_language.py
spacy/util.py

Add config callbacks for modifying nlp object before and after init

---

spacy/scorer.py
spacy/tests/test_scorer.py

Convert `PRFScore` to dict as other per type scores.

Fix return values for per feat score

---

spacy/pipeline/attributeruler.py

Add `pipe` to `AttributeRuler`
Bug fix.

Add pipe to AttributeRuler

---

spacy/errors.py
spacy/gold/corpus.py
website/docs/api/architectures.md
website/docs/api/cli.md
website/docs/api/data-formats.md
website/docs/api/entitylinker.md
website/docs/usage/processing-pipelines.md
website/docs/usage/spacy-101.md
website/docs/usage/training.md

- `DocBin` format
- update of EL docs
- architectures of EL & textcat
- various small fixes
docs

EL docs update

---

spacy/pipeline/attributeruler.py
website/docs/api/attributeruler.md
website/meta/sidebars.json

With additional minor updates to AttributeRuler docstrings.
Docs.

Add AttributeRuler API docs

---

spacy/gold/batchers.py

Not sure what the best approach is for documenting the registered functions vs the actual functions.

Draft docstrings for batchers

---

spacy/pipeline/lemmatizer.py

It was probably overlooked. Should there be a unit test covering this? In that case, could somebody else add it? I'm not familiar with the testing practices of this project.
Bug fix

Use init parameter of Lemmatizer

---

website/docs/usage/vectors-embeddings.md

* Wrote much more about using vectors in the Thinc models
* Tried to integrate the vectors vs transformers stuff into the text, instead of having a "other embeddings" section.
* Added a section on similarity calculations, and tried to highlight the limitations.
I need to fix lots of formatting, but I thought I'd show a version first.

Update the 'vectors' docs page

---

pyproject.toml
requirements.txt
setup.cfg
spacy/cli/templates/quickstart_training.jinja
spacy/default_config.cfg
spacy/tests/serialize/test_serialize_config.py
website/docs/api/architectures.md
website/docs/api/corpus.md
website/docs/api/data-formats.md
website/docs/api/top-level.md
website/docs/usage/training.md

- Update to lastest Thinc.
- Standardise variables to only use dot syntax, e.g. `${a:b}` &rarr; `${a.b}`

Update Thinc and config variables 

---

spacy/tests/regression/test_issue5838.py

The CI on `master` is failing recently for Python 2 due to the coding not being present in this test.
bug fix

add coding

---

spacy/lang/pl/__init__.py
spacy/lang/pl/lemmatizer.py

Rename Polish lemmatizer method to `pos_lookup` to distinguish it from pure token-based lookup methods.
Enhancement.

Rename Polish lemmatizer method

---

spacy/symbols.pyx

Remove PRON_LEMMA symbol
Enhancement.

Remove PRON_LEMMA symbol

---

spacy/lang/tokenizer_exceptions.py

Add missing raw string specifiers.
Bugfix.

Fix raw strings in URL pattern

---

spacy/scorer.py

Set macro AUC score in Scorer.score_cats

---

licenses/3rd_party_licenses.txt

Add missing 3rd-party-licenses from #5694.

Add 3rd party licenses file

---

spacy/pipeline/attributeruler.py
spacy/pipeline/tagger.pyx
spacy/tests/pipeline/test_attributeruler.py
website/docs/api/attributeruler.md
website/docs/api/tagger.md

Add scoring for TAG / POS / MORPH / LEMMA if these are present in the assigned token attributes.
Enhancement.

Add AttributeRuler.score

---

requirements.txt
setup.cfg
spacy/cli/__init__.py
spacy/cli/debug_config.py
spacy/cli/debug_data.py
website/docs/api/cli.md

* Update to latest `catalogue` so we can use `Registry.find`.
* Add `--show-functions` to `debug config`: list all registered functions and where they come from
* Add `--show-variables` to `debug config`: list all variables and their values (including from overrides)
enhancement

Add more info to debug config

---

spacy/gold/loggers.py

Add option to W&B logger to remove parts of the config before uploading it (does not otherwise affect the config file).
Will add docs in different PR (together with other doc changes).
enhancement

prevent uploading from some config fields to W&B

---

website/docs/usage/embeddings-transformers.md

There are many more doc edits coming up for some of the open PRs on `spacy` and `spacy-transformers`, but I wanted to commit already this bit to avoid duplicate work / conflicts on the specific TODO sections.
docs

custom transformer examples

---

spacy/pipeline/attributeruler.py
spacy/tests/pipeline/test_attributeruler.py

* Fix serialization using simpler `AttributeRuler.patterns` property
* Apply patterns in the order they were added
Bug fix.

Fix AttributeRuler serialization and rule ordering

---

website/docs/api/sentencerecognizer.md
website/docs/usage/linguistic-features.md

Update sentence segmentation usage docs to incorporate `senter`.
Docs

Update sentence segmentation usage docs

---

spacy/errors.py
spacy/tests/tokenizer/test_tokenizer.py
spacy/tokenizer.pyx
website/docs/usage/v3.md

Restrict tokenizer exceptions to ORTH and NORM
Enhancement?

Restrict tokenizer exceptions to ORTH and NORM

---

.github/contributors/jgutix.md
website/docs/usage/linguistic-features.md

The current example will throw `TypeError: can only concatenate list (not "tuple") to list`
Documentation

Update suffixes example

---

website/docs/api/top-level.md

Example output of logging training in the console
docs

console logging example

---

spacy/lang/hu/punctuation.py

Fix failing slow tests for Hungarian related to `%`.
(Not quite sure why/when this broke, though.)
Bug fix.

Fix Hungarian % tokenization

---

spacy/tokenizer.pxd
spacy/tokenizer.pyx

Simplify specials and cache checks (just some minimal refactoring taken from #5772).
?

Refactor specials and cache checks in tokenizer

---

website/meta/universe.json

Update to the SpaCy Universe website for the addition of "amrlib"
Simple update to .json file

Updates spaCy Universe for amrlib

---

extra/experiments/onto-joint/defaults.cfg
extra/experiments/ptb-joint-pos-dep/defaults.cfg
spacy/cli/templates/quickstart_training.jinja
spacy/default_config.cfg
spacy/displacy/render.py
spacy/errors.py
spacy/gold/batchers.py
spacy/ml/models/entity_linker.py
spacy/pipeline/entity_linker.py
spacy/tests/lang/test_lemmatizers.py
spacy/tests/pipeline/test_attributeruler.py
spacy/tests/pipeline/test_entity_linker.py
spacy/tests/pipeline/test_lemmatizer.py
spacy/tests/regression/test_issue5230.py
spacy/tests/serialize/test_serialize_config.py
spacy/tests/serialize/test_serialize_kb.py
spacy/util.py
website/docs/api/architectures.md
website/docs/api/cli.md
website/docs/api/entitylinker.md
website/docs/api/top-level.md
website/docs/api/transformer.md
website/docs/usage/embeddings-transformers.md
website/docs/usage/processing-pipelines.md

- `@assets` -> `@misc`
- add `spacy.` prefix to batchers
- add `spacy-transformers.` prefix to span getters (related: explosion/spacy-transformers#214)
enhancement

Registry renaming

---

spacy/cli/_util.py
spacy/cli/project/clone.py
website/docs/api/dependencyparser.md
website/docs/api/entityrecognizer.md
website/docs/api/language.md
website/docs/api/morphologizer.md
website/docs/api/pipe.md
website/docs/api/tagger.md
website/docs/api/textcategorizer.md

* hookup `branch` argument
* provide try-catch statements for each command that is run in the sparse checkout (the error is too uninformative otherwise)
* small fix in the docs (reference anchor)
bug fix & UX

Fix branch for spacy clone + UX

---

spacy/cli/_util.py
spacy/cli/project/clone.py
spacy/util.py

Fix project clone compatibility

---

spacy/tests/tokenizer/test_tokenizer.py
spacy/tokenizer.pyx

Fix token.idx for special cases with affixes
Bug fix

Fix token.idx for special cases with affixes

---

spacy/cli/_util.py
spacy/cli/project/assets.py
spacy/cli/project/clone.py
spacy/util.py

- Make sparse checkout optional via `--sparse` flag (while still falling back to non-sparse for older Git versions, but with warning).
- Improve handling of subprocess error and how it's messages are exposed to the user.
cli, ux

 Fix sparse checkout and error handling 

---

spacy/lang/bn/__init__.py
spacy/lang/fa/__init__.py
spacy/lang/nb/__init__.py
spacy/lang/sv/__init__.py
spacy/tests/lang/test_lemmatizers.py

For languages without custom lemmatizers and with lemmatizer rules in `spacy-lookups-data`, make the rule-based lemmatizer the default: Bengali, Persian, Norwegian, Swedish
Enhancement?

Set rule-based lemmatizers as default

---

spacy/ml/models/tok2vec.py
spacy/pipeline/morphologizer.pyx
spacy/tests/test_tok2vec.py

Add vectors option as `also_use_static_vectors` to `CharacterEmbed`.
Enhancement

Add vectors option to CharacterEmbed

---

spacy/pipeline/_parser_internals/arc_eager.pyx
spacy/pipeline/_parser_internals/nonproj.pyx
spacy/tests/doc/test_doc_api.py
spacy/tests/doc/test_token_api.py
spacy/tests/parser/test_parse.py
spacy/tests/regression/test_issue2501-3000.py
spacy/tokens/_retokenize.pyx
spacy/tokens/doc.pxd
spacy/tokens/doc.pyx
spacy/tokens/span.pyx
spacy/tokens/token.pyx

* Update `set_children_from_heads`
* Don't check `dep` when setting lr_* or sentence starts
* Set all non-sentence starts to `False`
* Use `set_children_from_heads` in `Token.head` setter
* Reduce similar/duplicate code (admittedly adds a bit of overhead)
* Update sentence starts consistently
* Remove unused `Doc.set_parse`
* Minor changes:
* Declare cython variables (to avoid cython warnings)
* Clean up imports
Enhancement

Clean up spacy.tokens

---

website/docs/usage/embeddings-transformers.md

Needs review and formatting. Not sure whether this was exactly what was required, but hopefully it's a start or can be edited down.

Draft text for static vectors intro

---

website/docs/usage/embeddings-transformers.md

Draft docs for pretrain usage

---

spacy/errors.py
spacy/tests/doc/test_doc_api.py
spacy/tokens/doc.pyx

This warning was hacky and being triggered too often.
?

Remove W106: HEAD and SENT_START in doc.from_array

---

website/meta/sidebars.json

Alphabetize API sidebars
Docs.

Alphabetize API sidebars

---

website/docs/api/doc.md
website/docs/usage/101/_architecture.md
website/docs/usage/saving-loading.md
website/meta/sidebars.json

* Update alignment mode in Doc.char_span docs
* Fix typo in saving and loading usage docs 
Docs.

Various minor v3 docs updates

---

requirements.txt

Add pin for `pyrsistent<0.17.0` since `pyrsistent>=0.17.1` is only compatible with python3.5+.
?

Add pin for pyrsistent<0.17.0

---

spacy/tests/doc/test_retokenize_split.py
spacy/tokens/_retokenize.pyx

Parallel to behavior in merge, reset norm on original token in retokenizer split.
Fixes #6060.
Bugfix

Fix norm in retokenizer split

---

spacy/cli/debug_model.py
spacy/tests/pipeline/test_tok2vec.py

call `tok2vec.update` instead of `predict`
bug fix

Fix tok2vec call

---

.github/contributors/rasyidf.md
spacy/lang/id/examples.py

The current example of the Indonesian language contains sensitive topics (Violent, Terrorism) and needs to be changed with more proper sentences.
No code changed, only strings. 
bugfix or enhancement

Update Indonesian Example Phrases  

---

spacy/cli/train.py
spacy/default_config.cfg
spacy/errors.py
spacy/schemas.py
website/docs/api/data-formats.md

Optional function called on the `nlp` object before it's saved to disk during/after training and can return a modified version. Can be used to implement all kinds of things, including cleaning up the config.

Add [training.before_to_disk] callback

---

spacy/errors.py
spacy/matcher/matcher.pyx
spacy/matcher/phrasematcher.pyx
spacy/pipeline/attributeruler.py
spacy/tests/matcher/test_matcher_api.py

So that the `AttributeRuler` component runs and doesn't produce cryptic errors when some pipeline components are disabled:
* Add option to disable Matcher errors when a doc doesn't contain a particular type of annotation
Minor additional change:
* Update `AttributeRuler.load_from_morph_rules` to allow direct `MORPH`
values
Enhancement.

Add option to disable Matcher errors

---

spacy/matcher/matcher.pyx
spacy/schemas.py
spacy/tests/matcher/test_matcher_api.py
website/docs/api/matcher.md
website/docs/usage/rule-based-matching.md

* Add `MORPH` to `Matcher` schema
* Rename `_SetMemberPredicate` to `_SetPredicate`
* Add `ISSUBSET` and `ISSUPERSET` operators to `_SetPredicate`
* Add special handling for normalization and conversion of morph values into sets
* For other attrs, `ISSUBSET` acts like `IN` and `ISSUPERSET` only matches for 0 or 1 values
Enhancement.

Add MORPH handling to Matcher

---

spacy/scorer.py

Revert changes to Scorer.score_spans
?

Revert changes to Scorer.score_spans

---

spacy/structs.pxd

Clean up MorphAnalysisC struct
?

Clean up MorphAnalysisC struct

---

spacy/pipeline/attributeruler.py

Simplify string match IDs for AttributeRuler
?

Simplify string match IDs for AttributeRuler

---

spacy/morphology.pyx
spacy/symbols.pxd
spacy/symbols.pyx

Add _ as a symbol

---

spacy/lang/ja/__init__.py
spacy/lang/ko/__init__.py
spacy/lang/zh/__init__.py

Add tokenizer scoring to ja / ko / zh
Enhancement

Add tokenizer scoring to ja / ko / zh

---

spacy/cli/project/document.py
website/docs/usage/training.md
website/setup/jinja_to_js.py

Ensure files are opened with the correct encoding, or this may crash for Windows users ;-)
bug fix

encoding UTF8

---

spacy/training/example.pyx

Update import from `collections.abc`
?

Update import from collections.abc

---

spacy/tests/doc/test_doc_api.py
spacy/tests/doc/test_retokenize_merge.py
spacy/tests/doc/test_to_json.py
spacy/tests/regression/test_issue3001-3500.py
spacy/tests/test_scorer.py
spacy/tests/training/test_training.py
spacy/tokens/doc.pyx

Switch `Doc.__init__(ents=)` to IOB tags
?

Switch Doc.__init__(ents=) to IOB tags

---

spacy/ml/featureextractor.py
spacy/ml/models/textcat.py
spacy/ml/models/tok2vec.py
website/docs/api/architectures.md
website/docs/usage/embeddings-transformers.md

As this layer is spaCy-specific, it makes more sense to have it here instead of in Thinc.
enhancement

Add FeatureExtractor from Thinc

---

spacy/training/converters/conllu_to_docs.py

This doesn't make a difference given how the `merged_morph` values override the `morph` values for all the final docs, but could have led to unexpected bugs in the future if the converter is modified.
Bugfix

Minor edit to CoNLL-U converter

---

setup.cfg
website/docs/usage/models.md
website/docs/usage/training.md

Various docs update for v3.
Docs.

Update docs: Chinese, Japanese, etc.

---

spacy/schemas.py

Allow more embedded per_x in `ModelMetaSchema`
Bugfix

Relax model meta performance schema

---

spacy/cli/templates/quickstart_training.jinja

Add morphologizer to quickstart template
Enhancement?

Add morphologizer to quickstart template

---

spacy/errors.py
spacy/pipeline/senter.pyx
spacy/pipeline/textcat.py
spacy/tests/pipeline/test_textcat.py
spacy/tests/serialize/test_serialize_pipeline.py
spacy/training/initialize.py
website/docs/api/textcategorizer.md

- Move `labels` and `positive_label` to `initialize`.
- Perform label checks in `initialize` and remove hacky validation functions.
fix

Fix label initialization of textcat component

---

spacy/tests/training/test_augmenters.py
spacy/tests/training/test_training.py
spacy/training/augment.py
spacy/training/example.pyx
website/docs/api/top-level.md

Update data augmenters

---

spacy/lang/ru/__init__.py
spacy/lang/ru/lemmatizer.py
spacy/lang/uk/__init__.py
spacy/lang/uk/lemmatizer.py
spacy/tests/conftest.py

Update ru/uk lemmatizers for new nlp.initialize
Bugfix.

Update ru/uk lemmatizers for new nlp.initialize

---

website/docs/api/pipe.md
website/docs/usage/layers-architectures.md
website/docs/usage/processing-pipelines.md

Docs section "Create new trainable components"
I wasn't sure at times how much detail to provide, but once the example project is finished, the full reference implementation will be available.
docs

docs on implementing new pipe component

---

spacy/errors.py
spacy/training/converters/conll_ner_to_docs.py
spacy/training/converters/iob_to_docs.py

E093 was ambiguous
bug fix in UX

fix error numbering

---

spacy/lookups.py
spacy/vocab.pyx

Remove `None` checks for lookups and vectors (they should never be `None`) and always serialize lookups to disk even if there are no tables. This synchronizes the behavior of `to_disk` and `to_bytes` for lookups and makes it harder to end up in an inconsistent state when overwriting an existing model directory.
Bugfix.

Always serialize lookups and vectors to disk

---

spacy/errors.py
spacy/training/loop.py

Remove output dirs before training

---

Makefile
spacy/lang/zh/__init__.py
spacy/tests/conftest.py

Update Chinese tokenizer for spacy-pkuseg fork
Enhancement

Update Chinese tokenizer for spacy-pkuseg fork

---

.github/contributors/florijanstamenkovic.md
spacy/tests/regression/test_issue6207.py
spacy/util.py

Fix Issue 6207

---

.github/contributors/zaibacu.md
website/meta/universe.json

Adding a domain specific language which compiles into spaCy patterns, simplifying process of defining custom rules for entity parsing

Website (Universe): An entry for rita-dsl

---

README.md
website/docs/usage/models.md

Various v3 docs updates

---

spacy/ml/staticvectors.py
spacy/tests/test_models.py

Fix empty input into StaticVectors layer

---

requirements.txt
setup.cfg
spacy/tests/package/test_requirements.py

`packaging.version.Version.major` was introduced in version 20.0.
install fix

Fix packaging pin

---

.github/contributors/delzac.md
website/docs/usage/rule-based-matching.md

One line update to the docs to reflect that `IS_SENT_START` is an available attribute for rule-based matching.
update to documentation

Reflect on usage doc that IS_SENT_START attribute exist

---

spacy/lang/th/tag_map.py

I add the mapping of POS tags from [LST20 Corpus](https://arxiv.org/abs/2008.05055) to UD. (tag map by @korakot)
enhancement

Add Thai tag map (LST20 Corpus)

---

.github/contributors/delzac.md
.github/contributors/florijanstamenkovic.md
.github/contributors/zaibacu.md
spacy/lang/tr/__init__.py
spacy/lang/tr/lex_attrs.py
spacy/lang/tr/syntax_iterators.py
spacy/tests/conftest.py
spacy/tests/lang/tr/test_noun_chunks.py
spacy/tests/lang/tr/test_parser.py
spacy/tests/lang/tr/test_text.py
spacy/tests/regression/test_issue6207.py
spacy/util.py
website/docs/usage/rule-based-matching.md
website/meta/universe.json

Update develop from master

---

spacy/tests/doc/test_doc_api.py
spacy/tests/doc/test_retokenize_merge.py
spacy/tokens/span.pxd
spacy/tokens/span.pyx

Remove `Span._recalculate_indices`, which is a remnant from the deprecated `Span.merge`.
?

Remove Span._recalculate_indices

---

spacy/ml/models/tok2vec.py
spacy/pipeline/morphologizer.pyx
spacy/tests/pipeline/test_tok2vec.py
website/docs/usage/embeddings-transformers.md

Also rename to include_static_vectors in CharEmbed
Bug fix, I guess

Also rename to include_static_vectors in CharEmbed

---

spacy/cli/convert.py
spacy/ml/models/textcat.py
spacy/ml/models/tok2vec.py
spacy/util.py
website/docs/usage/embeddings-transformers.md

-  remove `MultiHashEmbedCNN` reference from documentation
- fix `get_dim` calls in `build_simple_cnn_text_classifier`
- add utf8 encoding for opening file 
fixes

Various small fixes

---

spacy/training/loggers.py

Fits more results on one line.
enhancement

Make console logger table more compact

---

spacy/ml/models/entity_linker.py
website/docs/api/architectures.md
website/docs/api/entitylinker.md

update NEL docs to sync with PR #6216
docs fix

update NEL docs after latest refactor

---

spacy/util.py

Sofie forgot about programming lesson number 1: follow up `if` with `else` :'(
Hoping that this bugfix fixes our latest problems.
bug fix

bugfix in _pipe

---

spacy/pipeline/tagger.pyx
spacy/pipeline/trainable_pipe.pyx
website/docs/usage/layers-architectures.md

- always return `losses` in `update` and `rehearse` (a few edge cases didn't)
- few typos in docs
small fixes

Small fixes

---

spacy/tests/parser/test_ner.py
spacy/tests/parser/test_parse.py
spacy/tests/pipeline/test_entity_linker.py
spacy/tests/pipeline/test_models.py
spacy/tests/pipeline/test_morphologizer.py
spacy/tests/pipeline/test_senter.py
spacy/tests/pipeline/test_tagger.py
spacy/tests/pipeline/test_textcat.py

Add tests to ensure reproducibilty of trained ML models when making predictions at runtime.
Added similar tests to Thinc in https://github.com/explosion/thinc/pull/407.
tests

Test runtime reproducibility

---

spacy/training/gold_io.pyx

Use null raw for `has_unknown_spaces` in `docs_to_json`
Bug fix?

Use null raw for has_unknown_spaces in docs_to_json

---

website/docs/usage/training.md
website/docs/usage/v3.md
website/docs/usage/visualizers.md

There are only three or four typos here, but since nightly was just released and they are mostly in the "What's new in v3.0", I thought I would get them out now.
Fixes to documentation.

A few tiny typo fixes to push through with release of nightly

---

spacy/cli/templates/quickstart_training_recommendations.yml

* Switch from `en_vectors_web_lg` to `en_core_web_lg`
* Add vectors recommendations for all core models
* Sort list
Fixes #6260.
Bug fix.

Update quickstart vectors recommendations

---

website/meta/languages.json

Add and update website license links
Docs

Add and update website license links

---

.github/contributors/walterhenry.md

Here it is!
This is the long-delayed user-contributor agreement
Added documentation

User contributor agreement

---

website/docs/usage/101/_vectors-similarity.md
website/docs/usage/visualizers.md

I think these may the last remarks for the nightly docs. Only two minor things actually.
Just two small items in the last bits of the docs.
Documentaion fixes

Proofread remarks

---

spacy/cli/evaluate.py
website/src/templates/models.js

Add detailed scores to evaluate output
* Add `morph_per_feat` and `dep_las_per_type`
* Refactor to have a more generic PRF printer in `spacy evaluate`
* Save raw scores in `spacy evaluate` output
Fixes #6266
Enhancement?

Add detailed scores to evaluate output

---

requirements.txt
setup.cfg

Add dependency for jinja2
Fixes #6261.
?

Add dependency for jinja2

---

.github/contributors/KKsharma99.md
website/meta/universe.json

Mindmeld is a conversational AI platform for deep-domain voice interfaces and chatbots. https://www.mindmeld.com/
Adding MindMeld to Spacy Universe. MindMeld is a conversional AI platform. (MindMeld includes an inbuilt automatic query annotator that levarages Spacy's NER https://www.mindmeld.com/docs/userguide/auto_annotator.html.)
Added an entry for MindMeld in universe.json.
An enhancement.

Adding MindMeld to Universe JSON

---

.github/contributors/robertsipek.md

Fill contributor agreement by robertsipek

---

website/meta/languages.json

Add Nepali to supported languages on website
Fixes #6054.
Docs

Add Nepali to supported languages on website

---

website/docs/usage/rule-based-matching.md

Fix node name typo in dependency matcher example
Docs.

Fix node name typo in dependency matcher example

---

spacy/matcher/dependencymatcher.pyx
spacy/tests/matcher/test_dependency_matcher.py

Fix `DependencyMatcher` so that the callback is called only once per match.
Bug fix.

Fix on_match callback for DependencyMatcher

---

pyproject.toml
requirements.txt
setup.cfg
setup.py
spacy/errors.py
spacy/tests/training/test_training.py
spacy/training/__init__.py
spacy/training/align.pyx
spacy/training/alignment.py
spacy/training/example.pyx

Replace pytokenizations with internal alignment algorithm that is restricted to only allow differences in whitespace and capitalization.
* Rename `spacy.training.align` to `spacy.training.alignment` to contain the `Alignment` dataclass
* Implement `get_alignments` in `spacy.training.align`
Enhancement

Replace pytokenizations with internal alignment

---

website/docs/api/annotation.md

Update TIGER link and tag description
Docs

Update TIGER link and tag description

---

azure-pipelines.yml

This is just a minor change separated from #6338 so we don't have python 3.5 test failures for now.
* Use `--prefer-binary` (`requirements.txt`) and `--binary-only :all:` (sdist)
* Delete all installed packages before testing the sdist install
Chore

CI updates for python 3.5

---

setup.cfg
spacy/lang/zh/__init__.py
website/docs/usage/index.md
website/src/widgets/quickstart-install.js

* Add `cuda110` to setup.cfg and quickstart dropdown
* Switch to `pip` for pip-only packages in conda quickstart instructions
* Update zh pkuseg install message with version range and conda
* Remove `zh` from `extras_require` because the default doesn't require additional packages
?

Setup / install / quickstart updates

---

website/meta/universe.json

Adding medspaCy to GitHub universe and also tweaking the example on cov-bsv, a previous project.
Documentation

add medspacy to universe and fix example w/ cov-bsv

---

spacy/scorer.py
website/docs/usage/layers-architectures.md

Document `score` method as part of implementing a new trainable component from scratch
docs

Document score method

---

spacy/pipeline/morphologizer.pyx
spacy/tests/pipeline/test_morphologizer.py

Fix bug where `Morphologizer.get_loss` treated misaligned annotation as `EMPTY_MORPH` rather than ignoring it. Remove unneeded default `EMPTY_MORPH` mappings.
Fixes #6350.
Bug fix.

Ignore misaligned in Morphologizer.get_loss

---

spacy/tests/doc/test_doc_api.py
spacy/tests/pipeline/test_entity_ruler.py
spacy/tokens/doc.pyx

Add `ent_id_` to strings serialized with `Doc`
Fixes #5643.
Bug fix

Add ent_id_ to strings serialized with Doc

---

website/docs/usage/training.md

Fix DocBin init in training example
Closes #6392.
Docs

Fix DocBin init in training example

---

website/meta/universe.json

Adding [spaCyTextBlob](https://github.com/SamEdwardes/spaCyTextBlob) to the spaCy universe.
Added details for [spaCyTextBlob](https://github.com/SamEdwardes/spaCyTextBlob) to `universe.json`.
Change to docs.

Added spaCyTextBlob to universe.json

---

.github/contributors/revuel.md
website/meta/universe.json

_Request to include PatternOmatic in spaCy Universe_
First of all, let me say thank you all for creating spaCy. It is wonderful.
I'd tried to follow all the instructions and requirements, just let me know if I missed anything or I did something wrong.
PatternOmatic wants to join the spaCy Universe family. It is a library that searches for linguistic patterns by using a Grammatical Evolution (Evolutionary Computation) approach. Once this patterns are found, they could be used by the spaCy's Rule Based Matcher.
- Contributor agreement of @revuel added
- unviverse.json updated to include PatternOmatic, I had tried to follow the steps stated [here](https://github.com/explosion/spaCy/blob/master/website/UNIVERSE.md)

Update universe.json (include PatternOmatic)

---

spacy/vocab.pyx

Add all vectors to the vocab before pruning to correct the selection of vectors to prioritize.
Fixes #6405.
Bug fix.

Add all vectors to vocab before pruning

---

spacy/syntax/_beam_utils.pyx
spacy/syntax/nn_parser.pyx

Beam cleanup is handled through the Beam finalization method.
?

Remove Beam cleanup

---

spacy/matcher/matcher.pyx
spacy/typedefs.pxd
spacy/vocab.pxd

Use int8_t instead of char in Matcher to fix failures on aarch64 and ppc64le.
Also remove unused char* utf8_t typedef.
Fixes #4576.
Bug fix

Use int8_t instead of char in Matcher

---

spacy/cli/train.py

Fix bug from #5768 where the tag map is clobbered if a custom tag map isn't provided.
Bug fix.

Fix tag map clobbering in spacy train

---

.travis.yml

Update Travis CI pip install steps
?

Update Travis CI pip install steps

---

.github/contributors/jabortell.md

Add jabortell to the list of contributors
Adds jabortell to the list of contributors. First pull request is #6421 
Adding my copy of the contributor's agreement to .github/contributors
-  I ran the tests, and all new and existing tests passed. N/A

Add jabortell to the contributors

---

spacy/syntax/_beam_utils.pyx

Restore cleanup_beam method
Bug fix.

Restore cleanup_beam method

---

spacy/errors.py
spacy/tokens/_serialize.py

Add a better error message if DocBin zlib decompress fails, indicating that the data is not in `DocBin` format.
Closes #6390.
Enhancement?

Add error message if DocBin zlib decompress fails

---

spacy/matcher/_schemas.py
spacy/tests/matcher/test_matcher_api.py
website/docs/usage/rule-based-matching.md

Add `SPACY` as a `Matcher` attribute
Enhancement.

Add SPACY as a Matcher attribute

---

spacy/about.py

Prepare v2.2.5

---

website/docs/usage/v3.md

* Create the examples once
* Use the examples in the initialization
* Provide the batch size
* Fix `begin_training` migration example
Docs.

Improve simple training example in v3 migration

---

licenses/3rd_party_licenses.txt
spacy/scorer.py

Move `scikit-learn` license from `Scorer` to `licenses/3rd_party_licenses.txt`.
?

Clean up 3rd party license info

---

spacy/tests/regression/test_issue5501-6000.py
spacy/tests/training/test_readers.py

- fix `test_cat_readers` that is only run with `--slow`
- extend & cleanup of `test_issue5551`
fix in test suite

Fixes in test suite

---

spacy/cli/package.py

If present, include the file `input_dir/LICENSE` at the top level of the packaged model.
Enhancement.

Support LICENSE in spacy package

---

spacy/cli/download.py

Also check for spacy-nightly in download so that `--no-deps` isn't set for normal nightly installs.
Bug fix.

Check for spacy-nightly package in download

---

examples/training/create_kb.py
examples/training/train_entity_linker.py

Just updating the "Last tested with" mention.

tested EL scripts with 2.3.4

---

azure-pipelines.yml
pyproject.toml
setup.cfg

* Add `blis` to `pyproject.toml` and `setup_requires`. (The correct requirements were in `thinc`, but not `spacy`.)
* Remove detailed `numpy` build constraints from `pyproject.toml`
* Test without `--only-binary :all:` to test this for more typical use
* Reduce number of builds in CI to speed things up
Bug fix.

Improve blis and numpy build dependencies

---

website/docs/usage/index.md

* Use `pip install` instead of `python setup.py install`
* For developers recommend:
* `python setup.py build_ext --inplace -j N`
* `python setup.py develop`
Docs.

Update source install instructions

---

spacy/training/loop.py

Make the training loop return the current `nlp` object (which includes the accuracy numbers via `nlp.meta`), plus the path the model was saved to.
This makes it easier to implement abstractions on top of the training loop, like Prodigy's train curve, which needs to collect the accuracies of multiple runs.
enhancement

Make training.loop return nlp object and path

---

spacy/pipeline/entityruler.py

Fix subsequent pipe detection to detect the position of the current object by comparing the component itself rather than from the factory name.
Bug fix.

Fix subsequent pipe detection in EntityRuler

---

azure-pipelines.yml
pyproject.toml
requirements.txt
setup.cfg

After updating the blis sdist in v0.7.4, remove python version constraints for blis build and install dependencies.
?

Remove blis python version constraints

---

spacy/errors.py
spacy/pipeline/lemmatizer.py
spacy/tests/pipeline/test_lemmatizer.py

Add a warning to the rule-based lemmatizer for any tokens without POS annotation.
Enhancement

Warn on empty POS for the rule-based lemmatizer

---

spacy/cli/templates/quickstart_training.jinja
spacy/default_config.cfg
spacy/language.py
spacy/schemas.py
website/docs/api/data-formats.md
website/docs/api/language.md

Add a default `batch_size` setting for `Language.pipe` and `Language.evaluate` as `nlp.batch_size`.
Enhancement.

Add nlp.batch_size setting

---

spacy/cli/package.py
spacy/schemas.py
website/docs/api/cli.md
website/docs/api/data-formats.md
website/docs/usage/saving-loading.md
website/docs/usage/training.md

- `spacy package` now takes an optional `--code` argument that can point to one or more files
- files will be copied into the package and imported in the `__init__.py` (all that's needed for registered functions)
- updated documentation accordingly
enhancement

Include custom code via spacy package command

---

spacy/about.py

Set version to v2.3.5

---

spacy/cli/convert.py
spacy/tests/test_cli.py
spacy/tests/training/test_training.py
spacy/training/converters/conll_ner_to_docs.py
spacy/training/converters/conllu_to_docs.py
spacy/training/converters/iob_to_docs.py
spacy/training/converters/json_to_docs.py

To reduce the memory usage when converting large corpora, refactor the
convert methods to be generator functions.
Enhancement.

Switch converters to generator functions

---

.github/contributors/thomasbird.md

Adding SCA for myself in master, will follow this up with another MR to develop.

Adding SCA

---

spacy/cli/debug_data.py

* Update token alignment check to use `Example` alignment
* Update missing vector check further related to changes in v3 and check for the vectors for the predicted tokens rather than the gold tokens
Bug fix

Fix alignment and vector checks in debug data

---

spacy/morphology.pyx

Fix lookup of empty morph in the morphology table, which fixes a memory leak where a new morphology tag was allocated each time the empty morph tag was added.
Bug fix.

Fix memory leak when adding empty morph

---

spacy/pipeline/lemmatizer.py
spacy/tests/pipeline/test_lemmatizer.py

Use `logger.warning` instead of deprecated `logger.warn`.
?

Use logger.warning instead of logger.warn

---

spacy/errors.py
spacy/tests/doc/test_doc_api.py
spacy/tokens/doc.pyx

Add a warning that user hooks are lost on serialization.
Add a `user_hooks` exclude to skip the warning with pickle.
Enhancement?

Add logger warning when serializing user hooks

---

spacy/language.py
spacy/tests/test_language.py
spacy/training/loop.py

Reset annotation in predicted docs before evaluating and store all data in `examples`.
Fixes #6323.
Bug fix

Fix memory issues in Language.evaluate

---

spacy/tests/tokenizer/test_tokenizer.py
spacy/tokenizer.pyx

Use the special cases phrase matcher for exceptions that include space characters so that exceptions including spaces are supported.
Bug fix.

Use special matcher for exceptions with spaces

---

website/docs/api/architectures.md
website/docs/usage/embeddings-transformers.md

Documentation for PR https://github.com/explosion/spaCy/pull/6451
docs

Docs for pretrain architectures

---

spacy/tokens/doc.pyx

Convert a variable `attrs` from `tuple` to `list` because it is used as list (`append` method is called)
bug fix

convert tuple to list, because the type mismatches

---

.github/contributors/cristianasp.md
spacy/lang/pt/stop_words.py

Added three aditional stopwords: "a" and "o" that means "the", and "e" that means "and".
Added 3 stopwords to portuguese stopwords set.
"a" means "the" for female subjects
"o" means "the" for male objects
"e" means "and"
an enhancement
- [ X ] I have submitted the spaCy Contributor Agreement.
- [  ] I ran the tests, and all new and existing tests passed.
- [ X ] My changes don't require a change to the documentation, or if they do, I've added all required information.

Update stop_words.py in Portuguese (a,o,e)

---

.github/contributors/alexcombessie.md
spacy/lang/fr/stop_words.py

Remove questionable French stopwords

---

website/docs/usage/layers-architectures.md
website/docs/usage/training.md

Fixing small typos in docs

---

spacy/pipeline/tagger.pyx
spacy/tests/pipeline/test_tagger.py

Use `None` for both missing and misaligned annotation in `Tagger.get_loss`, reverting to the default missing value in the loss
function.
Bug fix.

Sync missing and misaligned values in Tagger loss
