pyproject.toml, requirements.txt, setup.cfg, spacy/errors.py, spacy/tests/lang/en/test_prefix_suffix_infix.py, spacy/tests/lang/en/test_sbd.py, spacy/tests/lang/fr/test_exceptions.py, spacy/tests/lang/uk/test_tokenizer.py, spacy/tests/parser/test_ner.py, spacy/tests/parser/test_neural_parser.py, spacy/tests/parser/test_parse.py, spacy/tests/parser/test_space_attachment.py, spacy/tests/regression/test_issue1-1000.py, spacy/tests/regression/test_issue1001-1500.py, spacy/tests/regression/test_issue2001-2500.py, spacy/tests/regression/test_issue3001-3500.py, spacy/tests/regression/test_issue3501-4000.py, spacy/tests/serialize/test_serialize_vocab_strings.py, spacy/tests/test_gold.py, spacy/tests/test_tok2vec.py, spacy/tests/vocab_vectors/test_stringstore.py
- Fixed few tests (new API etc)
- Fixed empty doc test with https://github.com/explosion/thinc/pull/366
- Removed truly outdated tests (e.g. referring to removed `set_frozen` functionality)
- Added reasons to some tests not working anymore (e.g. no more look-behind puntuation regex's)
- Rewrote some tests from `xfail` to `skip` if we know they're not going to work anyway - saves the time of execution
enhancement
=> Test suite clean up

.github/contributors/lizhe2004.md, website/docs/usage/adding-languages.md
change the #101 url hash path to #language-data
the  link of  "language data 101" item in the menu does not work. it should be changed to "#language-data" because of the documentation is changed.
it is a  change to the documentation
=> fix the wrong hash url in adding-languages.md file

pyproject.toml, requirements.txt, setup.cfg, spacy/cli/project/assets.py
The `spacy project assets` command really needs to support more transport options, e.g. s3, GCS etc. It's pretty limiting to only have https.
Radim developed a nice utility for this for Gensim: https://github.com/RaRe-Technologies/smart_open . It has extensions for many formats, but by default it only depends on requests, and it's been stable for quite some time now, it's quite widely used.
Using `smart_open`, the project asset download can remove our requests logic, and we'll grow support for whatever download helpers are installed alongside `smart_open`. I've tested and this works with GCS, for instance.
=> Add smart_open dependency to fetch project assets

website/meta/universe.json
This PR affects spaCy universe:
- some details of `spacy-universal-sentence-encoder` have been fixed (URL of repository, pypi version available, code example fixed)
- a new wrapper for spacy pipelines is added: sentence-transformers. With this package, it's possible to use [sentence-transformers](https://github.com/UKPLab/sentence-transformers) within spaCy. The package uses the `user_hooks` to retrieve an external vector representation that comes from a [siamese network](https://arxiv.org/abs/1908.10084) trained on NLI and STS data, providing therefore accurate semantic similarity measures 
This PR is a change in the documentation (https://spacy.io/universe)
=> Sentence transformers added to spaCy universe

spacy/lang/en/lex_attrs.py, spacy/tests/lang/en/test_text.py
This PR adds support to identify ordinal numbers as numders. 
- A bug fix to an issue raised in https://github.com/explosion/spaCy/issues/5827
=> English: Identifies ordinal numbers as numbers

spacy/cli/__init__.py, spacy/cli/_util.py, spacy/cli/debug_data.py, spacy/cli/debug_model.py, spacy/cli/init_config.py, spacy/cli/init_model.py, spacy/cli/pretrain.py, spacy/cli/train.py, spacy/cli/validate.py, website/docs/api/cli.md, website/docs/usage/training.md, website/docs/usage/transformers.md
- add CLI subcommand `init` and move `init-model` to `init model`
- add draft for `init config` CLI that currently expects **one of** the following arguments:
- `--base`: base config to auto-fill
- `--lang`: base language to use for blank config, with optional `--pipeline`
- `--model`: base model to copy config from, with optional `--pipeline` (only keep those components and add new components if not yet in the pipeline)
This solution feels a bit unideal but I couldn't immediately come up with a better one that covers all the different scenarios.
enhancement
=> Add init CLI and init config

spacy/errors.py, spacy/gold/align.py, spacy/tests/test_gold.py
Prevent alignment when texts don't match
- case-insensitive match
Also added some `Alignment` unit tests
enhancement
=> Prevent alignment when texts don't match

spacy/gold/example.pyx, spacy/pipeline/senter.pyx, spacy/pipeline/tagger.pyx, spacy/tests/test_gold.py, spacy/tests/test_new_example.py
For `Example`, we support two kind of dictionaries. 
1.  A simple one with entries like "tags", "words", etc
2. A more complex one with a sub-level `token_annotation` which should contain fields from `attr.IDS` such as "TAG" and "ORTH".
The function`get_aligned` uses the `IDS` fields (cf format 2) and I think we should put them in uppercase always to avoid confusion ("TAG" vs "tags" vs "tag" gets confusing)  
The `example.to_dict` method should output a format that is consistent (it was now a mixture of the two), and this format should be supported by the `example.from_dict` method (which wasn't the case if e.g. the dictionary had an entry `[token_annotation][TAG]`). As format 1 is considered "legacy", I think it makes sense to have `to_dict` output results in format 2.
Working on the …
=> Example Dict format consistency

examples/experiments/onto-joint/defaults.cfg, spacy/cli/_util.py, spacy/cli/debug_data.py, spacy/cli/train.py, spacy/default_config.cfg, spacy/errors.py, spacy/language.py, spacy/schemas.py, spacy/tests/pipeline/test_pipe_factories.py, spacy/util.py
This PR adds support for adding pipeline components from other loadable models.
In code:
```python
source_nlp = spacy.load("en_core_web_sm")
nlp = spacy_blank("en")
nlp.add_pipe("parser", source=source_nlp)
```
In config:
```ini
[components.my_parser]
source = "en_core_web_sm"
component = "parser"
```
* `source`: loadable spaCy model
* `component`: optional name of component in the source pipeline, defaults to instance name in the target pipeline
This also solves the "training from a base model" problem: instead of providing a base model, the config can provide the components to source from the base model. It can also provide a list of `frozen_components` that are not updated. In this example, the final trained pipeline will contain 3 components that are updated/not updated in different …
=> Allow adding pipeline components from source model

spacy/language.py, spacy/tests/pipeline/test_pipe_methods.py
Current bug: if a pipeline would contain more than one component (let's say 3), and you `nlp.replace_pipe` the last one, you would get an `E959` error about "Can't insert component before index 2", because that last (old) component would already be removed so the pipeline is temporarily smaller. Fixed it by using  insertion with `after` for these edge cases.
bug fix
=> Bugfix in nlp.replace_pipe

spacy/__init__.py, spacy/cli/debug_data.py, spacy/cli/debug_model.py, spacy/cli/pretrain.py, spacy/cli/train.py, spacy/language.py, spacy/tests/regression/test_issue5137.py, spacy/tests/serialize/test_serialize_config.py, spacy/util.py, website/docs/api/top-level.md
Now that Thinc allows passing config overrides directly to `Config` (and merging them _before_ variable interpolation!) we can simplify the overrides across the CLI and `Language` API.
enhancement
=> Simplify config overrides in CLI and deserialization

spacy/cli/download.py, spacy/errors.py, spacy/util.py
If loading a model fails, we might as well raise a more helpful error if the loaded string is a former shortcut. Or if the user typos and writes `.load` instead of `.blank` (which is what I did).
(Wasn't sure where to put the old model shortcuts that are only used for errors and warnings and shared across modules. So I put them in `spacy.errors` for now.)
enhancement
=> Add better error for failed model shortcut loading

spacy/cli/train.py, spacy/gold/example.pyx, spacy/lang/ja/__init__.py, spacy/lang/ko/__init__.py, spacy/lang/ru/lemmatizer.py, spacy/lang/th/__init__.py, spacy/lang/uk/lemmatizer.py, spacy/lang/vi/__init__.py, spacy/lang/zh/__init__.py, spacy/language.py, spacy/matcher/matcher.pyx, spacy/pipeline/attributeruler.py, spacy/pipeline/entity_linker.py, spacy/pipeline/morphologizer.pyx, spacy/pipeline/multitask.pyx, spacy/pipeline/pipe.pyx, spacy/pipeline/senter.pyx, spacy/pipeline/tagger.pyx, spacy/pipeline/textcat.py, spacy/pipeline/transition_parser.pyx, spacy/tokens/doc.pyx, spacy/util.py
Some background on `raise` with `from`: https://stackoverflow.com/a/24752607/6400719
This is mostly relevant for cases where we re-raise exceptions during exception handling. I think our general guidelines should be:
* `raise ... from None`: the exception we're handling isn't relevant to the custom error. Examples of this include: internal `pydantic` validation error we're using to provide custom config validation messages, third-party import error we're catching to provide a more descriptive message etc.
* `raise ... from original_exception`: related third-party exception that means whatever we're doing has to fail as well. The traceback will then read "The above exception was the direct cause of the following exception:".
(Not directly related, but I noticed this while going through all …
=> Use "raise ... from" in custom errors for better tracebacks

spacy/scorer.py, spacy/tests/pipeline/test_textcat.py
I'm not 100% sure this is correct, but I think the micro-F scoring should be applicable regardless of whether there are multiple classes and regardless of whether the labels are mutually exclusive. I think the same is true for some of the other measures?
If so, we should just dump all those scores into the scores dict.
=> Be less choosy about reporting textcat scores

spacy/gold/corpus.py, spacy/tests/test_gold.py, spacy/tokens/_serialize.py, website/docs/api/data-formats.md, website/docs/api/docbin.md
This PR adds the convenience methods `to_disk` and `from_disk` to the `DocBin`. Also changed some internals to call into this method instead, and used it in the roundtrip serialization tests so we're testing both the bytes and disk workflows.
enhancement
=> Add DocBin to/from_disk methods and update docs

pyproject.toml, requirements.txt, setup.cfg, spacy/pipeline/attributeruler.py, spacy/pipeline/entityruler.py, website/docs/api/attributeruler.md, website/docs/api/entityruler.md
=> Update to latest Thinc, use validate arg name, update attribute ruler

spacy/__init__.py, spacy/cli/evaluate.py, spacy/cli/train.py, spacy/errors.py, spacy/gold/corpus.py, spacy/pipeline/tok2vec.py, spacy/pipeline/transition_parser.pyx, spacy/tests/parser/test_ner.py, spacy/tests/regression/test_issue2001-2500.py, spacy/tests/regression/test_issue2501-3000.py, spacy/tests/regression/test_issue3001-3500.py, spacy/tests/regression/test_issue3501-4000.py, spacy/tests/regression/test_issue4001-4500.py, spacy/tests/regression/test_issue4501-5000.py, spacy/tests/regression/test_issue5152.py, spacy/tests/test_gold.py, spacy/tests/test_new_example.py, spacy/util.py
This PR includes various small fixes to warnings and logging, and some other small things I came across along the way.
bug fix, enhancement
=> Replace verbose warnings with logging, tidy up, small fixes

spacy/cli/debug_model.py, spacy/cli/init_config.py, spacy/cli/pretrain.py, spacy/cli/train.py, spacy/default_config.cfg, spacy/default_config_pretraining.cfg, spacy/language.py, spacy/schemas.py, spacy/tests/serialize/test_serialize_config.py
* The `[pretraining]` block now doesn't default to `null` anymore, which would cause Thinc to (correctly) raise an error because it's a top-level key that's not a section.
* Make `[pretraining]` default to `{}` (empty block) and adjust checks accordingly.
* Read `training.seed` in `debug-model`, not `pretraining.seed` (possibly copy-paste mistake?)
bug fix
=> Fix handling of optional [pretraining] block

pyproject.toml, requirements.txt, setup.cfg, spacy/cli/init_config.py, spacy/tests/serialize/test_serialize_config.py
This PR mostly updates Thinc and adds a test. The `init fill-config` command will now correctly remove extra keys (if the schema doesn't allow them).
enhancement
=> Support removing extra values in fill-config

spacy/tests/test_cli.py
[This edit](https://github.com/explosion/spaCy/commit/d1780db6a4b94669d9400af403bb6d5997aa5bd5) caused a test failure, fixing here. As the error type is now different for the different options, I split it into two different tests for clarity?
bug fix
=> update error type

spacy/language.py, spacy/tests/serialize/test_serialize_config.py
`Language.from_bytes` and `Language.from_disk` didn't correctly set `interpolate=False` when loading the config back from bytes/disk. This caused variables to be replaced, so the loaded config didn't match the original config and variable references were destroyed.
bug fix
=> Don't interpolate config on Language deserialization

spacy/errors.py, spacy/language.py, spacy/tests/pipeline/test_pipe_factories.py, spacy/util.py
This is especially relevant for environments where spaCy is live-reloaded (notebooks, Streamlit). The `@Language.factory` and `@Language.component` decorators should be allowed to re-run with the same function. This is a bit trickier for `@Language.component` where the decorator itself creates the factory function (and once that's done, it's harder to check whether the original stateless callable is the one we're using in the created factory).
(We can probably solve the `is_same_func` check more elegantly?)
=> Allow component decorators to re-run with same function

spacy/cli/templates/quickstart_training.jinja, spacy/pipeline/pipe.pyx, spacy/pipeline/tok2vec.py, spacy/tests/test_tok2vec.py, website/docs/api/architectures.md, website/docs/usage/embeddings-transformers.md, website/docs/usage/v3.md
Follow-up on https://github.com/explosion/spacy-transformers/pull/212, renaming Transformer listener.
=> Rename Transformer listener

spacy/errors.py, spacy/matcher/matcher.pyx, spacy/matcher/phrasematcher.pyx, spacy/tests/matcher/test_matcher_api.py, spacy/tests/matcher/test_phrase_matcher.py, website/docs/api/matcher.md, website/docs/api/phrasematcher.md, website/docs/usage/rule-based-matching.md, website/docs/usage/v3.md
Pretty basic, but it works? `Matcher._call__` and `PhraseMatcher.__call__` now both support an `as_spans` flag that returns a list of span objects, using the `match_id` as the span label.
This PR also deprecates `Matcher.pipe` and `PhraseMatcher.pipe`, which have always been pretty useless and misleading.
enhancement
=> Add as_spans to Matcher/PhraseMatcher and deprecate .pipe

spacy/language.py, spacy/strings.pxd, spacy/strings.pyx
A long time ago we went to some trouble to try to clean up "unused"
strings, to avoid the `StringStore` growing in long-running processes.
This never really worked reliably, and I think it was a really wrong
approach. It's much better to let the user reload the `nlp` object as
necessary, now that the string encoding is stable (in v1, the string IDs
were sequential integers, making reloading the NLP object really
annoying.)
The extra book-keeping does make some performance difference, and the
feature is unsed, so it's past time we killed it.
=> Remove 'cleanup' of strings

spacy/cli/_util.py, spacy/cli/project/clone.py
- Rewrite `https` repo to `git` protocol
- Don't use `stdin` but pass arguments directly (seems less error prone?)
- I think the final `checkout` command needs a branch? So let's assume `master` by default?
- Few UX updates
bug fix
=> Fix sparse checkout for 'spacy project'

spacy/tests/regression/test_issue5918.py, spacy/tokens/_retokenize.pyx
Fixes #5918
A bug in the `merge_entities` function resulted in entities being merged with eachother (instead of just their tokens merged into one token). This happened because after the lines
```
token = &doc.c[start]
token.ent_iob = doc.c[span.root.i].ent_iob
```
the code was still referring to `doc.c[start].ent_iob` as the "start token's IOB", but this information was already replaced by the information from the span's root. To prevent the error with minimal changes to the code, we can just store the old IOB & type values for the later comparison.
bug fix
=> Bugfix in merge_entities

spacy/pipeline/_parser_internals/_state.pxd, spacy/pipeline/_parser_internals/stateclass.pyx, spacy/pipeline/transition_parser.pyx
The parser training makes use of a trick for long documents, where we
use the oracle to cut up the document into sections, so that we can have
batch items in the middle of a document. For instance, if we have one
document of 600 words, we might make 6 states, starting at words 0, 100,
200, 300, 400 and 500.
The problem is for v3, I screwed this up and didn't stop parsing! So
instead of a batch of `[100, 100, 100, 100, 100, 100]`, we'd have a batch
of `[600, 500, 400, 300, 200, 100]`. Oops.
The implementation here could probably be improved, it's annoying to
have this extra variable in the state. But this'll do.
This makes the v3 parser training 5-10 times faster, depending on document
lengths. This problem wasn't in v2.
=> Fix significant performance bug in parser training

spacy/tests/pipeline/test_tagger.py, spacy/tests/pipeline/test_textcat.py
The textcat overfitting test called `textcat.model.attrs["multi_label"] = False`, which doesn't actually change the underlying model. When defining this in the config before construction, this test actually converts much faster and should hopefully not be "flaky" anymore. 
bug fix
=> Fix overfitting test

spacy/cli/train.py
Bugfix for #6014 
Index `i` starts from **0** and iterations in column `Itn` are numbered from **1**, so `iter_current = i + 1` was added to adjust the numbering.
=> Fix off-by-one error for best iteration calculation (closes #6014)

spacy/cli/_util.py, spacy/util.py
I'm not sure whether this will be the long-term plan, but I need a quick way to extend the CLI from an external package, in order to keep developing the `spacy-ray` integration.
What I've done is added a dummy registry called "cli", that just serves as a way to import modules that are trying to hook into the CLI. Within those modules, they'll be importing spaCy's CLI `app` object to extend it.
@ines is it okay to merge this until a better solution is developed, probably within typer?
=> Add quick hack to allow CLI extensions

website/docs/api/cli.md
Small addition to the `pretrain` documentation (https://spacy.io/api/cli#pretrain) to explain how one should pick the pretrained weights files for further training.
Closes issue #6027 
=> Clarify how to choose pretrained weights files (closes #6027)

setup.cfg
Just released a new dev version for the `spacy-lookups-data` package exposing the simpler entry points used in v3. Not sure if we need to specify this anywhere else (internally etc.)? This is mostly relevant for the lexeme tables, which are otherwise not available (because they were previously exposed via the `lookups_extra`).
dependencies?
=> Update to latest spacy-lookups-data

spacy/cli/_util.py, spacy/cli/project/assets.py
3 small bugfixes to projects: 
1. the git URL can have a trailing slash which needs to be removed in `_from_http_to_git`
2. `shutil.rmtree(dest)` doesn't work if `dest` is a file
3. If you clone from your main projects dir `C:\projects`, the message says something like
```
To fetch the assets, run:
python -m spacy project assets C:\projects\tutorials\ner_fashion_brands
``` 
but if you run that exact command, it wouldn't work because the assets are fetching relatively to the (expected) working dir. So prefixing that to always work with a full path. Hope that doesn't break anything in relation to PR #6048.
bug fix
=> project bug fixes

spacy/language.py
The `score_weights` in the training's config was getting overwritten bij the `Language` class. Suppose your config would have 
```
[training.score_weights]
cats_macro_p = 0.0 
cats_macro_r = 0.0
cats_macro_f = 1.0
```
then this would get overwritten (due to the defaults) by `cats_score = 1.0`, and the console logger would only show the `cat_score` instead of the scores from the config.
I think adding this conditional is sufficient?
bug fix
=> prevent overwriting score_weights

spacy/cli/_util.py, spacy/cli/debug_model.py, spacy/cli/init_config.py, spacy/tests/test_cli.py
The `pipeline` argument for `init config` should be a comma-seperated list like `-p "tagger, textcat"`. However, I think it is likely for people to try to write `-p "[textcat]"` (as in the config). So we may as well support this, because it gives an ugly error downstream otherwise. With this edit, we even support people writing something like `-p "["tagger", "textcat"]"`
enhancement
=> Support "list" pipeline argument

spacy/errors.py, spacy/tests/doc/test_morphanalysis.py, spacy/tokens/token.pyx
Modify `Token.morph` property so that `Token.c.morph` can be reset back
to an internal value of `0`. Allow setting `Token.morph` from a hash as
long as the morph string is already in the `StringStore`, setting it
indirectly through `Token.morph_` so that the value is added to the
morphology. If the hash is not in the `StringStore`, raise an error.
Enhancement
=> Modify Token.morph to enable unsetting

spacy/pipeline/textcat.py, spacy/tests/serialize/test_serialize_pipeline.py, website/docs/api/textcategorizer.md
Hook up the scorer's threshold to textcat's config, to see custom accuracy scores when training:
```
[components.textcat]
factory = "textcat"
threshold = 0.2
```
enhancement
=> define threshold for scoring textcat in TextCat config

spacy/training/loggers.py
Fix W&B logger when called multiple times from same script, cf docs [here](https://docs.wandb.com/library/init#how-do-i-launch-multiple-runs-from-one-script).
bug fix
=> fix W&B logger

spacy/tests/test_language.py
The new `test_language_init_invalid_vocab` fails for me locally (in Pycharm) as `str(e)` would be `<ExceptionInfo ValueError tblen=2>` instead of the expected string `"ValueError: [E918] Received invalid value for vocab..."`.
Rewriting it to explicitely check `e.value`, which is the original `ValueError`.
I have no clue why this fails locally and not on the CI, but I think this fix should be universal.
bug fix
=> Fix unit test with ExceptionInfo

spacy/about.py, spacy/scorer.py
A single document with reference annotations won't always have annotations for every component in the pipeline. For instance, you might have a senter or a parser in the pipeline, but the reference doc only has NER annotations. Or you might have a document that only has reference categories, but the pipeline includes a tagger.
Currently the `Language.evaluate()` method will fail in these situations, because it will attempt to evaluate every component in the pipeline. The scorer will then raise an error when it tries to access the missing value from the reference doc.
The temporary hack here is a `try/except`. It's not the right solution, but we need it to move forward with the nightly.
=> Temporary work-around for scoring a subset of components

spacy/cli/train.py, spacy/default_config.cfg, spacy/language.py, spacy/schemas.py, spacy/tests/test_util.py, spacy/util.py, spacy/vocab.pxd, spacy/vocab.pyx
Similar to how vectors are handled, move the vocab lookups to be loaded at the start of training rather than when the vocab is initialized, since the vocab doesn't have access to the full config when it's created.
The option moves from `nlp.load_vocab_data` to `training.lookups`.
Typically these tables will come from `spacy-lookups-data`, but any `Lookups` object can be provided.
The loading from `spacy-lookups-data` is now strict, so configs for each language should specify the exact tables required. This also makes it easier to control whether the larger clusters and probs tables are included.
To load `lexeme_norm` from `spacy-lookups-data`:
```
[training.lookups]
@misc = "spacy.LookupsDataLoader.v1"
lang = ${nlp.lang}
tables = ["lexeme_norm"]
```
?
=> Load vocab lookups tables at beginning of training

spacy/cli/_util.py, spacy/cli/package.py, spacy/cli/project/run.py, spacy/util.py
The `run_command` utility now supports two modes:
* `capture=True`: The stdout and stderr and collected into a single string, and not printed. If an error occurs, a `subprocess.SubprocessError` is raised with a traceback message that includes the full output and the returncode. This mode may lead to the Python program exiting with a different returncode from the child.
* `capture=False`: The stdout and stderr are not redirected, and if an error occurs, sys.exit is called with the return code. This mode loses the Python traceback.
The `capture=False` mode is used when we're turning over execution to an arbitrary command, and don't want to use its output and we can exit when the subprocess exits. The `capture=True` mode is used when we want to call the subprocess like a function.
I've also …
=> Improve subprocess handling and git clone

spacy/cli/_util.py, spacy/tests/test_cli.py
- Env variables take precedence over CLI overrides (and values defined in the config).
- Allows overriding config from the `project` CLI.
- Will hopefully make it easier for us to set up automated CI tests for the project templates because we can force-override the number of epochs/steps and actually train.
The `SPACY_CONFIG_OVERRIDES` env variable can be set to a string and currently support the same format as the CLI, e.g.: `SPACY_CONFIG_OVERRIDES="--training.batch_size 128 --paths.train=/some_path"`. This way, we can re-use a lot of the parsing logic we already have (and you'll be able to easily copy-paste your overrides around without having to modify them).
enhancement
=> Allow config overrides from environment variables

spacy/cli/debug_config.py, spacy/tests/test_cli.py
Add logic to `debug config` to check that certain sections we know contain references to other config sections are valid and exist. Unfortunately, we have to kinda hard-code this and can't do it as part of the regular config validation process, since it needs to run on the resolved config, in case users have a `[corpora]` function that returns a dict etc.
But I made sure to set up the function and logic so it's easily extensible in the future.
enhancement, ux
=> Validate section refs in debug config

spacy/pipeline/tok2vec.py, spacy/tests/pipeline/test_tok2vec.py
The `Tok2VecListener` shouldn't receive a `None` callback - this can result in an error when `chain` [goes through](https://github.com/explosion/thinc/blob/master/thinc/layers/chain.py#L60) its reversed callbacks  ("`'NoneType' object is not callable`").
bug fix
=> avoid None callback

spacy/lang/de/syntax_iterators.py
Add a similar fix as in #5470 to prevent the German noun chunks iterator from producing overlapping spans.
Fixes #6073.
Bugfix.
=> Fix overlapping German noun chunks

spacy/cli/_util.py, spacy/cli/convert.py, spacy/errors.py, spacy/tests/regression/test_issue4001-4500.py, spacy/tests/regression/test_issue4501-5000.py, spacy/tests/test_cli.py, spacy/tests/test_scorer.py, spacy/tests/training/test_training.py, spacy/training/__init__.py, spacy/training/converters/__init__.py, spacy/training/converters/conll_ner_to_docs.py, spacy/training/converters/conllu_to_docs.py, spacy/training/converters/iob_to_docs.py, spacy/training/converters/json_to_docs.py, spacy/training/example.pyx, spacy/training/gold_io.pyx, spacy/training/iob_utils.py, website/docs/api/data-formats.md, website/docs/api/top-level.md, website/docs/usage/processing-pipelines.md, website/docs/usage/v3.md
Rename convertor functions so they're all standardized to `in_to_out`.
- `_from_http_to_git` --> `_http_to_git`
Previously `in2out`:
- `annotations2doc` -> `annotations_to_doc`
- `iob2docs`  -> `iob_to_docs`
- `conll_ner2docs`  ->  `conll_ner_to_docs`
- `json2docs`  ->  `json_to_docs`
- `conllu2docs`  -> `conllu_to_docs`
Previously `out_from_in`:
- `biluo_tags_from_offsets` --> `offsets_to_biluo_tags` 
- `spans_from_biluo_tags` --> `biluo_tags_to_spans` 
- `offsets_from_biluo_tags` --> `biluo_tags_to_offsets` 
- `biluo_tags_from_doc` --> `doc_to_biluo_tags`
- `doc_from_conllu_sentence` --> `conllu_sentence_to_doc`
renaming
=> consistent convertor names

spacy/cli/init_config.py, spacy/cli/templates/quickstart_training.jinja
- add `textcat` component: `TextCatEnsemble` if optimizing for accuracy, `TextCatBOW` otherwise.
- add `entity_linker` component so it can share the `Transformer` / `Tok2Vec` layer with the NEL
- didn't add the Morphologizer & senter because I'm not sure it makes sense for them to share the `tok2vec`: the Morphologizer uses a `CharacterEmbed` by default and the `senter` a `tok2vec` layer with a much smaller width. We could add them here with those defaults as such, but it wouldn't make a difference (they can get added through their default factories anyway)
enhancement
=> extend quickstart components

spacy/cli/train.py, spacy/training/loggers.py
By default, the logger would try to log all pipe names, even if they were marked as "frozen". That would result in a downstream error because the training process wouldn't have the loss of those non-trained components. Fixing that here.
bug fix
=> avoid logging performance of frozen components

spacy/cli/project/pull.py
`spacy project pull` was simply going through the commands in the order they're defined in the file, which means if you put an earlier-running command lower down, your pulls wouldn't work. In short examples it feels natural that of course, the earlier thing is earlier in the file. But when you add stuff over time, or have a template, you can easily just not have them in order. This already bit me when training the models, so I figured I'd better fix it.
The "fancy" approach to this sort of thing is to define the input/output dependencies as a graph, and then do a topological sort. I'm using a while loop because it gets the same result and the code is much clearer (imo). What I'm doing would even work if we wanted to download the things in parallel...In that case we would just use a thread …
=> Make project pull order insensitive

spacy/scorer.py, spacy/tests/pipeline/test_textcat.py
There was a typo bug in the calculation of the micro PRF for textcat, using `=` instead of `+=` when iterating through the labels.
bug fix
=> fix micro PRF for textcat

spacy/errors.py, spacy/kb.pyx, spacy/pipeline/entity_linker.py, spacy/scorer.py, spacy/tests/pipeline/test_entity_linker.py, spacy/tests/training/test_new_example.py, website/docs/api/entitylinker.md, website/docs/api/scorer.md
Updates & bug fixes to NEL functionality:
- `entity_linker.update` now relies on gold sentences and entities, to allow training an NEL in isolation
- implemented scoring for NEL that works together with the train CLI
- write KB to directory instead of file, and include `strings.json` that will be added to the new `vocab` when the KB is loaded back in. 
bug fix & enhancement
=> updates to NEL functionality

spacy/training/example.pxd, spacy/training/example.pyx
The `Example.alignment` property has grown an extra check to make sure the cached alignment is still valid. However, this check means that using the `alignment` property in a loop is now problematic.
I've added a preliminary check that hashes the `TokenC` contents. There shouldn't be a way this check could match falsely, but it could fail to match at times when the alignment hasn't changed. We therefore fall back to the text check, and update the hashes if necessary.
=> Make a pre-check to speed up alignment cache

spacy/pipeline/ner.pyx, spacy/scorer.py
In our OntoNotes evaluation, we're working off documents that have some sentences that don't have NER annotations, because we've merged the annotations from the parse and name sections of the corpus onto one doc, so that we can train them together. The missing annotations are tricky to deal with during scoring.
Previously we were skipping documents that had missing data for the NER. This is fine when comparing spaCy models to other spaCy models, as they're all running over the same test set, but it means our test was slightly different from what other people were running, which makes it a bit harder to directly compare against other people's OntoNotes numbers. Our comparison is already a bit indirect anyway, because we do the task "whole document" without the sentence boundaries. But …
=> Fix skipped documents in entity scorer

pyproject.toml, requirements.txt, setup.cfg, spacy/cli/_util.py, spacy/cli/debug_config.py, spacy/cli/train.py, spacy/tests/lang/zh/test_tokenizer.py, spacy/tests/pipeline/test_pipe_factories.py, spacy/tests/serialize/test_serialize_config.py, spacy/tests/test_cli.py
- update to latest Thinc
- clean up CLI config validation formatting helper and use new `ConfigValidationError`
- add custom validation error if loading vectors package fails due to conifg
enhancement, ux, cli
=> Improve CLI config validation with latest Thinc 

spacy/cli/train.py
I noticed that our trained models ended up with interpolated configs and duplicated values. That's because we interpolate the config before training so we can access all values directly (e.g. `config["training"]["seed"]`, even if it's a variable referring to the `[system]` block). This is fine, but we shouldn't use that config to create the `nlp` object. Instead, we can keep a separate non-interpolated version.
bug fix
=> Construct nlp from uninterpolated config before training

pyproject.toml, requirements.txt, setup.cfg, spacy/cli/debug_config.py, spacy/cli/debug_data.py, spacy/cli/debug_model.py, spacy/cli/init_config.py, spacy/cli/pretrain.py, spacy/cli/train.py, spacy/language.py, spacy/schemas.py, spacy/tests/doc/test_add_entities.py, spacy/tests/parser/test_add_label.py, spacy/tests/parser/test_arc_eager_oracle.py, spacy/tests/parser/test_neural_parser.py, spacy/tests/parser/test_preset_sbd.py, spacy/tests/pipeline/test_tok2vec.py, spacy/tests/regression/test_issue3001-3500.py, spacy/tests/regression/test_issue3501-4000.py, spacy/tests/serialize/test_serialize_config.py, spacy/tests/serialize/test_serialize_pipeline.py, spacy/tests/test_misc.py, spacy/tests/test_util.py, spacy/tests/training/test_readers.py, spacy/util.py
~WIP because it needs another small update to Thinc (see explosion/thinc#400).~
- support filling configs without resolving them (e.g. to auto-fill in `Language.from_config` without actually loading functions in the `[training]` or `[corpus]` blocks or requiring that any functions referenced there exist)
- add `resolve_training_config` helper to explicitly resolve trainin (non-runtime-relevant) blocks
- remove `nlp.resolved` hack in `Language.from_config` and only return `nlp` object from `load_model_from_config`
enhancement
=> Update config resolution to use new Thinc 

spacy/cli/templates/quickstart_training.jinja, spacy/default_config.cfg, spacy/tests/training/test_training.py, spacy/training/__init__.py, spacy/training/augment.py, spacy/training/corpus.py, spacy/util.py, website/docs/api/corpus.md, website/docs/usage/training.md
Allow an optional `augmenter` argument on the Corpus class, which can be built from the registry. A data augmenter is a callable that takes the `nlp` object and an `Example`, and yields zero or more `Example` objects, which may be copies or the original.
I've stubbed out a TODO section of the training docs as well, I think we're missing a bit about how to work with data? It would cover stuff like conversion, batching and the data augmentation.
=> Support data augmentation in Corpus

requirements.txt, setup.cfg
Need to have `pydantic>=1.5` to use `field.default_factory` in Thinc
cf https://pydantic-docs.helpmanual.io/changelog/#v15-2020-04-18
fix
=> upgrade pydantic pin

spacy/cli/templates/quickstart_training.jinja, spacy/cli/train.py, spacy/default_config.cfg, spacy/errors.py, spacy/tests/serialize/test_serialize_config.py, spacy/training/corpus.py
Corpus paths no longer default to `""` (which would resolve to the current working directory and cause the training to hang). Instead, they are `None` and the function will raise an error when it's loaded with a `None` path (which only happens when the config is actually resolved, not when it's filled or validated).
Also just building a new Thinc that will improve the error message around registered functions raising errors (and actually show the function string name).
fix / enhancement
=> Make corpus paths default to None and improve errors

spacy/cli/debug_data.py
Fixed an issue whereby a tagmap is replaced by an empty mapping if a custom tagmap is not provided. See #6129 
Bug fix
=> reorder so tagmap is replaced only if a custom file is provided.

spacy/errors.py, spacy/lang/da/__init__.py, spacy/lang/de/__init__.py, spacy/lang/el/__init__.py, spacy/lang/en/__init__.py, spacy/lang/id/__init__.py, spacy/lang/ja/__init__.py, spacy/lang/ko/__init__.py, spacy/lang/lb/__init__.py, spacy/lang/pt/__init__.py, spacy/lang/ru/__init__.py, spacy/lang/sr/__init__.py, spacy/lang/ta/__init__.py, spacy/lang/th/__init__.py, spacy/lang/vi/__init__.py, spacy/lang/zh/__init__.py, spacy/tests/conftest.py, spacy/tests/lang/zh/test_serialize.py, spacy/tests/parser/test_ner.py
Just a quick experiment to test the `[initialize]` block with a tokenizer that depends on data. Could probably be more elegant but I think conceptually, it works well?
Also included an `[initialize.lookups]` block as default for all languages we have lexeme normalization for. This will only run during `nlp.initialize` (e.g. if the user exports a config and wants to train from it) and if the package is not installed, they will see an error. Users can always choose to remove the data but by default, they get the best possible configuration (and won't have to know that they need to add this slightly obscure block for better performance).
enhancement
=> Update [initialize] block in languages

pyproject.toml, requirements.txt, setup.cfg, spacy/default_config_pretraining.cfg, spacy/errors.py, spacy/tests/training/test_training.py, spacy/training/augment.py, spacy/training/corpus.py, spacy/util.py, website/docs/api/corpus.md, website/docs/api/data-formats.md, website/docs/api/top-level.md, website/docs/usage/embeddings-transformers.md, website/meta/type-annotations.json
- Integrate and document file reader functions exposed by `srsly`.
- Rename `JsonlReader` corpus class to `JsonlCorpus`
- Consume orth variants for data augmentation from a JSON file and validate the result with a schema.
Relevant files for orth variants (we can just download them in the `assets` block of the project when we train the models):
- [`en_orth_variants.json`](https://github.com/explosion/spacy-lookups-data/blob/master/spacy_lookups_data/data/en_orth_variants.json)
- [`de_orth_variants.json`](https://github.com/explosion/spacy-lookups-data/blob/master/spacy_lookups_data/data/de_orth_variants.json)
enhancement
=> Integrate file readers via srsly, update orth_variants loading

.github/contributors/Stannislav.md, spacy/language.py
The `texts` argument in `Language.pipe` should be `iterable`, not `iterator`.
A `list` is an `iterable`, but not an `iterator`.
- Iterable: defines `__iter__()`, returns an iterator
- Iterator: defines `__next__()`, defines `__iter()` that returns `self`.
Not all iterables are iterators. Therefore such iterables should not be passed to `Language.pipe` via the
`texts` parameter according to the docstring. One example of such iterable that is not an iterator is a list.
Therefore not even lists should be passed to `Language.pipe`, which seems wrong.
Wrong argument type in docstring.
=> Change type of texts argument in pipe to iterable

spacy/errors.py, spacy/language.py, spacy/pipeline/pipe.pyx
We currently provide bwd-compatibility in case users call the old `nlp.begin_training()` instead of the new `nlp.initialize()`. But there would also be a problem if a user has a custom component that extends `Pipe` and implements `begin_training`: because of the "dummy" implementation in `Pipe.initialize`, the user's `begin_training` would silently be ignored as `Pipe.initialize` would be called, causing potentially weird problems downstream when it looks like the component is initialized, but in practice it's not. 
I'm not particularly fond of the solution proposed in this PR, and I wouldn't necessarily keep it in the codebase very long, but I think we need something especially right after the launch of v3, to warn users that they should rename this function name in their custom …
=> compat warning for pipe.begin_training

spacy/pipeline/attributeruler.py, spacy/tests/pipeline/test_attributeruler.py, website/docs/api/attributeruler.md, website/docs/usage/linguistic-features.md, website/docs/usage/v3.md
- Remove data resources from component factory.
- Add `AttributeRuler.initialize` that can load from patterns, tag map or morph rules and support `[initialize.components.attribute_ruler]` block to load from JSON data etc.
- Update tests and docs
enhancement
=> Update attribute ruler initialization

spacy/language.py, spacy/tests/pipeline/test_pipe_methods.py
- Remove component block from `[initialize.components]` if pipe is removed, rename key if pipe is renamed.
- Accept if component init config is pre-defined and accept components without init config (obviously)
bug fix
=> Adjust [initialize.components] on Language.remove_pipe and Language.rename_pipe

spacy/lang/tr/lex_attrs.py, spacy/tests/lang/tr/test_text.py
Minor addition to `is_num`  lexical attributes, I added ordinal words and ordinal endings. 
- Minor addition to `lex_attrs`
- corresponding unittest
- doc not needed, minor change.
=> Ordinal numbers for Turkish

spacy/_ml.py, spacy/ml/_legacy_tok2vec.py, spacy/ml/tok2vec.py, spacy/tests/regression/test_issue6177.py, spacy/tests/regression/test_issue_6177.py
Fixes #6177 
Training results could differ between runs, even with a fixed random seed, as the  `HashEmbed` layer could be getting a different seed/key. Fixing them resolves this issue.
This is a backport of https://github.com/explosion/spaCy/pull/5735 and intended as quick bugfix for the next 2.x release.
bug fix
=> Reproducibility for TextCat and Tok2Vec

spacy/cli/train.py
Fixes #6140
Bugfix for v2, ensuring that (disabled) pipeline components from a base model are added back to the `meta.json` after training.
bug fix
=> Fix serialization of disabled 'base' components

spacy/pipeline/attributeruler.py, spacy/pipeline/entityruler.py, spacy/tests/pipeline/test_attributeruler.py, spacy/tests/pipeline/test_entity_ruler.py
Just like the model weights, `initialize` should also reset rule-based components and start with a blank component that's then initialized with the data. Otherwise, you can end up with pretty confusing results.
fix
=> Clear rule-based components on initialize

spacy/language.py, spacy/pipeline/entity_linker.py, spacy/tests/pipeline/test_entity_linker.py, spacy/tests/regression/test_issue5230.py, spacy/tests/serialize/test_serialize_kb.py, website/docs/api/language.md, website/docs/usage/saving-loading.md, website/docs/usage/v3.md
[EDIT] : removed the `init_config` thing again after discussion (see below), but kept the `kb_loader` as an argument of `entity_linker.initialize`
The `nlp` methods `rename_pipe` and `remove_pipe` currently already take care of syncing `nlp._config["initialize"]["components"]`, but I think we also need a setting in `add_pipe` and `create_pipe`. Proposal to define an additional argument `init_config` (the naming is very unfortunate... ideas?) 
This allows us to have the `kb_loader` argument on `entity_linker.initialize` instead of in the constructor. This makes reading a KB from a file path cleaner as it only happens during initialization and not at run-time.
```
config = {"incl_prior": False}
init_config = {"kb_loader": {"@misc": "spacy.KBFromFile.v1", "kb_path": "my_kb"}}
entity_linker = …
```
=> kb_loader in NEL's initialize method

spacy/tests/doc/test_to_json.py, spacy/tokens/doc.pyx
The method is mostly internals at the moment (I think because we weren't sure whether we wanted it like this?) but I've been using it in the Streamlit integration. This fixes the integration of `Token.morph`.
bug fix
=> Fix morph in Doc.to_json

spacy/errors.py, spacy/language.py, spacy/tests/pipeline/test_pipe_methods.py, spacy/training/loop.py
If you had a pipeline with the tagger disabled, and you would run the context manager `with nlp.select_pipes` to disable the tagger (again), the tagger would actually be enabled when the context manager exists. This is fixed by ensuring that `DisabledPipes` only gets pipes that are currently enabled.
This actually came up when your config would define a component both as "disabled" as well as "frozen". Temporarily disabling it as "frozen" would actually result it being enabled again for evaluation etc. 
Cf also new unit test.
Also added a UX warning about non-initialized frozen components, inspired by Issue #6226.
bug fix
=> Bugfix in disabled context manager

spacy/about.py, spacy/errors.py, spacy/kb.pxd, spacy/kb.pyx, spacy/pipeline/attributeruler.py, spacy/pipeline/entity_linker.py, spacy/pipeline/lemmatizer.py, spacy/pipeline/morphologizer.pyx, spacy/pipeline/senter.pyx, spacy/pipeline/tagger.pyx, spacy/pipeline/textcat.py, spacy/pipeline/tok2vec.py, spacy/pipeline/trainable_pipe.pxd, spacy/pipeline/trainable_pipe.pyx, spacy/pipeline/transition_parser.pyx, spacy/tests/pipeline/test_entity_linker.py, spacy/tests/pipeline/test_morphologizer.py, spacy/tests/pipeline/test_senter.py, spacy/tests/pipeline/test_tagger.py, spacy/tests/pipeline/test_textcat.py, spacy/tests/regression/test_issue5230.py, spacy/tests/serialize/test_serialize_pipeline.py, spacy/util.py
Revert the `added_strings` change in the trainable pipes.
Also added some error handling in the serialization methods: it's important to note that when we subclass `TrainablePipe` and the subclass doesn't implement a `self.model`, `self.vocab` or `self.cfg`, those will **default to `None`** (probably because they're declared in the `.pxd` and it's a Cython class?). So we need to perform some extra validation to show more useful errors by default.
?
=> Revert added_strings change

spacy/pipeline/trainable_pipe.pyx, spacy/tests/pipeline/test_entity_linker.py
Just adding a unit test to ensure that serializing a KB from file, merges the KB's strings with those of the `nlp` object. 
adding unit test
=> Add test for vocab after serializing KB

spacy/about.py, spacy/ml/staticvectors.py
Avoid applying the dropout at runtime.
I'll add more unit tests in Thinc & spaCy in a follow-up PR, but this version (3.0.0a41) could already be used to restart the model training, if we want (otherwise we also have to build a new thinc etc)
bug fix
=> Avoid dropout at runtime

.github/contributors/jmargeta.md, spacy/schemas.py, spacy/tests/regression/test_issue6258.py
This fixes the non-emptiness check of the field  "pattern" in TokenPatternSchema
This fixes issue #6258 with a simple replacement of minItems by min_items as described in Pydantic's docs:
https://pydantic-docs.helpmanual.io/usage/schema/
This is a minor fix in one of TokenPatternSchema field constraint
=>  Fix TokenPatternSchema validation

requirements.txt, setup.cfg
We get a
```
RuntimeError: no validator found for <class 'spacy.tokens.span.Span'>, see `arbitrary_types_allowed` in Config
```
with Pydantic 1.7, which was released today. I couldn't find the culprit immediately, so let's pin the upper version as a temporary hot fix. See also https://github.com/explosion/thinc/pull/413 which is being released as v8.0.0rc1 (which should, in practice, already sufficiently limit the pydantic version during a spaCy install)
hot fix
=> Limit pydantic pin

spacy/training/pretrain.py
The dot notation of the pretraining corpus was not resolved correctly anymore. It was looking for `corpora.pretrain` only in `_config["training"]` instead of in the whole ` _config`.
Fixes #6325
bug fix
=> Fix pretrain

spacy/matcher/matcher.pxd, spacy/matcher/matcher.pyx, spacy/tests/matcher/test_matcher_api.py
Modify the internal pattern representation in `Matcher` patterns to identify the final ID state using a unique quantifier rather than a combination of other attributes.
It was insufficient to identify the final ID node based on an uninitialized `quantifier` (coincidentally being the same as the `ZERO`) with `nr_attr` as 0. (In addition, it was potentially bug-prone that `nr_attr` was set to 0 even though attrs were allocated.)
In the case of `{"OP": "!"}` (a valid, if pointless, pattern), `nr_attr` is 0 and the quantifier is `ZERO`, so the previous methods for incrementing to the ID node at the end of the pattern weren't able to distinguish the final ID node from the `{"OP": "!"}` pattern.
Fixes #6148.
Bug fix.
=> Identify final Matcher pattern node by quantifier

spacy/cli/evaluate.py, spacy/pipeline/attributeruler.py, spacy/pipeline/dep_parser.pyx, spacy/pipeline/entityruler.py, spacy/pipeline/morphologizer.pyx, spacy/pipeline/ner.pyx, spacy/pipeline/sentencizer.pyx, spacy/pipeline/senter.pyx, spacy/scorer.py, spacy/tests/pipeline/test_attributeruler.py, spacy/tests/test_scorer.py, spacy/tokens/doc.pyx, website/docs/api/doc.md, website/docs/api/scorer.md
Handle missing values in reference doc during scoring where it is possible to detect an unset state for the attribute. If no reference docs contain annotation, `None` is returned instead of a score. `spacy evaluate` displays `-` for missing scores and the missing scores are saved as `None`/`null`.
Attributes without unset states:
* `token.head`: relies on `token.dep` to recognize unset values
* `doc.cats`: unable to handle missing annotation
Additional changes:
* add optional `has_annotation` check to `score_spans` to replace `doc.sents` hack
* update `score_token_attr_per_feat` to handle missing and empty morph representations
* fix bug in `Doc.has_annotation` for normalization of `IS_SENT_START` vs. `SENT_START`
Enhancement.
=> Handle missing reference values in scorer

spacy/matcher/dependencymatcher.pyx, spacy/tests/matcher/test_matcher_api.py
For the `DependencyMatcher`:
* Fix on_match callback so that it is called once per matched pattern
* Fix results so that patterns with empty match lists are not returned
Fixes #6300.
Bug fix
=> Fix on_match callback and exclude empty match lists from results

.github/contributors/vha14.md, spacy/lang/en/syntax_iterators.py
Currently, the noun chunking algorithm checks if the `dep` for a token is in a whitelist of approved `deps`. This list does not 
include `oprd`, which is [Object Predicative](https://www.thoughtco.com/object-predicative-grammar-1691446#:~:text=In%20English%20grammar%2C%20an%20object,attribute%2C%20and%20objective%20predicative%20complement.). As a result, some valid noun phrases are dropped during chunking. See [this issue](https://github.com/explosion/spaCy/issues/6301) for a test case.
Add `oprd` to the list of accepted `deps`
=> add oprd to the list of accepted deps for noun chunking

spacy/cli/templates/quickstart_training.jinja, spacy/ml/models/textcat.py
Fixes #6340
- Add `pooling` argument to the `textcat`'s `tok2vec` layer when using a `Transformer`
- Allow `width` to  be `None` when building `spacy.TextCatEnsemble.v2`
bug fix
=> Fix textcat + transformer architecture

.github/contributors/forest1988.md, website/meta/universe.json
Fixed a usage of quotation marks in the example of spaCy Universe self-attentive-parser.
Fixed a issue #6424
I'd like to say thank you to @svlandeg for telling me how to solve the issue and encouraging me to make this PR.
a documentation typo fix
=> Avoid a SyntaxError in self-attentive-parser 

spacy/training/pretrain.py
Avoid resolving the full config to get the pretraining corpus, because that would mean you'd already have to fill in the paths to `dev` and `train` datasets, which you don't necessarily have yet at the moment of pretraining.
bug fix
=> Small fix for config resolving when pretraining

spacy/tests/doc/test_retokenize_merge.py, spacy/tokens/_retokenize.pyx
Instead of setting `NORM` on both the token and lexeme, set `NORM` only on the token.
The retokenizer tries to set all possible attributes with `Token/Lexeme.set_struct_attr` so that it doesn't have to enumerate which attributes are available for each. `NORM` is the only attribute that's stored on both and for most cases it doesn't make sense to set the global norms based on an individual retokenization. For lexeme-only attributes like `IS_STOP` there's no way to avoid the global side effects, but I think that `NORM` would be better only on the token.
Enhancement.
=> Only set NORM on Token in retokenizer

spacy/pipeline/morphologizer.pyx, spacy/pipeline/multitask.pyx, spacy/pipeline/tagger.pyx, website/docs/api/morphologizer.md, website/docs/api/tagger.md
Clean up of docs & constructor
* remove `set_morphology` from docs (not in code base anymore)
* remove labels from constructor (set them in `initialize` instead): in `Tagger`, `MultitaskObjective` and `Morphologizer`
small fixes
=> Clean up docs & constructors

website/docs/usage/layers-architectures.md
Updating the REL documentation section and syncing it with the latest code from https://github.com/explosion/projects/tree/v3/tutorials/rel_component
I'm not in favor of directly showing the actual code from the project repo, as sometimes I simplified the code a little to avoid clutter and focus on the main parts. I also really like the current way of showing the implementation in the main body of the docs and the corresponding config section on the right.
docs update
=> Update REL example in docs

spacy/language.py
Move `max_length` check to `nlp.make_doc()` so that's it's also checked for `nlp.pipe()`.
Enhancement?
=> Move max_length check to nlp.make_doc()

spacy/tests/training/test_training.py, spacy/training/align.pyx
* When checking for token alignments, check not only that the tokens are identical but that the character positions are both at the start of a token.
It's possible for the tokens to be identical even though the two tokens aren't aligned one-to-one in a case like `["a'", "''"]` vs. `["a", "''", "'"]`, where the middle tokens are identical but should not be aligned on the token level at character position 2 since it's the start of one token but the middle of another.
* Use the lowercased version of the token texts to create the character-to-token alignment because lowercasing can change the string length (e.g., for `İ`, see the not-a-bug bug report: https://bugs.python.org/issue34723)
Bug fix.
=> Fix alignment for 1-to-1 tokens and lowercasing

spacy/tests/tokenizer/test_tokenizer.py, spacy/tokenizer.pyx
Preserve `token.spacy` corresponding to the span end token in the
original doc rather than adjusting for the current offset.
* If not modifying in place, this checks in the original document (`doc.c` rather than `tokens`).
* If modifying in place, the document has not been modified past the current span start position so the value at the current span end position is valid.
Bug fix.
=> Fix spacy when retokenizing cases with affixes

spacy/cli/_util.py, spacy/cli/debug_config.py, spacy/cli/debug_data.py, spacy/cli/debug_model.py, spacy/cli/init_pipeline.py, spacy/cli/pretrain.py, spacy/cli/train.py, spacy/util.py, website/docs/api/cli.md, website/docs/usage/training.md, website/src/components/code.js
Allow setting the config path argument to `-` to read a config from standard input, e.g. to pipe forward a config file generated by a different process (`init config`, `init fill-config`, Prodigy commands generating config, third-party tools, and so on).
```bash
cat config.cfg | spacy train -
```
Instead of saving a `config.cfg` to a file just to load it back in with `spacy train`, this change would allow training via a single command, and simplify integrations of utilities that generate spaCy config files (e.g. Prodigy's training helpers).
enhancement
=> Allow reading config from stdin in spacy train

spacy/lang/ja/__init__.py, spacy/util.py
For [spacymoji](https://spacy.io/universe/project/spacymoji)  with `Japanese()`.
To use JapaneseTokenizer.pipe as same as Tokenizer.pipe
=> JapaneseTokenizer.pipe added

spacy/errors.py, spacy/ml/staticvectors.py, spacy/training/initialize.py
Catch an error that occurs when using `StaticVectors` without initializing the vectors in the vocab properly. Thinc throws a "_Buffer and memoryview are not contiguous in the same dimension_" `ValueError` which is a bit confusing ;-)
& small fix removing an non-existing argument from a `ConfigValidationError.from_error` call.
UX enhancement
=> Add specific error when StaticVectors can't read the vectors data

spacy/ml/extract_ngrams.py, spacy/tests/pipeline/test_textcat.py
Fixing a small little bug that took quite a bit of time to find, but required only one word to fix :-)
The `textcat` architecture `with_cpu(extract_ngrams>>sparse_linear)>>...` had a problem: `extract_ngrams` would create a `lengths` array with `dtype=numpy.int_` that would later on be [interpreted](https://github.com/explosion/thinc/blob/master/thinc/layers/sparselinear.pyx#L76) as an array with `int32` values. However, on MacOS & Unix, `numpy.int_` resolves to `int64`.
As a result, [this loop](https://github.com/explosion/thinc/blob/master/thinc/layers/sparselinear.pyx#L118) would not read the proper lengths, and ultimately the wrong scores would be passed forward. I think this got compensated by other parts of the neural network, but you could see the difference in predictions when …
=> Bugfix multi-label textcat reproducibility

spacy/cli/init_config.py, spacy/tests/test_cli.py
Very small edit making `init_config` return the `Config` instead of calling `save_config` itself. Allows for more modularity if other scripts wish to create a new config file (but not necessarily save it)
enhancement
=> returning config in init_config

spacy/util.py
The root logger is initialised in v3 of spaCy when the format is set, this causes repeated logging messages in other applications that import spacy. Instead the spacy logger should should be initialised with the correct formatting.
The below is an example which causes this issue:
```
import spacy
import logging
logger = logging.getLogger('example_package')
ch = logging.StreamHandler()
ch.setFormatter(logging.Formatter("EXAMPLE: %(message)s"))
logger.addHandler(ch)
logger.error('hello')
```
This produces:
```
EXAMPLE: hello
hello
```
Instead of simply:
```
EXAMPLE: hello
```
The changes produce the same logging messages within spacy, but prevent it from changing the output of other packages when spacy is imported.
Let me know if you need anything further to merge this, thanks for a great …
=> Prevent root logger from initialising

spacy/pipeline/tagger.pyx, spacy/tests/pipeline/test_tagger.py
Two fixes to the tagger:
- Allow missing values when updating the tagger
- Make sure that labels are added when the tagger is initialized, throw a custom error otherwise. Fixes #6567 
bug fix & UX
=> Tagger robustness

spacy/cli/templates/quickstart_training.jinja, spacy/ml/models/parser.py, spacy/ml/tb_framework.py, spacy/pipeline/dep_parser.pyx, spacy/pipeline/ner.pyx, spacy/tests/parser/test_ner.py, spacy/tests/serialize/test_serialize_config.py, website/docs/api/architectures.md
Our pretrained models would usually have `use_upper=True` for the `TransitionBasedParser`, but the new transformer models have `use_upper=False`. In this latter case, it seems like there was a bug when trying to resize the parser. For instance, this would fail:
```
import spacy
import os
nlp = spacy.load("en_core_web_trf")
ner = nlp.get_pipe('ner')
ner.add_label("FRIENDS")
ner.add_label("LOC")
nlp("Test sentence")
output_dir = "test_dir"
os.mkdir(output_dir)
nlp.to_disk(output_dir)
model = spacy.load(output_dir)
```
as reported in https://stackoverflow.com/questions/64968313/error-loading-trained-en-core-web-trf-spacyv3-ner-model.
The reason seems to be this bit of code in `resize_output`:
```
if not model.attrs["has_upper"]:
if lower.has_dim("nO") is None:
lower.set_dim("nO", new_nO) …
```
=> Fix  parser resizing when there is no upper layer

spacy/cli/info.py
There is a small typo in spacy/cli/info.py.
Should read `specified` rather than `speficied`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, speficied -> specified

website/docs/api/tokenizer.md
`tokenizer.to_disk` takes a file, not a directory.
Fixes #5256
docs fix
=> fix documentation of 'path' in tokenizer.to_disk

website/docs/api/tokenizer.md
Fixing backticks in docs
docs fix
=> fix backticks in docs

spacy/cli/info.py, spacy/tests/test_cli.py, website/docs/api/cli.md
Fixes to `spacy info` command:
- Avoid issues when trying to parse a URL as a `Path`
- Fix code when path is not a package but a directory
- Avoid printing labels by setting a default "exclude" parameter. This makes the output pretty much unreadable otherwise if there's a `morphologizer`. If you do still want the labels, you can run with
```
spacy info es_core_news_lg --exclude ""
```
(this is not very intuitive but I think it's fine, as typically we'll probably be the ones to ask this to users if we really want the label information to solve a specific ticket)
bug fixes & enhancement
=> Fixing CLI info command

spacy/tests/lang/en/test_exceptions.py, spacy/tests/lang/uk/test_tokenizer.py, spacy/tests/serialize/test_serialize_pipeline.py, spacy/tests/serialize/test_serialize_tokenizer.py, spacy/tests/vocab_vectors/test_lookups.py
With spaCy 3.x supporting Python >= 3.6, I'm hoping we can unskip some tests. 
Some of the tests could be unskipped because the code has been fixed in the meantime.
repo maintenance?
=> Unskipping tests

spacy/cli/init_config.py, website/docs/api/cli.md
- By default, don't overwrite an existing config file with `init config` (as this can be quite unfortunate)
- Allow overwriting with a `-W` flag
enhancement
=> prevent overwriting existing config file

spacy/morphology.pyx, spacy/pipeline/_parser_internals/arc_eager.pyx, spacy/pipeline/_parser_internals/ner.pyx, spacy/tokenizer.pyx, spacy/tokens/doc.pyx, spacy/vocab.pyx
Adding sanity checks to avoid 0-length memory allocations, which would not result in NULLs, as we learnt [previously](https://github.com/explosion/spaCy/pull/4423).
Zero allocation occassionally happened in `create_morph_tag`. It didn't seem to do much damage, but best to avoid anyway.
bug fix
=> Prevent 0-length mem alloc

.github/contributors/bratao.md, spacy/training/loop.py
During a training session using the latest spaCy v3 I realized that it was not saving the "best" version during training, it was saving only the latest. 
After a debug I found the error. During the training loop the check condition for is_best_checkpoint was wrong. I also realized that it was always saving the optimizer average, and also put a condition to check this. 
It is a bugfix to the training loop
=> spaCy v3 is not saving the best version in training loop

spacy/tests/doc/test_retokenize_merge.py, spacy/tests/doc/test_retokenize_split.py, spacy/tokens/_retokenize.pyx
Instead of unsetting lemmas on retokenized tokens, set the default lemmas to:
* merge: concatenate any existing lemmas with `SPACY` preserved
* split: use the new `ORTH` values if lemmas were previously set, otherwise leave unset
Bug fix?
=> Set default lemmas in retokenizer

spacy/lang/en/tokenizer_exceptions.py, spacy/tests/lang/en/test_exceptions.py
Fixes #6624 
Removing `cause` from norm exceptions so it's not normalized to `because` if there is no leading apostrophe. The case with the leading apostrophe (with and without capitalization) was already present in the file around L422. Added test for both cases.
bug fix / enhancement in English tokenizer
=> remove cause without apostrophe from norm exceptions

spacy/pipeline/_parser_internals/arc_eager.pxd, spacy/pipeline/_parser_internals/arc_eager.pyx, spacy/pipeline/_parser_internals/ner.pyx, spacy/pipeline/dep_parser.pyx, spacy/tests/parser/test_ner.py, spacy/tests/parser/test_parse.py
Adding back the `get_beam_parses` method for the parser & added a `scored_parses` function that gives probabilities for the different possible heads and labels.
enhancement
=> Getting scores out of beam_parser

spacy/cli/templates/quickstart_training.jinja, spacy/ml/models/tok2vec.py, spacy/pipeline/morphologizer.pyx, spacy/pipeline/textcat.py, spacy/tests/pipeline/test_tok2vec.py, website/docs/api/architectures.md, website/docs/usage/embeddings-transformers.md, website/docs/usage/layers-architectures.md
This fix is required to resolve https://github.com/explosion/spaCy/issues/6318, together with https://github.com/explosion/thinc/pull/432.
I think the "encode" architectures were not returning the correct type, and they should incorporate `with_array` themselves instead of relying on `Tok2Vec` to do so. Technically this changes these models, so I've bumped the versions and kept the old ones in the same file (for now).
This was necessary to make `TorchBiLSTMEncoder.v1` function correctly, and I think it's better overall.
Also fixed the documentation of `TorchBiLSTMEncoder.v1` which was referring to wrong parameters.
bug fix + docs fix
=> Fix types of Tok2Vec encoding architectures

spacy/training/loop.py
The try/except/finally logic in the `spacy.training.loop.train` function was wrong: too much code was under the `finally` block, I think I made an indentation error. The result was that on errors, we were swallowing the traceback and returning exit status 0.
=> Fix train loop to avoid swallowing tracebacks

spacy/util.py
Fix the `minibatch` function in `spacy.util` when the size `iterator` is finished.
This may seem unnecessary, and I'd be skeptical of the change. However, since Python 3.7, if a `StopIteration` exception is raised inside generators or coroutines, they are converted into runtime errors, thus not interpreted as the end of the iteration anymore but they're vanilla exceptions. See [this SO answer](https://stackoverflow.com/a/51701040/1165181) for more info.
So when an iterator is provided in `minibatch` (instead of an `int`), there are chances it's finished, and then this problem can happen. I added a default value to `next` so it isn't raised and the behavior is the expected one.
Bugfix.
=> Fix `spacy.util.minibatch` when the size iterator is finished

spacy/pipeline/functions.py, spacy/tests/pipeline/test_functions.py, website/docs/api/pipeline-functions.md, website/docs/usage/embeddings-transformers.md
Add a `token_splitter` component for use with transformer pipelines. This component splits up long tokens like URLs into smaller tokens. This is particularly relevant for pretrained pipelines with `strided_spans`, since the user can't change the length of the span `window` and may not wish to preprocess the input texts.
The `token_splitter` splits tokens that are at least `min_length` chars long into smaller tokens of `split_length` chars size.
Notes:
* Since this is intended for use as the first component in a pipeline, the token splitter does not try to preserve any token annotation.
Enhancement.
=> Add token_splitter component

spacy/language.py, spacy/util.py
We want to let the pipeline mutate the `example.predicted` `Doc` object during training and evaluation without the user having to worry about their data changing. The solution is to make our own copy of the relevant data once we're inside the methods, so that we can mutate it freely.
This will allow allow a subsequent change to `component.update()`: we'll be able to add `component.set_annotations()` calls within the component, which should make it quite a lot easier to have components communicate with each other. The change is potentially breaking though, so it's probably better to put it in a second PR.
(Potentially breaking) change.
=> Copy the Example objects (and their predicted Doc) in nlp.evaluate() and nlp.update()

spacy/language.py, spacy/pipeline/tok2vec.py, spacy/training/initialize.py, website/docs/usage/processing-pipelines.md, website/docs/usage/training.md
- Change in `Tok2Vec` to store not only the listener `Model` instances, but also the downstream component names to which those listeners belong.
- Warn when trying to train a component which has a frozen tok2vec layer, or when (re)training a tok2vec layer which has a downstream frozen component listening to it.
- Added a few notes in the documentation
UX enhancement
=> warn when frozen components break listener pattern

spacy/about.py, spacy/pipeline/entity_linker.py, spacy/pipeline/multitask.pyx, spacy/pipeline/tagger.pyx, spacy/pipeline/textcat.py, spacy/pipeline/tok2vec.py, spacy/pipeline/trainable_pipe.pyx, spacy/pipeline/transition_parser.pyx, spacy/tests/pipeline/test_entity_linker.py, website/docs/api/dependencyparser.md, website/docs/api/entitylinker.md, website/docs/api/entityrecognizer.md, website/docs/api/morphologizer.md, website/docs/api/multilabel_textcategorizer.md, website/docs/api/pipe.md, website/docs/api/sentencerecognizer.md, website/docs/api/tagger.md, website/docs/api/textcategorizer.md, website/docs/api/tok2vec.md, website/docs/api/transformer.md, website/docs/usage/layers-architectures.md
Follow-up to PR https://github.com/explosion/spaCy/pull/6765 - ensuring `component.update()` calls `component.set_annotations()` and removing the boolean flag, also from documentation. 
(Potentially breaking) change -> bumping to `3.0.0rc4` to avoid confusion with the recently released `3.0.0rc3`
=> Set annotations in update

spacy/matcher/phrasematcher.pyx, spacy/tests/matcher/test_phrase_matcher.py
Fixes #6770
support `IS_SENT_START` in `PhraseMatcher`, just like we do in `Matcher`
enhancement
=> support IS_SENT_START in PhraseMatcher

spacy/tests/regression/test_issue6755.py, spacy/tokens/span.pyx
Fixes #6755
Ensure `span.text` works for an empty span, and is consistent with the behaviour in `text_with_ws`
bug fix
=> ensure span.text works for an empty span

.github/contributors/keshav.md, spacy/cli/info.py
Spacy Cli info method was causing backward compatibility issues with all other third 
party consumers.
Reference issue : https://github.com/explosion/spaCy/pull/6793#issue-560075424
Fixed backward compatibility by setting default value to exclude in info
method.
=> Spacy Cli info method causing backward compatibility issues 

spacy/ml/models/tok2vec.py
We've been making a number of fixes to the `tok2vec` layer definitions, including @sofie's fix to make other encoders work. Those problems masked this issue, which I hit when doing the spancat testing.
=> Avoid assuming encode nO dimension is preset in tok2vec

spacy/tokens/_dict_proxies.py, spacy/tokens/doc.pyx, spacy/vocab.pyx
* Avoid letting the `Doc` object own `LexemeC` data. Instead all lexemes should be owned by the `Vocab`. Also avoids weird heuristics.
* Copy `doc.spans` attribute.
=> Fix Doc.copy bugs

website/docs/usage/_benchmarks-models.md, website/docs/usage/facts-figures.md
Speed benchmark on 10K reddit comments. Ran this on larger datasets too, the results are virtually the same, but the trf model had some issues with some of the texts, so not sure if it's worth the trouble. The relative timings between libraries were pretty stable across runs.
Also updated the accuracy numbers for the recent a1 models.
doc update
=> Add speed benchmark

spacy/pipeline/_parser_internals/arc_eager.pyx, spacy/pipeline/_parser_internals/ner.pyx, spacy/pipeline/dep_parser.pyx, spacy/pipeline/transition_parser.pyx, spacy/tests/parser/test_add_label.py
Addresses #6681 
In v2 (and maybe older?), labels are added to the NER if they're present in the batch of data but aren't in the model yet. The `EntityRecognizer` support dynamically resizing their output arrays, and a lot of applications have found success in sticking a new entity type into an exisiting NER model. The implicit label adding makes this easier. The labels need to be there for prediction too, or the imitation learning can't work.
I've implemented this a bit more cleanly than it was, in that the labels come in at a more consistent time, and they're added all at once for the batch before we resize the model once.
For the parser, it's a bit different. We have a label frequency cut-off for the parser, and the parser won't fail to find a parse just because a label is missing. …
=> Restore implicit label addition for NER

spacy/pipeline/transition_parser.pyx, spacy/tests/parser/test_add_label.py, spacy/tests/regression/test_issue4001-4500.py
Follow-up to PR https://github.com/explosion/spaCy/pull/6827
Make sure the implicit label resizing of the NER also works when calling `ner.beam_parse` or `ner.greedy_parse` directly
(bug)fix
=> Fix beam NER resizing

spacy/cli/init_config.py, spacy/cli/templates/quickstart_training.jinja, spacy/cli/templates/quickstart_training_recommendations.yml, website/src/widgets/quickstart-training.js
- Introduce `__default__` block in quickstart recommendations and fall back to multilingual transformer weights if no language-specific recommendations are available. This also means you never end up with a non-transformer config on GPU.
- Update labels in quickstart widget to make trade-offs a bit more obvious.
enhancement, ux
=> Update config generation defaults and transformers

spacy/training/example.pyx
Just came across this: otherwise, the error message is very confusing if you pass in a dict instead of a list. We should also be able to support a list instead of a tuple?
~~**Edit:** Okay, I think I broke something 😅~~
ux
=> Improve Example error handling for NER data

spacy/language.py, spacy/pipeline/attributeruler.py, spacy/pipeline/entity_linker.py, spacy/pipeline/entityruler.py, spacy/pipeline/lemmatizer.py, spacy/pipeline/pipe.pyx, spacy/pipeline/sentencizer.pyx, spacy/pipeline/tagger.pyx, spacy/pipeline/textcat.py, spacy/pipeline/tok2vec.py, spacy/pipeline/trainable_pipe.pyx, spacy/pipeline/transition_parser.pyx, spacy/tests/test_language.py, spacy/util.py, website/docs/api/language.md, website/docs/api/pipe.md
This seems a frequently asked feature - e.g. https://github.com/explosion/spaCy/issues/6630 and https://github.com/explosion/spaCy/issues/4847, and I've been wanting it myself too ;-)
With the `Pipe` / `TrainablePipe` API revamped for spaCy 3, I thought it would make sense to also add an error handler to `nlp.pipe` and the `pipe` methods of trainable pipeline components.
The default error handler changes nothing: it just reraises the same exception. But the user has an option of specifying its own error handling function that can ignore the batch, inspect the batch, warn, ... 
Which arguments should the error handler function take? Currently it takes the component's name, the offending batch of documents, and the original error that was thrown.
enhancement, UX
=> Error handling in nlp.pipe

spacy/errors.py, spacy/kb.pyx, spacy/tests/regression/test_issue6730.py, website/docs/api/kb.md
Fixes #6730
- Throw a generic error (E891) when an alias could not be added to the KB for some reason, to avoid a more cryptic AssertionError during IO 
- Specifically prevent the empty string from being an alias (E890)
bug fix
=> avoid empty KB alias

spacy/errors.py, spacy/matcher/dependencymatcher.pyx, spacy/tests/matcher/test_dependency_matcher.py
Instead of silently using only the first token in each matched span:
* Forbid `OP: ?/*/+` through `DependencyMatcher` validation
* As a fail-safe, add warning if a token match that's not exactly one token long is found by a token pattern.
?
=> Forbid OP matching 2+ tokens in DependencyMatcher

.github/contributors/tupui.md, spacy/cli/download.py
When `--no-cache-dir` is present, it prevents caching to properly function.
If the user still wants to do this, there is the possibility to pass options with `user_pip_args`.
But you should not enforce options like these. In my case this is preventing some docker build (using buildkit caching) to have proper caching of models.
This PR removes the enforced `pip` options and leave this to the user.
=> Remove --no-cache-dir when downloading models

spacy/cli/package.py, website/docs/api/cli.md, website/docs/usage/v3.md
Allow `spacy package` to build binary wheels by introducing a unified `--build` option that defaults to `sdist` (but can also be set to `wheel`, `sdist,wheel` or `none`). Building the wheel will then run `setup.py bdist_wheel` under the hood.
enhancement
=> Support building wheel in spacy package

spacy/language.py, spacy/tests/pipeline/test_tok2vec.py, spacy/training/initialize.py
Related to https://github.com/explosion/spaCy/discussions/6789
When linking a `TransformerListener` to a downstream component, the `nO` dimension of the listener is set according to the dimension of the `Transformer`. This linking is triggered by `nlp.initialize`, but we have to ensure that we also link resumed/frozen components. I think, in hindsight, having the linking implicitely in `nlp.initialize` is therefor probably a bad idea.
As a minimal fix, this PR adds a flag whether or not the linking should happen by `nlp.initialize`, allowing the CLI to turn it off and instead perform the linking on *all* components.
At least this fixes the bug from https://github.com/explosion/spaCy/discussions/6789, but we may want to refactor/reconsider this further at some point.
Not sure whether to …
=> Fix linking resumed components

spacy/language.py, spacy/pipeline/tok2vec.py, spacy/training/initialize.py
Follow-up to https://github.com/explosion/spaCy/pull/6859
Removing the flag `link_components` again in favour of a more general solution. Depending on what components need initialization and which don't (e.g. because they are frozen), the required order changes: sometimes we need to link first, sometimes we need to initialize first. To resolve this, I think for now it makes more sense to ensure that it's not harmful if the linking happens twice. This generically catches all use-cases.
bug fix
=> remove link_components flag again

spacy/about.py, spacy/cli/project/run.py, spacy/util.py
Add `capture` flag to `project_run` instead of having it default at `False`. From the unit tests of `projects` it would be good to be able to set this to `True` so we can debug cases where the CLI fails.
Bumping the version to 3.0.1. so we can potentially release it to test the projects CLI further.
enhancement
=> Add capture argument to project_run

spacy/pipeline/entity_linker.py, spacy/pipeline/multitask.pyx
Fixes #6826
Ensure that the loss value is cast as float. Otherwise on GPU, the `cupy.core.core.ndarray` object will create trouble during IO as it is not JSON serializable.
bug fix
=> Ensure the loss value is cast as float

spacy/lexeme.pyx, spacy/training/initialize.py, website/docs/api/top-level.md
Rewrote an internal function `ensure_shape` used by `init vectors`. When the file does not contain the number of vectors as the first line, this function goes through the file and counts them. Previously, the lines were cached in a list but this may blow up your memory/pc. Instead, I think it's actually a better idea to just iterate through the file twice. It takes slightly longer but seems to work more smoothly at least on my end.
Also fixed a typo in an unrelated docstring.
memory-speed trade-off
=> reduce memory load when reading all vectors from file

website/docs/api/lemmatizer.md
The `overwrite` key in the `config` definition on line 70 was treated like a function argument – it needs quotes and should be followed by a colon.
Documentation change. (Typo.)
This is merely a documentation change.
=> Syntax error in Lemmatizer docs

spacy/tests/pipeline/test_pipe_factories.py, spacy/util.py
Check of `__qualname__` attribute existance.
When making some components with class objects, they do not have `__qualname__` before they are included in `__pycache__`.
Bug fix.
=> Several callable objects do not have __qualname__

.github/contributors/peter-exos.md, spacy/matcher/phrasematcher.pxd, spacy/matcher/phrasematcher.pyx, spacy/tests/matcher/test_phrase_matcher.py, spacy/tests/regression/test_issue6839.py, spacy/tokenizer.pyx, website/docs/api/phrasematcher.md
Addresses https://github.com/explosion/spaCy/issues/6839
Since you may be busy with the spacy 3 release (thank you and congrats!), I went ahead and tried to implement the requested feature myself. It was easier than I thought: 
I extended PhraseMatcher to run on Spans and Docs (like Matcher) by adding start and end index arguments to `PhraseMatcher.find_matches` and using them to constrain the loops. 
Created a regression test and a functional test. All tests passed.
I adjusted the relevant doc strings, but the website docs may need to be updated as well. I have not done that.
This is my first contribution to this repo. 
Please let me know if I am missing anything, or if I can improve something in this PR.
enhancement, matcher/feat
=> Run PhraseMatcher on Spans 

spacy/pipeline/tok2vec.py, spacy/tests/regression/test_issue6950.py
The `lambda` in `Tok2Vec.predict` would result in the `nlp` object not being picklable if the pipeline is initialized and has tok2vec listeners.
Open question: Could we simplify this and just use `None` here, like we do in `spacy-transformers`? https://github.com/explosion/spacy-transformers/blob/392b442eb39e2cbf1f6d6152690a7547f48877ff/spacy_transformers/pipeline_component.py#L220-L221
bug fix, serialization
=> Fix issue #6950: allow pickling Tok2Vec with listeners

spacy/cli/_util.py, spacy/cli/project/run.py, spacy/schemas.py, spacy/tests/test_cli.py, website/docs/usage/projects.md
* allow CLI overrides in `project run` (just like config overrides, e.g. `--vars.batch_size 128`)
* add `env` section to `project.yml` for mapping variables to environment variable names, e.g. `batch_size: TRAINING_BATCH_SIZE`, which can be referenced as `${env.batch_size}` and set on the CLI or in other processes as `TRAINING_BATCH_SIZE=128`
enhancement, CLI
=> Support env vars and CLI overrides for project.yml

spacy/cli/evaluate.py, spacy/tests/regression/test_issue7019.py
Only try to pretty-print actual numbers and don't error on `None` scores in `evaluate` printer.
=> Fix issue #7019: Handle None scores in evaluate printer

spacy/cli/init_config.py, spacy/tests/regression/test_issue7055.py
Fixes #7055.
Under the hood, `init fill-config` creates an `nlp` object from the base config, which takes care of auto-filling and validation, and also ensures that the config is loadable. However, if the `[components]` block includes components sourced from a different pipeline, creating the `nlp` object will copy those components over, including their config (so that `nlp.config` reflects the actual component config). As a result, auto-filling a config with `init fill-config` would replace sourced component blocks, which is not the intended behaviour.
bug fix
=> Preserve sourced components in fill-config

website/meta/universe.json
This pull request adds a project to the SpaCy Universe.
[spacy-dbpedia-spotlight](https://github.com/MartinoMensio/spacy-dbpedia-spotlight) allows to get annotations from DBpedia Spotlight within SpaCy. The `doc.ents` are populated with the linked entities.
It is a change to the documentation, since it is only an addition to Universe.
=> added spacy-dbpedia-spotlight

spacy/tests/regression/test_issue7029.py, spacy/tests/regression/test_issue7056.py, spacy/tests/regression/test_issue7065.py, spacy/tokens/span.pyx, website/docs/api/doc.md, website/docs/api/span.md, website/docs/usage/linguistic-features.md
Fixes #7065
When a span contains a sentence boundary, `span.sent` only returns the first entity.
Also some doc fixes:
- document `span.ent` separately to provide more background information
- add `model=sentences` to `doc.sents` and `span.sent` - used to be `model=parser`. I would have prefered to put `model=sentence boundaries` but that feels very long, and `model=sbd` too short?
- `Doc.md` had two `#ents` anchors - fixed that
API & docs update
=> span.ent only returns first sentence

spacy/errors.py, spacy/pipeline/entity_linker.py, website/docs/api/entitylinker.md
Quick fix for https://github.com/explosion/spaCy/issues/7119
- custom error when calling `set_kb` with an actual `KnowledgeBase` object instead of a function - it feels like this mistake might be common
- NEL docs fix
UX & docs fix
=> NEL docs & UX

spacy/scorer.py, spacy/tests/regression/test_issue7062.py
Fixes #7062
Only evaluate named entities for NEL if there is a corresponding gold span. The code was actually set up to do so, but lacked a small check.
bug fix
=> fix NEL scoring eval

spacy/pipeline/entity_linker.py, spacy/tests/pipeline/test_entity_linker.py, spacy/tests/pipeline/test_pipe_methods.py, website/docs/api/entitylinker.md
- The `n_sents` functionality from https://github.com/explosion/spaCy/pull/5548 got broken - probably in the refactor for v3. Adding it back in. 
- Avoiding duplication between the config file and the "cfg" file, as pointed out by @adrianeboyd for `textcat`
bug fix
I don't think this PR will break backwards compatibility, even though `n_sents` is now a new parameter in the `entity_linker` block? I checked with the Emerson project and that still runs (with the old config), but just adds the default `n_sents = 0` to the final, trained model. But I wanted to double check / highlight the issue just to be sure.
=> fix NEL config and IO, and n_sents functionality

website/docs/api/sentencizer.md
Update sentencizer documentation example with sentencizer pipe name
One of the examples is using `entity_ruler` as a pipe name, so just changed it to `sentencizer`
Documentation
=> Update sentencizer documentation example with sentencizer pipe name

spacy/errors.py, spacy/training/loggers.py
I was testing a config with `WandbLogger` in, without having `wandb` installed in that specific venv. It gave a confusing error because Python seemed to import some other "wandb" folder that got written during previous experiments. 
So instead of failing directly on the `import wandb` statement, it only failed when calling `wandb.init`, which is confusing:
```
AttributeError: module 'wandb' has no attribute 'init'
```
It feels like this may happen to others as well - so I added a quick check & custom error to address this case:
```
ImportError: [E880] The 'wandb' library could not be found - did you install it? Alternatively, specify the 'ConsoleLogger' in the 'training.logger' config section, instead of the 'WandbLogger'.
```
UX enhancement
=> import wandb failure - UX

spacy/scorer.py, website/docs/api/scorer.md
Fix documented type of `has_annotation` for `scorer.score_spans`
docs fix
=> has_annotation docs fix

spacy/tests/doc/test_doc_api.py, spacy/tokens/_dict_proxies.py, spacy/tokens/doc.pyx
`Doc.copy()` would corrupt the doc reference stored in `doc.spans`, because the copied `spans` would keep pointing to the old doc, which would get garbage-collected at some point, eventually leading to dead references.
Proposed solution: allow `Spangroups.copy()` to optionally define a new `Doc` object, so that `Doc.copy()` sets the correct new `Doc`.
bug fix
=> Fix spans weak ref in doc copy

spacy/ml/models/entity_linker.py, spacy/ml/models/multi_task.py, spacy/ml/models/parser.py, spacy/ml/models/tagger.py, spacy/ml/models/textcat.py, spacy/ml/models/tok2vec.py, spacy/tests/pipeline/test_entity_linker.py, spacy/tests/serialize/test_serialize_config.py, spacy/tests/serialize/test_serialize_kb.py, spacy/tests/test_architectures.py, spacy/tests/training/test_readers.py, website/docs/api/architectures.md, website/docs/usage/layers-architectures.md
Using the different registries as callable instead of calling the function `register()` specifically. 
chore
=> Consistently use registry as callable

website/meta/languages.json
I was looking at the [model list on the docs](https://spacy.io/usage/models) and I noticed a few languages were listed twice. 
So I figured I'd remove the ones that were listed twice. 
Minor documentation fix.
=> Removed Languages that were listed twice on Docs

spacy/errors.py, spacy/language.py, spacy/ml/models/multi_task.py, spacy/tests/serialize/test_serialize_config.py, spacy/tests/test_cli.py, spacy/tests/training/test_pretraining.py, spacy/training/initialize.py, spacy/training/pretrain.py, website/docs/api/architectures.md
- Fixes https://github.com/explosion/spaCy/issues/6952
- Fixes https://github.com/explosion/spaCy/issues/7289
- Fixes https://github.com/explosion/spaCy/discussions/7285
The `tok2vec` pretraining functionality got pretty broken, I think during the final refactors of the release candidates for spaCy 3. This PR fixes quite a few bugs and introduces better tests:
- in `nlp.initialize`, `init_tok2vec` was called before the components got initialized themselves, meaning that the latter would overwrite the pretrained weights.
- `nlp.from_config` did not play well with the schema because of `pretraining: Union[ConfigSchemaPretrain, ConfigSchemaPretrainEmpty] = {}` in `ConfigSchema`. I'm not sure whether the current solution of temporarily popping the pretraining section is OK, other solutions …
=> Fixing pretrain

spacy/errors.py, spacy/language.py, spacy/util.py, website/docs/api/top-level.md, website/docs/usage/v3.md
Due to the bug reported in #6990, warn users with `cupy` available who are working in a Jupyter notebook that they need to run `require_gpu` or `prefer_gpu` in the same cell as `spacy.load` for the model to be loaded on the correct device.
`thinc` uses `contextvars` to store the GPU selection and there is a bug in IPython (https://github.com/ipython/ipython/issues/11565) that does not preserve `contextvars` settings across cells.
Enhancement?
=> Add warning about GPU selection in Jupyter notebooks

spacy/training/pretrain.py
When running spacy with python3.9 I get the following warning
```text
/srv/venv/venvname/lib/python3.9/site-packages/spacy/training/pretrain.py:145: SyntaxWarning: "is not" with a literal. Did you mean "!="?
tok2vec.upstream_name if tok2vec.upstream_name is not "*" else "tok2vec"
```
replace "is not" with `!=` as we are comparing with a string
=> replace "is not" with !=

spacy/default_config.cfg
Maybe this used to work differently, but currently a negative patience
just causes immediate termination.
Doc fix
=> Remove mention of -1 for early stopping (fix #7535)

spacy/tests/doc/test_retokenize_merge.py, spacy/tokens/_retokenize.pyx
In the retokenizer, only reset sent starts (with `set_children_from_head`) if the doc is parsed. If there is no parse, merged tokens have the unset `token.is_sent_start == None` by default after retokenization.
Bug fix.
=> Keep sent starts without parse in retokenization

website/docs/usage/linguistic-features.md
Fix a wrong function name in the documentation. `tokenizer.infixes_finditer`, as mentioned [here](https://spacy.io/usage/linguistic-features#native-tokenizers), should instead be `tokenizer.infix_finditer`, as shown in the API [here](https://spacy.io/api/tokenizer#init).
Change in the documentation.
=> fix fn name: tokenizer.infixes_finditer -> tokenizer.infix_finditer

website/docs/api/architectures.md, website/docs/api/legacy.md, website/meta/sidebars.json
Introducing a dedicated page in the docs to document legacy functions.
Perhaps in time we'd want a submenu and separate pages? But it seemed a little overkill for now...
Where do we want this in the sidebar? I added it to "Other" for now.
Related PR: https://github.com/explosion/spacy-legacy/pull/3
docs fix
=> Legacy docs

website/meta/universe.json
Numerizer is a spaCy extension that converts numbers written in natural language
into numeric strings. This commit adds Numerizer to `website/meta/universe.json`.
=> Add Numerizer to SpaCy universe

spacy/scorer.py, spacy/tests/test_scorer.py
The `__add__` method of `PRFScore` can't be run because of incorrect constructor usage. It isn't used anywhere in the code. Because it would be weird to have `__iadd__` without `__add__`, I decided to fix it instead of removing it.
bug fix
=> Fix __add__ method of PRFScore

spacy/language.py
Implement `replace_listeners` for sourced components loaded from a config.
Bug fix.
=> Implement replace_listeners for source in config

spacy/training/gold_io.pyx
Data in the JSON format is split into sentences, and each sentence is
saved with is_sent_start flags. Currently the flags are 1 for the first
token and 0 for the others. When deserialized this results in a pattern
of True, None, None, None... which makes single-sentence documents look
as though they haven't had sentence boundaries set.
Since items saved in JSON format have been split into sentences already,
the is_sent_start values should all be True or False.
Bug fix.
=> Fix is_sent_start when converting from JSON (fix #7635)

spacy/strings.pyx, spacy/tests/serialize/test_serialize_vocab_strings.py, spacy/tokens/_serialize.py
The attribute `DocBin.strings` is a set. In `DocBin.get_docs`
a given vocab is updated by iterating over this set.
Iteration over a python set produces an arbitrary ordering,
therefore vocab is updated non-deterministically.
When training (fine-tuning) a spacy model, the base model's
vocabulary will be updated with the new vocabulary in the
training data in exactly the way described above. After
serialization, the file `model/vocab/strings.json` will
be sorted in an arbitrary way. This prevents reproducible
model training.
Here's a small code snippet that will reproduce the non-determinism.
```python
import sys
import spacy
from spacy.training import Corpus
from spacy.util import fix_random_seed
DATASET_PATH = "<some path>/train.spacy"
def run(prefix):
fix_random_seed(7)
nlp = …
```
=> Make vocab update in get_docs deterministic

spacy/cli/__init__.py, spacy/errors.py, website/docs/usage/v3.md
Typically, deprecated is used for functionality that is bound to become unavailable but that can still be used. Obsolete is used for features that have been removed. In E941, I think what is meant is "obsolete" since loading a model by a shortcut simply does not work anymore (and throws an error). This is different from downloading a model with a shortcut, which is deprecated but still works.
In light of this, perhaps all other error codes should be checked as well.
Change in error code
=> Terminology: deprecated vs obsolete

spacy/vectors.pyx, spacy/vocab.pyx
`vectors.data` can be of type `numpy.ndarray` or `cupy.ndarray`, but [recent GPU testing](https://github.com/explosion/spaCy/pull/7293) highlighted some trouble when using `cupy`. This PR makes the code more general by relying on current ops, and also avoids using the implicit conversion to scalar by `numpy` (which `cupy` doesn't do).
Tested locally, this seemed to fix the trouble from PR #7293 🤞 
bug fix
=> Fix vectors data on GPU

.github/contributors/armsp.md, website/docs/usage/linguistic-features.md
To the uninitiated, the example at https://spacy.io/usage/linguistic-features#setting-entities errors on Binder because the code tries to set the entity for "fb" twice.
The exact error as reported is -
```
ValueError                                Traceback (most recent call last)
<ipython-input-1-73c2a9e8d913> in <module>
15
16 # Option 2: Assign a complete list of ents to doc.ents
---> 17 doc.ents = list(doc.ents) + [fb_ent]
18
19 ents = [(e.text, e.start, e.end, e.label_) for e in doc.ents]
/srv/conda/envs/notebook/lib/python3.7/site-packages/spacy/tokens/doc.pyx in spacy.tokens.doc.Doc.ents.__set__()
/srv/conda/envs/notebook/lib/python3.7/site-packages/spacy/tokens/doc.pyx in spacy.tokens.doc.Doc.set_ents()
ValueError: [E1010] Unable to set entity information for token 0 which is …
```
=> Default code for Setting Entity annotations on the website errors

website/docs/api/data-formats.md
As pointed out in https://github.com/explosion/spaCy/discussions/7817, the EL training data format from the docs was not complete and could be confusing, as the EL needs gold sentences & entities. 
doc fix
=> update EL training data format in docs

spacy/cli/package.py
* Only prepend the language code if it's not there already - otherwise calling `package` with for instance `name="nl_core_my_pipeline"` would result in an `"nl_nl_core_my_pipeline"` package.
* Nitpicking: add empty newline at the end of the Python files that are written.
enhancement
=> Optionally append lang for packaged model name

spacy/lang/it/stop_words.py
I stumbled upon the fact that "torino" is in the list of stop words for Italian. Torino is the proper name of a city and the token has no other common meanings.
I think the inclusion is unintended since most likely people want it to not be ignored and may even want a NER tagger to detect it.
Bug fix
=> Remove torino from stop words for Italian

spacy/cli/debug_data.py
This was showing (ratio %), so 10% would show as 0.10%. Fix by
multiplying ratio by 100.
Might want to add a warning if this is over a threshold.
Minor fix to display output of debug data.
=> Fix percent unk display in debug data

spacy/cli/pretrain.py
This came up in #7878, but if --resume-path is a directory then loading
the weights will fail. On Linux this will give a straightforward error
message, but on Windows it gives "Permission Denied", which is
confusing.
CLI verification enhancement
=> Check if the resume path points to a directory

spacy/ml/models/entity_linker.py
If the `entity_linker` model is created with `nO=None`, that should still work through shape inference. To accomodate this use-case, use `maybe_get_dim` instead of `get_dim` when deciding on the token width.
I don't think we need to bump the `EntityLinker`'s version number, as this is a bug fix for use-cases that would have otherwise not worked, and won't affect existing, working use-cases.
This came up in https://github.com/explosion/spaCy/discussions/7884.
bug fix
=> Small fix for EL

spacy/cli/debug_model.py, website/docs/api/cli.md
When the `debug model` command was constructed, we attempted to create artificial training data to run the model. I think we don't have to do this anymore, we can assume the same usage as with `spacy train` - i.e. the training data is available in the config or from `overrides` parameters.
This makes the `debug model` command more generally applicable.
Also fix for Transformer listeners.
bug fix & enhancement
=> Fix 'debug model' for transformers + generalize

.github/contributors/juliensalinas.md, website/meta/universe.json
Adding a new entry to spaCy Universe.
Adding the NLP Cloud API to spaCy Universe.
@honnibal suggested that, even if it is a commercial API, it is still ok to add it.
A documentation change (spaCy Universe).
=> Add NLP Cloud API to spaCy Universe

spacy/errors.py, spacy/language.py, spacy/tests/test_language.py
Handle errors while multiprocessing without hanging.
* Return the traceback for errors raised while processing a batch, which can be handled by the top-level error handler
* Allow for shortened batches due to custom error handlers that ignore errors and skip documents
Notes:
* The behavior between for errors raised by `nlp.make_doc` is currently slightly different with and without multiprocessing. For multiprocessing, an exception in `nlp.make_doc` is returned and handled in the same way as exceptions from the pipeline components using the default error handler. Without multiprocessing, an error in `nlp.make_doc` will be raised directly from `nlp.pipe` instead of being handled by the default error handler.
* Depending on whether a component has implemented `pipe`, when a batch is skipped …
=> Handle errors while multiprocessing

spacy/cli/templates/quickstart_training.jinja
The behavior of `spacy.Corpus.v1` is unexpected enough for `max_length != 0` that `0` is a better default for users creating a new config with the quickstart.
If not, documents are skipped, sometimes the entire corpus is skipped, and sometimes documents are (quite unexpectedly for your average user) split into sentences.
?
=> Switch default train corpus max_length to 0 in quickstart

spacy/training/batchers.py
Looks like `spacy.batch_by_words.v1` wasn't correctly passing onwards the `tolerance` parameter.
Should we bump its version to v2?
bug fix
=> ensure tolerance is properly passed on

spacy/language.py, spacy/tests/pipeline/test_tok2vec.py
Related discussion: https://github.com/explosion/spaCy/discussions/8104
The new `replace_listener` functionality wasn't working correctly for a transformer-based pipeline - cf https://github.com/explosion/spacy-transformers/pull/277. This is because the replacing functionality assumes the standalone component and the in-house equivalent are mapped 1-1, which isn't the case for the Transformer.
This PR allows more complicated listeners to define their behaviour through `model.attrs["replace_listener_cfg"]` and ` model.attrs["replace_listener"]`. 
If we agree with the approach, this PR can be merged by itself as it'll have no influence until https://github.com/explosion/spacy-transformers/pull/277 is merged & released. 
bug fix
=> Support replace_listener for transformers

setup.cfg, spacy/cli/__init__.py
Fixes https://github.com/explosion/spaCy/issues/7732
If `spacy-ray` is installed, it only works when calling `python -m spacy ray`. With this fix, it also works with just `spacy ray` - cf https://github.com/explosion/spaCy/issues/7732 for details.
fix/enhancement
=> ensure 'spacy ray' works

spacy/errors.py, spacy/pipeline/_parser_internals/ner.pyx, spacy/pipeline/transition_parser.pyx, spacy/tests/parser/test_ner.py
- Add test to unlearn entity
- Add custom warning when using the old deprecated format of `!Label`
- Add test to check custom error
- Add `break` when defining the cost for `Begin` to be similar to `Last` and `Unit`
- Add property on `Parser`. If we keep this configuration with the parser, it would be convenient to query it easily.
=> Additions to "neg examples" PR

spacy/lang/char_classes.py, spacy/tests/training/test_training.py
In #8102 it came up that the rupee symbol was treated different from
dollar / euro / yen symbols. This adds many symbols not already
included.
https://en.wikipedia.org/wiki/Currency_Symbols_(Unicode_block)
There are probably other symbols that could be added.
Minor enhancement (?)
=> Add all symbols in Unicode Currency Symbols block

spacy/__init__.py, spacy/errors.py, spacy/matcher/matcher.pyx, spacy/pipeline/entityruler.py, spacy/tests/matcher/test_matcher_api.py, spacy/tests/pipeline/test_entity_ruler.py
This PR is inspired by a bug hunt where it finally appeared that the `entity_ruler` was happily running without patterns...
Show a user warning when an `entity_ruler` or `matcher` runs without patterns having been defined.
We could even consider throwing an error instead. I can't really think of valid use-cases where you'd want the matcher to run without being able to produce matches?
I named the method `require_patterns` in symmetry with `require_labels` though the latter does in fact error instead of warn.
UPDATE: make sure this warning is only raised once. Put `warnings.filterwarnings` statements together in one function in `errors.py` where it feels more central to manage, and provide `filter_warning` wrapper utility.
UX enhancement
=> Show warning if entity_ruler runs without patterns

spacy/pipeline/tok2vec.py, spacy/tests/pipeline/test_tok2vec.py
Stumbled upon a very specific issue thanks to https://github.com/explosion/spaCy/discussions/7651. If the `TextCatEnsemble` architecture is used, in combination with a `Tok2VecListener`, AND there's another component further down the pipeline also using a `Tok2VecListener`, then, and only then, we'll get a crash in Thinc's `concatenate` layer:
```
File "/home/user/.virtualenvs/spacy-experiments/lib/python3.8/site-packages/thinc/layers/concatenate.py", line 68, in backprop
dX += bwd(dY)
TypeError: 'NoneType' object is not iterable
```
This happens because the ensemble textcat architecture is the only one that `concatenate`'s (and backpropagates) results of a `Tok2VecListener`. All other architectures simply use `chain`. And all this works if there is just one listener. But when there are …
=> Ensemble textcat with listener

spacy/pipeline/entityruler.py, spacy/tests/regression/test_issue8168.py
Removed a part of the line that adds a **None** `id` to the pattern in `entityruler`.
Added test for the same bug.
Resolves #8168 
**entityruler.py**:  Line 305 checks and adds an _id_ to `phrase_patterns` if it is passed in the pattern by a user, and Line  304 was also adding an _id_ to `phrase_patterns`.
This was redundant when an _id_ is present in patterns but results in a **None** _id_ when not passed.
=> Fix bug from Entityruler: ent_ids returns None for phrases

spacy/attrs.pyx, spacy/tests/vocab_vectors/test_vocab_api.py
The attributes `PROB`, `CLUSTER` and `SENT_END` are not supported by `Lexeme.get_struct_attr` so should not be included through `attrs.IDS` as supported attributes in `Doc.to_array` and other methods.
Bug fix?
=> Remove unsupported attrs from attrs.IDS

spacy/matcher/phrasematcher.pyx, spacy/pipeline/entityruler.py, spacy/tests/parser/test_ner.py, spacy/tests/pipeline/test_entity_ruler.py, spacy/tests/regression/test_issue8216.py
Before this change, the EntityRuler `add` would add new patterns to internal lists, and then use those lists to add patterns to the internal Matcher and PhraseMatcher. This resulted in the same pattern being added multiple times. 
This adds new patterns one at a time without reference to the internal lists, so the duplicating behavior is avoided.
Bugfix
=> Don't add duplicate patterns all the time in EntityRuler (fix #8216)

spacy/errors.py, spacy/tests/doc/test_creation.py, spacy/tests/doc/test_retokenize_merge.py, spacy/tests/doc/test_retokenize_split.py, spacy/tests/doc/test_token_api.py, spacy/tests/parser/test_parse_navigate.py, spacy/tokens/doc.pyx
Before this change, if heads were passed without deps they would be
silently ignored, which could be confusing. See #8334.
Minor bugfix
=> Raise error if deps not provided with heads

spacy/training/corpus.py
To avoid config errors during training when `[corpora.pretrain.path]` is `None` with the default `spacy.JsonlCorpus.v1` reader, make the reader path optional, similar to `spacy.Corpus.v1`.
Bug fix.
=> Make JsonlReader path optional

spacy/lang/fi/tokenizer_exceptions.py, spacy/tests/lang/fi/test_tokenizer.py
This improves the Finnish language tokenizer by adding the support for common contractions of a conjunction and the negative verb. I also added a new tests cases.
Enhancement
=> [Finnish tokenizer] Support for common contractions

spacy/language.py, spacy/tests/test_language.py
The source models should not be loaded with the vocab from the current pipeline because this loads the vectors from the source model into the current vocab when they should be loaded separately in the pipeline config. If multiple components are sourced from separate pipelines, the current pipeline ends up with the vectors from the last sourced component and no warnings are shown about potentially incompatible vectors because at each point when a component was sourced, the current vectors looked compatible.
The strings are all copied in `Language.create_pipe_from_source`, so if the vectors are configured correctly in the current pipeline, the sourced component will work as expected. If there is a vector mismatch, a warning is shown. (It's not possible to inspect whether the vectors are …
=> Don't use the same vocab for source models

spacy/pipeline/entityruler.py, spacy/tests/matcher/test_matcher_api.py, spacy/tests/matcher/test_matcher_logic.py, spacy/tests/pipeline/test_entity_linker.py, spacy/tests/pipeline/test_entity_ruler.py
Improve UX for W036 around the entity ruler:
* Since an entity ruler may contain only matcher or only phrase matcher patterns, ignore `W036` when calling the internal matchers.
* Check for this warning if the entity ruler has no patterns in tests.
* Filter this warning in other tests where not relevant.
Additional:
* Don't run the entity ruler itself as part of the pipeline when adding phrase patterns.
Enhancement.
=> Improve UX for W036 for entity ruler, etc.

website/docs/usage/projects.md
Essentially the documentation for the prodigy projects integration throws an error because the data is passed in the place of the model as documented in #8468 
Fixes #8468 
This is a "bug" fix in the docs so not exactly a bug fix.
=> Fix prodigy project recipe

spacy/cli/package.py, website/docs/api/cli.md
This PR moves some of our internal `README.md` generation for pipeline packages from our internal modelbuilder scripts into the `spacy package` command. The readme mostly includes the information present in the `meta.json`, but in a nicely-formatted and human-readable way. If a `README.md` is already present in the source directory, it's respected and just copied over.
Notes / drawbacks:
* I had to remove the "size" column, which was based on a value we calculate _after_ building the wheel in the modelbuilder. This means that the GitHub releases wouldn't list the size in the table anymore (but it'd still be on the website, since that uses the `meta.json` directly). I think this is okay, though? The GH release will have the actual files attached, so it lists the file sizes anyways.
* If no …
=> Auto-generate README in spacy package

.github/contributors/xadrianzetx.md, spacy/errors.py, spacy/pipeline/entity_linker.py
* Adds error code `E1018`  that mentions knowledge base is not set.
* This error can be raised when user calls `validate_kb()`
* resolves #8280
=> Raise custom error in EntityLinker when KB is not set

website/src/templates/models.js
Fixes that the links are like:
https://github.com/explosion/spacy-models/releases//tag/en_core_web_sm-3.0.0
The link still works, but who knows if in the future GitHub would prevent this from working.
=> Fix double slash in model release web page

spacy/tests/test_language.py, website/docs/usage/linguistic-features.md
The docs show a custom whitespace tokenizer. Adjusting that example to not use a `sep` in the `text.split` call, as that could easily [lead to empty strings](https://docs.python.org/3.3/library/stdtypes.html?highlight=split#str.split), which are prohibited as tokens by spaCy. Ofcourse this is a silly example, but it could quickly become confusing to users when `E031` gets thrown.
small docs fix
=> adjust whitespace tokenizer to avoid sep in split()

website/docs/usage/models.md
"dowmload" -> "download"
Just a PR to fix a typo in the documentation on the [models page](https://spacy.io/usage/models). 
Changes a typo in a suggested command on the models page. Just to be extra sure, I tried out the command. (It doesn't work 😄.)
```sh
$ python -m spacy dowmload en_core_web_sm
Usage: python -m spacy [OPTIONS] COMMAND [ARGS]...
Try 'python -m spacy --help' for help.
Error: No such command 'dowmload'.
```
=> Fix a command typo in models.md

spacy/cli/evaluate.py
This isn't perfectly elegant, but it'd be very useful to be able to access the logic that outputs the scores per type separately (e.g. for Prodigy). I tried to avoid code duplication, so the helper currently takes an optional existing dict that it updates and returns 🤷‍♀️
enhancement
=> Move scores per type handling into util function

spacy/pipeline/spancat.py, spacy/tests/pipeline/test_spancat.py
Two small `spancat` fixes
- The spancat is not resizable (adding a label won't change the output `nO`) so make sure to raise an error when this is attempted
- Allow the `initialize` method to take in examples without actual spans if the labels were added explicitely
Added unit tests for both cases + some additional ones for basic behaviour
bug fix
=> Small spancat fixes

spacy/cli/_util.py, spacy/cli/evaluate.py, website/docs/usage/processing-pipelines.md
The `evaluate` command calls `setup_gpu` but the latter doesn't respect the `silent` setting because it defines a new `Printer`. Adding an option to pass the `silent` parameter forward.
bug fix
=> Fix silent evaluation

requirements.txt, setup.cfg, spacy/ml/_precomputable_affine.py, spacy/ml/models/parser.py, spacy/ml/tb_framework.py, website/docs/api/architectures.md, website/docs/api/legacy.md
Move TransitionBasedParser.v1 to `legacy` - https://github.com/explosion/spacy-legacy/pull/11 must be merged & released first. Keeping in Draft until then.
chore
=> TransitionBasedParser.v1 to legacy

spacy/cli/init_pipeline.py, spacy/pipeline/spancat.py, spacy/tests/test_cli.py
`spancat.initialize` had the wrong type definition for its `labels`, causing an error:
```
✘ Error validating initialization settings in [initialize.components]
spancat -> labels   value is not a valid dict
```
This PR fixes that, and adds a unit test for `init labels`.
bug fix
=> fix spancat initialize with labels

spacy/pipeline/spancat.py, spacy/tests/pipeline/test_spancat.py, website/docs/api/spancategorizer.md
I think it would be more consistent to call the default n-gram suggester `spacy.ngram_suggester.v1` instead of (just) `ngram_suggester.v1`? The docs we wrote use both so we already confused ourselves. I added the prefix to the official name in this PR.
fix
=> add spacy prefix to ngram_suggester.v1

.github/workflows/autoblack.yml
The autoblack job is an occasional cleanup job. If it runs on forks and
those PRs are accepted the git history will be weird and that doesn't
help anyone.
The way to make the job not run on forks is a little non-obvious but
based on this thread.
https://github.com/prisma/prisma/issues/3539
Actions related bug fix?
=> Make the autoblack job not run on forks

spacy/ml/models/multi_task.py
Use 0-vector for OOV lexemes in `PretrainVectors` loss. Otherwise the effective result is `vectors[-1]` for unknown vectors, which differs from `StaticVectors.v2` (related bug fix: #7674).
Bug fix.
=> Use 0-vector for OOV lexemes in PretrainVectors

spacy/pipeline/spancat.py, spacy/tests/pipeline/test_spancat.py, website/docs/api/spancategorizer.md
Adding `spacy.ngram_range_suggester.v1` for a more concise config file if we need large ranges (rather than using a large list of intes)
feature
=> spacy.ngram_range_suggester.v1

website/meta/universe.json
From the documentation of spacymoji (and the requirements.txt) it seems like it is not only for version 2.
=> [minor] removed outdated spacy version for spacymoji

spacy/tests/doc/test_span.py, spacy/tokens/span.pyx
Fix start/end chars for empty and out-of-bounds spans
Bug fix.
=> Fix start/end chars for empty and out-of-bounds spans

spacy/errors.py, spacy/matcher/dependencymatcher.pyx, spacy/tests/matcher/test_dependency_matcher.py
If a non-anchor node does not have RIGHT_ATTRS, the dep matcher throws
an E100, which says that non-anchor nodes must have LEFT_ID, REL_OP, and
RIGHT_ID. It specifically does not say RIGHT_ATTRS is required.
An empty dict for RIGHT_ATTRS is also valid, and patterns with one will be
accepted. While not normal, sometimes a REL_OP is enough to specify a
non-anchor node - maybe you just want the head of another node
unconditionally, for example.
This change just sets RIGHT_ATTRS to {} if not present. Alternatively
changing E100 to state RIGHT_ATTRS is required could also be reasonable.
Became aware of this issue while looking at https://github.com/explosion/spaCy/discussions/8803. 
Bug fix?
=> Fix check for RIGHT_ATTRS in dep matcher

spacy/cli/train.py
Add info message when no output directory was provided in `spacy train` CLI
=> No output info message in train

spacy/pipeline/spancat.py, spacy/tests/pipeline/test_spancat.py, website/docs/api/spancategorizer.md
This exposes the scores as an attribute on the SpanGroup. Includes a
basic test.
Scores can now be accessed in spancat output for all spans.
```
doc = nlp(...)
spans = doc.spans["spancat"] # SpanGroup
print(spans.attrs["scores"]) # list of numbers, span length as SpanGroup
```
Minor enhancement.
(Docs update still needed)
=> Add scores to output in spancat

spacy/pipeline/spancat.py, spacy/tests/pipeline/test_spancat.py
PR https://github.com/explosion/spaCy/pull/8855 introduced a bug that would sometime lead to indexing errors, when there is only one candidate entity:
```
File "...\spacy\spacy\pipeline\spancat.py", line 421, in _make_span_group
keeps[ranked[:, max_positive:]] = False
IndexError: index 1 is out of bounds for axis 0 with size 1
```
Upon inspection, it became clear that this line
``` 
keeps[ranked[:, max_positive:]] = False
```
wasn't doing exactly what we wanted (put the correct indices to `False`) as examplified by the (previously failing) unit tests of this PR.
I rewrote the line into a longer `for`-loop to ensure we have the correct behaviour. If anyone knows the correct indexing voodoo to make this shorter ánd keep the tests green, I'm happy to make that adjustement ;-) 
bug fix
=> Fix making span_group

.github/contributors/bbieniek.md, website/meta/universe.json
Added Spacy API v3 docker
Currently, the universe only contains Spacy API in v2. 
I have added docker images for v3.
Added to universe docker images for Spacy V3.
=> Added Spacy API v3 docker

spacy/errors.py, spacy/tests/pipeline/test_spancat.py, spacy/tokens/span_group.pyx, website/docs/api/spangroup.md
`SpanGroup.doc` uses a `weakref.ref` to refer to the `Doc` without causing circular references. Unfortunately this means that something like this will fail:
```
all_spans = [doc.spans for doc in nlp.pipe(texts)]
print(all_spans)
```
because the `SpanGroup` objects within `all_spans` will refer to dead referents.
In this PR, we raise a custom error to explain why this happens & to avoid it + document this behaviour in the API docs.
> RuntimeError: [E866] A SpanGroup is not functional after the corresponding Doc has been garbage collected. To keep using the spans, make sure that the corresponding Doc object is still available in the scope of your function.
I'm not sure there's a solution where we can avoid the whole issue entirely...
UX & docs
=> Warn and document spangroup.doc weakref

spacy/glossary.py
This adds a glossary entry for the `_SP` tag, which is used for whitespace that gets a tag rather than being subsumed. This wasn't documented anywhere, as pointed out in #8982. 
It's possible this was `SP` at some point in the past but was changed. In Chinese OntoNotes SP is used for "sentence [final] particles", which is unrelated.
I guess this should also be added to model docs?
Glossary addition.
=> Add glossary entry for _SP (fix #8982)

requirements.txt, setup.cfg, spacy/cli/package.py, spacy/tests/test_cli.py
The logic for automatically adding third-party dependencies to the package requirements in `spacy package` only checked for registered functions (`@` keys) in the config. However, component factories are also often provided via a third-party packages and weren't covered, because they are specified as `factory =`. This PR includes them.
enhancement
=> Include component factories in third-party dependencies resolver

spacy/lang/fr/tokenizer_exceptions.py
=> Fix verbs list in lang/fr/tokenizer_exceptions.py

extra/DEVELOPER_DOCS/Listeners.md
First stab at the dev documentation for the listener pattern.
Preview: https://github.com/svlandeg/spaCy/blob/docs/dev-docs-listeners/extra/DEVELOPER_DOCS/Listeners.md
This isn't just documenting one part of the code, but rather spans various parts of the code across both `spacy` and `spacy-transformers`. The docs aim to explain how it all kind of fits & work together. 
docs
=> Dev docs: listeners

spacy/errors.py, spacy/training/pretrain.py
When an epoch_resume value is not specified individually, it can often
be inferred from the filename. The value inference code was there but
the value wasn't passed back to the training loop.
This also adds a specific error in the case where no epoch_resume value
is provided and it can't be inferred from the filename.
This does not handle the case where a value can be inferred from the filename and an epoch resume value is explicitly passed. In that case the explicitly passed value will be ignored, which seems a bit weird. Should there be a warning or error or something instead?
Bug fix
=> Fix inference of epoch_resume

spacy/cli/_util.py, spacy/cli/project/assets.py, spacy/tests/test_cli.py, website/docs/usage/projects.md
In the case of the first asset I wanted to get from git, the data I wanted was the entire repository. I tried leaving "path" blank, which gave a less-than-helpful error, and then I tried `path: "/"`, which started copying my entire filesystem into the project. The path I should have used was "".
I've made two changes to make this smoother for others:
- The 'path' within a git clone defaults to ""
- If the path points outside of the tmpdir that the git clone goes into, we fail with an error
This is an ergonomics/bug fix, with a corresponding change in the documentation to describe the added default.
(Instead of submitting the Contributor Agreement, I have added a `Signed-off-by` line to the commit, which I understand is the new practice.)
=> Fix surprises when asking for the root of a git repo

spacy/cli/package.py, spacy/tests/test_cli.py, spacy/util.py
Handle spacy-legacy in package CLI for dependencies
Bug fix.
=> Handle spacy-legacy in package CLI for dependencies

spacy/ml/models/parser.py
Dear SpaCy team,
I think there was a mistake in the documentation: In (e.g.) NER, the parser uses an additional network to predict the action/state scores in the transition-based parsing stage when using a small, non-transformer network.
Kind regards,
Johann
Documentation update
=> Correct parser.py use_upper param info

spacy/attrs.pyx, spacy/kb.pyx, spacy/lang/en/lemmatizer.py, spacy/lexeme.pyx, spacy/matcher/dependencymatcher.pyx, spacy/matcher/matcher.pyx, spacy/pipeline/_parser_internals/arc_eager.pyx, spacy/strings.pxd, spacy/strings.pyx, spacy/tests/lang/ky/test_tokenizer.py, spacy/tokenizer.pxd, spacy/tokenizer.pyx, spacy/tokens/_serialize.py, spacy/tokens/doc.pyx, spacy/tokens/span.pyx, spacy/tokens/token.pyx, spacy/vocab.pxd, spacy/vocab.pyx
`basestring` was a compatibility type introduced by Cython to make
dealing with utf-8 strings in Python2 easier. In Python3 it is
equivalent to the unicode (or str) type. 
I replaced all references to basestring with unicode, since that was
used elsewhere, but we could also just replace them with str, which
should also be equivalent.
All tests pass locally.
cleanup
=> Update Cython string types

spacy/cli/package.py
Previously, the external package dependency detection in `spacy package` would include the entire config, including sections not relevant at runtime. So if the `[training]` or `[initialize]` block included references to registered functions exposed by third-party packages, these packages would become dependencies of the packaged pipeline. That's unideal, so this PR only includes the runtime-relevant sections `nlp` and `components`.
fix / enhancement (?)
=> Only include runtime-relevant config in package CLI dependency detection

spacy/errors.py, spacy/tests/doc/test_creation.py, spacy/tests/doc/test_token_api.py, spacy/tokens/doc.pyx, spacy/tokens/token.pyx
When you pass pos values to a Doc they aren't validated. Before this change, any value could be set via `Doc.__init__`, but if you tried to access `.pos_` on an invalid value you would get a `KeyError`.
In contrast, if you try to set an invalid pos value directly you get a `KeyError` immediately.
This checks if pos values are valid, and if not throws an error that explains they must be UD values, and other tags should use the `tag` field.
See #9145 for motivating case.
Added validation
=> Validate pos values when creating Doc

spacy/cli/project/assets.py
`spacy project run` allows overriding arguments through the command-line (e.g. `--vars.gpu=-1`). Overriding variables is not supported by the `spacy project assets` subcommand. However, this would be handy when e.g. a data repository contains multiple corpora and one wants to fetch a different corpus based on the variable set.
This change makes the `project assets` subcommand accept variables to override as well, making the interface more similar to `project run`.
Enhancement
With regards to the last checkbox: from the current documentation I inferred that it would be possible to override variables with `project assets` as well, until I found out you can't 😅.
=> Allow overriding vars in the project assets subcommand

spacy/cli/project/run.py
Avoid crash when there's unicode in a project title and console doesn't support unicode well enough. Prints "?" instead.
bug fix
=> avoid crash when unicode in title

spacy/errors.py, spacy/tokens/_serialize.py
This came up when testing user's code from the forum.
If the `attrs` list in the `DocBin` constructor receives a wrong value, `intify_attr` produces `None` and the code crashes because `None` can't be sorted. This PR catches this situation and produces a more helpful error message.
Also expanded on the `E923` error msg.
UX
=> Raise E983 early on in docbin init

spacy/tests/training/test_training.py, spacy/tokens/_serialize.py
If you create a DocBin with `store_user_data = False`, the data won't be included in `to_bytes`, but it will still be serialized as soon as it's added to the DocBin. If you have a non-serializable item in user data, this means you can get an error about that even though you don't want to serialize it, which is confusing. See #9190 
This just doesn't save user data if `store_user_data` is `False`. Another option would be to save empty user data. That might be better if someone changes the value on an existing DocBin, but that sounds like a terrible idea in general.
Convenience fix.
=> Don't serialize user data in DocBin if not saving it (fix #9190)

spacy/lang/ja/__init__.py, spacy/tests/lang/ja/test_lemmatization.py, spacy/tests/lang/ja/test_morphologizer_factory.py, spacy/tests/lang/ja/test_tokenizer.py, website/docs/usage/models.md
This moves most of the extra Japanese tokenizer info that was in `user_data` into a `Token.morph`. 
It also adds the normalized form SudachiPy provides, which previously wasn't exposed at all. 
The one thing that's not moved into `Token.morph` is subtokens. This is a list of full token information, but it's only populated for some words with non-default tokenizer settings. Since it's just a list of `None` with the default tokenizer settings, in that case I changed it to not set `user_data` at all. With non-default settings the behavior regarding subtokens is unchanged.
As a result of this, with default tokenizer settings the Japanese tokenizer no longer modifies `user_data`. 
The docs didn't previously mention any of the `user_data` info, so I'm adding a short section on the current data …
=> Moving Japanese tokenizer extra info to Token.morph

spacy/language.py, spacy/training/initialize.py
Since a component may reference anything in the vocab, share the full vocab when loading source components and vectors (which will include `strings` as of #8909).
When loading a source component from a config, save and restore the vocab state after loading source pipelines, in particular to preserve the original state without vectors, since `[initialize.vectors] = null` skips rather than resets the vectors.
The vocab references are not synced for components loaded with `Language.add_pipe(source=)` because the pipelines are already loaded and not necessarily with the same vocab. A warning could be added in `Language.create_pipe_from_source` that it may be necessary to save and reload before training, but it's a rare enough case that this kind of warning may be too noisy overall.
Bug fix.
=> Sync vocab in vectors and components sourced in configs

website/meta/universe.json
Add [WordDumb](https://github.com/xxyzz/WordDumb/) to spaCy Universe. WordDumb uses spaCy to find named entities in books to create Kindle X-Ray file.
Update `universe.json`.
I only run `.github/validate_universe_json.py` on `universe.json`, I guess this commit won't affect other tests...
=> Add WordDumb to spaCy Universe

spacy/tests/conftest.py, spacy/tests/lang/tl/test_indices.py, spacy/tests/lang/tl/test_punct.py, spacy/tests/lang/tl/test_text.py
Improving spaCy language support for Tagalog (Austronesian) by adding tests (cf. https://github.com/explosion/spaCy/discussions/3056)
Added a few tests on the Tagalog language, some of which I patterned from the English language test structure.
**Note:** there are some tests that I plan to add but unsure if correct (mostly pertaining to contractions and their corresponding number of tokens, similar to [this](https://github.com/explosion/spaCy/blob/master/spacy/tests/lang/en/test_exceptions.py). I decided to leave them out first:
- *Sa'yo* is a contraction of "sa iyo" ("to you", "yours" [possessive]) 
- *Sa'kin* -> "sa akin" ("to me", "mine" [possessive]). It was given to me (*Binigay sa'kin*), That's mine! (*Sa'kin iyan!*)
- *Ako'y* -> "ako ay estudyante" ("i am a student")
- ... and …
=> Add initial Tagalog (tl) tests

spacy/cli/templates/quickstart_training.jinja
Something is going wrong with the expression conversion or evaluation on the javascript side, but separating the expression into smaller components seems to at least temporarily fix the problem.
?
=> Fix tok2vec-less textcat generation in website quickstart

spacy/errors.py, spacy/tests/test_errors.py
When trying to pickle with dill, as happens under the hood when processing a HuggingFace `dataset`, I found that spaCy couldn't be pickled (related issue: https://github.com/huggingface/datasets/issues/3178). I found that the cause was `dill.Pickler` that recursively pickled all objects (`Pickler(file, recurse=True).dump(obj)`). This is preferred in `datasets`: such iterative pickling allows for fingerprinting, i.e. keeping track of all the processing done to a dataset, deterministically. If the fingerprint is the same as an earlier processing attempt, then a cache can be used and the processing (e.g. tokenizing with spaCy) does not have to be done again. Very useful and great to save time and processing.
The culprit in the spaCy codebase that could not be pickled in this way, was this …
=> Use metaclass to subclass errors to allow better pickling

spacy/training/corpus.py
In #8396 the path arg to the JsonlCorpus was made optional. This was done so that you could use a config with a pretraining section for training without including the raw text path. However, #9167 made the path non-optional again, apparently inadvertently. 
minor fix
=> Make Jsonl Corpus reader path optional again

spacy/ml/extract_spans.py, spacy/pipeline/spancat.py, spacy/tests/pipeline/test_spancat.py
Fix spancat for empty docs and zero suggestions
Bug fix.
=> Fix spancat for empty docs and zero suggestions

spacy/language.py, spacy/training/initialize.py
Exclude strings from `Vector.to_bytes()` comparions for v3.2+ `Vectors` that now include the string store so that the source vector comparison is only comparing the vectors and not the strings.
Bug fix.
=> Exclude strings from v3.2+ source vector checks

website/docs/api/architectures.md
Using listeners requires batches to be consistent. This is obvious if
you understand how the listener works, but it wasn't clearly stated in
the Docs, and was subtle enough that the EntityLinker missed it.
There is probably a clearer way to explain what the actual requirement
is, but I figure this is a good start.
This issue was raised by #9669.
=> Add note on batch contract for listeners

spacy/errors.py, spacy/pipeline/entityruler.py, spacy/tests/pipeline/test_entity_ruler.py
Improve the error messages for bad .jsonl paths and bad directories.
Minor enhancement
=> EntityRuler improve disk load error message 

spacy/cli/package.py, spacy/language.py, spacy/tests/test_cli.py
If a component factory is registered like `@French.factory(...)` instead
of `@Language.factory(...)`, the name in the factories registry will be
prefixed with the language code. However in the nlp.config object the
factory will be listed without the language code. The `add_pipe` code
has fallback logic to handle this, but packaging code and the registry
itself don't.
This change makes it so that the factory name in nlp.config is the
language-specific form. It's not clear if this will break anything else,
but it does seem to fix the inconsistency and resolve the specific user
issue that brought this to our attention (#9652). 
Bug fix, probably?
- [] I ran the tests, and all new and existing tests passed.
=> Fix Language-specific factory handling in package command

spacy/displacy/__init__.py, spacy/tests/test_displacy.py, website/docs/api/top-level.md
The PR adds support for visualizing kb_id on entities when run via displacy.serve
The PR adds support for visualizing kb_id on entities when run via displacy.serve. The recent changes from [PR 9199](https://github.com/explosion/spaCy/pull/9199) only address rendered html produced with the `manual=True` option set. I believe the same should also be afforded when passing `Doc` objects with entities that have the `kb_id` set. 
For the `kb_url` to be set, one can pass the `kb_url_format_template` (can be named better?) in the `options` argument of `displace.serve`. If not set, `kb_url` defaults to `#` similar to the setting in the above linked PR. Please suggest if there is a better way to do this.
Enhancement
=> Displacy serve entity linking support without `manual=True` support.

spacy/pipeline/morphologizer.pyx, spacy/pipeline/tagger.pyx
The `labels` property converts the dictionary key set to a tuple. This property was used for every annotated token, recreating the tuple over and over again.
Construct the tuple once in the set_annotations function and reuse it.
On a Finnish pipeline that I was experimenting with, this results in a speedup of ~15% (~13000 -> ~15000 WPS).
=> morphologizer: avoid recreating label tuple for each token

spacy/lang/char_classes.py
This includes the main kana, or phonetic characters, used in Japanese. Not having these in the tokenizer exception list means that when they are used in non-Japanese text they behave strangely, and can combine with punctuation.
There are some supplemental kana blocks in Unicode outside the BMP that
could also be included, but because their actual use is rare I omitted
them for now, but maybe they should be added. The omitted blocks are:
- Kana Supplement
- Kana Extended (A and B)
- Small Kana Extension
I didn't add a test, not sure if the speed tradeoff is worth it since it seems other similar classes aren't tested.
tokenizer exception adjustment
=> Add Japanese kana characters to default tokenizer exceptions (fix #9693)

spacy/lang/nb/stop_words.py
Default stop words in Norwegian bokmål (nb) in Spacy contain important entities, e.g. France, Germany, Russia, Sweden and USA, police district, important units of time, e.g. months and days of the week, and organisations.
Nobody expects their presence among the default stop words. There is a danger of users complying with the general recommendation of filtering out stop words, while being unaware of filtering out important entities from their data.
See explanation in https://github.com/explosion/spaCy/issues/3052#issuecomment-986756711 and comment https://github.com/explosion/spaCy/issues/3052#issuecomment-986951831
=> Remove NER words from stop words in Norwegian

spacy/tokenizer.pyx
Update the description of `token_match` and `url_match` arguments for Tokenizer
Currently the callables are described as 
> A boolean function
which is not enough as those functions would be serialized with `_get_regex_pattern`. 
Description changed to match the correct requirement - result of `re.compile(string).match`
=> Update Tokenizer documentation 

requirements.txt
Since mypy 0.920 was released, mypy fails with:
```
setup.cfg:140: error: Error importing plugin "pydantic.mypy": cannot import name 'TypeVarDef' from 'mypy.types' (/Users/daniel/.pyenv/versions/torch-1.10/lib/python3.9/site-packages/mypy/types.cpython-39-darwin.so)
```
It seems that we need to wait for a version of pydantic that is compatible
with this new mypy release. So, pin the mypy version for the time being.
Bug fix
=> Pin mypy to 0.910 until there is a compatible pydantic version

spacy/training/converters/conllu_to_docs.py
If a conllu file has no data for a token's part of speech, `conllu_sentence_to_doc()` throws an error that `'_'` is not a valid upos value.  
To allow tokens with no pos data, this PR changes the "_" to "" to allow pos assignment during `spacy convert` from conllu. It's a small change that will help our users with less than complete and polished treebanks. 
Handles an exception when UD has a upos value of `"_"`.
=> Handle "_" value for token pos in conllu data

spacy/ml/models/tok2vec.py, website/docs/api/architectures.md
Fixes a typo in the tok2vec documentation for describing what happens with static vectors in MultiHashEmbed.
Documentation
=> MultiHashEmbed Docs correction

spacy/lexeme.pyi
On recent PRs, the CI is failing over a `lexeme.rank` assignement. I actually think the CI is right, and that the `pyi` file is wrong, though I don't understand why we didn't see this error before and why it only occurs in older Python versions.
Anyway, let's see if this fix makes the CI happy, because I can't reproduce the original error locally.
bug fix
=> Fix type of lexeme.rank

spacy/default_config.cfg
Added a few lines of explanation for `patience`, `max_epochs`, and `max_steps`. 
Even if their definitions are defined in the [config training docs](https://spacy.io/api/data-formats#config-training) and [FAQ](https://github.com/explosion/spaCy/discussions/8226) it's not the first thing they encounter. Usually, [this training config page](https://spacy.io/usage/training#config) is what they see. I just copied over some definitions to the config file itself. 
Ref: #7450 #7465
Doc change
=> Add a few docs to the default_config.cfg

spacy/cli/project/assets.py
I ran into an issue where, if downloading an asset (without a checksum) failed in a way that left a 0-byte file on disk, the next run of `spacy project assets` would assume the asset doesn't need to be redownloaded. 0-byte files are probably never what we want, so if that's the case, let's delete it so it will reattempt the download (and warn the user):
Bug fix
=> Check for assets with size of 0 bytes

spacy/pipeline/_parser_internals/ner.pyx, spacy/tests/doc/test_span.py, spacy/tokens/span.pxd, spacy/tokens/span.pyx, spacy/tokens/span_group.pxd, spacy/tokens/span_group.pyx
When a `Span` that was retrieved from a `SpanGroup` was modified, these changes were not reflected in the `SpanGroup` because the underlying `SpanC` struct was copied.
This change applies the solution proposed by @nrodnova, to wrap `SpanC` in a `shared_ptr`. This makes a `SpanGroup` and Spans derived from it share the same `SpanC`. So, changes made through a `Span` are visible in the `SpanGroup` as well.
Enhancement
=> Span/SpanGroup: wrap SpanC in shared_ptr

spacy/pipeline/textcat.py, spacy/tests/pipeline/test_textcat.py
This PR fixes issue #9904 by removing the division by the batch size and the summation accross classes before the mean is applied in `TextCategorizer#get_loss`.
#9904 
enhancement/bug fix
=> Fix texcat loss scaling (#9904)

spacy/pipeline/_parser_internals/_state.pxd
`StateC::L` gets the n-th most-recent left-arc with a particular head.
Before this change, `StateC::L` would construct a vector of all left-arcs
with the given head and then pick the n-th most recent from that vector.
Since the number of left-arcs strongly correlates with the doc length
and the feature is constructed for every transition, this can make
transition-parsing quadratic.
With this change `StateC::L`:
- Searches left-arcs backwards.
- Stops early when the n-th matching transition is found.
- Does not construct a vector (reducing memory pressure).
This change doesn't avoid the linear search when the transition that is
queried does not occur in the left-arcs. Regardless, performance
improves quite a bit with very long docs (benchmarked by repeating
a Wikipedia paragraph N times): …
=> Speed up the StateC::L feature function

website/docs/usage/processing-pipelines.md
Url extension in https://spacy.io/usage/processing-pipelines#component-example3 is no longer available
Replacing https://restcountries.eu/rest/v2/all for https://restcountries.com/v2/all
Only changing an URL. No further test is required.
Changed the script within documentation
- [] I ran the tests, and all new and existing tests passed.
=> Update usage example url for GPE span labeling

spacy/tests/doc/test_doc_api.py, spacy/tokens/doc.pyx
Fix spaces in `Doc.from_docs(ensure_whitespace=True)` for cases where a doc ending in whitespace is followed by an empty doc.
Bug fix.
=> Fix spaces in Doc.from_docs for empty docs

spacy/lexeme.pyx, spacy/tests/vocab_vectors/test_similarity.py, spacy/tokens/span.pyx, spacy/tokens/token.pyx
In the past, calls to `Lexeme.similarity()`, `Span.similarity()` and `Token.similarity()` have returned inconsistent return types: depending on whether or not matrix multiplication was performed to determine the similarity and whether or not Numpy (CPU) or Cupy (GPU) was in use, the return value could be a native Python float, a Numpy float or a Cupy array. This pull request duplicates the pre-existing behaviour of `Doc.similarity()` and ensures that all return values are native floats.
Bug fix
=> Bugfix for similarity return types

spacy/displacy/render.py
displaCy's color list includes FACILITY instead of FAC, but the English models use FAC. (Based on the presence of FACILITY in some places maybe it used to be the other way?) 
This change makes the colors match the model.
I noticed this because of #10042, which I think is reporting this issue.
bug fix
=> Rename FACILITY to FAC in color list

spacy/pipeline/_parser_internals/_state.pxd
This PR changes the type of left/right-arc collections from `vector[ArcC]` to `unordered_map[int, vector[Arc]]`, so that the arcs are keyed by the head. This allows us to find all the left/right arcs for a particular head in constant time in `StateC::{L,R}`.
Benchmarks with long docs (N is the number of text repetitions):
Before (using #10019):
```
N  Time (s)
400   3.2
800   5.0
1600   9.5
3200  23.2
6400  66.8
12800  220.0
```
After (this commit):
```
N   Time (s)
400   3.1
800   4.3
1600   6.7
3200  12.0
6400  22.0
12800  42.0
```
Related to #9858 and #10019.
=> Use constant-time head lookups in StateC::{L,R}

website/Dockerfile, website/README.md
Adds a `Dockerfile` for a repeatable build of the website with a working version of node/npm and instructions for accessing the images through the github container registry for others to use.
Documentation
=> Docker Image for Website Dev

website/meta/universe.json, website/src/templates/universe.js
Display the supported version of spaCy at the top of universe projects. Can be specified in the `universe.json` as either `"spacy_version": 3` or `"spacy_version": [2, 3]` etc. Also add note about reporting non-working projects at the bottom. Open to wording suggestions here.
docs
=> Support version tags in universe and add note about reporting

setup.cfg, spacy/language.py, spacy/matcher/dependencymatcher.pyi, spacy/matcher/matcher.pyi, spacy/matcher/phrasematcher.pyi, spacy/tokens/doc.pyi, spacy/tokens/underscore.py
This PR is a follow up on #8427. Improves typing hints for `Matcher`, `PhraseMatcher`, `Language` and `Doc`, and adds new ones for `Underscore` extensions and `DependencyMatcher`.
Typing hints for the following classes have been created/updated:
Overloaded return type of `Matcher.__call__()` depending on whether `as_spans` is `True` or `False`.
Fixed return type for `Language.component()` decorator.
Fixed `np.ndarray` type for `Doc.tensor`.
Adds typing hint support for `DependencyMatcher`.
Treats underscore extension values as `Any` types. Typing hints for underscore extensions were not set before and all accesses to `Object._.extension` were of type `Unknown`. With the current implementation, access to any extension returns an object of type `Any`, so the user can redefine the type upon …
=> Update typing hints

spacy/lang/xx/examples.py
* This comma has been most probably been left out unintentionally, leading to string concatenation between the two consecutive lines. This issue has been found automatically using a regular expression.
It's a small bugfix
=> fix: Add missing comma to `examples.py`

spacy/tokens/span.pyx, website/docs/api/span.md
Ref: #10135
Retain current behaviour. Span.ents will only include entities within
said span. You can't get tokens outside of the original span.
Documentation update
=> Clarify Span.ents documentation

website/docs/api/corpus.md
Update docs for `Corpus` to include the `shuffle` parameter (cf. https://github.com/explosion/spaCy/blob/master/spacy/training/corpus.py#L103)
=> Add shuffle parameter to Corpus API docs

spacy/lang/fi/__init__.py, spacy/lang/fi/syntax_iterators.py, spacy/tests/lang/fi/test_noun_chunks.py
Add a noun chunker for Finnish.
(One unrelated test case (test_Example_aligned_whitespace) is failing, but since the same test case fails also on the current develop branch head I am quite sure it's not related my changes.)
Enhancement
=> Add a noun chunker for Finnish

.github/workflows/gputests.yml, .github/workflows/slowtests.yml
Adds two github actions to trigger matrices of automated buildkite builds on the `master`, `develop`, and `v4` branches - daily for slow tests, weekly for GPU tests
Tests only
=> Add github actions for slow and gpu tests

spacy/util.py
Support mixed case model package names
The current status seems to be:
* pip and setuptools support mixed case names, although case isn't significant in package names
* you can load a package with uppercase characters with `spacy.load()` or with a direct `import`
* `spacy validate` and the CI CLI tests fail on cases with uppercase characters
I don't see any evidence of the bug mentioned in 8dbe49ec in tests with current versions of setuptools and pip.
?
=> Support mixed case model package names

website/meta/universe.json
Add the [`textnets` package](https://github.com/jboynyc/textnets) to spaCy Universe.
No tests needed.
Documentation only.
=> add textnets to spaCy Universe

.github/workflows/gputests.yml, .github/workflows/slowtests.yml
Based on this morning's [errors](https://github.com/explosion/spaCy/actions/runs/1815380183), hopefully fixing the syntax
=> fix the syntax for the slow/gpu test crons

.github/workflows/gputests.yml, .github/workflows/slowtests.yml
`develop` will not be an active branch anymore in the near future, so canceling the daily/weekly tests to avoid spending unnecessary resources.
repo org, automated tests
=> Remove daily/weekly tests for develop branch

spacy/lang/ko/__init__.py
Delay loading of mecab until the tokenizer is called the first time so that it's possible to initialize a blank `ko` pipeline without having mecab installed, e.g. for use with `spacy init vectors`.
In addition, remove `KoreanTokenizer.__del__`, which appears to lead to additional ignored exceptions rather than fewer with the current version of mecab.
?
=> Delay loading of mecab in Korean tokenizer

spacy/tests/test_cli.py, spacy/training/converters/conllu_to_docs.py
Leave ents unset if no NER annotation is found in the MISC column.
Bug fix.
=> Fix NER check in CoNLL-U converter

spacy/pipeline/_parser_internals/nonproj.pyx, spacy/tests/parser/test_nonproj.py
While profiling the parser, I noticed that relatively a lot of time is spent in projectivization. This change rewrites the functions in the core loops as `cdef nogil` for efficiency.
In C++-land, we use vector in place of Python lists and absent heads are represented as `-1` in place of `None`.
Profile in the refactored parser, before:
After:
We still need to expose `_get_smallest_nonproj_arc` as a Python function for tests, but I couldn't think of anything better than `get_smallest_nonproj_arc_slow` 😅.
=> Make core projectivization functions cdef nogil

spacy/errors.py, website/docs/api/legacy.md, website/docs/api/top-level.md
Further cleanup after we previously moved the logger functionality to https://github.com/explosion/spacy-loggers
docs fix
=> Clean up loggers docs

spacy/util.py
Even though it was in the docstring, `load_model_from_config` wasn't taking in a `meta` argument, which meant that `load_model_from_path` wasn't using the input arg `meta` either.
bug fix
=> hook up meta in load_model_from_config

website/docs/usage/processing-pipelines.md, website/docs/usage/saving-loading.md
Updates docs to add `path.mkdir()` to the custom component examples that include a `to_disk` method.
Documentation
=> Add `path.mkdir` to custom component examples of `to_disk`

spacy/displacy/render.py, spacy/tests/test_displacy.py
displacy: avoid overlapping arcs in manual mode
Resolves #5447
Two arcs with the same start and end index will currently display as overlapped. I think this will only occur in manual mode (see issue above). The fix keys the levels assigned to the arcs by `(start, end, label)` (instead of `end-start`). Each arc is compared to the current levels across its span, stored in the list `max_level`.
(I was in two minds about submitting this PR - it takes a nice one-liner and turns it into a chunk of code for a fringe use-case... Happy for ideas for improvements or to drop it entirely 😄).
This PR is a bug fix for #5447.
=> displacy: avoid overlapping arcs in manual mode

spacy/errors.py, spacy/glossary.py
`spacy.explain()` queries a glossary that is not exhaustive for all languages or token attributes. In many cases where it does not find a definition for a given abbreviation, the abbreviation will be defined in documentation for corpora used to train the model. When `spacy.explain()` returns no output, this PR causes a message to be displayed pointing the user to such corpus documentation.
Enhancement / new feature
=> Display warning when spacy.explain() finds no term

spacy/tokens/span_group.pyx, website/docs/api/doc.md, website/docs/api/spangroup.md
This updates SpanGroup docs examples to align with their expected results.
A couple of the SpanGroup examples had assertions that failed, and there was a missing attr lookup ("label_") which resulted in an unintended comparison--comparing a Span with a string ("LABEL"), rather than comparing the Span label_ with the string (to assert that the Span label_ had not changed from a previous operation).
Change to documentation
===
Note (for a related issue): I also noticed that one of the Spans repeatedly used in SpanGroup examples didn't quite seem to reflect what I interpreted the example as intending. Specifically: given that the Doc string is "Their goi ng home", the SpanGroup with the name "errors" is created in several examples, with the Spans doc[0:1] and doc[2:4], which refer to spans …
=> Fix a few minor bugs in the SpanGroup API web docs

.github/contributors/fonfonx.md, spacy/lang/fr/lex_attrs.py
Add the feminine form of `one`, `first` and `second` (`une`, `première` and `seconde`) in order to make it recognized by the `LIKE_NUM` operator of the `Matcher`.
=> Add feminine form of word "one" in French

spacy/matcher/matcher.pyx, spacy/tests/matcher/test_matcher_api.py
The returned match offsets were only adjusted for `as_spans`, not generally. Because the `on_match` callbacks are always applied to the doc, the `Matcher` matches on spans should consistently use the doc offsets.
Bug fix.
=> Return doc offsets in Matcher on spans

extra/DEVELOPER_DOCS/ExplosionBot.md
This is a docs-only change that adds a readme for the `@explosion-bot please` commands.
=> add readme for explosion-bot

spacy/tests/lang/tr/test_tokenizer.py, spacy/tests/pipeline/test_morphologizer.py, spacy/tests/test_cli.py
Removing `print` statements from the test suite - likely remnants from debugging efforts :-)
fix
=> removing print statements from the test suite

.pre-commit-config.yaml, spacy/displacy/__init__.py, spacy/tests/test_displacy.py, website/docs/api/top-level.md, website/docs/usage/visualizers.md
Closes #10672
In addition:
- had to add a dependency for black due to error caused by click package (see https://github.com/psf/black/issues/2964), another option would be to go to newest black version
- I also updated the docs that did not yet mention that a dict is also possible as input (https://spacy.io/api/top-level#displacy.render)
- I saw that List is not used in import line below, but judging from other files in the package I used a noqa to prevent the flake8 fail just in case this import is important for dependent code
```from typing import List, Union, Iterable, Optional, Dict, Any, Callable```
Now you no longer need to manually sort entities by their start value if providing a dict with ents in it. See #10672 and #4951
Bugfix if you would consider it a bug, enhancement if you …
=> #10672: fixes displacy output for manual unsorted entities

spacy/tokens/graph.pyx
Removes one of the last, potential GIL-Refnanny related regressions.
Bug fix
=> Remove vestigial debug print statement in `walk_head_nodes`

spacy/tests/parser/test_parse.py, spacy/tests/pipeline/test_textcat.py, spacy/tests/pipeline/test_tok2vec.py, website/docs/api/legacy.md
Add (slow) tests for old architectures so we can spot it easily when something goes wrong with stuff in `spacy-legacy`. Now that we run the slow test suite regularly, I think it's fine to mark some of these tests as slow.
Also includes a doc fix as 2 textcat architectures were under the subheading "layers" instead of "architectures". The diff looks weird but basically I just moved some subsections around.
adding (slow) tests
=> Add test for old architectures

spacy/cli/project/assets.py, spacy/tests/test_cli.py, website/docs/usage/projects.md
Allow assets in spaCy projects to be downloaded optionally.
- Assets can be marked as `optional`. If `optional` is not set, it is assumed to be `False`. Example:
```yaml
assets:
- dest: "assets/${vars.treebank}"
optional: True
git:
repo: "https://github.com/UniversalDependencies/${vars.treebank}"
branch: "master"
path: ""
```
- New argument for `spacy project assets`: `--all` (`-a`). If this is set, all assets - including those marked as `optional` - are downloaded. Otherwise `optional` assets are ignored.
New feature
=> Allow assets to be optional in spacy project

spacy/errors.py, spacy/language.py, spacy/tests/pipeline/test_pipe_factories.py
Resolves https://github.com/explosion/spaCy/issues/10766 by ignoring name overrides in pipes' `config` argument.
Removes overrides for `name` in pipes' `config` argument. Issues a warning if this override is set. Extends existing test to ensure pipe name isn't changed when overriden in `config`.
Bug fix/prevention.
=> Ignore overrides for pipe names in config argument

spacy/matcher/phrasematcher.pyx, spacy/tests/matcher/test_phrase_matcher.py
When removing keywords from a `PhraseMatcher`, the node after the last token was not considered a `path_node`. 
On line 140, we check if the current node contains other successors, and remove it if it doesn't.
```python
if node_pointer.filled == 1:
else:
```
If we don't include the node after the last token, we never check, if there are tokens of other keywords following this token.  As a result, removing the shorter of two overlapping keywords resulted in the removal of both terms.
The illustration below shows the issue using the terms of the newly added test case.
```mermaid
graph LR
id1(self.c_map)-- binary --> id2( )
id2 -- "self._terminal_hash" --> id3( )
id2 -- "data" --> id4( )
id4 -- "self._terminal_hash" --> id5( )
subgraph "path_nodes (fixed)"
id2
subgraph "path_nodes (master)" …
```
=> Fix PhraseMatcher remove overlapping terms

spacy/tests/training/test_rehearse.py
Small bugfix to the rehearse test
In the `parser` test loop the `tagger` labels were added by accident.
One liner bugfix
- [x ] I confirm that I have the right to submit this contribution under the project's MIT license.
=> bugfix parser labels

spacy/training/example.pyx
Previously, we were aligning heads and dependencies between candidate and gold tokens by manually iterating over elements in the example/alignment array. This wasn't optimal as it didn't leverage `numpy`'s vectorization. This PR rewrites the alignment code with `numpy` ops, reducing parser loss calculation time by ~45-50 ms per mini-batch.
Performance enhancement
=> Vectorize `example.get_aligned_parses`

website/docs/models/index.md
Small edit to the docs at https://spacy.io/models. 
Floret vectors compute representations for all strings and as such there are never out-of-vocabulary vectors. This means for all `Token` objects the `is_oov` attribute is always `False`. The docs said its `True`, but the implementation is correct and it does output `False`.
Mini doc fix
- [] I ran the tests, and all new and existing tests passed.
=> oov confusion fix

website/docs/usage/embeddings-transformers.md
Adds a link to [floret](https://github.com/explosion/floret) in the static vectors section of the docs.
=> add floret to static vectors docs

spacy/pipeline/entity_linker.py, spacy/tests/pipeline/test_entity_linker.py
As outlined in #9575, the Entity Linker has issues when tokenization differs between gold and predicted Docs. This was separate from the issue addressed with the recent fix for tok2vec issues, so this PR should address it. 
The main issue is that while KB IDs are taken aligned to tokens in the predicted Doc, they are indexed into using entity token indices from the gold Doc. This means if there was any change in the tokenization before the token in question, the tokens won't line up, which can result in nonsense or IndexErrors. 
Right now this PR just has a failing test; the fix is in progress. 
My basic strategy for fixing this is to use the `get_matching_ents` function introduced in the previous NEL fix PR to get aligned entities. That should give correct results all cases,  but may be …
=> Fix Entity Linker with tokenization mismatches (fix #9575)

spacy/ml/models/__init__.py, spacy/ml/models/coref.py, spacy/ml/models/coref_util.py, spacy/ml/models/span_predictor.py
Torch is required for the coref/spanpred models but shouldn't be
required for spaCy in general.
The one tricky part of this is that one function in coref_util relied on
torch, but that file was imported in several places. Since the function
was only used in one place I moved it there.
Tests are not working because they're a bit out of sync with other re-organizations, but that is not specific to the changes in this PR.
bug fix? for in-progress PR
=> Add guards around torch import for coref

spacy/errors.py, spacy/matcher/matcher.pyx, spacy/tokens/doc.pyx
More informative errors when wrong `Doc` attribute is provided
Noticed that when providing a wrong attribute to `Doc.has_annotation` the error does not get caught and the `None` returned by `intify_attr` propagates down to leading to a cryptic message:
```
~/spaCy/spacy/tokens/doc.pyx in genexpr()
TypeError: an integer is required
```
The `Matcher` object handles this user error, but it first assigns `None` with `attr = IDS.get(attr)` and then tells the user that `None` is an invalid input. This PR stores the `input_attr = attr` early on and then reports the error with the input rather than `None`.  
Small fix to the error messages.
=> Better errors for has_annotation and Matcher

website/docs/api/top-level.md
Added `"span"` to the accepted values for the visualization styles in the `displacy.serve` and `displacy.render` top-level functions. The `"span"` style is new as of spaCy 3.3, so I added the "new" tag for that option only. The `"span"` visualization style is listed between the `"dep"` and `"ent"` visualization styles to avoid the appearance of the "new" tag applying to all visualization styles while maintaining the default-value-first convention.
Update documentation
=> Update documentation for displacy style kwargs

website/docs/api/spanruler.md, website/docs/usage/rule-based-matching.md
Fix version in SpanRuler docs: the component is new since 3.3.1, not 3.3.0
docs fix
=> Fix version in SpanRuler docs

website/meta/universe.json
Added Aim-spaCy to spaCy Universe.
Edited the [universe.json](https://github.com/explosion/spaCy/blob/master/website/meta/universe.json) and added Aim-spaCy JSON object to the list of "resources".
=> Add "Aim-spaCy" to spaCy Universe

spacy/ml/_precomputable_affine.py
The `forward` of `precomputable_biaffine` performs matrix multiplication and then `vstack`s the result with padding. This creates a temporary array used for the output of matrix concatenation.
This change avoids the temporary by pre-allocating an array that is large enough for the output of matrix multiplication plus padding and fills the array in-place.
This gave me a small speedup (a bit over 100 WPS) on de_core_news_lg on M1 Max (after changing thinc-apple-ops to support in-place gemm as BLIS does).
Enhancement.
=> precomputable_biaffine: avoid concatenation

spacy/tests/matcher/test_matcher_api.py
This `xfail` test shows how `_SetPredicate` in `matcher.pyx` incorrectly handles sequence values that are stored in `Doc` extension attributes.
New test
=> Add failing test: `test_matcher_extension_in_set_predicate`

spacy/vectors.pyx
The float -1 was returned rather than the integer -1 as the row for
unknown keys. This doesn't introduce a realy bug, since such floats
cast (without issues) to int in the conversion to NumPy arrays. Still,
it's nice to to do the correct thing :).
Bugfix
=> vectors: remove use of float as row number

spacy/cli/debug_data.py, spacy/pipeline/_parser_internals/arc_eager.pyx, spacy/pipeline/_parser_internals/ner.pyx, spacy/pipeline/dep_parser.pyx, spacy/pipeline/ner.pyx, spacy/tests/parser/test_ner.py, spacy/tests/util.py, spacy/tokens/doc.pyx, spacy/training/__init__.py, spacy/training/augment.py, spacy/training/example.pyx, spacy/training/iob_utils.py
This came up when running `spacy debug data` on data from [AnEM](https://raw.githubusercontent.com/juand-r/entity-recognition-datasets/master/data/AnEM/CONLL-format/data/AnEM.train), which contains an entity label `"Multi-tissue_structure"`. The `ner` pipe would parse this as `"Multi"` and the `debug data` command would do the same internally, because both were using
```
label.split("-")[1]
```
instead of
```
label.split("-", 1)[1]
```
when stripping of the BILU prefix (e.g. `"B-"`)
bug fix
=> account for NER labels with a hyphen in the name

spacy/cli/debug_data.py
`labels_with_counts` wasn't being printed for the NER, not even when `verbose`. I think this was probably just a typo/oversight: the variable was constructed but never actually used. We do print the counts for other components including the tagger, parser and recently spancat. 
small fix
=> add NER counts to debug data

.github/contributors/Lucaterre.md, website/meta/universe.json
A proposal to update `universe.json` file to add [spacyfishing](https://github.com/Lucaterre/spacyfishing) to the spaCy Universe.
spacyfishing is based on spaCy pipeline components and performs named entity disambiguation and linking against Wikidata knowledge base with [Entity-Fishing](http://nerd.huma-num.fr/nerd/) API.
=> updated spacy universe for spacyfishing

spacy/tests/training/test_readers.py
Our slow test suite has been failing for two days because the Stanford URL for IMDB can not be reached. This is likely connected to a current [power outage](https://emergency.stanford.edu/) at Stanford’s campus.
temporarily disable failing test
=> disable failing test because Stanford servers are down

website/meta/universe.json
Currently some of the "AUTHOR INFO" links (e.g. here[0]) are broken:
```
https://github.com/https://github.com/explosion
```
[0] https://spacy.io/universe/project/spacy-experimental
Also one remains broken with `https://szegedai.github.io/`.
=> Fix some of the broken links on universe pages

website/docs/api/architectures.md
This just removes the word `simply` from the architecture docs. I was reading this page, and as a relative beginner, nothing about it was simple. There might be other ways to express some of these ideas, eg `only`, but I'm not actually sure what most of these sentences are saying :) 
Doc fix
=> Remove `simply`

spacy/tests/training/test_training.py, spacy/training/example.pyx
We were unnecessarily squeezing the gold token index vectors, causing unit-length vectors to yield a scalar and breaking indexing (the root cause seems to point to a reference sentence containing just one token). We additionally provide the output type to `np.vectorize` to correctly handle corner cases where no alignment can be made between the gold and candidate tokens.
These changes were sanity checked by locally training English and German parser models for multiple epochs.
Bugfix
=> `Example.get_aligned_parse`: Handle unit and zero length vectors correctly

spacy/displacy/render.py, spacy/displacy/templates.py
This PR updates displaCy's template and logic for calculating the vertical spacing between lines when there are multiple labels covering a single span.
**Before (w/ prodigy comparison):**
**After: (Ignore specific span differences + lack of coloring)**
bug fix / enhancement
=> displaCy: Fix horizontal spacing for multiple span labels

spacy/vectors.pyx
Avoid expensive comparisons between numpy ints and Python ints when mapping hashes to rows in the embedding table. When doing some repeated benchmarks, this seems to improve performance by 800-900WPS on an 5950X.
=> vectors: avoid expensive comparisons between numpy ints and Python ints

spacy/pipeline/textcat.py
Update for new `thinc` compatibility
The behavior of `get_array_module` is changing in `thinc` and it will `raise ValueError` when passing an argument that is neither a `numpy` object nor a `cupy` object.
Mini update
=> dont use get_array_module

spacy/tests/conftest.py
Occasionally, we have spurious test failures caused by a test iteration/run taking too long to execute and running afoul of the default, arbitrary deadline of 200ms. This PR raises the deadline significantly for all tests to eliminate this particular kind of test failure.
Thinc companion PR - https://github.com/explosion/thinc/pull/714
Tests
=> Increase test deadline to 30 minutes to prevent spurious test failures

spacy/ml/parser_model.pyx, spacy/pipeline/transition_parser.pyx
`get_ops("cpu")` is quite expensive. To avoid this, we want to cache the result as in #11068. However, for 3.x we do not want to change the ABI. So we avoid the expensive lookup by using NumpyOps. This should have a minimal impact, since `get_ops("cpu")` was only used when the model ops were `CupyOps`. If the ops are `AppleOps`, we are still passing through the correct BLAS implementation.
Performance fix.
=> precompute_hiddens/Parser: do not look up CPU ops (3.4)

website/meta/universe.json
Added asent to spacy universe. Asent is a package for rule-based sentiment analysis in spaCy using
=> Added asent to spacy universe

.github/workflows/spacy_universe_alert.yml
Since we use forking model instead of branching model, when outside collaborator creates pull request with `universe.json` file change, `pull_request` event gets triggered by Github Action (GA) but **`spacy_universe_alert.yml` workflow** fails as `SLACK_BOT_TOKEN` wont be shared with forked public repository. Thankfully there is a way to overcome this unable to access `SLACK_BOT_TOKEN` issue, we can use `pull_request_target` event which can access `SLACK_BOT_TOKEN` and send the notification to our #alerts-universe properly :)
Resources:
1. https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
2. [Github blog: improvements-for-public-repository-forks](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows …
=> Use `pull_request_target` event for spaCy universe GA trigger

spacy/tokens/span.pyi
`Span` is missing `id` and `id_` attributes in the typing file, i.e. `span.pyi`. But it is [available properties](https://github.com/explosion/spaCy/blob/master/spacy/tokens/span.pyx#L784)
Fixes #11118
Bug fix on typings
=> Fix span typings

website/docs/api/matcher.md
Simple update of documentation (example for Matchers) to reflect the code.  Function `on_match` in the example was not called, therefore the sample was not doing anything. This PR fixes it (added necessary code in the example).
```python
def on_match(matcher, doc, id, matches): # ⚠️ NOTE: this function is unused in the current example
print('Matched!', matches)
matcher = Matcher(nlp.vocab)
patterns = [
[{"LOWER": "hello"}, {"LOWER": "world"}],
[{"ORTH": "Google"}, {"ORTH": "Maps"}]
]
matcher.add("TEST_PATTERNS", patterns) #  ⚠️ NOTE: on_match argument is not passed! (fixed in the PR)
doc = nlp("HELLO WORLD on Google Maps.")
matches = matcher(doc)
```
Documentation update.
=> Matchers documentation update (error in example)

spacy/ml/_precomputable_affine.py
After the precomputable affine table of shape `[nB, nF, nO, nP]` is computed, padding with shape `[1, nF, nO, nP]` is assigned to the first row of the precomputed affine table. However, when we are indexing the precomputed table, we get a row of shape `[nF, nO, nP]`. CuPy versions before 10.0 cannot paper over this shape difference.
This change fixes compatibility with CuPy < 10.0 by squeezing the first dimension of the padding before assignment.
Compatibility fix.
=> Fix compatibility with CuPy 9.x

spacy/cli/download.py, spacy/util.py
Switching to minor version based compatibility in the compatibility table has simplified making patch releases and keeps the compatibility table smaller, however it's difficult to publish prerelease model versions for testing because there's no way to specify a prerelease version based on minor version compatibility, and as soon as there's a newer stable-looking minor version in the compatibility table, the website uses it by default for the model entries.
This isn't the only way to solve this problem, but it seemed like a relatively straightforward alternative for dev releases as in #10624, where the models could only be installed through external URLs rather than `spacy download` for v3.3.0.dev0.
?
=> Support full prerelease versions in the compat table

spacy/tests/training/test_new_example.py, spacy/training/example.pyx, website/docs/api/data-formats.md
Added spans to doc_annotation in the Example.to_dict method.
I've added a test for the issue in test_new_example.py. I'm not sure, if it's the right place and if it should be tested differently.
Fix to #11260
=> adding spans to doc_annotation in Example.to_dict

spacy/lang/nl/syntax_iterators.py, spacy/tests/lang/nl/test_noun_chunks.py
Fix Dutch noun chunks to skip overlapping spans.
Bug fix.
=> Fix Dutch noun chunks to skip overlapping spans

spacy/errors.py
Now that `span_ruler` can also emit `W036` it makes sense to add it to the default warnings filter.
fix
=> include span_ruler for default warning filter

.github/azure-steps.yml, spacy/tests/doc/test_doc_api.py, spacy/tests/lang/ru/test_lemmatizer.py, spacy/tests/lang/uk/test_lemmatizer.py, spacy/tests/matcher/test_phrase_matcher.py, spacy/tests/pipeline/test_entity_linker.py, spacy/training/initialize.py
Clean up warnings in the test suite
?
=> Clean up warnings in the test suite

website/docs/usage/linguistic-features.md
Swap 'Vectors & Similarity' and 'Mappings & Exceptions' in menu to match order in body. The original order leads to incorrect highlighting in the menu when scrolling.
Documentation
=> Fix menu order in linguistic-features.md

spacy/lang/ca/lemmatizer.py, spacy/lang/fr/lemmatizer.py
Before using the lookups table in the French (and Catalan) lemmatizers, there's a check to see if the current term is in the table. But it's checking a string against hashes, so it's always false. Also the lookup table is designed so that you don't have to check if something is already present in advance.
The lookup lemmatizer always falls back to the input string, so I've also modified these lemmatizers to not have their own separate fallback. However I'm not sure if that's something we should rely on or an implementation detail. 
bug fix
=> Fix lookup usage in French/Catalan (fix #11347)

setup.cfg, spacy/tests/package/test_requirements.py
Remove `setup_requires` from `setup.cfg`.
`setup_requires` worked in the original `setup.py`-only version but I have never found a version of `setuptools` where it was supported in `setup.cfg`. But since it was possible that there was some old version of `setuptools` that did indeed support this, I kept it around for v3. However I really do not think it is needed at this point, and this reduces the duplication of build requirements specifications. Now they should only go in `pyproject.toml` and `build-constraints.txt`. Install requirements remain in `install_requires` and `requirements.txt` as before.
Chore.
=> Remove setup_requires from setup.cfg

spacy/ml/tb_framework.pyx
This PR replaces references to the vestigial `thinc.backend.linalg` module with `CBlas` calls and a local function. The aforementioned module will be removed once [this PR](https://github.com/explosion/thinc/pull/742) is merged.
Refactoring
=> Replace references to `thinc.backends.linalg` in the parser

spacy/tests/test_misc.py
These tests assumed that GPUs are only supported with CuPy, but since Thinc 8.1 we also support Metal Performance Shaders.
Bug fix.
=> Fix `test_{prefer,require}_gpu`

spacy/errors.py, spacy/language.py, spacy/tests/test_language.py
Check for any non-`Doc` returned value for components.
?
=> Check for any non-Doc returned value for components

spacy/errors.py, spacy/matcher/matcher.pyx, spacy/tests/matcher/test_matcher_api.py
The `IN` and `NOT_IN` set predicates in `Matcher` would raise an unhandled exception when matching against attribute values that are non-hashable (like `list`s). This is now resolved by performing some defensive type checking of the attribute values prior to calling the Python `in` operator.
Going forward, if _any_ set predicate encounters a value of an unexpected type, it will fail early, i.e., return `False`, instead of crashing.
Bug fix.
=> Better handling of unexpected types in `SetPredicate`

requirements.txt, spacy/cli/download.py, spacy/cli/info.py, spacy/tests/package/test_requirements.py, website/docs/api/cli.md, website/docs/usage/models.md, website/src/templates/models.js
This adds a `--url` flag to the `spacy info [model]` command that prints the URL of the most recent compatible version of the named pipeline. This URL is printed without any formatting for use in scripts, like:
```
url=$(spacy info en_core_web_sm --url)
wget "$url"
```
Because this requires a compatibility check, it requires an Internet connection.
This also adds the download URL for installed packages to the output of `spacy info [model]` if available. The information is typically available for pipelines installed with pip, and is accessed through `pkg_resources`. This does not require an Internet connection.
-----
Original description: 
This is a simple implementation of a `--dry-run` flag for `spacy download` that makes it print the URL of the package to be installed without …
=> Add a way to get the URL to download a pipeline to the CLI

spacy/cli/project/run.py
Error message update form the `project run` cli when the user wants to run `project run assets`. 
This is a common mistake I make personally and I get confused for a second sometimes. I've felt like I cannot be the only one.
Error message update.
=> Assets message

spacy/ml/callbacks.py, spacy/pipeline/pipe.pyx, spacy/pipeline/trainable_pipe.pyx
When loading pipelines from a config file, the arguments passed to individual pipeline components are validated by `pydantic` during init. For this, the validation model attempts to parse the function signature of the component's c'tor/entry point in order to check if all mandatory parameters are present in the config file.
When using `models_and_pipes_with_nvtx_range` as an `after_pipeline_creation` callback, the methods of all pipeline components get replaced by an NVTX range wrapper **before** the above-mentioned validation takes place. This can be problematic for components that are implemented as Cython extension types - if the extension type is not compiled with Python bindings for its methods, they will have no signatures at runtime. This resulted in `pydantic` validating the …
=> Fix config validation failures caused by NVTX pipeline wrappers

website/docs/api/example.md, website/docs/usage/linguistic-features.md
Closes #11482.
Correction to the documentation, including an example that was not running correctly
=> Correct alignment example and documentation

.github/azure-steps.yml
Until `mypy` 0.980 is released with [this fix](https://github.com/python/mypy/issues/13627), we're disabling the mypy tests on the CI for Python 3.10.
hot fix to CI infrastructure
=> Disable mypy for Python 3.10 (v4)

.github/azure-steps.yml
Until `mypy` 0.980 is released with [this fix](https://github.com/python/mypy/issues/13627), we're disabling the mypy tests on the CI for Python 3.10.
hot fix to CI infrastructure
=> Disable mypy for Python 3.10 (develop)

website/docs/api/example.md
The API docs for `Example` refer to a dummy function `parse_gold_doc` that implies "parse whatever data to create your `Doc` object", but this seems to create some confusion among users. Instead, proposing to make this example code much more explicit by calling the `Doc` constructor for both `predicted` and `reference`.
doc fix
=> more explicit Example constructor example

website/meta/sidebars.json
The spaCy website displays a duplicate "New in v3.2" link in the sidebar
Fix the docs.
=> fix: remove duplicate "New in v3.2" in sidebar

spacy/tests/training/test_augmenters.py, spacy/training/augment.py, spacy/training/iob_utils.py
Preserve both `-` and `O` annotation in augmenters rather than relying on `Example.to_dict`'s default support for one option outside of labeled entity spans.
This is intended as a temporary workaround for augmenters for v3.4.x. The behavior of `Example` and related IOB utils could be improved in the general case for v3.5.
Bug fix.
=> Preserve missing entity annotation in augmenters

.github/azure-steps.yml, requirements.txt, spacy/pipeline/entityruler.py
The latest version of `mypy` (0.981) now works with Python 3.10, so we're updating and at the same time dropping support for `mypy` usage with Python 3.6.
fix, follow-up to https://github.com/explosion/spaCy/pull/11508
=> update mypy to latest version

azure-pipelines.yml, requirements.txt
`importlib-metadata` just released 5.0.0 yesterday and this seems to be breaking our CI - this PR is currently just WIP for testing.
fix
=> PR to test importlib-metadata

spacy/pipeline/spancat.py, spacy/pipeline/textcat_multilabel.py
Some default configurations of our components were still using [legacy](https://spacy.io/api/legacy) version for the tok2vec layer.
fix
=> update default configs to recent tok2vec versions

.github/workflows/autoblack.yml
Our autoblack github workflow uses a couple github actions that are currently deprecated:
We've still got some time before this starts actually breaking, but I'm getting started on this across our infra. The changing of the `@version` for 3 of the steps should be pretty straightforward. The changing the `set-output` is based on [this blog post](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). 
There isn't a way AFAIK to locally test these workflow changes so we might just have to merge and iterate a bit. If it's inconvenient to do that right now, we have ~6 months before we have to do this, I just wanted to get a start on it so we don't have to rush or forget.
=> update github actions to deal with deprecations

website/src/styles/quickstart.module.sass, website/src/widgets/quickstart-install.js
Currently support for M1 GPUs is experimental and limited, but the install widget allows you to select the M1/GPU combination as though everything will work. This adds a warning about the experimental status and links to the FAQ on the subject. This should prevent issues like #11641.
The way this displays is not ideal - for example, there's a link but it's not obvious because it's not underlined or anything. I will see if there's a way to modify the CSS to make it clearer, but any suggestions on other places to display this would also be welcome.
=> Add warning to install widget for M1 GPUs

.github/workflows/autoblack.yml, .github/workflows/explosionbot.yml, .github/workflows/slowtests.yml, .github/workflows/spacy_universe_alert.yml
A couple more fixes for the deprecation warnings. 
There will be one more after this - `lock.yml` uses an action that hasn't pushed a fix for this yet. Once they do I'll make that last fix.
=> More version updates for github action deprecation warnings

.github/azure-steps.yml, spacy/util.py
Some load functions used SimpleFrozenList() directly instead of the _DEFAULT_EMPTY_PIPES parameter. That mostly worked as intended, but the changes in #11459 check for equality using identity, not value, so a warning is incorrectly raised sometimes, as in #11706.
This change just has all the load functions use the singleton value instead.
minor bugfix
=> Fix default parameters for load functions (fix #11706)

spacy/tokens/span.pyi
Make types for `Span.id` and `Span.id_` the same as for other properties in `Span` with getters and setters.
It seems like the property types are not interpreted as writable by pyright (see #11113). mypy doesn't seem to have an issue and I'm not sure what's intended/correct, but it seems sensible that they are all the same.
Types.
=> Fix types for Span.id and Span.id_

spacy/cli/project/assets.py
On the `projects` CLI, when running `spacy project assets`, the helper function `convert_asset_url` attempts to catch regular github links that wouldn't download the actual file. However, a link can look like `https://github.com/user/project/raw/main/data` and this will download just fine. These cases shouldn't be rewritten because that will in fact result in a 404.
bug fix
=> prevent rewriting an already raw URL

spacy/errors.py, spacy/pipeline/textcat.py, spacy/pipeline/textcat_multilabel.py, spacy/tests/pipeline/test_textcat.py
The textcat components expect all category values to be either 1 or 0 if present. When this expectation is not met the errors generated are surprising and don't make the issue clear, like in #11757. 
This change checks sample data during initialization and throws an error if invalid values are found. That's not perfect, since it might not catch things if only a few examples have bad values, but in the typical case it should prevent confusion by quickly identifying the issue.
data validation
=> Check textcat values for validity

.pre-commit-config.yaml, spacy/tests/vocab_vectors/test_vocab_api.py, spacy/vocab.pyx
=> Vocab.to_disk exclude doesn't respect vectors #11833 

spacy/language.py
In `Language.add_pipe`, an error is created if a factory that doesn't exist is specified, but the error isn't used for anything. This has never been an issue because `create_pipe` is called immediately after and raises the same kind of error early in its definition.
Because `create_pipe` seems to be doing the right thing I just removed the error check and object creation here, but we could alternately raise here instead. 
Cleanup?
=> Remove unused error object in add_pipe

website/meta/languages.json
Added example sentence for Chinese in website/meta/languages.json so that it can be displayed instead of "No text available yet" when the "Show text example" option is checked.
Docs
=> Add example sentence for Chinese on website.

spacy/displacy/__init__.py, spacy/errors.py, spacy/tests/test_displacy.py
If you use displaCy to render spans but the span key is unset (as opposed to merely empty), it will throw a generic error. This change makes it so no error is thrown, but instead the (already in place) warning about no spans being found is shown. 
The case where the key is unset is a stronger sign that a mistake has been made than the key being empty, but it still feels off to throw an error here.
cleanup?
=> Don't throw an error if using displacy on an unset span key

website/docs/api/top-level.md
Add function document for `training.biluo_to_iob` and `training.iob_to_biluo`, solving #9671.
Docs.
- [ x] I confirm that I have the right to submit this contribution under the project's MIT license.
=> Add docs for biluo_to_iob and iob_to_biluo.

spacy/cli/templates/quickstart_training.jinja
If you don't have spacy-transformers installed, but try to use `init config` with the GPU flag, you'll get an error. The issue is that the `use_transformers` flag in the config is conflated with the GPU flag, and then there's an attempt to access transformers config info that may not exist.
There may be a better way to do this, but this stops the error.
cli/docs fix
=> Config generation fails for GPU without transformers

website/docs/usage/v3-4.md
It looks like the md/lg links in the 3-4 readme got mixed up 
doc fix
=> fix links in 3.4 release notes

.github/workflows/lock.yml
The `lock-threads` action has been updated upstream to fix the node deprecation warnings, so now we can bump it here.
=> update lock-threads to v4

spacy/cli/_util.py, spacy/tests/test_cli.py
Solving #11235.
When loading config files, do the interpolation before checking the directories to handle variables in the directory names correctly. Related tests are added to test_cli.py.
Testing result:
- OS: `Windows 11`
- Python: `3.10`
- Result: 
```bash
$ py.test spacy
3298 passed, 1211 skipped, 32 xfailed, 1 xpassed in 354.31s (0:05:54)
```
Bugfix.
=> Fix the interpolation in directory names when loading config files using cli.

spacy/pipeline/edit_tree_lemmatizer.py, spacy/tests/pipeline/test_edit_tree_lemmatizer.py
Strings in replacement nodes where not added to the `StringStore` when `EditTreeLemmatizer` was initialized from a set of labels. The corresponding test did not capture this because it added the strings through the examples that were passed to the initialization.
This change fixes both this bug in the initialization as the 'shadowing' of the bug in the test.
Bug found while implementing distillation, since it relies purely on this functionality to initialize the teacher.
Bug fix.
=> EditTreeLemmatizer: correctly add strings when initializing from labels

spacy/errors.py
There are a few errors in the beam search code that were removed (it looks like in #5664). I don't think there's any way to use the beam code at the moment, but as long as it's around the errors it refers to should also be present. 
minor fix?
=> Add in errors used in the beam code that were removed at some point

spacy/errors.py, spacy/training/loggers.py, website/docs/api/top-level.md
This PR adds `ConsoleLogger.v3` which expands the progress bar feature to count up the training/distillation steps to either the next evaluation pass or the maximum number of steps.
Additionally, `ConsoleLogger.v2` was modified to call `v3` while retaining its current behaviour.
New feature
=> New console logger with expanded progress tracking

spacy/lexeme.pxd, spacy/tokenizer.pxd
This PR removes unused imports for `StringStore` from lexeme and tokenizer.
=> Delete unused imports for StringStore

spacy/displacy/__init__.py, spacy/displacy/render.py, website/docs/api/top-level.md
The `page` option, which wraps the output SVG in HTML, is true by default for `serve` but not for `render`. The `render` docs were wrong though, so this updates them.
Minor docs fix
=> Fix inconsistency in displaCy docs about page option

spacy/cli/_util.py, spacy/cli/convert.py, spacy/tests/test_cli.py, spacy/tests/test_cli_app.py
The refactoring of `walk_directory` in https://github.com/explosion/spaCy/pull/11376 changed the behaviour of matching on a suffix that is not "iob", "jsonl" or "conll", returning zero hits instead of all files. However, `convert` relies on getting all files when using the option "auto", but it wasn't properly hooked up to the new `walk_directory` implementation. This PR fixes that and introduces new unit tests to ensure the correct behaviour going forward.
bug fix
=> fix processing of "auto" in convert

spacy/scorer.py, spacy/tests/test_scorer.py, website/docs/api/scorer.md
In the v3 scorer refactoring, `token_acc` was implemented incorrectly. It should use `precision` instead of `fscore` for the measure of correctly aligned tokens / number of predicted tokens.
Fix the docs to reflect that the measure uses the number of predicted tokens rather than the number of gold tokens.
Bug fix, docs.
=> Restore v2 token_acc score implementation

spacy/pipeline/edit_tree_lemmatizer.py, spacy/tests/pipeline/test_edit_tree_lemmatizer.py
The edit-tree lemmatizer has a hyperparameter `top_k` that specifies the number of alternative predicted trees to consider for each token: if the first predicted tree is not applicable to the raw token text, the second predicted tree is considered and so on up to the value of `top_k`.
Although accuracies are normally higher if alternative predictions can be considered, the current standard published models all specify `top_k = 1`. This is because the pre-existing code is several times slower when executed on a CPU for any higher value of `top_k` owing to an expensive NumPy sort that is used to order the predictions for each token (the sort is avoided in the pre-existing code if `top_k == 1`).
This PR retains the existing approach if `top_k==1`, but introduces a procedural approach if …
=> Fix speed problem with `top_k>1` on CPU in edit tree lemmatizer

azure-pipelines.yml
- update to specify `.mdx` instead of `.md`
- update `pr` section to be more broad and include `website/*` so we capture things like `website/meta/sidebars.json`
Can't reallly test this properly though,  until this is merged and we have another docs PR :/
CI fix
=> Fix Azure ignoring website files

website/src/templates/universe.js
This fixes a rendering issue with the GitHub badge on Universe projects.
- Website frontend improvements
=> Fix GitHub badge

website/docs/usage/101/_vectors-similarity.mdx, website/docs/usage/layers-architectures.mdx, website/docs/usage/projects.mdx, website/docs/usage/spacy-101.mdx, website/docs/usage/visualizers.mdx, website/pages/index.tsx, website/src/components/card.js, website/src/components/title.js, website/src/templates/universe.js
This adds `alt` tags to all images that were missing them, and that weren't [decorative](https://www.w3.org/WAI/tutorials/images/decorative/).
It also replaces a few remaining `img` with `Next/Image` to allow for automatic file compression.
- Website accessibility improvements
=> WEB-27 Add `alt` tags to images

website/src/components/embed.js
This removes links on images, that just link to themself. There is no need to link to the image we are already viewing and this is also considered an accessibility issue by Lighthouse, because there is no text description for the link.
- Website frontend/accessibility improvements
=> Remove unnecessary links on website

website/src/components/embed.js
Originally introduced in 62b9c9c6d711584cea91244bc765e56e74337fdd (https://github.com/explosion/spaCy/pull/12005)
Original error: 
> `Warning: Invalid DOM property `class`. Did you mean `className`?`
React doesn't have `class`, it uses `className`.
- Website frontend bug fix
=> Fix wrong HTML element attribute in website front page

website/src/templates/index.js
Fixes a regression introduced in #12163, which hid the alert in the navigation
- Fix missing navigation alert in docs
=> Fix navigation alert

spacy/lexeme.pyx, spacy/tokenizer.pxd, spacy/tokenizer.pyx, spacy/tokens/doc.pyx, spacy/tokens/retokenizer.pyx, spacy/vocab.pxd, spacy/vocab.pyx, website/docs/api/cython-classes.mdx
This changes the `_new_lexeme` method in the vocab to not take a memory pool as an argument. The passed value has not been used since #6809. 
~~I am having some local test failures, but they are related to my thinc version, and don't seem to have anything to do with the changes in this PR. (On review, this seems to be normal because Thinc is currently using a dev version.)~~ This is not an issue in CI.
minor refactor
=> Refactor lexeme mem passing

website/docs/api/cli.mdx
Fixes a regression after #12058 where some type annotations where interpreted as links by MDX, which then broke the component handling them.
As far as I can tell, those are the only places affected by that.
- Fix for regression in docs
-
=> Fix broken syntax for type annotations

website/src/components/code.js
Fixes a similar regression as in #12169, introduced in #12163
- Fixes docs regression
=> Fix regression with links in prompts

website/src/components/quickstart.js
Adds a label to the Quickstart widget for screenreader support.
- Accessibility improvement for docs
=> Add `aria-label` to quickstart widget

spacy/tests/training/test_corpus.py, spacy/training/__init__.py, spacy/training/corpus.py, website/docs/api/corpus.mdx
This is a corpus reader that reads plain text corpora with the following format:
- UTF-8 encoding
- One line per document.
- Blank lines are ignored.
It is useful for applications where we deal with very large corpora, such as distillation, and don't want to deal with the space overhead of serialized formats. Additionally, many large corpora already use such a text format, keeping the necessary preprocessing to a minimum.
New feature
=> Add `spacy.PlainTextCorpusReader.v1`

spacy/tests/doc/test_span.py, spacy/tokens/span.pyi, spacy/tokens/span.pyx, website/docs/api/span.mdx
Adds the `alignment_mode` parameter present in `Doc.char_span()` to `Span.char_span()` as well.
Enhancement
=> Add alignment_mode argument to Span.char_span()

.github/azure-steps.yml, spacy/cli/download.py
When downloading a model, this checks if the same version of the same model is already installed. If it is then the download is skipped.
This is necessary because pip uses the final download URL for its caching feature, but because of the way models are hosted on Github, their URLs change every few minutes, so pip is unable to cache downloads correctly. This is basically a workaround for that caching issue. 
minor enhancement
=> Don't re-download installed models

CONTRIBUTING.md, spacy/cli/_util.py, spacy/cli/project/pull.py, spacy/cli/project/push.py, spacy/language.py, spacy/tests/test_language.py, spacy/training/callbacks.py, spacy/training/corpus.py, spacy/training/initialize.py, spacy/training/loop.py
After internal discussion, we decided to stick to format string templates when using the `logger`. The advantage here is that if calling `str()` on a variable is expensive, it should only be done when the log line is actually getting printed at a given log level.
I'm very sad to lose the readability of our beloved f-strings, but efficiency of the code base is still number one priority.
enhancement + docs update
=> Have logging calls use string formatting types

spacy/language.py, spacy/tests/pipeline/test_annotates_on_update.py, spacy/tests/test_language.py, spacy/training/loop.py
**Preamble:** This it the first PR in probably 2-3 PRs to improve `Language.update`, but I thought it is best to split these up.
The components in a pipeline can be updated independently. However, tok2vec implementations are an exception to this, since they depend on listeners for their gradients. The update method of a tok2vec implementation computes the tok2vec forward and passes this along with a backprop function to the listeners. This backprop function accumulates gradients for all the listeners. There are two ways in which the accumulated gradients can be used to update the tok2vec weights:
1. Call the `finish_update` method of tok2vec *after* the `update` method is called on all of the pipes that use a tok2vec listener.
2. Pass an optimizer to the `update` method of tok2vec. In …
=> `Language.update`: ensure that tok2vec gets updated

website/docs/usage/rule-based-matching.mdx, website/docs/usage/v3-5.mdx
The default length of the FUZZY operator is 2 and not 3. 
Example:
````
pattern = [{"LOWER": {"FUZZY": "kitten"}}]
matcher.add("KITTEN", [pattern])
doc = nlp("kitten -> sitten -> sittin -> sitting")
matches = matcher(doc)
````
Returns matches on 'kitten' (0 edits),' sitten' (1 edit), and 'sittin' (2 edits).
Bug fix
=> Fix FUZZY operator definition

spacy/tokens/doc.pyx, spacy/tokens/span.pyx, spacy/tokens/token.pyx, website/docs/usage/101/_vectors-similarity.mdx
Remove backoff from `.vector` to `.tensor`
This backoff is problematic in various ways:
* tensors from `tok2vec` are used to make the `similarity` API easier to demo for `sm` models, but don't actually work for this purpose
* there's no way to get the right vector size for an empty doc (see #5471)
?
=> Remove backoff from .vector to .tensor

spacy/matcher/matcher.pyx
v3.5 introduced a performance regression for Matcher rules which use predicates with extension attributes.
Cause was found to be that cache key used to search for extension predicates had a different format from the cache key generated by the predicates themselves. Fix is to use a single method to generate all cache keys.
performance bug fix
discussion at https://github.com/explosion/spaCy/discussions/12261
=> Matcher performance fix for extension predicates: use shared key function

spacy/errors.py, spacy/kb/kb_in_memory.pyx, spacy/pipeline/entity_linker.py, spacy/tests/pipeline/test_entity_linker.py
The `entity_linker` was still querying the `KnowledgeBase` `__len__` property, which got moved to `InMemoryLookupDB` since 3.5. Instead, proposing to have an `is_empty` function. Internals for now, but from `v4` onwards we could have this as an abstract method on `KnowledgeBase` so that downstream implementations always provide it.
bug fix
=> KnowledgeBase length fix

website/docs/api/top-level.mdx, website/docs/usage/visualizers.mdx
Add detail about the how to provide the `color` information for `displaCy`.
The discussion https://github.com/explosion/spaCy/issues/12276 raised the point that it is not clearly documented that all and only CSS legal strings are valid color representations for `displaCy`.  
Documentation.
=> Displacy doc fix

spacy/errors.py, spacy/ml/models/multi_task.py, spacy/tests/training/test_pretraining.py
Raise error for non-default vectors with PretrainVectors
* Switch to absolute imports in pretraining tests.
Bug fix.
=> Raise error for non-default vectors with PretrainVectors

spacy/tests/doc/test_span.py, spacy/tokens/span.pyx
Spans may be associated with multiple sentences. These `.sents` should always be complete, not partial, sentences. The implementation of `Span.sents` in `main` however truncates the last sentence if the end of the executing `Span` instance isn't equal with the end of that sentence.
=> Fix sentence indexing bug in `Span.sents`

spacy/pipeline/entity_linker.py, spacy/tests/pipeline/test_entity_linker.py
`EntityLinker` crashes when `incl_context is True and `len(list(ent.sents)) > 1` and the first of the sentences in `ent.sents` (which is the one used in the context calculation) doesn't have an entity. 
This currently adds a test to reproduce this behavior. A fix will be added later - probably in this PR, hence this is marked as draft.
=> Fix EL failure with sentence-crossing entities

website/docs/api/stringstore.mdx, website/docs/api/vocab.mdx
Adds a warning to the `Vocab` and `StringStore` docs that their size is not static and increases with every newly seen token. This adjustment resulted from this [discussion](https://github.com/explosion/spaCy/discussions/10015).
Documentation
=> Add info that Vocab and StringStore are not static in docs

website/docs/api/spancategorizer.mdx
Minor addition to the `spancat` docs to warn about overwriting spans.
Warn users about `spancat` overwriting existing `SpanGroup`.
Small documentation update.
=> add explanation about overwriting behaviour

website/docs/api/coref.mdx
In the file `website/docs/api/coref.mdx` ,the comma in line 6 of example under subheading `Config and implementation {id="config”}` is unnecessary and generates error while executing code.
The link to colab notebook displaying the same: [link](https://colab.research.google.com/drive/1mVtfeKPXmDfh--iAFjKoYhqtNnthJWfj?usp=sharing)
=> corrected example code

spacy/pipeline/spancat.py, spacy/tests/pipeline/test_spancat.py
Add missing span-scores, fix related bug and add corresponding tests.
The `spancat` component returns for each `Span` the score (more like probability) corresponding to the assigned label. The `spancat_singlelabel` was missing this feature as noted by a Prodigy user. Adding the corresponding tests also surfaced a small bug causing a mismatch between the spans and the scores. 
Adding missing tests and bug fix.
=> Fix spancat-singlelabel score

spacy/tests/doc/test_span.py, spacy/tokens/span.pyx
Fix `Span.sents` edge case of `Span` instance being the only one in the last sentence of its `Doc` instance.
=> Fix `Span.sents` edge case

spacy/language.py, spacy/tests/test_language.py, spacy/training/loop.py, website/docs/api/language.mdx
PR #12136 fixed an issue where the tok2vec pipe was updated before gradient were accumulated. However, it introduced a new bug that cause `finish_update` to be called twice when using the training loop. This causes a fairly large slowdown.
The `Language.update` method accepts the `sgd` argument for passing an optimizer. This argument has three possible values:
- `Optimizer`: use the given optimizer to finish pipe updates.
- `None`: use a default optimizer to finish pipe updates.
- `False`: do not finish pipe updates.
However, the latter option was not documented and not valid with the existing type of `sgd`. I assumed that this was a remnant of earlier spaCy versions and removed handling of `False`.
However, with that change, we are passing `None` to `Language.update`. As a result, we …
=> Avoid `TrainablePipe.finish_update` getting called twice during training

website/docs/api/dependencymatcher.mdx, website/docs/usage/rule-based-matching.mdx
Semgrex now has new relations (`..`, `-`, `--`, `>++`, `>--`, `<++`, `<--`) since [CoreNLP v4.5.2 release](https://github.com/stanfordnlp/CoreNLP/releases/tag/v4.5.2), as described in Table 2 of [Bauer _et al._ (2023: 68)](https://aclanthology.org/2023.tlt-1.7.pdf). This PR:
1. Adds _counterpart_ info for REL_OPs whose names are different with Semgrex's (`.*` vs. `..`, `;` vs. `-`, `;*` vs. `--`). 
2. Removes _not-in-Semgrex_ info for REL_OPs that have been included in Semgrex (`>++`, `>--`, `<++`, `<--`).
Changes to the documentation for REL_OPs
=> docs(REL_OP): modify docs for REL_OPs to match Semgrex's update on CoreNLP v4.5.2 release

spacy/tokenizer.pyx
In `Tokenizer.from_bytes`, the exceptions should be loaded last so that they are only processed once as part of loading the model.
The exceptions are tokenized as phrase matcher patterns in the background and the internal tokenization needs to be synced with all the remaining tokenizer settings. If the exceptions are not loaded last, there are speed regressions for `Tokenizer.from_bytes/disk` vs. `Tokenizer.add_special_case` as the caches are reloaded more than necessary during deserialization.
Bug fix.
=> Load exceptions last in Tokenizer.from_bytes

website/meta/universe.json
Adds `spaCysee` to the universe json. It is a visualizer that is designed to work with Jupyter notebooks and allows you to scroll through the dependency parse output for a given doc.
Adds `spaCysee` to the universe json
- [ x] I confirm that I have the right to submit this contribution under the project's MIT license.
=> Add spaCysee to Universe

.github/workflows/tests.yml, spacy/ml/extract_spans.py
During out Slack discussion @adrianeboyd identified a hotspot that slows `spancat` down. It only required a small change to speed it up. 
To estimate the difference I trained the default `spancat` for a few epochs on `LitBank` using this codebase: https://github.com/explosion/princetondh/tree/master/litbank_pipeline. I ran the command:
```
python -m spacy project run spancat
```
According to tqdm the time elapsed between evaluations using the old function the time elapsed between evaluations is~50 seconds with about 3.8it/s . The output of the evaluation command is:
```
SPEED    6431
```
With the new code the time elapsed is ~10 seconds with about 16it/s and the output of the evaluation command is:
```
SPEED    18358
```
Small bug-fix to improve speed.
=> Spancat speed improvement

spacy/cli/evaluate.py, spacy/tests/test_cli.py
This PR attempts to fix that by creating a new parameter for "spans" and calling the appropriate displaCy value.
#12566 
The current implementation of spaCy benchmark accuracy / spacy evaluate doesn't include the "spans" type, so calling the command doesn't render the HTML displaCy file needed. The reason why it wasn't included in the first place was *probably* because the "spans" feature in displaCy is relatively new.
Bugfix
=> Add spans in spacy benchmark

spacy/training/initialize.py
In initialize only calculate current vectors hash if needed. Otherwise this takes unnecessary time and RAM, and fails on extremely large vectors due to msgpack limits.
Bug fix.
=> In initialize only calculate current vectors hash if needed

spacy/errors.py, spacy/tests/doc/test_span_group.py, spacy/tests/parser/test_ner.py, spacy/tests/test_scorer.py, spacy/tokens/doc.pyx, spacy/tokens/span_group.pyx
The restriction on only adding spans from the current doc were already implemented for all operations except for `SpanGroup.__init__`.
Initialize copied spans for `SpanGroup.copy` with `Doc.char_span` in order to validate the character offsets and to make it possible to copy spans between documents with differing tokenization. Currently there is no validation that the document texts are identical, but the span char offsets must be valid spans in the target doc, which prevents you from ending up with completely invalid spans.
Bug fix?
=> Require that all SpanGroup spans are from the current doc

spacy/tests/test_cli_app.py
Some of the tests in `test_cli_app` rely on `touch` being available as a system wide command, which isn't necessarily the case. Instead, using `spacy init config` here which should generate a file as well. Also removing the dependency on the command `rm`.
fix
=> use system-independent commands

website/src/components/quickstart.js
This is a really odd bug, where Firefox doesn't re-render the `code` element, even though `children` changed.
I couldn't find any explanation for why this is happening and why it only happens in Firefox. I assume it is a bug caused by one of our many dependencies (or their interplay). Updating dependencies didn't fix the bug.
To make matters worse: This bug *doesn't* occure when running the site in dev mode. You have to build and serve the site to recreate it.
Two things fixed that:
- remove the `language-ini` `className`
- replace the `code` block with a `div`
Both are not ideal. Therefor this solution adds an inner `div` that now has the classes while still maintaining the semantic `code` element.
=> Fix #12716 does not update the `config` generation section

spacy/errors.py
Removed the dot in the link
Removed the dot in the link of spaCy's models as that dot was rendered as part
of the link when raised in a jupyter notebook, and when that happens, the hyperlink
leads to a broken webpage, [https://spacy.io/models.](https://spacy.io/models.) instead of [https://spacy.io/models](https://spacy.io/models)
Minor change to the link
=> Fixed e941 link rendering by removing the dot

spacy/language.py, spacy/tests/pipeline/test_tok2vec.py, spacy/training/initialize.py
When sourcing a component, the object from the original pipeline is added to the new pipeline as the same object. This creates a situation where there are several attributes that cannot be in sync between the original pipeline and the new pipeline at the same time for this one object:
* `component.name`
* `component.listener_map` / `component.listening_components` for `tok2vec` and `transformer`
When running `replace_listeners` on a component, the config is not updated correctly if the state of the component is incorrect for the current pipeline (in particular changes that should be applied from `model.attrs["replace_listener_cfg"]` as used in `spacy-transformers`) due to the fact that:
* `find_listeners` relies on `component.name` to set the name in the `listener_map`
* …
=> Address issues with source with component names and replacing listeners

requirements.txt, setup.cfg, spacy/about.py, spacy/language.py, spacy/tests/pipeline/test_tok2vec.py, spacy/tests/serialize/test_resource_warning.py, spacy/tests/serialize/test_serialize_config.py, spacy/tests/test_misc.py, spacy/training/initialize.py, spacy/util.py
=> Backports for v3.5.4

website/docs/usage/training.mdx
The Ray integration is currently broken, having these docs around suggest that this functionality is currently available.
Documentation update.
=> Remove section about parallel training with Ray

website/src/components/code.js
This fixes a bug with some pages not rendering correctly, because they use a code language (for syntax highlighting), that isn't loaded. 
- Add missing `docker` and `r` languages
- Default to no syntax-highlighting for pages using an unknown language (instead of runtime failing)
=> Fix problem with missing syntax highlighting languages causing runtime crash on the website

website/meta/universe.json
Hello!
Replace `disable` with `exclude`, as the former will unnecessarily load the unused "ner" model still.
Thank you @svlandeg for the suggestion on LinkedIn.
Documentation.
- [-] I ran the tests, and all new and existing tests passed.
---
- Tom Aarsen
=> Universe docs: Use 'exclude' instead of 'disable'

extra/DEVELOPER_DOCS/Listeners.md, spacy/errors.py, spacy/language.py
Prior to this PR, `Language.replace_listeners` only passed the copied `tok2vec`/`transformer` model to the `replace_listener` callback. This worked for `spacy-transformers` as the library only uses a single `TransformerListener` class, i.e., the replacement model was always the same. However, `spacy-curated-transformers` introduces the concept of different listener classes for downstream components. So, the replacement process needs to provide extra information about the listener model being replaced to correctly select the target model.
This PR adds support for such situations by passing the following extra arguments to the `replace_listener` callback: the replaced listener instance and the `tok2vec` pipe whose model is copied into the downstream component. These argumentss are only …
=> `Language.replace_listeners`: Pass the replaced listener and the `tok2vec` pipe to the callback

spacy/cli/templates/quickstart_training.jinja, spacy/pipeline/span_finder.py
When the default `max_length` is not set and there are longer training documents, it can be difficult to train and evaluate the span finder due to memory limits and the time it takes to evaluate a huge number of predicted spans.
Enhancement.
=> SpanFinder: set default max_length to 25

spacy/errors.py, spacy/language.py, spacy/tests/pipeline/test_pipe_methods.py, website/docs/api/language.mdx
Follow up to https://github.com/explosion/spaCy/pull/12349, which is on `master` - this PR targets `v4` and can get rid of the option `False` alltogether
The `first` and `last` arguments of `add_pipe` were meant to only take `None` or `True`, and disallow `False`. This PR makes that explicit in both the typing, UX and docs.
fix
=> Disallow False for first/last arguments of add_pipe

website/docs/usage/linguistic-features.mdx
Add an anchor to the docs subsection on "trainable lemmatizer" so we can link to it directly.
Also move the "needs model" bit to the trainable subsection.
docs fix
=> Trainable lemmatizer docs link

spacy/displacy/render.py, spacy/tests/test_displacy.py
These changes add a missing call to `escape_html` in the displaCy span renderer. Previously span-annotated tokens would be inserted into the page markup without being escaped, resulting in potentially incorrect rendering. When I encountered this issue, it resulted in some docs and span underlines being superimposed on top of properly rendered docs and span underlines near the beginning of the visualization (due to an unescaped `<span>` tag).
Fixes #12816.
Bug fix
=> 🐛 Escape annotated HTML tags in span renderer

spacy/language.py, website/docs/api/language.mdx
I corrected the misspelling of the word "significantly" from "significally".
modified:   spacy/language.py
- corrected typo in docstring for :method:`Language.replace_listeners`
~- added noqa comment on unused local variable assignment in :method:`Language.from_config` as I wasn't sure if it should be unassigned~
modified:   website/docs/api/language.mdx
- corrected typo in `Language.replace_listeners` markdown
=> Typo fix in `Language.replace_listeners` docs

setup.py
Additionally remove outdated `is_new_osx` check and settings.
?
=> Switch from distutils to setuptools/sysconfig

website/meta/universe.json
Added OdyCy to the spaCy Universe page.
Created entry in `universe.json` for OdyCy, the Ancient Greek pipeline that has been developed at the Center for Humanities Computing.
Extending the Universe page.
=> Added OdyCy to spaCy Universe

spacy/displacy/render.py, spacy/tests/test_displacy.py, website/docs/api/top-level.mdx, website/docs/usage/visualizers.mdx
PR redone from https://github.com/explosion/spaCy/pull/12202 to target `master` instead of `v4`.
This PR adds a new section to the `api/top-level#functions` documentation for displaCy: `Visualizer data structures`. The section shows examples of the three data structures (`Dependency Parsing`, `Entity Recognition`, and `Span Classification`) and their types formatted as tables. To reduce cluttering, the nested dictionary types are formatted as a collapsable table.
The idea for this PR initially came from this discussion https://github.com/explosion/spaCy/pull/10950
The types are based on [this gist](https://gist.github.com/pmbaumgartner/85b3a0256131e86fbdd78a8b4060d361) by @pmbaumgartner  
Documentation
=> Add displaCy data structures to docs (2)

spacy/util.py
As detailed in #12855, only the major and minor versions of the model's spaCy version are displayed in the incompatibility warning. This can be confusing if the difference is in the patch version (which is only displayed for the installed package). This PR adds the patch version of the former to the warning message.
Fix
=> Display model's full base version string in incompatiblity warning

website/docs/usage/rule-based-matching.mdx
There was a mistake in the regex pattern which caused not matching all the desired spans. The problem was that when we use r string literal prefix to demonstrate a raw text, we should not use two backslashes to be interpreted as a single backslash.
The regular expression that was written in the documentation was supposed to match 4 substrings in the given sentence:
- United States (4, 17)
- United States (61, 74)
- U.S. (76, 80)
- US (84, 86)
But it only matches the first two spans. The problem was caused by writing redundant backslashes in the regular expression, i.e. for stating a dot character in the raw string, we should use `\.` in our regular expression, but it was written in the form `\\.` mistakenly.
Documentation
=> fix the regular expression matching on the full text

spacy/cli/package.py, spacy/displacy/render.py, spacy/tests/test_displacy.py
I think the intention in displacy was `<br/>`, but maybe now `<br>` would be better (says the w3c markup validator anyway)?
Bug fix?
=> Update br tags

requirements.txt, setup.cfg, spacy/pipeline/_edit_tree_internals/schemas.py, spacy/schemas.py, spacy/tests/pipeline/test_initialize.py, spacy/tests/pipeline/test_pipe_factories.py, spacy/tests/test_misc.py
Allow pydantic v2 using transitional v1 support.
Enhancement?
=> Allow pydantic v2 using transitional v1 support

spacy/lang/zh/__init__.py
So that users can use `copy_from_base_model` for other segmenters without having to override an irrelevant `pkuseg_model` setting, switch the default `pkuseg_model` to `spacy_ontonotes`.
Enhancement.
=> Switch zh tokenizer default pkuseg_model to spacy_ontonotes

spacy/errors.py, spacy/matcher/dependencymatcher.pyx, spacy/tests/matcher/test_dependency_matcher.py
Follow-up to https://github.com/explosion/spaCy/issues/12926.
The Dependency Matcher only supports 4 specific keys in the (sub)pattern dictionaries. While it may be reasonable to assume that e.g. `'OP'` is supported, it's not, and currently this would be entirely ignored if you do try to specify it. Instead, this PR ensures a warning is printed:
```
UserWarning: [W126] These keys are unsupported: OP, FOO
```
UX enhancement
=> warn for unsupported key in dependency matcher

website/docs/api/large-language-models.mdx
Fix "langauge" typo in docs links + one parameter from `spacy.REL.v1` was misspelled.
docs fix
=> fix typo in link

website/docs/api/large-language-models.mdx, website/docs/usage/large-language-models.mdx
Added documentation for the new `spacy.ner.v3` and `spacy.spancat.v3` tasks that will be available in `spacy-llm` 0.5.0.
Also added a few smaller fixes.
docs update
=> Docs for ner.v3 and spancat.v3 spacy-llm tasks

website/docs/api/large-language-models.mdx, website/docs/usage/large-language-models.mdx
Update docs for upcoming `spacy-llm` 0.5.0 release.
- Document `LLMWrapper` like other pipe instances, including `__init__` andf `add_label` functions etc.
- Reduce redundancy between API and usage pages.
- Update OpenAI models to their `v2` versions.
- Simplify Python example with task-specific factory and `add_label` functionality.
docs update
=> Docs for spacy-llm 0.5.0

spacy/cli/evaluate.py, website/docs/api/cli.mdx
The internal `evaluate` method called by the `evaluate`/`benchmark accuracy` CLI commands accepts a spans_key value, but the CLI command itself does not. This PR adds a `--spans-key` option so that the CLI can be used to evaluate spancat models with span key values other than the default `sc`.
I also updated the CLI documentation, but I didn't add a "new" tag because I'm not sure what the version would be there.
Minor CLI enhancement
=> add --spans-key option for CLI spancat evaluation

spacy/__init__.py, spacy/tests/test_cli.py
This avoids that the `spacy` module cannot be imported when the users chooses not to install `typer`/`requests`.
Proposed alternative to #12952. With lazy loading, people that do have typer/requests installed will not pay the loading penalty when they just import `import spacy`.
Enhancement
=> Load the cli module lazily for spacy.info

website/docs/api/large-language-models.mdx
- Update `spacy-llm` task argument docs w.r.t. task refactoring in 0.5.0.
- Add disclaimer regarding licensing/login situation for Llama 2.
Docs update.
=> Update `spacy-llm` task argument docs w.r.t. task refactoring

spacy/kb/__init__.py, spacy/matcher/__init__.py, spacy/pipeline/__init__.py, spacy/tokens/__init__.py, spacy/training/__init__.py
Update `__all__` fields across the main modules 
Ensure that the imported classes/functions can be easily imported from the main module instead of a submodule (and doesn't get flagged by type checking). For easier maintenance, alphabetize the lists.
fix
=> Update __all__ fields

website/docs/api/spancategorizer.mdx
Add note on `score_weight` config if using a non-default span_key for SpanCat. Motivated by https://github.com/explosion/spaCy/issues/13090.
Docs improvement.
=> Add note in docs on `score_weight` config if using a non-default `spans_key` for SpanCat

website/docs/api/large-language-models.mdx
cf https://github.com/explosion/spaCy/discussions/13080
Explain that task-specific factories use GPT3.5 by default, but this can be changed by providing config settings.
docs update
=> Update llm docs to clarify task-specific factories

spacy/tests/tokenizer/test_explain.py, spacy/tokenizer.pyx
Update `Tokenizer.explain` to skip special case matches if the exact text has not been matched due to intervening whitespace.
Bug fix, tests.
=> Update Tokenizer.explain for special cases with whitespace

spacy/cli/package.py, website/docs/usage/saving-loading.mdx
Build with `build` if available. Warn and fall back to previous `setup.py`-based builds if `build` build fails.
Enhancement?
=> Add preferred use of build for package CLI

website/meta/universe.json
Add Redfiled NLP Nodes to the Spacy Universe page
Add an entry in the universe.json file for the Redfiled NLP Nodes - KNIME extension that makes the functionality of the spaCy library available in KNIME Analytics Platform. 
Extending the Spacy Universe page
=> Add Redfield NLP Nodes to the Spacy Universe

spacy/cli/templates/quickstart_training.jinja, spacy/errors.py, spacy/ml/models/textcat.py, spacy/pipeline/textcat.py, spacy/pipeline/textcat_multilabel.py, spacy/tests/pipeline/test_pipe_factories.py, spacy/tests/pipeline/test_textcat.py, spacy/tests/test_cli_app.py, spacy/tests/test_misc.py, website/docs/api/architectures.mdx, website/docs/api/legacy.mdx, website/docs/usage/layers-architectures.mdx, website/docs/usage/processing-pipelines.mdx
A while ago, we fixed the `SparseLinear` layer to use all available
parameters: https://github.com/explosion/thinc/pull/754
This change updates `TextCatBOW` to `v3` which uses the new
`SparseLinear_v2` layer. This results in a sizeable improvement on a
text categorization task that was tested.
While at it, this `spacy.TextCatBOW.v3` also adds the `length_exponent`
option to make it possible to change the hidden size. Ideally, we'd just
have an option called `length`. But the way that `TextCatBOW` uses
hashes results in a non-uniform distribution of parameters when the
length is not a power of two.
Bugfix
=> Update `TextCatBOW` to use the fixed `SparseLinear` layer

website/docs/api/large-language-models.mdx
Document `spacy-llm`'s `RawTask`. See https://github.com/explosion/spacy-llm/pull/395.
Doc update.
=> Document `spacy-llm`'s `RawTask`

website/docs/api/large-language-models.mdx
Document `spacy-llm`'s `TranslationTask`. See https://github.com/explosion/spacy-llm/pull/396.
Doc update.
=> Document `spacy-llm`'s `TranslationTask`

website/docs/api/large-language-models.mdx, website/docs/usage/large-language-models.mdx
Updated docs w.r.t. infinite doc length changes. See https://github.com/explosion/spacy-llm/pull/332.
Also updates task list in usage docs with `TranslationTask`.
Docs update.
=> Updated docs w.r.t. infinite doc length changes

spacy/language.py
Before this change, the workers of pipe call with `n_process != 1` were
stopped by calling `terminate` on the processes. However, terminating a
process can leave queues, pipes, and other concurrent data structures in
an invalid state.
With this change, we stop using terminate and take the following approach
instead:
* When the all documents are processed, the parent process puts a
sentinel in the queue of each worker.
* The parent process then calls `join` on each worker process to
let them finish up gracefully.
* Worker processes break from the queue processing loop when the
sentinel is encountered, so that they exit.
We need special handling when one of the workers encounters an error and
the error handler is set to raise an exception. In this case, we cannot
rely on the sentinel to …
=> Properly clean up multiprocessing workers

website/docs/api/vocab.mdx
Fixes https://github.com/explosion/spaCy/issues/13252
The example in the docs assumes that `"apple"` is in the vocab but this isn't necessarily the case. Expanding the example to ensure that it is, and to (hopefully) clarify that the vocab works as a cache.
docs update
=> Clarify vocab docs

website/docs/api/cli.mdx
Fixes https://github.com/explosion/spaCy/issues/13230
Attempt to clarify that if a specified .spacy file contains annotations, that these will be preserved by the `apply` CLI command, and run through the pipeline as is. There are valid cases to do for this, like e.g. evaluating an EL pipeline on files that have gold entities, but the behaviour may be surprising for users assuming that the pipeline will be applied to raw text only.
doc update
=> Clarify data_path loading for apply CLI command

spacy/cli/benchmark_speed.py, website/docs/api/cli.mdx
Adds `--code` option to the speed benchmark CLI command so that pipelines with custom components can be benchmarked.
I used `[doc.from_docs([doc]) for doc in docs]` to deep-copy the warmup docs to prevent errors with pipelines that modify sentence boundaries. Happy to change this to something else if there's a more idiomatic way to copy those docs!
CLI enhancement + associated documentation update
=> add custom code support to CLI speed benchmark

spacy/tests/serialize/test_serialize_extension_attrs.py
The doc/token extension serialization tests add extensions that are not
serializable with pickle. This didn't cause issues before due to the
implicit run order of tests. However, test ordering has changed with
pytest 8.0.0, leading to failed tests in test_language.
Update the fixtures in the extension serialization tests to do proper
teardown and remove the extensions.
Bugfix
=> Extension serialization attr tests: add teardown

spacy/cli/benchmark_speed.py, spacy/tests/serialize/test_serialize_extension_attrs.py, website/docs/api/cli.mdx, website/docs/api/vocab.mdx
Merge `main` into `develop`.
Maintenance
=> Merge main into `develop`

spacy/ml/models/textcat.py, spacy/tests/pipeline/test_textcat.py, spacy/tests/tok2vec.py
This is necessary for tok2vec implementations that initialize lazily (e.g. curated transformers).
Set key transform dimensions in `TextCatParametricAttention.v1`, otherwise the key transformation dimensionality cannot be inferred for lazily-initialized tok2vecs listeners like transformers.
Not sure how we can test this without making a new tok2vec model in spaCy that is lazily initialized (does know its width until initialization). Maybe we should add a separate model to the tests?
=> `TextCatParametricAttention.v1`: set key transform dimensions

spacy/language.py
=> Test if closing explicitly solves recursive lock issues

spacy/errors.py, spacy/language.py, spacy/tests/test_language.py
Also warn when any worker exited with a non-zero exit code and modify test to ensure that workers exit cleanly by default.
Bugfix
=> Make `Language.pipe` workers exit cleanly

spacy/cli/__init__.py, spacy/cli/download.py, spacy/tests/test_cli.py
The 'direct' option in 'spacy download' is supposed to only download from our model releases repository. However, users were able to pass in a relative path, allowing download from arbitrary repositories. This meant that a service that sourced strings from user input and which used the direct option would allow users to install arbitrary packages.
=> Sanitize direct download

requirements.txt, setup.cfg
spaCy doesn't need to manage the `smart_open` requirement, as this is taken care of by Weasel.
Related PR to bump `smart_open` to the latest version: https://github.com/explosion/weasel/pull/84
fix
=> remove smart_open requirement

.github/workflows/gputests.yml, .github/workflows/slowtests.yml
For clarity, renamed `main` back to `v4` to avoid confusion for users.
fix
=> Renamed main branch back to v4 for now

requirements.txt, setup.cfg
Bump weasel upper pin to allow v0.4.x.
Weasel 0.4.0 has no breaking changes other than dropping Python 3.6, which spaCy already did since 3.7.0.
Update
=> Bump weasel upper pin to allow v0.4.x

spacy/lexeme.pyx, spacy/tokenizer.pyx, spacy/tokens/doc.pyx, spacy/tokens/span.pyx, spacy/tokens/token.pyx, spacy/training/example.pyx, spacy/vocab.pyx
spaCy uses a legacy syntax for defining properties in a Cython extension class which has been deprecated since ~2016:
https://cython.readthedocs.io/en/stable/src/userguide/extension_types.html#properties
Switching to the new syntax required moving the property docstrings. Previously, the docstring was placed on the line below the property keyword. However, using the new syntax there can not be anything between the decorator and the def statement, so the docstring was moved to below the def statement.
Syntax change only
- [X ] I confirm that I have the right to submit this contribution under the project's MIT license.
- [X ] I ran the tests, and all new and existing tests passed.
- [X ] My changes don't require a change to the documentation, or if they do, I've added all required …
=> Convert properties to decorator syntax

.github/workflows/explosionbot.yml, .github/workflows/slowtests.yml, .github/workflows/spacy_universe_alert.yml, .github/workflows/tests.yml, .github/workflows/universe_validation.yml, requirements.txt, setup.cfg
- Update `typer` pin to allow up to 1.0.0, cf report in https://github.com/explosion/spaCy/discussions/13464
- Update versions of GH actions
update
=> Update Typer pin and GH actions

website/docs/api/morphology.mdx
Fix #13406: Fixing the documentation of `MorphAnalysis.__contains__`  
docs fix
=> Fix docs for MorphAnalysis.__contains__

requirements.txt, setup.cfg
Removing `typing-extensions` from spaCy's requirements, as this is dealt with by `confection`. In the latest release `v0.1.5` of `confection`, we've [bumped](https://github.com/explosion/confection/pull/63) the upper pin to allow up to 5.0.0 for Python < 3.8, hopefully dealing with an install issue that was preventing us to build the wheels for spaCy 3.7.5. 
Fix & update
=> Remove typing-extensions from requirements

.github/workflows/cibuildwheel.yml, .github/workflows/publish_pypi.yml, pyproject.toml, setup.cfg, spacy/about.py
Our wheelwright process is very complicated and hard to maintain. There's some extra architectures missing currently, but using cibuildwheel directly like this makes things much easier.
=> Use cibuildwheel to build wheels

spacy/lang/kmr/__init__.py, spacy/lang/kmr/examples.py, spacy/lang/kmr/lex_attrs.py, spacy/lang/kmr/stop_words.py, spacy/tests/lang/kmr/test_text.py, spacy/tests/lang/test_initialize.py, spacy/tests/tokenizer/test_explain.py, website/meta/languages.json
I could not find a document on how to add a new language. I just checked what the existing ones have and added them for Kurdish Kurmanji. I may miss things. Please let me know and also if there is you could provide a doc link for it. 
Adding a new language Kurdish Kurmanji
=> Add Kurdish Kurmanji language

spacy/strings.pxd, spacy/strings.pyx, spacy/tests/vocab_vectors/test_memory_zone.py, spacy/tokenizer.pxd, spacy/tokenizer.pyx, spacy/vocab.pxd, spacy/vocab.pyi, spacy/vocab.pyx
Add a context manage nlp.memory_zone(), which will begin
memory_zone() blocks on the vocab, string store, and potentially
other components.
Example usage:
```
with nlp.memory_zone():
for text in nlp.pipe(texts):
do_something(doc)
```
Once the memory_zone() block expires, spaCy will free any shared
resources that were allocated for the text-processing that occurred
within the memory_zone. If you create Doc objects within a memory
zone, it's invalid to access them once the memory zone is expired.
The purpose of this is that spaCy creates and stores Lexeme objects
in the Vocab that can be shared between multiple Doc objects. It also
interns strings. Normally, spaCy can't know when all Doc objects using
a Lexeme are out-of-scope, so new Lexemes accumulate in the vocab,
causing memory …
=> Support 'memory zones' for user memory management

website/meta/universe.json
=> added gliner-spacy to universe (#13417) [ci skip]

website/meta/universe.json
Added the Constituent-Treelib library to the spaCy's universe.
The change represents an enhancement to the spaCy's universe.
=> Added: Constituent-Treelib to: universe.json (#13432) [ci skip]

website/docs/usage/101/_serialization.mdx
"Pickle protocol" text previously linked to https://www.diveinto.org/python3/serializing.html#dump, however diveinto is not currently a valid domain. Updating hyperlink to the Python documentation for pickle.
Documentation.
=> [Documentation] Replace broken URL in  _serialization.mdx

CONTRIBUTING.md
Fix 'issue template' link to point to the issue templates instead of a blank new issue.
I updated the link and changed the grammar to point to the issue templates.
Here is [the issue](https://github.com/explosion/spaCy/issues/13586) I created for this.
=> Fix 'issue template' link in CONTRIBUTING.md (#13587) [ci skip]

website/meta/universe.json
I am adding my course to spaCy universe
Adding new information to the spaCy universe
=> Update universe.json to add my spaCy online course (#13632) [ci skip]

website/docs/api/large-language-models.mdx
=> Fix typo (#13657) [ci skip]

README.md
SpaCy 3.8 is not compatible with Python 3.13 yet but the doc says otherwise, which can lead for users to loose time on that if they are ill-informed.
See https://github.com/explosion/spaCy/issues/13658
Update README.md to fix compatible Python versions.
=> docs: fix README.md for compatible Python versions

website/meta/universe.json
This is a very small change to update the `title` attribute of the [spaCy Universe entry for ChatterBot](https://spacy.io/universe/project/Chatterbot) to use the correct casing for the name so that it matches the logo and casing of the [ChatterBot GitHub repository](https://github.com/gunthercox/chatterbot) and [documentation](https://docs.chatterbot.us/).
Current:
Expected:
Documentation update
***
_P.S. The spaCy Universe collection is wonderful and I was quite happy and surprised when I recently stumbled upon the fact that ChatterBot had an entry there._
=> Update spaCy Universe entry for ChatterBot to use the correct name casing

requirements.txt, setup.cfg
This PR changes the dependency on [`typer`](https://github.com/fastapi/typer) to [`typer-slim`](https://github.com/fastapi/typer?tab=readme-ov-file#typer-slim) which has lighter dependencies.
Relates to https://github.com/explosion/spaCy/discussions/13538.
Dependency.
=> Switch to typer-slim

spacy/lang/ht/__init__.py, spacy/lang/ht/examples.py, spacy/lang/ht/lemmatizer.py, spacy/lang/ht/lex_attrs.py, spacy/lang/ht/punctuation.py, spacy/lang/ht/stop_words.py, spacy/lang/ht/syntax_iterators.py, spacy/lang/ht/tag_map.py, spacy/lang/ht/tokenizer_exceptions.py, spacy/tests/conftest.py, spacy/tests/lang/ht/test_exceptions.py, spacy/tests/lang/ht/test_noun_chunks.py, spacy/tests/lang/ht/test_prefix_suffix_infix.py, spacy/tests/lang/ht/test_text.py
This PR adds official support for Haitian Creole (ht) to spaCy's spacy/lang module.
It includes:
- Added all core language data files for spacy/lang/ht:
- tokenizer_exceptions.py
- punctuation.py
- lex_attrs.py
- syntax_iterators.py
- lemmatizer.py
- stop_words.py
- tag_map.py
- Unit tests for tokenizer and noun chunking (test_tokenizer.py, test_noun_chunking.py, etc.). Passed all 58 pytest spacy/tests/lang/ht tests that I've created.
- Basic tokenizer rules adapted for Haitian Creole orthography and informal contractions.
- Custom like_num atrribute supporting Haitian number formats (e.g., "3yèm").
- Support for common informal apostrophe usage (e.g., "m'ap", "n'ap", "di'm").
- Ensured no breakages in other language modules.
- Followed spaCy coding style (PEP8, Black).
This provides a …
=> Added Haitian Creole (ht) Language Support to spaCy
