explosion/spaCy

- spacy/default_config.cfg
- spacy/language.py
- spacy/schemas.py
- spacy/tests/test_language.py
- website/docs/usage/training.md
- website/docs/usage/v3.md
Add `initialize.before_init` and `initialize.after_init` callbacks to the config. The `initialize.before_init` callback is a place to implement one-time tokenizer customizations that are then saved with the model.
Enhancement.
> Add initialize.before_init and after_init callbacks

- Makefile
- spacy/lang/ru/lemmatizer.py
- spacy/lang/uk/lemmatizer.py
* Update pymorphy2 error messages for Russian and Ukrainian
* Add pymorphy2 to pex
* Update spacy-pkuseg version for pex
?
> Update model-related dependencies

- spacy/tests/serialize/test_serialize_tokenizer.py
- spacy/tokenizer.pyx
When the serialized `token_match` or `url_match` is `None`, override the language defaults to preserve `None` on deserialization.
Bug fix.
> Override language defaults for null token and URL match

- spacy/lang/da/syntax_iterators.py
- spacy/lang/es/syntax_iterators.py
* Prevent overlapping noun chunks in Spanish noun chunk iterator
* Clean up similar code in Danish noun chunk iterator
Bug fix
> Prevent overlapping noun chunks for Spanish

- spacy/cli/debug_config.py
- spacy/errors.py
- spacy/training/initialize.py
Validate both `[initialize]` and `[training]` in `debug data` and `nlp.initialize()` with separate config validation error blocks that indicate which block of the config is being validated.
Enhancement
> Expand initialize/training config validation

- spacy/language.py
Add all strings from the source model when adding a pipe from a source model.
Minor:
* Skip `disable=["vocab", "tokenizer"]` when loading a source model from the config, since this doesn't do anything and is misleading.
Bug fix.
> Add all strings from source models

- spacy/pipeline/_parser_internals/arc_eager.pyx
Remove assertion for default debug value in `get_oracle_sequence_from_state`.
Bug fix.
> Fix assertion in default get oracle sequence usage

- spacy/lang/mk/lemmatizer.py
Remove unimplemented/incorrect `is_base_form` for Macedonian lemmatizer.
Bug fix.
> Remove unused is_base_form for mk lemmatizer

- spacy/ml/models/parser.py
Fix parser resizing for cupy
Bug fix.
> Fix parser resizing for cupy

- spacy/ml/models/textcat.py
Related to https://github.com/explosion/spacy-transformers/pull/231 and https://github.com/explosion/spaCy/commit/c2a18e4fa35355124e9da78c90526a01557e7cfb. Unfortunately the shape inference still doesn't work well when we call `Maxout` with `dropout` and `normalize` arguments, because they call `chain` behind the scene, preventing us to set the dimensions correctly on the "inner" core `maxout` model.
As said before - the shape inference can be a bit of a headache and perhaps we need to revise this at some point. But this is a quick fix to get `test_transformer_pipeline_textcat` working.
bug fix
> rewrite Maxout layer

- spacy/matcher/matcher.pyx
- spacy/tests/matcher/test_matcher_api.py
Add hack to prevent matcher from returning 0-length matches.
Fixes #6677.
Bug fix.
> Skip 0-length matches

- website/meta/languages.json
* Add Macedonian
* Add Russian dependencies
* Switch Chinese dependency to `spacy-pkuseg`
Docs
> Update languages for website

- website/meta/languages.json
Add xx_sent_ud_sm model to website
Docs
> Add xx_sent_ud_sm model to website

- website/docs/api/transformer.md
> Fix default config init in Transformer API docs

- website/docs/api/pipeline-functions.md
- website/docs/usage/embeddings-transformers.md
Remove transformers model max length section now that there is working truncation in `spacy-transformers`.
Docs.
> Remove transformers model max length section

- spacy/cli/info.py
Fix types for exclude args in info CLI
?
> Fix types for exclude args in info CLI

- spacy/lang/bn/__init__.py
- spacy/lang/el/__init__.py
- spacy/lang/en/__init__.py
- spacy/lang/fa/__init__.py
- spacy/lang/fr/__init__.py
- spacy/lang/mk/__init__.py
- spacy/lang/nb/__init__.py
- spacy/lang/nl/__init__.py
- spacy/lang/pl/__init__.py
- spacy/lang/ru/__init__.py
- spacy/lang/sv/__init__.py
- spacy/lang/uk/__init__.py
Implement overwrite param for all custom lemmatizers
Bug fix
> Implement overwrite param for all custom lemmatizers

- .github/contributors/dhruvrnaik.md
- spacy/tests/regression/test_issue6815.py
- spacy/tokens/span.pyx
Added test for checking that labels, kb_id passed to Span.char_span are actually assigned.
Added the `label`, `kb_id` and `vector` to `doc.char_span()`
Resolves #6815 
Bugfix: passed the `label`, `kb_id` and `vector` arguments to doc.char_span()
> Fix Span.char_span bug

- website/docs/api/cli.md
Update `--code` arg in evaluate CLI docs
Docs
> Update --code arg in evaluate CLI docs

- spacy/lang/es/__init__.py
- spacy/lang/es/lemmatizer.py
- spacy/tests/lang/test_lemmatizers.py
Add a default Spanish rule-based lemmatizer for Spanish based on work by Guadalupe Romero. (Will require `spacy-data-lookups>=1.0.0rc2`.)
Enhancement.
> Add Spanish rule-based lemmatizer

- website/docs/api/language.md
- website/docs/api/pipe.md
Quick docs fix after https://github.com/explosion/spaCy/pull/6817
docs
> adding new="3" mentions in the doc

- website/docs/usage/embeddings-transformers.md
* Recommend installing PyTorch separately
* Add instructions for `sentencepiece`
Docs.
> Update transfomers install docs

- website/docs/usage/embeddings-transformers.md
Rephrase transformers PyTorch instructions
Docs
> Rephrase transformers PyTorch instructions

- requirements.txt
Ensuring the `hypothesis` stuff in Thinc works properly
requirements fix
> update pytest pin to match Thinc 8.0

- requirements.txt
- setup.cfg
Just making sure everything builds as expected.
chore, dependencies, serialization
> Update srsly pin

- spacy/cli/templates/quickstart_training.jinja
Remove `nlp.tokenizer` from quickstart template so that the default language-specific tokenizer settings are filled instead.
Docs / bug fix?
> Remove nlp.tokenizer from quickstart template

- website/docs/usage/models.md
> Fix a typo

- spacy/cli/project/run.py
Follow-up to PR #6878
(there's no rush to release this in a dev version orso)
Forgot one place where to add the flag
fix
> add capture arg

- spacy/__init__.py
Pass on vocab arg in spacy.blank()
Bug fix.
> Pass on vocab arg in spacy.blank()

- .github/contributors/reneoctavio.md
- spacy/pipeline/textcat.py
- spacy/pipeline/textcat_multilabel.py
- spacy/tests/regression/test_issue6908.py
As per issue #6908, I fixed textcat labels argument to expect a Optional[Iterable[str]] instead of Optional[Dict].
I created a regression test called test_issue6908.py, to check the bug.
I ran the regression test and `py.test spacy` all passed.
This is my first contribution to this repo. Let me know if I am missing anything, or if I can improve something in this PR.
Fix #6908
> fix: Fix textcat labels to expect a Optional[Iterable[str]] instead of Optional[Dict]

- README.md
- website/docs/usage/index.md
* Remove duplicate section about compiling from source
* Recommend `pip install --no-build-isolation --editable`
> Update install instructions

- spacy/errors.py
Now that the initialize step is fully implemented, the source of E923 is typically missing or improperly converted/formatted data rather than a bug in spaCy, so rephrase the error and message and remove the prompt to open an issue.
?
> Rephrase error related to sample data initialization

- website/docs/usage/_benchmarks-models.md
- website/docs/usage/facts-figures.md
Update accuracy tables with final numbers from 3.0.0 models
docs
> final 3.0 benchmark numbers

- spacy/cli/templates/quickstart_training_recommendations.yml
Add/update trf recommendations for Bengali, Hindi, Sinhala, and Tamil based on #7044.
Enhancement.
> Update trf quickstart recommendations

- spacy/tests/test_pickles.py
- spacy/vocab.pyx
Include noun chunks method when pickling Vocab (broken after b507f616).
Bug fix.
> Include noun chunks method when pickling Vocab

- website/docs/usage/v3.md
It seems that nlp.update(examples) should be nlp.update(batch)
> var batch is useless

- spacy/cli/convert.py
Map `conll` to the NER converter, not the `CoNLL-U` converter.
Bug fix.
> Fix conll converter option

- spacy/cli/evaluate.py
Now that `nlp.evaluate()` does not modify the examples, rerun the pipeline on the (limited) texts in order to provide the predicted annotation in the displacy output option.
Bug fix.
> Fix displacy output in evaluate CLI

- spacy/lang/ru/lemmatizer.py
- spacy/lang/uk/lemmatizer.py
Fix class variable and init for `UkrainianLemmatizer` so that it loads the `uk` dictionaries rather than having the parent `RussianLemmatizer` override with the `ru` settings.
Bug fix.
> Fix Ukrainian lemmatizer init

- website/docs/usage/models.md
> fix typo in models.md

- website/meta/universe.json
This pull request adds a project "ruTS" to the SpaCy Universe. The library allows extracting the following statistics from a text in russian: basic statistics, readability metrics, lexical diversity metrics, morphological statistics.
It is a change to the documentation, since it is only an addition to Universe.
> Adding project "ruTS" to the spaCy Universe

- spacy/util.py
Add `asctime` and `levelname` to default logging formatter so that it's easier for users to distinguish warnings warnings from logger warnings.
(No particular effort to make this pretty. I mainly added the timestamp to make it look extremely logger-like. Alternate/prettier formatting would be fine.)
Enhancement.
> Add time and level to default logging formatter

- spacy/pipeline/sentencizer.pyx
Reapply the refactoring (#4721) so that `Sentencizer` uses the faster `predict` and `set_annotations` for both `__call__` and `pipe`.
Bug fix.
> Re-refactor Sentencizer with Pipe API

- spacy/language.py
Check `component_names` instead of `pipe_names` to allow sourcing disabled components.
Bug fix.
> Allow sourcing disabled components

- spacy/cli/templates/quickstart_training_recommendations.yml
Fix formatting in bg/bn quickstart recs
Bug fix.
> Fix formatting in bg/bn quickstart recs

- spacy/vocab.pyx
- website/docs/api/doc.md
- website/docs/api/vocab.md
Extend docs related to `Vocab.get_noun_chunks`.
Docs.
> Extend docs related to Vocab.get_noun_chunks

- setup.py
Set the `include_dirs` in each `Extension` rather than in `setup()` to handle the case where there is a custom `distutils.cfg` that modifies the include paths, in particular for python from homebrew.
Bug fix?
> Set include_dirs in Extension

- spacy/tests/test_misc.py
- spacy/tests/util.py
- spacy/util.py
* Fix `is_cython_func` for imported code loaded under `python_code` module name
* Add `make_named_tempfile` context manager to test utils to test loading of imported code
* Add test for validation of `initialize` params in custom module
Bug fix.
> Fix is_cython_func for additional imported code

- requirements.txt
- setup.cfg
> sync pins with thinc

- spacy/cli/_util.py
If the user has `cupy` and an available GPU, add a hint about using `--gpu-id 0` to the CLI output.
Enhancement.
> Add hint for --gpu-id to CLI device info

- website/src/templates/models.js
Limit to v2 models on v2.spacy.io
Docs.
> Limit to v2 models on v2.spacy.io

- spacy/cli/templates/quickstart_training.jinja
Omit unused tok2vec/transformer components in quickstart template.
Enhancement.
> Omit unused tok2vec/transformer components

- spacy/training/loop.py
Fix training patience so that the earliest best step is chosen for identical max scores.
Previously, it would chose the latest best step and the patience would never be exceeded.
Bug fix.
> Fix patience for identical scores

- spacy/tests/training/test_augmenters.py
- spacy/training/augment.py
* Fix aborted/skipped augmentation for `spacy.orth_variants.v1` if lowercasing was enabled for an example
* Simplify `spacy.orth_variants.v1` for `Example` vs. `GoldParse`
* Preserve reference tokenization in `spacy.lower_case.v1`
Bug fix.
> Fix lowercase augmentation

- .github/contributors/jankrepl.md
- spacy/pipeline/entityruler.py
Closes #7352
The idea is to sort the labels. This way the order will always be the same.
This is a bug fix.
> Sort EntityRuler labels 

- spacy/about.py
> Set version to v3.0.4

- spacy/tests/package/test_requirements.py
Following requirements and pyproject.toml adjustments, update package requirements test to:
* ignore `hypothesis`
* include `numpy`
Tests.
> Update package requirements tests

- spacy/displacy/__init__.py
Also exclude user hooks in displacy conversion
Bug/UX fix.
> Also exclude user hooks in displacy conversion

- spacy/__init__.py
- website/docs/api/top-level.md
Align keyword-only kwargs been load/util and docs
?
> Align keyword-only kwargs been load/util and docs

- examples/README.md
- examples/training/README.md
> Add examples README

- .github/contributors/bsweileh.md
- website/docs/usage/101/_training.md
Fix broken link on backpropagation
> Update _training.md - Fix broken link on backpropagation

- spacy/util.py
Check for callbacks entry points
Bug fix.
> Check for callbacks entry points

- spacy/lang/ru/lemmatizer.py
* To allow default lookup lemmatization from `spacy-lookups-data` with a blank Russian model, rename pymorphy2 lookup mode to `pymorphy2_lookup`
* Bug fix: update pymorphy2 lookup lemmatize to return list rather than string
Bug fix.
> Rename and update Russian pymorphy2 lookup lemmatize

- website/meta/universe.json
This PR adds SpikeX to the spaCy universe.
SpikeX is a collection of pipes ready to be plugged in a spaCy pipeline. It aims to help in building knowledge extraction tools with almost-zero effort.
Only spaCy universe.
> Add SpikeX to spaCy universe

- spacy/training/corpus.py
Update deprecated doc.is_sentenced in Corpus
?
> Update deprecated doc.is_sentenced in Corpus

- website/docs/models/index.md
Add details about pretrained pipeline design
Docs.
> Add details about pretrained pipeline design

- spacy/errors.py
- spacy/pipeline/morphologizer.pyx
- spacy/pipeline/senter.pyx
- spacy/pipeline/tagger.pyx
- spacy/pipeline/transition_parser.pyx
- spacy/util.py
* Add util method for check
* Add new languages to list with lexeme norm tables
* Add check to all relevant components
* Add config details to warning message
Note that we're not actually inspecting the model config to see if `NORM` is used as an attribute, so it may warn in cases where it's not relevant.
?
> Update lexeme_norm checks

- spacy/language.py
- spacy/training/initialize.py
See here:
https://github.com/explosion/spaCy/discussions/7463
Still need to check if there are any side effects of listeners being
present but not in the pipeline, but this commit will silence the
warnings.
Warning fix.
> Don't warn about components not in the pipeline

- spacy/errors.py
- spacy/tests/doc/test_doc_api.py
- spacy/tokens/doc.pyx
Merge data from `doc.spans` in `Doc.from_docs()`.
* Fix internal character offset set when merging empty docs (only affects tokens and spans in `user_data` if an empty doc is in the list of docs)
Bug fix?
> Merge doc.spans in Doc.from_docs()

- spacy/tokens/_retokenize.pyx
Implement manual `append` and `delete` for non-numpy ops.
Bug fix.
> Fix tensor retokenization for non-numpy ops

- setup.cfg
- website/docs/usage/index.md
> Add support for CUDA 11.2

- spacy/tests/doc/test_doc_api.py
- spacy/tests/doc/test_span.py
- spacy/tokens/doc.pyx
- spacy/tokens/span.pyx
* Adjust custom extension data when copying user data in `Span.as_doc()`
* Restrict `Doc.from_docs()` to adjusting offsets for custom extension data
* Update test to use extension
* (Duplicate bug fix for character offset from #7497)
Bug fix.
> Fix/update extension copying in Span.as_doc and Doc.from_docs

- spacy/matcher/dependencymatcher.pyx
- spacy/tests/matcher/test_dependency_matcher.py
Preserve user data for DependencyMatcher on spans
Bug fix.
> Preserve user data for DependencyMatcher on spans

- .github/contributors/SamEdwardes.md
- website/meta/universe.json
Updated the documentation for spaCy 3.0 for spaCyTextBlob.
Updated the documentation for spaCyTextBlob which now supports spaCy 3.0.
Change to documentation.
> Updates to universe.json for spaCyTextBlob

- spacy/errors.py
- spacy/training/initialize.py
See #7637, where this came up.
Add a warning
> Add warning if initial vectors are empty

- spacy/training/converters/conll_ner_to_docs.py
Fix parser sourcing in NER converter
Bug fix.
> Fix parser sourcing in NER converter

- website/src/widgets/quickstart-install.js
Expand quickstart widget with cuda 11.1 and 11.2 - follow-up of PR https://github.com/explosion/spaCy/pull/7583
docs enhancement
> Update quickstart with new cuda

- spacy/pipeline/lemmatizer.py
- spacy/tests/pipeline/test_lemmatizer.py
Use the morph hash rather than the `MorphAnalysis` object in the cache key so that the `Lemmatizer` can be pickled.
Bug fix.
> Use morph hash in lemmatizer cache key

- spacy/cli/debug_data.py
* Remove new/existing label distinction (new labels are not immediately distinguishable because the pipeline is already initialized)
* Warn on missing labels in training data for all components except parser
* Separate textcat and textcat_multilabel sections
* Add section for morphologizer
?
> Update debug data further for v3

- requirements.txt
- setup.cfg
- spacy/util.py
Set catalogue lower pin to v2.0.2
Bug fix?
> Set catalogue lower pin to v2.0.3

- spacy/ml/_character_embed.py
Register `CharacterEmbed` layer (not to be confused with `CharacterEmbed` architecture) as `spacy.CharEmbed.v1`.
?
> Register CharEmbed layer

- spacy/tests/tokenizer/test_explain.py
- spacy/tokenizer.pyx
- website/docs/usage/linguistic-features.md
Update `Tokenizer.explain` and the pseudo-code in the docs to include the processing of special cases that contain affixes or whitespace.
> Update Tokenizer.explain with special matches

- website/meta/universe.json
Adding an entry for the Coreferee project to universe.json.
> Add entry for Coreferee project to universe.json

- website/meta/universe.json
Add `TRUNAJOD` text complexity library to `spaCy` universe.
* Update `universe.json` with `TRUNAJOD` info.
Not sure.
> Add TRUNAJOD to spaCy universe.

- website/meta/universe.json
Added a logo to spaCyTextBlob
Documentation enchancement.
> Added a logo to spaCyTextBlob

- .github/contributors/meghanabhange.md
- website/meta/universe.json
Project Idea for spaCy universe : Denomme is a person name detector which is trained on XLM-Roberta. It can be added as pipe and will detect multilingual name
Person Name Detector. Currently works on English, Arabic and Indian names. It can be used as a pipeline extension as follows
```
from spacy.lang.xx import MultiLanguage
from denomme.name import person_name_component
nlp = MultiLanguage()
nlp.add_pipe("denomme")
doc = nlp("Hi my name is Meghana S.R Bhange and I want to talk Asha")
print(doc._.person_name)
```
Addition to spaCy Universe.
> Project Idea : denomme | Multilingual Name Detection

- requirements.txt
- setup.cfg
- spacy/cli/templates/quickstart_training.jinja
- spacy/ml/models/tok2vec.py
- spacy/ml/staticvectors.py
- spacy/pipeline/dep_parser.pyx
- spacy/pipeline/entity_linker.py
- spacy/pipeline/morphologizer.pyx
- spacy/pipeline/multitask.pyx
- spacy/pipeline/ner.pyx
- spacy/pipeline/senter.pyx
- spacy/pipeline/tagger.pyx
- spacy/pipeline/textcat.py
- spacy/pipeline/textcat_multilabel.py
- spacy/pipeline/tok2vec.py
- website/docs/api/architectures.md
- website/docs/api/data-formats.md
- website/docs/api/legacy.md
- website/docs/usage/embeddings-transformers.md
- website/docs/usage/layers-architectures.md
Replace negative row indices with 0-vectors in `StaticVectors`.
Bug fix.
> Replace negative rows with 0 in StaticVectors

- spacy/tests/serialize/test_serialize_tokenizer.py
- spacy/tests/tokenizer/test_tokenizer.py
- spacy/tokenizer.pxd
- spacy/tokenizer.pyx
Fix/simplify tokenizer init detection in order to fix cache flushing when properties are modified.
Bug fix.
> Fix tokenizer cache flushing

- spacy/tests/training/test_new_example.py
- spacy/training/example.pyx
- spacy/util.py
- website/docs/api/data-formats.md
- website/docs/api/doc.md
- website/docs/api/token.md
Update `sent_starts` for `Example.from_dict` so that `Optional[bool]` values have the same meaning as for `Token.is_sent_start`.
Use `Optional[bool]` as the type for sent start values in the docs.
?
> Update sent_starts in Example.from_dict

- spacy/errors.py
- spacy/training/__init__.py
- spacy/training/callbacks.py
- spacy/util.py
- website/docs/api/top-level.md
Add callback `spacy.copy_from_base_model.v1` to copy the tokenizer settings and/or vocab (including vectors) from a base model.
Enhancement.
> Add callback to copy vocab/tokenizer from model

- spacy/about.py
> Set version to v3.0.6

- requirements.txt
- setup.cfg
Update spacy-legacy to >=3.0.4
> Update spacy-legacy requirements for v3.0.6

- spacy/kb.pxd
- spacy/tokenizer.pxd
- spacy/vocab.pxd
Replace `cpdef` variables with equivalent `cdef` due to removal in cython 3.0
?
> Replace cpdef variables with cdef

- spacy/morphology.pxd
- spacy/morphology.pyx
Clean up `Morphology` imports and definitions
?
> Clean up Morphology imports and definitions

- requirements.txt
- setup.cfg
Set `spacy-legacy` to `>=3.0.5` due to `spacy.StaticVectors.v1` init bug.
Bug fix.
> Set spacy-legacy to >=3.0.5

- .github/contributors/jklaise.md
- spacy/lookups.py
Fixes #7894.
Updated docstring and return type hint of a function.
> Update load_lookups return type and docstring

- spacy/tests/test_misc.py
- spacy/util.py
* Refactor to avoid literal comparison with `is`
* Extend tests
Bug fix.
> Refactor util.to_ternary_int

- requirements.txt
- setup.cfg
> Update to catalogue>=2.0.4

- website/docs/api/transformer.md
Fix Transformer.initialize example
Docs.
> Fix Transformer.initialize example

- spacy/lang/nb/punctuation.py
Add / to nb infixes as proposed in #7721.
?
> Add / to nb infixes

- spacy/tests/doc/test_doc_api.py
- spacy/tokens/doc.pyx
Fix Docs.from_docs for all empty docs
Bug fix.
> Fix Docs.from_docs for all empty docs

- website/docs/usage/embeddings-transformers.md
The fragment here is reused from a heading higher up, so you couldn't
link to this section.
> Fix pretraining objectives fragment

- spacy/vocab.pyx
Skip vector ngram backoff if minn is not set, corresponding to the documented/intended behavior.
Bug fix.
> Skip vector ngram backoff if minn is not set

- spacy/matcher/matcher.pyx
- spacy/tests/matcher/test_matcher_api.py
Fix returned span offsets for `Matcher(as_spans=True)(span)`.
Bug fix.
> Fix span offsets for Matcher(as_spans) on spans

- spacy/pipeline/_parser_internals/ner.pyx
- spacy/tests/parser/test_ner.py
Preserve `ent_kb_id` annotation on existing entity spans, which is not preserved by the transition system.
Bug fix.
> Preserve existing ENT_KB_ID annotation in NER

- website/meta/universe.json
Addition of eMFDscore library to the spacy universe. No edits to main codebase or documentation.
> Added eMFDscore to universe.json

- spacy/errors.py
- spacy/tests/doc/test_span.py
- spacy/tokens/span.pyx
Also allow `Span` string properties `label_` and `kb_id_` to be writable following #6696.
> Make all Span attrs writable

- licenses/3rd_party_licenses.txt
- spacy/lang/vi/__init__.py
- spacy/tests/conftest.py
- spacy/tests/lang/vi/test_serialize.py
- spacy/tests/lang/vi/test_tokenizer.py
* Adapt tokenization methods from `pyvi` to preserve text encoding and whitespace
* Fix non-`pyvi` tokenization to be whitespace tokenization
* Add serialization support similar to Chinese and Japanese
Note: as for Chinese and Japanese, some settings are duplicated in `config.cfg` and `tokenizer/cfg`.
Bug fix.
> Update Vietnamese tokenizer

- spacy/cli/debug_data.py
* Check for unsupported cats values
* Check for at least two labels with `textcat`
* Only show labels if train/dev mismatched
* Don't show label counts (only counting positive labels seems odd)
* Use warnings for mismatched train/dev data
Enhancement.
> Update debug data for textcat

- spacy/tests/doc/test_span.py
- spacy/tokens/doc.pyx
Fix the adjusted token index / lca matrix index ranges for `_get_lca_matrix` for spans.
* The range for `k` should correspond to the adjusted indices in `lca_matrix` with the `start` indexed at `0`
Bug fix.
> Fix range in Span.get_lca_matrix

- spacy/tests/doc/test_span.py
- spacy/tokens/doc.pyx
Fix the adjusted token index / lca matrix index ranges for `_get_lca_matrix` for spans.
* The range for `k` should correspond to the adjusted indices in `lca_matrix` with the `start` indexed at `0`
Bug fix.
> Fix offsets in Span.get_lca_matrix

- website/docs/usage/training.md
- website/src/widgets/quickstart-training.js
* add the `morphologizer` to the list of components
* add a warning that the quickstart supports the latest version of spaCy
Docs.
> Minor updates to quickstart settings/instructions

- spacy/about.py
> Set version to v2.3.6

- requirements.txt
- setup.cfg
Update pydantic requirements following
https://github.com/explosion/thinc/pull/499
?
> Update pydantic requirements

- azure-pipelines.yml
> Disable GPU CI tests

- spacy/training/iob_utils.py
- website/docs/api/top-level.md
Some docstrings & documentation was not up-to-date
docs fix
> Fix docs iob_utils

- spacy/pipeline/trainable_pipe.pyx
When reading the `model` file for some components a file was opened and read without a context manager, which could make Python complain when run in dev mode or in some environments. This change just uses a context manager to fix that.
Minor bugfix
> Fix unclosed model file

- .github/contributors/narayanacharya6.md
- spacy/language.py
- spacy/tests/regression/test_issue8190.py
- spacy/util.py
This change addresses issue #8190 and below is the testing environment used to verify the change:
```
(spaCy) narayan@Narayans-MacBook-Pro spaCy % python -m spacy info
============================== Info about spaCy ==============================
spaCy version    3.0.6                         
Location         /Users/narayan/OSS/spaCy/spacy
Platform         Darwin-20.5.0-x86_64-i386-64bit
Python version   3.7.10                        
Pipelines  
```
Additional unit test to cover the change was added.
Bug fix.
> Address missing config overrides post load of models

- setup.cfg
This adds the links to PyPI. To see that in action check out https://pypi.org/project/Django/ ([source code](https://github.com/django/django/blob/b8c9e9fae14676d2e81242cb8df1e2eeef9c3a2d/setup.cfg#L27-L32))
Link from PyPI (and other places that use that information) to the release notes and the source code.
Change of package metadata
> Add project urls to package metadata

- spacy/cli/convert.py
- spacy/pipeline/entity_linker.py
- spacy/tests/tokenizer/test_tokenizer.py
This catches a few more issues like #8244.
> Close files properly

- .github/contributors/ZeeD.md
- spacy/ml/models/multi_task.py
Simple changes to fix #8255 
changed some import as suggested in python/mypy#10542 to support `mypy --strict` 
bug fix
> applying suggestion to avoid mypy errors

- MANIFEST.in
Exclude generated `.cpp` files from package
?
> Exclude generated .cpp files from package

- spacy/cli/download.py
Fix pip args in download CLI
Bug fix.
> Fix pip args in download CLI

- azure-pipelines.yml
- spacy/about.py
Set version to v2.3.7.
Add `spacy download` test to CI.
> Set version to v2.3.7

- spacy/pipeline/entity_linker.py
> Fix typos in comments

- .github/azure-steps.yml
- azure-pipelines.yml
* Switch instances to `ubuntu-18.04`
* Add model download test, currently only for one job with python 3.8
?
> Update CI: update ubuntu image, add download test

- pyproject.toml
- requirements.txt
- setup.cfg
> Restrict cython to <3.0

- spacy/lang/ru/lemmatizer.py
- spacy/lang/uk/lemmatizer.py
- spacy/tests/conftest.py
- spacy/tests/lang/uk/test_lemmatizer.py
For the Russian and Ukrainian lemmatizers, restrict the `pymorphy2` requirement to the mode `pymorphy2` so that lookup or other lemmatizer modes can be loaded without installing `pymorphy2`.
Bug fix.
> Restrict pymorphy2 requirement to pymorphy2 mode

- spacy/__init__.py
- spacy/errors.py
- spacy/language.py
- spacy/matcher/dependencymatcher.pyx
- spacy/matcher/matcher.pyx
- spacy/pipeline/entityruler.py
- spacy/pipeline/lemmatizer.py
- spacy/tests/doc/test_doc_api.py
- spacy/tests/matcher/test_matcher_api.py
- spacy/tests/pipeline/test_entity_ruler.py
- spacy/tests/pipeline/test_lemmatizer.py
- spacy/tests/pipeline/test_pipe_factories.py
- spacy/tokens/doc.pyx
* Use `warnings.warn` instead of `logger.warning` everywhere outside of `spacy.training`
* Only show the noisy rule-based lemmatizer warning about missing POS once
Enhancement?
> Refactor warnings

- spacy/cli/package.py
In addition to `LICENSE`, move the files `README.md` and `LICENSES_SOURCES` to the top directory in `spacy package` if present in the model directory.
Enhancement.
> Move README.md and LICENSES_SOURCES in package

- setup.cfg
- spacy/lang/ca/__init__.py
- spacy/lang/ca/lemmatizer.py
- spacy/lang/ca/punctuation.py
- spacy/lang/ca/syntax_iterators.py
- spacy/lang/ca/tokenizer_exceptions.py
- spacy/tests/lang/ca/test_text.py
- spacy/tests/lang/test_lemmatizers.py
Update Catalan language data based on contributions from the Text Mining Unit at the Barcelona Supercomputing Center:
https://github.com/TeMU-BSC/spacy4release/tree/main/lang_data
Enhancement.
> Update Catalan language data

- website/meta/languages.json
Add Catalan and Danish trf to website models
Docs
> Add Catalan and Danish trf to website models

- spacy/about.py
> Set version to v3.1.0.dev0

- spacy/tests/doc/test_span.py
- spacy/tokens/span.pyx
This is a redo of #8371 based off master.
The test for this required some changes to existing tests. I don't think
the changes were significant but I'd like someone to check them.
Minor bugfix.
> Change span lemmas to use original whitespace (fix #8368)

- spacy/lang/el/lemmatizer.py
Fix non-deterministic deduplication in Greek lemmatizer
Bug fix.
> Fix non-deterministic deduplication in Greek lemmatizer

- Makefile
Update spacy-lookups-data in `Makefile`
?
> Update spacy-lookups-data in Makefile

- spacy/tests/training/test_new_example.py
- spacy/training/example.pyx
Fix setting empty entities in `Example.from_dict`: only skip `None` values, not also empty lists.
Bug fix.
> Fix setting empty entities in Example.from_dict

- spacy/cli/package.py
* Copy rather than move files to top-level of package
* Add all files to `MANIFEST.in` (primarily for older versions of pip)
* Include the `README.md` contents as `long_description` in the setup
Enhancement.
> Update package CLI handling of README and LICENSE

- spacy/cli/evaluate.py
Added Spans with default key as "sc" in cli/`evaluate`
Minor CLI improvement
> Add Spans to Evaluate CLI

- website/docs/api/lemmatizer.md
- website/docs/models/index.md
Various minor docs updates for v3.1.
Docs.
> Various docs updates for v3.1

- spacy/about.py
- spacy/tests/test_language.py
> Set version to v3.1.0

- website/docs/usage/linguistic-features.md
change /api/registry to /api/top-level#registry
> Fix broken link

- spacy/tests/doc/test_doc_api.py
- spacy/tokens/doc.pyx
* Fix spans offsets if a doc ends in a single space and no space is inserted
* Also include spans key in merged doc for empty spans lists
Bug fix
> Various fixes for spans in Docs.from_docs

- spacy/cli/templates/quickstart_training.jinja
Preserve paths.vectors/initialize.vectors setting in quickstart template
Bug fix?
> Preserve paths.vectors/initialize.vectors setting in quickstart template

- .github/azure-steps.yml
Test download in CI with `ca_core_news_sm`
Tests
> Test download in CI with ca_core_news_sm

- website/meta/universe.json
Minor fix to `universe.json` accommodating new PyATE (a project under spaCy universe) syntax
Change to documentation
> Updated PyATE syntax to fit spaCy V3 in spaCy universe

- azure-pipelines.yml
- requirements.txt
- spacy/ml/models/entity_linker.py
- spacy/pipeline/entity_linker.py
- spacy/schemas.py
- spacy/tests/serialize/test_serialize_kb.py
To include updates for `@overload` and other features, use a newer version of flake8 in the requirements and CI.
* Update some unneeded forward refs related to flake8 checks
?
> Update flake8 version in reqs and CI

- website/meta/universe.json
> Remove extra parenthesis from the example for spacy-streamlit

- spacy/cli/package.py
Use `-c` for `--code` and not additionally for `--create-meta`, in line with the docs.
Bug fix
> Fix duplicate spacy package CLI opts

- website/meta/universe.json
- ruby-spacy, ruby wrapper for spaCy, is added to Non-Python section of spaCy Universe
- added entry for ruby-spacy to [universe.json]
> Adds ruby-spacy to universe.json

- website/docs/usage/models.md
> Add docs notes on installing models from Python and in Jupyter

- .github/azure-steps.yml
- spacy/language.py
- spacy/training/initialize.py
Since vectors are not loaded when components are sourced, store a hash for the vectors of each sourced component and compare it to the loaded vectors after the vectors are loaded from the `[initialize]` block.
Suppress the warning related to mismatched vectors in `add_pipe`, since the vectors are not loaded yet.
Bug fix.
> Fix vectors check for sourced components

- .github/azure-steps.yml
- spacy/cli/_util.py
avoid `msg` var impliciteness
bug fix
> avoid msg var impliciteness

- website/docs/usage/v3-1.md
> Update v3.1 usage docs

- website/docs/usage/linguistic-features.md
A few fixes of typos in the documentation.
Typo fixes in documentation.
> Typo fixes

- website/meta/universe.json
Add forte to the spaCy universe.
Add a new entry forte(https://github.com/asyml/forte) to universe.json.
Forte is a toolkit for building Natural Language Processing pipelines, featuring cross-task interaction, adaptable data-model interfaces and composable pipelines. Forte is integrated with SpaCy API, making it easy to use as part of a heterogeneous pipeline.
document change
> Add forte to universe.json

- website/meta/languages.json
Add Macedonian models to website
Docs
> Add Macedonian models to website

- .github/contributors/julien-talkair.md
- .pre-commit-config.yaml
- CONTRIBUTING.md
- requirements.txt
Using the pre-commit framework, installs a git pre-commit hook so that `black` and `flake8` run automatically on modified files when user initiates as `git commit`
New feature for devs.
Documentation change in CONTRIBUTING.md
> Black / Flake8 as Pre-Commit hooks

- spacy/lang/az/__init__.py
- spacy/tests/lang/test_initialize.py
Fix Azerbaijani language, extend lang init tests
Bug fix.
> Fix Azerbaijani init, extend lang init tests

- spacy/lang/ru/lemmatizer.py
- spacy/lang/uk/lemmatizer.py
Use an instance variable instead a class variable for the morphological analzyer so that multiprocessing with spawn is possible.
Bug fix.
> Fix ru/uk lemmatizer mp with spawn

- .github/contributors/thomashacker.md
- spacy/cli/package.py
+ Existing meta like `performance` which is added by `spacy package` is not preserved when using a custom `meta.json` for `--meta-path`. **As discussed with** @ines this can be fixed by updating the `meta` with `nlp.meta` and afterwards with `existing_meta`
+ Added info/message if `Readme` is created or if it already exists
Bug fix
> Fix preservation of spacy package meta 

- website/meta/universe.json
Update `code_example` for `spacy-stanza` in `universe.json`
Code is from the github's [Readme](https://github.com/explosion/spacy-stanza)
Fixes #8696.
Documentation/Website
> Update spacy-stanza universe.json

- spacy/cli/validate.py
This is a backport for #8403.
?
> Update validate CLI to fix compat and ignore warnings

- spacy/tests/package/test_requirements.py
Add `pre-commit` to ignored requirements
?
> Add pre-commit to ignored requirements

- website/docs/api/lemmatizer.md
Remove TrainablePipe as base class for Lemmatizer in API docs
Docs.
> Remove TrainablePipe as base class for Lemmatizer in API docs

- .github/contributors/mariosasko.md
- website/meta/universe.json
This PR adds the `TakeLab/spacy-udpipe` project to spaCy Universe.
cc @asajatovic
> Add TakeLab/spacy-udpipe to Universe

- .github/contributors/KennethEnevoldsen.md
- website/meta/universe.json
> Added DaCy to universe

- website/meta/universe.json
Sorry, I seem to have misunderstood that the GitHub reference shouldn't be a link. This should fix it.
> fixed GitHub link and thumbnail

- spacy/language.py
Update `Language.replace_pipe` for disabled components:
* Fix the index where the replacement is inserted to account for disabled components
* Allow `Language.replace_pipe` to replace disabled components
Bug fix, minor enhancement
> Update Language.replace_pipe for disabled components

- spacy/training/initialize.py
Update the ranks for any lexemes that have been added to the vocab before the vectors are added to the model.
Bug fix.
> Update lexeme ranks for loaded vectors

- spacy/cli/debug_data.py
Reload the train corpus in debug data after `initialize` in order to take changes during `initialize` into account, in particular modifications to the tokenizer in `before_init`.
Bug fix.
> Reload train corpus in debug data after initialize

- website/docs/api/data-formats.md
I changed `python -m spacy convert ./data.json ./output.spacy` to `python -m spacy convert ./data.json .` in the docs, which yields the error 
```
Usage: python -m spacy convert [OPTIONS] INPUT_PATH [OUTPUT_DIR]
Try 'python -m spacy convert --help' for help.
```
implying OUTPUT_DIR is a directory, although the documentation says the second argument is a file.
> Changed a CLI command in data-formats.md due to erroneous information

- spacy/cli/project/run.py
Seems like the logic for this was just left out. See #8796.
This makes the `no_skip` value work. Previously it did nothing, except it used to tell DVC that there was always a change.
Should probably add tests for this.
Bug fix.
> Respect the no_skip value

- website/docs/usage/rule-based-matching.md
This adds docs for the the `IS_SUBSET` matcher. It's not much but there are a few examples. Related to #8784. 
Even the small number of examples here is more than for some of the related matchers, like `IN`, but I think it's good to have more detail because these matchers are more specialized / it can be less obvious what they're doing.
Minor docs enhancement.
> Update subset/superset docs

- website/docs/api/data-formats.md
Remove labels from textcat component config example
Docs.
> Remove labels from textcat component config example

- website/docs/usage/v3.md
This just adds the resolution from #6388 to the docs.
Minor doc update.
> Add note to migration guide about lexeme tables (fix #7290)

- website/docs/api/architectures.md
Changed `spacy.Tok2VecTransformer.v1` to `spacy-transformers.Tok2VecTransformer.v1` in docs
Documentation
> Fix typo in Tok2VecTransformer example config

- website/docs/api/entityruler.md
Fix formatting of ent_id_sep in EntityRuler API docs
Docs.
> Fix formatting of ent_id_sep in EntityRuler API docs

- website/docs/api/cli.md
- website/docs/usage/training.md
In #8823 it was pointed out that the `SPEED` value wasn't documented
anywhere.
Maybe there's a better place for this? 
Doc fix
> Add note about SPEED in output

- spacy/training/loggers.py
This is necessary to avoid "logging blackouts" when running training on Kubernetes pods
> Make ConsoleLogger flush after each logging line

- .github/contributors/nsorros.md
- spacy/cli/project/pull.py
- spacy/cli/project/push.py
As discussed in #8822 it would be helpful to have some debug information for spacy project push and pull in case the sync does not go as planned.
Adds debugging information for spacy project pull and push.
> Add logger debug for project push and pull

- spacy/language.py
Only add sourced vectors hashes to meta if necessary
Otherwise if you save out a pretrained pipeline, the meta includes this unnecessarily.
?
> Only add sourced vectors hashes to meta if necessary

- spacy/matcher/matcher.pyx
- spacy/schemas.py
- spacy/tests/matcher/test_matcher_api.py
- website/docs/api/matcher.md
- website/docs/usage/rule-based-matching.md
* Support list values as token attributes for set operators, not just as
pattern values.
* Add `INTERSECTS` operator.
* Fix incorrect `ISSUBSET` and `ISSUPERSET` in schema and docs.
Enhancement, minor docs/bug fix.
> Support list values and INTERSECTS in Matcher

- spacy/language.py
- spacy/pipeline/attributeruler.py
- spacy/pipeline/entity_linker.py
- spacy/pipeline/lemmatizer.py
- spacy/pipeline/trainable_pipe.pyx
- spacy/pipeline/transition_parser.pyx
- spacy/tests/serialize/test_serialize_pipeline.py
- spacy/tokenizer.pyx
Pass excludes when serializing vocab
Additional minor bug fix:
* Deserialize vocab in `EntityLinker.from_disk`
Bug fix.
> Pass excludes when serializing vocab

- azure-pipelines.yml
- spacy/tests/pipeline/test_spancat.py
> Fix spancat tests on GPU

- website/meta/universe.json
Information about my new book added to spaCy universe
> updated unv json for new book

- spacy/pipeline/attributeruler.py
- spacy/pipeline/dep_parser.pyx
- spacy/pipeline/entity_linker.py
- spacy/pipeline/entityruler.py
- spacy/pipeline/lemmatizer.py
- spacy/pipeline/morphologizer.pyx
- spacy/pipeline/ner.pyx
- spacy/pipeline/sentencizer.pyx
- spacy/pipeline/senter.pyx
- spacy/pipeline/spancat.py
- spacy/pipeline/tagger.pyx
- spacy/pipeline/textcat.py
- spacy/pipeline/transition_parser.pyx
- website/docs/api/attributeruler.md
- website/docs/api/dependencyparser.md
- website/docs/api/entitylinker.md
- website/docs/api/entityrecognizer.md
- website/docs/api/entityruler.md
- website/docs/api/lemmatizer.md
- website/docs/api/morphologizer.md
- website/docs/api/pipe.md
- website/docs/api/scorer.md
- website/docs/api/sentencerecognizer.md
- website/docs/api/sentencizer.md
- website/docs/api/spancategorizer.md
- website/docs/api/tagger.md
- website/docs/api/textcategorizer.md
- website/docs/api/top-level.md
Document scorers in registry and components from #8766
Docs.
> Document scorers in registry and components from #8766

- spacy/cli/templates/quickstart_training_recommendations.yml
Update the da trf recommendation to the same model used in the
pretrained pipelines.
?
> Update da trf recommendation

- website/docs/api/data-formats.md
- website/docs/usage/training.md
This adds a section to the Usage docs on how to prepare training data, right above the Quickstart. Not sure if that's the best location for it.
Docs update
> Add notes on preparing training data to docs

- .github/contributors/swfarnsworth.md
- spacy/cli/templates/quickstart_training_recommendations.yml
- spacy/matcher/dependencymatcher.pyx
This is just a small refactor of the dependency matcher. 
* Replaced loops that append to a list with a list comprehensions where this does not change the behavior.
* Replace `range(len(...))` loops with `enumerate` where both the index and the element itself are wanted. 
* Corrected one typo in a comment. 
* Replaced a call to set() with a set literal.
* Removed an unused numpy import.
This is just a refactor.
I ran the unit tests in the matcher directory (after recompiling, since this is cython) and they all passed.
1. The term "contribution" or "contributed materials" means any source code,
object code, patch, tool, sample, graphic, specification, manual,
documentation, or any other material posted or submitted by you to the project.
2. With respect to any worldwide copyrights, or …
> Refactor dependencymatcher.pyx to use list comps and enumerate.

- spacy/pipeline/spancat.py
Fix `allow_overlap` default for spancat scoring
* Remove irrelevant default options
Bug fix.
> Fix allow_overlap default for spancat scoring

- spacy/lang/ja/__init__.py
- spacy/lang/ko/__init__.py
- spacy/lang/th/__init__.py
- spacy/lang/vi/__init__.py
- spacy/lang/zh/__init__.py
- spacy/tests/lang/ja/test_serialize.py
- spacy/tests/lang/ko/test_serialize.py
- spacy/tests/lang/th/test_serialize.py
- spacy/tests/lang/vi/test_serialize.py
* Fix incorrect pickling of Japanese and Korean pipelines, which led to the entire pipeline being reset if pickled
* Enable pickling of Vietnamese tokenizer
* Update tokenizer APIs for Chinese, Japanese, Korean, Thai, and Vietnamese so that only the `Vocab` is required for initialization
Bug fix, mainly
> Update custom tokenizer APIs and pickling

- spacy/about.py
> bump to 3.1.2

- spacy/tokens/span.pyx
- website/docs/api/span.md
> fix docs for Span constructor arguments

- spacy/cli/project/run.py
Pass overrides to subcommands in workflows
Bug fix.
> Pass overrides to subcommands in workflows

- website/docs/api/docbin.md
I performed a tiny change in docs.
> Fix point typo on docbin docs

- requirements.txt
- setup.cfg
Closes #9014
See also https://github.com/tiangolo/typer/releases/tag/0.4.0
dependency fix
> Allow typer 0.4

- spacy/matcher/matcher.pyx
- website/docs/usage/rule-based-matching.md
small corrections in the matcher docs
docs
> matcher doc corrections

- spacy/matcher/matcher.pyx
- spacy/tests/matcher/test_matcher_api.py
When Matcher is called with `with_alignments=True`, make alignments accessible in `on_match` callback functions.
Enhancement to make Matcher results consistent in callbacks.
> Pass alignments to Matcher callbacks

- .github/contributors/shigapov.md
- website/meta/universe.json
This pull request adds the pipeline [spaCyOpenTapioca](https://github.com/UB-Mannheim/spacyopentapioca) to the spaCy Universe. It performs named entity linking on Wikidata updated by edits in real time using the [OpenTapioca](https://opentapioca.org) API.
It is a change to the documentation.
> added spaCyOpenTapioca

- spacy/tokenizer.pxd
- spacy/vocab.pxd
- spacy/vocab.pyi
- spacy/vocab.pyx
Two attributes in `tokenizer.pxd` were marked for removal in 3.1 but left in. This just removes them. They were no longer in use anywhere.
Minor cleanup.
> Remove two attributes marked for removal in 3.1

- spacy/training/loggers.py
- website/docs/api/top-level.md
Just adding `run_name` to WandbLogger. When you run multiple trainings sometimes it's better to assign them own name so it's easier to distinguish them in Wandb Dashboard
https://docs.wandb.ai/guides/track/launch#can-i-just-set-the-run-name-to-the-run-id
> feat: add `spacy.WandbLogger.v3` with optional `run_name` and `entity` parameters

- spacy/tests/doc/test_span.py
- spacy/tokens/span.pyx
Fix vector for 0-length span
Bug fix.
> Fix vector for 0-length span

- spacy/errors.py
- spacy/language.py
- spacy/tests/test_language.py
Allow `Doc` input to `Language.__call__` and `Language.pipe`, which
skips `Language.make_doc` and passes the doc directly to the pipeline.
Enhancement.
> Accept Doc input in pipelines

- .github/contributors/philipvollet.md
- website/meta/universe.json
Added spaCy Universe projects:
- https://github.com/explosion/spacy-huggingface-hub
- https://www.amazon.com/Mastering-spaCy-end-end-implementing/dp/1800563353
-  https://github.com/mmxgn/spacy-clausie
- https://www.amazon.com/dp/149206257X
- https://github.com/natasha/ipymarkup
- https://github.com/KoichiYasuoka/deplacy
Please double check the spaCy Universe page if everything works fine in production 8-) 
Changes to documentation
> Add projects to spaCy Universe

- spacy/tests/training/test_readers.py
Update slow readers test to use `textcat_multilabel`
Bug fix for tests.
> Update slow readers test to use textcat_multilabel

- spacy/language.py
Restore tokenization timing steps that were accidentally removed in #6765.
Bug fix.
> Restore tokenization timing in Language.evaluate

- spacy/pipeline/entity_linker.py
- spacy/pipeline/entityruler.py
- spacy/pipeline/morphologizer.pyx
- spacy/pipeline/sentencizer.pyx
- spacy/pipeline/senter.pyx
- spacy/pipeline/tagger.pyx
- spacy/tests/pipeline/test_morphologizer.py
For pipeline components where it's relevant and not already implemented, add an explicit `overwrite` setting that controls whether `set_annotations` overwrites existing annotation.
For the `morphologizer`, add an additional setting `extend`, which controls whether the existing features are preserved.
* +overwrite, +extend: overwrite values of existing features, add any new features
* +overwrite, -extend: overwrite completely, removing any existing features
* -overwrite, +extend: keep values of existing features, add any new features
* -overwrite, -extend: do not modify the existing value if set
In all cases an unset value will be set by `set_annotations`.
Preserve current overwrite defaults:
* True: morphologizer, entity linker
* False: tagger, sentencizer, senter
Enhancement.
> Add overwrite settings for more components

- website/docs/usage/index.md
This updates the troubleshooting section in the docs to link to the Discussions FAQ. It also removes some FAQs that are old and probably no longer relevant.
docs update
> Updating Troubleshooting Docs

- website/docs/api/cli.md
The docs were missing some information 
doc fix
> Doc fixes in convert API

- website/docs/usage/linguistic-features.md
Fix broken link to mappings-exceptions (the `s` in mappings was missing)
Bug fix
> Fix broken link to mappings-exceptions

- spacy/tests/test_cli.py
Temporarily skip compat tests until v3.2.0 release
Tests.
> Temporarily skip compat tests

- spacy/language.py
- spacy/tokens/doc.pxd
- spacy/tokens/doc.pyi
Set as_tuples on Doc during processing
* Rename unused `Doc._py_tokens` to `Doc._context`
Enhancement?
> Set as_tuples on Doc during processing

- spacy/tests/doc/test_pickle_doc.py
- spacy/tokens/doc.pyx
> Pickle Doc._context

- website/docs/api/language.md
The serialization functions in the API docs for Language did not link to the part in the docs that explains how to actually serialize and reload a Language. This adds a note and link. 
This has come up in support a few times, most recently in #9577. 
docs update
> Add note about round-trip serializing pipeline to API docs

- website/src/templates/models.js
* Remove vectors from core trf model descriptions
* Update performance labels and exclude `morph_acc` for ja
Docs.
> Update website model display

- spacy/language.py
- spacy/tests/test_language.py
- spacy/util.py
Add test for Language.pipe as_tuples with custom error handlers
Started with an alternate approach in #9032, but after modifying how the context is stored, few additional changes were needed to fix the `as_tuples` alignment for error handlers that warn and continue.
Tests.
> Add test for Language.pipe as_tuples with custom error handlers

- spacy/lang/pt/__init__.py
- spacy/lang/pt/syntax_iterators.py
- spacy/tests/conftest.py
- spacy/tests/lang/pt/test_noun_chunks.py
Noun chunker for Portuguese language
Feature
> Portuguese noun chunks review

- spacy/lang/es/syntax_iterators.py
- spacy/tests/conftest.py
- spacy/tests/lang/es/test_noun_chunks.py
Quick review on Spanish noun chunks. I checked adjectival clauses, nominal modifiers, compounds that are made by `fixed`, `flat` and `compound`.
Here are some cases to compare to English:
Adjectives usually come after the noun, but  `ADJ NOUN` is also quite OK. Using several adjectives to qualify the noun also looks different:
Making compounds is a bit different too, English uses `compound` tag and arcs aim left. Spanish parser uses `flat` and in this case we have to extend to right:
Hence for Spanish, I put some code to extend the NPs to right.
A final word is on nominal modifiers and `poss` relation. Spanish doesn't have a `poss` relation and marker, hence possessiveness is shown by `nmod`. Please compare the below constructions, I also included those in tests. 
Bug fix
> Spanish noun chunks review

- .github/azure-steps.yml
- spacy/tests/test_cli.py
Reenable tests for v3.2.0
Tests.
> Reenable tests for v3.2.0

- website/docs/usage/v3-2.md
- website/meta/sidebars.json
- website/src/templates/index.js
> What's new in v3.2

- website/meta/universe.json
This is a simple python wrapper for analysing sentiment in simple English sentences. 
This is the complete build version and most probably won't do further updates
It is a new python library/package for the community to try out
> Update universe.json with new library eng_spacysentiment

- spacy/cli/package.py
Convert labels to strings for README in package CLI
Bug fix.
> Convert labels to strings for README in package CLI

- spacy/pipeline/_parser_internals/arc_eager.pyx
Use reference parse to initialize parser moves
Bug fix?
> Use reference parse to initialize parser moves

- spacy/scorer.py
If the predicted docs are missing annotation according to `has_annotation`, treat the docs as having no predictions rather than raising errors when the annotation is missing.
The motivation for this is a combined tokenization+sents scorer for a component where the sents annotation is optional. To provide a single scorer in the component factory, it needs to be possible for the scorer to continue despite missing sents annotation in the case where the component is not annotating sents.
Enhancement.
> Allow Scorer.score_spans to handle pred docs with missing annotation

- spacy/errors.py
- spacy/pipeline/functions.py
- spacy/tests/pipeline/test_functions.py
- website/docs/api/pipeline-functions.md
Add `doc_cleaner` component
Enhancement.
> Add doc_cleaner component

- spacy/lang/it/__init__.py
- spacy/lang/it/syntax_iterators.py
- spacy/tests/conftest.py
- spacy/tests/lang/it/test_noun_chunks.py
Noun chunks for Italian. I checked adjectival clauses, nominal modifiers, compounds that are made by `fixed`, `flat` and `compound`. NPs extended to right for adjectives and compounds.
New feature
> Noun chunks for Italian

- website/meta/universe.json
Added the following entry into `universe.json`:
```
{
"type": "education",
"id": "applt-course",
"title": "Applied Language Technology",
"slogan": "NLP for newcomers using spaCy and Stanza",
"description": "These learning materials provide an introduction to applied language technology for audiences who are unfamiliar with language technology and programming. The learning materials assume no previous knowledge of the Python programming language.",
"url": "https://applied-language-technology.readthedocs.io/",
"image": "https://www.mv.helsinki.fi/home/thiippal/images/applt-preview.jpg",
"thumb": "https://applied-language-technology.readthedocs.io/en/latest/_static/logo.png",
"author": "Tuomo Hiippala",
"author_links": {
"twitter": "tuomo_h",
"github": "thiippal",
"website": …
```
> Add entry for Applied Language Technology under "Courses"

- website/docs/usage/v3-2.md
Update Catalan acknowledgements for v3.2
Docs.
> Update Catalan acknowledgements for v3.2

- azure-pipelines.yml
Switch to latest CI images
Chore.
> Switch to latest CI images

- spacy/lang/fr/syntax_iterators.py
- spacy/tests/conftest.py
- spacy/tests/lang/fr/test_noun_chunks.py
Enhancement, review on french syntax iters
> French NP review

- spacy/pipeline/tagger.pyx
Make the Tagger `neg_prefix` configurable.
Bug fix.
> Make the Tagger neg_prefix configurable

- spacy/language.py
Now that `Language.pipe` accepts `Doc` input, refactor `Language.evaluate` to call `Language.pipe` directly, improving the memory usage when processing examples for evaluation.
Enhancement.
> Use Language.pipe in evaluate

- spacy/about.py
> Set version to v3.2.1

- website/src/components/embed.js
- website/src/styles/embed.module.sass
- website/src/templates/index.js
Support embeds from Google Sheets in docs, mostly used for extensive benchmarks etc.
Usage:
```html
<GoogleSheet height="800" id="2PACX-1vTnOci_B78CDpqU9npkikDkcNqhyhwPWL1_TYF4Ip_YYHngVMQAnznl4oVBM4omP9piQNWU-OZdURHP" link="1j3aEVfWSr728kPddRblhXbIDXgvpdYYF1HJXWpU6mtI"></GoogleSheet>
```
docs
> Support Google Sheets embeds in docs

- spacy/pipeline/_parser_internals/arc_eager.pyx
- spacy/vectors.pyx
Use dict.copy().items() instead of list(.items())
?
> Use dict.copy().items() instead of list(.items())

- MANIFEST.in
Remove outdated patterns MANIFEST.in
Newer versions of `setuptools` are producing warnings related to these patterns.
Chore.
> Remove outdated patterns MANIFEST.in

- spacy/vectors.pyx
Make floret murmurhash endian-neutral
?
> Make floret murmurhash endian-neutral

- spacy/lang/it/stop_words.py
- spacy/tests/lang/it/test_stopwords.py
Addition to Italian stop words, where some stopwords go through elision process
Minor enhancement
> added ellided forms

- website/meta/universe.json
Package seems to have been deleted, repo 404s.
docs update
> Remove denomme from universe

- website/meta/universe.json
I added my project spacypdfreader to the universe.json file.
Change to the docs.
> Added spacypdfreader to universe.json

- website/meta/site.json
- website/src/components/search.js
- website/src/pages/404.js
- website/src/templates/index.js
Algolia DocSearch, which we use for the documentation, updated its API and integration for DocSearch websites, so we need to update our keys accordingly.
docs
> Update website to use new Algolia search API

- LICENSE
- spacy/cli/project/assets.py
- spacy/default_config.cfg
- website/meta/site.json
- website/src/components/search.js
- website/src/pages/404.js
- website/src/templates/index.js
[Don't squash]
Making sure `develop` has the latest changes from `master`
chore
> Update develop with master

- setup.cfg
By @polm, redone from #9917 after incorrect (reverted) rebase.
`sudachipy>=0.5.2` is needed for newer dictionaries. `sudachipy<0.6.0`
is kept for users who might still prefer the older version, in
particular to be able to compile it without rust.
?
> Update sudachipy extras

- spacy/tests/pipeline/test_spancat.py
In #9669 it came up that this particular test is flaky. The test is not particularly new, so it's not clear when it became flaky. To keep other development moving, for the moment the test will be skipped, but we should figure out what's going on and fix it soon.
test skip
> Mark flaky spancat test so it doesn't fail the build

- spacy/language.py
- spacy/ml/models/multi_task.py
- spacy/ml/staticvectors.py
- spacy/tests/vocab_vectors/test_vectors.py
- spacy/tokens/doc.pyx
- spacy/tokens/span.pyx
- spacy/training/initialize.py
- spacy/vectors.pyx
- spacy/vocab.pyx
- website/docs/api/vectors.md
Throughout spaCy, we rely on internals of the `Vector` class. This is a first PR to replace a bunch of such uses by methods/properties. In particular:
* `Vectors.data.shape` -> `Vectors.shape`
* `Vectors.data.size` -> `Vectors.size`
*  `self.vocab.vectors.data = ops.asarray(self.vocab.vectors.data)` -> `self.to_ops(ops)`
This was the lower-hanging fruit 🥝, I'll make a separate PR for more difficult cases.
Cleanup.
> User fewer Vector internals

- website/docs/api/entityruler.md
> Add link to pattern file info in EntityRuler.initialize docs

- website/src/widgets/quickstart-install.js
* For conda:
* Use conda environment rather than venv
* Install `spacy-transformers` as a conda package
* For pip:
* Add quotes if extras are included
Docs
> Update quickstart install steps

- spacy/cli/debug_data.py
- spacy/tests/test_cli.py
For all components, return labels for all components with the
corresponding factory name rather than for only the default name.
For `spancat`, return labels as a dict keyed by `spans_key`.
Bug fix.
> Determine labels by factory name in debug data

- spacy/ml/tb_framework.py
Two changes to speed up masking by ~10%:
- Use a bool array rather than an array of float32.
- Let the mask indicate whether a label was seen, rather than
unseen. The mask is most frequently used to index scores for
seen labels. However, since the mask marked unseen labels,
this required computing an intermittent flipped mask.
> Improve unseen label masking

- spacy/pipeline/spancat.py
Instead of the running the actual suggester, which may require annotation from annotating components that is not necessarily present in the reference docs, use the built-in 1-gram suggester.
Bug fix.
> Use simple suggester for spancat initialization

- spacy/tests/tokenizer/test_tokenizer.py
- spacy/tokenizer.pyx
- website/docs/usage/linguistic-features.md
Update `Tokenizer.explain` to align with the `Tokenizer` algorithm:
* skip infix matches that are prefixes in the current substring
Bug fix.
> Fix infix as prefix in Tokenizer.explain

- spacy/tests/training/test_new_example.py
- spacy/training/example.pyx
Remove exception for whitespace tokens in `Example.get_aligned` so that annotation on whitespace tokens is aligned in the same way as for non-whitespace tokens.
Bug fix
> Allow Example to align whitespace annotation

- spacy/pipeline/transition_parser.pyx
This avoids elementwise indexing and the allocation of an additional array.
Gives a ~15% speed improvement when using batch_by_sequence with size
32.
> Write moves costs directly into numpy array

- spacy/cli/templates/quickstart_training.jinja
So that overriding `paths.vectors` works consistently in generated configs, set vectors model in `paths.vectors` and always refer to this path in `initialize.vectors`.
?
> Use paths.vectors for vectors in init config

- spacy/lang/uk/tokenizer_exceptions.py
> Update Ukrainian tokenizer_exceptions

- spacy/cli/debug_data.py
- spacy/tests/test_cli.py
* Use aligned sent starts to have the same indices for the NER and sent start annotation
Bug fix.
> Fix debug data check for ents that cross sents

- website/meta/universe.json
Added Augmenty, a package of spaCy augmenters to the spaCy universe.
Update to the spacy universe (change to the documentation)
> Added Augmenty to universe

- spacy/errors.py
Fix small typo in `errors.py`
"Bug" fix
> Fix small typo in errors.py

- spacy/about.py
> Set version to v3.2.2

- azure-pipelines.yml
Exclude github workflow edits from CI
Chore
> Exclude github workflow edits from CI

- website/meta/universe.json
Add the [tmtoolkit package](https://tmtoolkit.readthedocs.io/) to the spaCy universe.
No tests needed.
Documentation only.
> add tmtoolkit package to spaCy universe

- .github/workflows/slowtests.yml
[It works correctly this time](https://github.com/explosion/spaCy/runs/5199972356?check_suite_focus=true#step:5:10).
> Fix the datemath for reals

- azure-pipelines.yml
Also exclude workflows from non-PR CI runs
Chore.
> Also exclude workflows from non-PR CI runs

- spacy/tests/training/test_augmenters.py
- spacy/training/augment.py
Add whitespace augmenter that inserts a single whitespace token into a doc containing the types of annotation used in core trained pipelines.
Add a combined augmenter that handles lowercasing, orth variants and whitespace augmentation.
Enhancement.
> Add whitespace and combined augmenters

- spacy/pipeline/tok2vec.py
- spacy/tests/pipeline/test_tok2vec.py
Fix `Tok2Vec` for empty batches. Previously this failed with `cupy` or `blis>=0.7.6`.
Bug fix.
> Fix Tok2Vec for empty batches

- spacy/lang/ko/__init__.py
- spacy/lang/ko/punctuation.py
- spacy/tests/conftest.py
- spacy/tests/lang/ko/test_tokenizer.py
Update Korean defaults for `Tokenizer` for tokenization following conventions in UD Korean Kaist.
Enhancement?
> Update Korean defaults for Tokenizer

- spacy/pipeline/tok2vec.py
- spacy/tests/pipeline/test_tok2vec.py
Backport #10324 to v3.2
Bug fix.
> Fix Tok2Vec for empty batches (#10324)

- spacy/language.py
- spacy/pipeline/tagger.pyx
- spacy/pipeline/textcat.py
- spacy/tests/training/test_rehearse.py
> Bugfixes and test for rehearse

- website/meta/universe.json
Updated spaCy universe for spacytextblob.
Docs
> Updated spaCy universe for spacytextblob

- spacy/ml/extract_spans.py
- spacy/pipeline/spancat.py
- spacy/tests/pipeline/test_spancat.py
> Backports for v3.1.5

- spacy/about.py
- spacy/tests/conftest.py
- spacy/tests/training/test_readers.py
Set version to v3.0.8 and backport unit test fixes
Chore.
> Set version to v3.0.8

- spacy/about.py
> Set version to v3.1.5

- spacy/about.py
> Set version to v3.2.3

- spacy/tests/vocab_vectors/test_vectors.py
- spacy/vectors.pyx
- website/docs/api/vectors.md
Fix `Vectors.n_keys` for floret vectors to match docstring description and avoid W007 warnings in similarity methods.
Bug fix.
> Fix Vectors.n_keys for floret vectors

- spacy/lang/hsb/__init__.py
- spacy/lang/hsb/examples.py
- spacy/lang/hsb/lex_attrs.py
- spacy/lang/hsb/stop_words.py
- spacy/lang/hsb/tokenizer_exceptions.py
- spacy/tests/conftest.py
- spacy/tests/lang/hsb/test_text.py
- spacy/tests/lang/hsb/test_tokenizer.py
Add Upper Sorbian language class.
Enhancement
> Add Upper Sorbian support.

- spacy/tests/pipeline/test_entity_linker.py
- spacy/training/example.pyx
`Example.get_matching_ents` was added as part of  #9669, but for some reason master seems to have an old version of the code that just doesn't work. It's already covered by tests that were in #9669 (and fail without this commit) but were succeeding there for some reason. 
Fix
> Fix get_matching_ents

- spacy/lang/dsb/__init__.py
- spacy/lang/dsb/examples.py
- spacy/lang/dsb/lex_attrs.py
- spacy/lang/dsb/stop_words.py
- spacy/tests/conftest.py
- spacy/tests/lang/dsb/test_text.py
- spacy/tests/lang/dsb/test_tokenizer.py
Add Lower Sorbian language class.
Enhancement
> Add Lower Sorbian support.

- website/docs/usage/models.md
- website/meta/languages.json
Add Finnish, Korean, and Swedish models and Korean support notes
Docs
> Add Finnish, Korean, and Swedish models and Korean support notes

- spacy/lang/en/tokenizer_exceptions.py
Remove English tokenizer exception May.
?
> Remove English tokenizer exception May.

- spacy/tests/tokenizer/test_tokenizer.py
- spacy/tokenizer.pyx
- website/docs/usage/linguistic-features.md
Add the missing initial check for special cases to `Tokenizer.explain` to align with `Tokenizer._tokenize_affixes`.
Bug fix.
> Fix initial special cases for Tokenizer.explain

- extra/DEVELOPER_DOCS/Code Conventions.md
Mention that we should use mypy when developing and add a few notes on typing (context: from Ora)
Documentation update
> Add a note to the dev docs on mypy

- requirements.txt
Quick test to see whether CI works with `pytest`<7.1
test
> limit pytest to <7.1

- spacy/vocab.pyx
- website/docs/api/vocab.md
Update docs for `Vocab.get_vector`
Docs.
> Update docs for Vocab.get_vector

- website/meta/universe.json
The [whatlies](https://github.com/koaning/whatlies) project moved from Rasa to my own personal GitHub space. That means some of the URLs changed. 
It's a change to the documentation, the universe json file to be specific.
> Update universe.json - whatlies

- website/docs/usage/embeddings-transformers.md
- website/src/widgets/quickstart-install.js
Various install docs updates
* Use `pip` and editable install in quickstart instructions:
* Avoid compiling twice
* Switch to editable install
* Update pytorch example to more recent versions
In general we should try to move away from `python setup.py` commands, however I am entirely not sure whether we want `--editable` by default in these instructions.
> Various install docs updates

- requirements.txt
Update pytest to forbid `==7.1.0`, allow `>=7.1.1` to avoid `conftext` bug in pytest v7.1.0.
Chore.
> Update pytest to forbid ==7.1.0, allow >=7.1.1

- website/meta/universe.json
Add [EDS-NLP](https://aphp.github.io/edsnlp), a set of rule-based pipeline components to process French-language clinical note, to spaCy Universe.
Add an EDS-NLP resource to [`universe.json`](https://github.com/aphp/spaCy/blob/master/website/meta/universe.json).
Modification of the documentation: add a resource to spaCy universe.
> docs: add EDS-NLP to spaCy universe

- spacy/lang/ko/__init__.py
- spacy/tests/lang/ko/test_tokenizer.py
Handle unknown tags in KoreanTokenizer tag map
Bug fix.
> Handle unknown tags in KoreanTokenizer tag map

- spacy/cli/_util.py
Stream assets on download rather than reading the whole file at once and potentially running into `urllib3` limits on single read sizes.
Bug fix.
> Stream assets on download

- spacy/matcher/matcher.pyx
Indexing into a zero-length `std::vector` is an undefined behavior. This change first checks that the vector is not empty before retrieving the (address of) the first element.
> matcher: remove an undefined behavior

- spacy/tokens/_serialize.py
Maintain support for empty DocBin span groups
(I suspect this only affects `DocBin`s created with spaCy v2.x or pre-release versions of v3, but it's easy enough to avoid breaking the behavior here.)
Bug fix.
> Maintain support for empty DocBin span groups

- spacy/lang/sl/examples.py
Added example sentences for Slovenian language 
Enhancement
> Examples for Slovene

- requirements.txt
- setup.cfg
Add click pin to avoid typer issues.
?
> Add click pin to avoid typer issues

- requirements.txt
- setup.cfg
- spacy/about.py
Backport click pin, set version to v3.2.4
?
> Backport click pin, set version to v3.2.4

- requirements.txt
- setup.cfg
- spacy/about.py
Typer workaround, set version to v3.1.6
> Typer workaround, set version to v3.1.6

- spacy/lang/tr/lex_attrs.py
- spacy/tests/lang/tr/test_text.py
Fixed a typo in lex_attrs.py file in Turkish lang.
In lex_attrs.py file _ordinal_words has a typo. "mliyonuncu" should be "milyonuncu". Fixed that issue.
It is a bug/typo fix.
> Fixed typo in Turkish lang.

- requirements.txt
- setup.cfg
This reverts commit 9966e08f32cf59963591b589bf816aa114ed39a9.
?
> Revert "Add click pin to avoid typer issues (#10573)"

- spacy/cli/templates/quickstart_training.jinja
- website/src/widgets/quickstart-training.js
Add spancat, trainable_lemmatizer to quickstart
?
> Add spancat, trainable_lemmatizer to quickstart

- .github/azure-steps.yml
- spacy/pipeline/transition_parser.pyx
Serialization of a model fails with:
```
TypeError: array(738.3855, dtype=float32) is not JSON serializable
```
Fix this using float conversion.
Bug fix
> Fix loss serialization issue

- .github/azure-steps.yml
- spacy/about.py
- spacy/tests/test_cli.py
Set version to v3.3.0.dev0
Chore.
> Set version to v3.3.0.dev0

- CONTRIBUTING.md
Fixes a broken link to the flake8 linter config file.
Change to the developer documentation.
> Update link to flake8 config

- website/meta/universe.json
Universe update of [`spacy_conll`](https://github.com/BramVanroy/spacy_conll).
> Update to spacy_conll in universe

- spacy/ml/models/coref.py
- spacy/ml/models/coref_util.py
- spacy/pipeline/coref.py
This PR is midway debugging the `SpanPredictor` and preparing it for training from gold-spans only.
Debugging experimental code.
> Preparing span predictor for predicting from gold

- website/meta/universe.json
Deleting the following spaCy universe objects:
- [wmd-relax](https://spacy.io/universe/project/wmd-relax)
- [spaCy.jl](https://spacy.io/universe/project/spaCy.jl)
- [saber](https://spacy.io/universe/project/saber)
- [languagecrunch](https://spacy.io/universe/project/languagecrunch)
- [gracyql](https://spacy.io/universe/project/gracyql)
- [ExcelCy](https://spacy.io/universe/project/excelcy)
- [EpiTator](https://spacy.io/universe/project/epitator) 
Deleting entries fom the `universe.json` file
> Batch #1 | spaCy universe cleanup

- website/meta/site.json
It's not possible to have two different forms for one newsletter audience, so I create a new one covering spaCy and Explosion audiences together
New id for our newsletter signup
> Update newsletter id

- spacy/lang/vi/lex_attrs.py
- Modified the _num_words array which contains numbers and counting units in Vietnamese
- Added alternative forms for several numbers
- Added comments for each elements in English for a better understanding of usages
- Added "ten thousand" and "million" units
- Enhancements
> Add numbers and definitions for Vietnamese

- spacy/matcher/matcher.pyx
This check incurred a significant performance penalty due to implict interactions between the GIL and Cython ref-counting code.
Bug fix
> `Matcher`: Remove superfluous GIL-acquiring check in `get_is_final`

- spacy/lang/es/examples.py
- spacy/lang/es/stop_words.py
Remove significant or not very frequent words from stop word list for Spanish.
https://github.com/explosion/spaCy/issues/3052#issuecomment-1100760100
Some issues in Spanish examples.
Bug fix.
> Fix some issues in Spanish stop-word list and examples

- extra/DEVELOPER_DOCS/ExplosionBot.md
Small addition to explosion-bot docs
docs
> Syntax for a branch from a PR

- spacy/tests/doc/test_doc_api.py
- spacy/tokens/doc.pyx
- website/docs/api/doc.md
Support `exclude` in `Doc.from_docs` for `spans`, `tensor`, and `user_data`.
Enhancement.
> Support exclude in Doc.from_docs

- .pre-commit-config.yaml
- Bumped `black` in the `pre-commit` config to 22.3.0 due to a fix for [this incompatibility](https://github.com/psf/black/issues/2964).
Bug fix
> Bumped black to 22.3.0

- .github/azure-steps.yml
- spacy/about.py
- spacy/tests/test_cli.py
Set version to v3.3.0 and revert temporary dev changes.
Chore.
> Set version to v3.3.0

- website/meta/universe.json
I noticed that episode 6 was missing, so I added it.
Merely adding a missing video to `universe.json`.
> Update universe.json to Include spaCy video #6

- spacy/errors.py
- spacy/ml/parser_model.pyx
- spacy/pipeline/_edit_tree_internals/edit_trees.pyx
- spacy/pipeline/_parser_internals/arc_eager.pyx
- spacy/tokens/graph.pyx
- spacy/tokens/span.pyx
Replace all remaining hardcoded error message with references to `spacy.errors.Errors`.
Replaces hardcoded error message with references to `spacy.errors.Errors`.
Refactoring
> Refactor error messages to remove hardcoded strings

- setup.py
- spacy/ml/tb_framework.py
- spacy/pipeline/_parser_internals/_beam_utils.pyx
- spacy/pipeline/_parser_internals/batch.pxd
- spacy/pipeline/_parser_internals/batch.pyx
- spacy/pipeline/transition_parser.pyx
- spacy/tests/parser/test_ner.py
- spacy/tests/parser/test_parse.py
Beam parsing was already implemented as part of the `BeamBatch` class.
This change makes its counterpart `GreedyBatch`. Both classes are hooked
up in `TransitionModel`, selecting `GreedyBatch` when the beam size is
one, or `BeamBatch` otherwise.
Enhancement.
> Add back support for beam parsing to the refactored parser

- website/docs/usage/rule-based-matching.md
> Small doc typos

- website/docs/usage/models.md
Document/emphasize different ways to create pipelines in docs.
Moved up and slightly modified a snippet describing the usage of `spacy.blank()` and calling the `Language` object directly.
Changes to existing documentation.
> Document different ways to create a pipeline

- spacy/tests/doc/test_doc_api.py
- spacy/tokens/_dict_proxies.py
- website/docs/api/spangroup.md
Override `SpanGroups.setdefault` to provide `default` values from `SpanGroup`/`Iterable` as `SpanGroup`
Minor:
* fix a mistake in the `SpanGroup` docs
?
> Override SpanGroups.setdefault to provide default SpanGroup

- website/meta/universe.json
Updating the code example of `spacytextblob` from the spaCy Universe.
The additions are from the [stackoverflow ](https://stackoverflow.com/questions/70720126/oserror-e053-could-not-read-config-cfg-spacy-on-colab) thread, which suggested a workaround to solve an `OSError` with the `config.cfg` file. 
The change includes additional installations to prevent the `OSError` from occurring.
updating `universe.json`
> Update spaCy Universe: spacytextblob (code example)

- spacy/glossary.py
There was already one but it was lower case, maybe that should be
removed?
This fixes #10817. 
glossary addition
> Add glossary entry for root

- website/docs/usage/index.md
- website/src/widgets/quickstart-install.js
* Remove cuda extras for non-linux arm platforms in install widget
* Extend cuda versions install widget
* Update GPU install docs to clarify cuda
Docs.
> Remove cuda extras for non-linux arm in install widget

- .github/workflows/gputests.yml
- .github/workflows/slowtests.yml
Prevent forks of the main repo from inheriting our regularly-scheduled Buildkite CI workflows.
Fix
> Disable weekly GPU/slow tests on forks

- website/docs/api/stringstore.md
Fixes a syntax error in an example in the StringStore docs caused by a misspelt keyword
* Documentation example code fix
> Fix misspelt keyword in StringStore docs example

- website/docs/api/pipeline-functions.md
Adds `doc_cleaner` to the left menu in the Pipeline Functions docs.
> add doc cleaner to menu

- spacy/cli/_util.py
This change removes `thinc.util.has_cupy` from the GPU presence check. Currently `gpu_is_available` already implies `has_cupy`.  We also want to show this warning in the future when a machine has a non-CuPy GPU.
Enhancement.
> Simplify GPU check

- spacy/ml/models/entity_linker.py
- spacy/pipeline/entity_linker.py
NEL code had a TODO related to typing, this fixes it. 
There was also a line that was giving a mypy error that I have marked to be ignored, I'm not sure if there's a better way to handle it.
type fix
> Minor NEL type fixes 

- .github/workflows/explosionbot.yml
Enables support for the [`test_slow_gpu` explosion-bot command](https://github.com/explosion/explosion-bot/pull/4).
Tests, CI
> Add `test_slow_gpu` explosion-bot command

- spacy/tokens/doc.pyx
Fix schemas import in `Doc`
Bug fix.
> Fix schemas import in Doc

- requirements.txt
- setup.cfg
Extend typing_extensions to <4.2.0
See: https://github.com/explosion/thinc/issues/665
Chore.
> Extend typing_extensions to <4.2.0

- spacy/about.py
> Set version to v3.3.1

- website/meta/universe.json
Added https://github.com/koaning/spacy-report to the spaCy universe. 
Just an update to the json file.
> Add spacy-report to universe

- website/docs/api/token.md
Fix documentation of `Token.ancestors` attribute, previously duplicating that of `Token.right_edge` attribute.
> `token.md`: Fix documentation of `Token.ancestors`

- README.md
Bump latest version in the README.
Doc fix
> Update README: spaCy 3.3.1 is out now

- spacy/ml/tb_framework.pyx
- spacy/tests/serialize/test_serialize_config.py
The naming of some identifiers came up in the reviews of #10878. This PR tries to address these issues:
* `lower`/`upper` are renamed to `hidden`/`output`.
* `_parseC` is renamed to `_parse_batch`.
* Some functions in `tb_framework` are prefixed by an underscore to make it more explicit that they are private.
Improve source code readability.
> Rename some identifiers in the parser refactor

- spacy/kb.pyx
Make KB initialization methods for entities/vectors/aliases private.
Refactoring `initialize_entities()`, `initialize_vectors()`, `initialize_aliases()` by adding a `_` prefix.l
Refactoring.
> Make KB entities/vector/aliases initialization methods private 

- website/docs/usage/linguistic-features.md
Update the link for downloading fasttext word vectors
Updated the link to download the Latin fasttext vectors in the "Adding word vectors" example section of the website because it was outdated. 
Fix/Update
> Update the link for downloading Latin fasttext word vectors

- .github/azure-steps.yml
- setup.cfg
This change ensures that installing spaCy with `apple` uses thinc-apple-ops version 0.1.0.dev0 or later, which has the proper CBLAS passthrough. Also test with at least this version.
Enhancement
the project's MIT license.
do, I've added all required information.
> Use thinc-apple-ops>=0.1.0.dev0 with `apple` extras

- website/docs/usage/saving-loading.md
While testing the code example from [implement serialization methods](https://spacy.io/usage/saving-loading#serialization-methods), I encountered several errors:
- Missing named arguments for nlp and name
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_2635/33377126.py in <module>
9 
10 @Language.factory("my_component")
---> 11 class CustomComponent:
12     def __init__(self):
13         self.data = []
~/.local/lib/python3.8/site-packages/spacy/language.py in add_factory(factory_func)
488             arg_names = util.get_arg_names(factory_func)
489             if "nlp" not in arg_names or "name" not in arg_names:
--> 490                 raise …
```
> Update serialization methods code block

- website/src/widgets/quickstart-install.js
remove `cuda116` extra from install widget
> remove `cuda116` extra from install widget

- website/docs/api/attributes.md
- website/meta/sidebars.json
Add API docs for token attribute symbols.
Docs.
> Add API docs for token attribute symbols

- extra/DEVELOPER_DOCS/Code Conventions.md
Adds a note about needing to rebuild Cython extensions if you're trying to test code.
Documentation (development)
> Add note about Cython for testing in code conventions developer docs

- spacy/training/alignment_array.pyx
- spacy/training/example.pyx
- spacy/util.py
Ports the changes introduced in #10789 and #10798 so that pre-4.0 releases can benefit from the optimizations.
Performance enhancement
> Backport parser/alignment optimizations from `feature/refactor-parser`

- .github/azure-steps.yml
- spacy/about.py
- spacy/tests/test_cli.py
> Set version to v3.4.0

- spacy/cli/_util.py
- spacy/cli/project/clone.py
> Try cloning repo from main & master

- spacy/tests/vocab_vectors/test_similarity.py
- spacy/tests/vocab_vectors/test_vectors.py
- spacy/tokens/doc.pyx
- spacy/tokens/span.pyx
- spacy/tokens/token.pyx
Distinguish between vectors that are 0 vs. missing vectors when warning about missing vectors.
Update `Doc.has_vector` to match `Span.has_vector` and `Token.has_vector` for cases where the vocab has vectors but none of the tokens in the container have vectors.
Bug fix? (I was mainly trying to remove warnings from the test suite, but then noticed this inconsistency in the definitions of `has_vector` that made it difficult to fix the warning for all cases.)
> Update vector handling in similarity methods

- spacy/matcher/matcher.pyx
- spacy/schemas.py
- spacy/tests/matcher/test_matcher_api.py
- spacy/tests/matcher/test_matcher_logic.py
- spacy/tests/matcher/test_pattern_validation.py
- website/docs/api/matcher.md
- website/docs/usage/rule-based-matching.md
Reupload of #10919 
Resolved #5603 
Added min max quantifier {n,m}
Summary
1. Modified API and Usage for spaCy website to include min_max operator
2. Modified matcher.pyx to include min_max function {n,m} and its variants
3. Modified schemas.py to include min_max validation error
4. Added test cases to test_matcher_api.py, test_matcher_logic.py and test_pattern_validation.py
Min_max operator {n,m} for matcher
> Addition of min_max quantifier in matcher {n,m}

- setup.cfg
- website/src/widgets/quickstart-install.js
> Update cupy extras

- spacy/tests/training/test_readers.py
This reverts commit f8116078ce2c5760ae218bc1657977ed116fcf18.
Chore.
> Revert "disable failing test because Stanford servers are down (#11015)"

- setup.py
Support `SPACY_NUM_BUILD_JOBS` (similar to `NPY_NUM_BUILD_JOBS`) to pass `--parallel` to `build_ext` when using `pip` rather than `python setup.py`.
?
> Support env var for num build jobs

- .github/spacy_universe_alert.py
- .github/workflows/spacy_universe_alert.yml
- website/meta/universe.json
This is internal requirement of Community Team @ Explosion.
We want to have an alert system to get list of new spaCy universe projects when a PR is raised against spaCy repo involving changes to `website/meta/universe.json` file only.
> Github Action for spaCy universe project alert

- website/docs/usage/index.md
Add docs for compiling with build constraints.
Docs.
> Add docs for compiling with build constraints

- extra/DEVELOPER_DOCS/ExplosionBot.md
Add examples for new explosion bot commands
Documentation
> Add examples for new explosion bot commands

- website/meta/universe.json
The URL for the Holmes demo has changed; this PR changes the Universe website to reference the new URL.
Reference change
> Change Holmes demo URL in Universe entry

- setup.py
- website/docs/usage/index.md
Tweak build jobs setting, update install docs.
Install, docs.
> Tweak build jobs setting, update install docs

- spacy/ml/models/coref.py
- spacy/ml/models/span_predictor.py
- spacy/pipeline/coref.py
- spacy/pipeline/entity_linker.py
- spacy/pipeline/span_predictor.py
- website/docs/api/architectures.md
This updates a few areas in the coref docs that had not been filled in or had gotten out of sync. There is also some cleanup of old TODOs and error messages. This should not affect any tests.
Cleanup.
> Update Coref Docs

- .github/azure-steps.yml
CI: Install with two parallel build jobs
Chore.
> CI: Install with two parallel build jobs

- build-constraints.txt
- requirements.txt
Update build setup for aarch64.
Chore.
> Update build setup for aarch64

- README.md
- website/docs/usage/v3-4.md
- website/meta/languages.json
- website/meta/sidebars.json
- website/src/templates/index.js
> Docs for v3.4

- website/meta/site.json
Update binder version in docs
Docs.
> Update binder version in docs

- website/meta/universe.json
A proposal to update `universe.json` file to add [BERTopic](https://github.com/MaartenGr/BERTopic) to the spaCy Universe.
> Added BERTopic to Spacy Universe

- website/meta/universe.json
little metadata update in `universe.json` with new spacyfishing logo location for spaCy universe.  
> Update meta for spacyfishing in spaCy Universe

- website/meta/universe.json
Created a project that uses Spacy to return the results of English interpretation.
link : https://github.com/lll-lll-lll-lll/sent-pattern
Pre-processing for accurate translation of English into Japanese. 
It's PR is universe project
> [universe project] create English interpretation project 

- website/meta/universe.json
Fix #11184 by moving the entry to the correct section of `universe.json`.
Docs fix.
> Move sent-patterns to correct section of universe.json

- website/src/templates/universe.js
The Universe has a link at the bottom to the `project idea` label, which we no longer use. This updates it to point to the related section in Discussions.
docs fix
> Update link to project ideas

- .github/azure-steps.yml
- spacy/tests/test_cli.py
This reverts commit d9320db7db74b970b3751e38ed6f14de5b7d16d5.
Chore.
> Revert "Temporarily skip tests that require models/compat"

- CONTRIBUTING.md
Add link to developer docs code conventions
Docs.
> Add link to developer docs code conventions

- spacy/about.py
> Set version to v3.4.1

- spacy/cli/pretrain.py
This `PR` adds the `parents=True` argument to the `mkdir` command when initializing the directories. It's the same argument configuration as in the [train command](https://github.com/explosion/spaCy/blob/master/spacy/cli/train.py#L64).
Enhancement
> Adjust mkdir for pretrain command

- extra/DEVELOPER_DOCS/ExplosionBot.md
Add note about case-sensitivity to the explosion-bot developer docs.
Documentation
> `ExplosionBot`: Add note about case-sensitivity

- setup.cfg
As outlined in #11218, version 0.9.0 of natto-py, which we had pinned, has issues with recent versions of setuptools. This increases the version pin `>=1.0.0,<2.0.0`. 1.0.0 is the current release and the package is feature complete so updates aren't common. 
We could make the version range tighter, but I think in this case it's better for it to be open. I would also be fine with removing the high limit like we do for pythainlp. 
Dependencies change
> Update natto-py version spec

- website/docs/api/textcategorizer.md
Add scorer to textcat API docs config settings
Docs.
> Add scorer to textcat API docs config settings

- spacy/lang/ko/punctuation.py
- spacy/schemas.py
Fix regex invalid escape sequences
Kind of a bug?
> Fix regex invalid escape sequences

- azure-pipelines.yml
Add W605 to the errors raised by flake8 in the CI
Chore.
> Add W605 to the errors raised by flake8 in the CI

- spacy/pipeline/textcat.py
Cherry-picked from `master`.
Bug fix.
> Fix for the `textcat` test failure in `feature/refactor-parser`

- spacy/attrs.pyx
- spacy/tests/lang/test_attrs.py
- spacy/tokenizer.pyx
- spacy/vocab.pyx
Remove `intify_attrs(_do_deprecated)`.
?
> Remove intify_attrs(_do_deprecated)

- setup.py
- spacy/pipeline/_parser_internals/_beam_utils.pxd
- spacy/pipeline/_parser_internals/_beam_utils.pyx
- spacy/pipeline/_parser_internals/arc_eager.pyx
- spacy/pipeline/_parser_internals/ner.pyx
- spacy/pipeline/_parser_internals/search.pxd
- spacy/pipeline/_parser_internals/search.pyx
- spacy/pipeline/transition_parser.pyx
- spacy/tests/conftest.py
- spacy/tests/parser/_search.pyx
- spacy/tests/parser/test_search.py
Moves the `thinc.extra.search` module and its related tests from thinc and fixes a null-pointer exception in `Beam.__dealloc__`. 
Additionally, this PR also adds support for executing unit tests written in Cython using the `pytest` framework (required for the moved test suite, which was actually never executed until now).
Refactoring, bug fix, new tests
> Move `thinc.extra.search` to `spacy.pipeline._parser_internals`

- website/meta/languages.json
Add uk pipelines to website
Docs
> Add uk pipelines to website

- spacy/errors.py
- spacy/language.py
- spacy/tests/test_language.py
Check for `.` in factory names
Bug fix.
> Check for . in factory names

- spacy/lang/ru/__init__.py
- spacy/lang/ru/lemmatizer.py
- spacy/lang/uk/__init__.py
- spacy/lang/uk/lemmatizer.py
- spacy/tests/conftest.py
- website/docs/api/lemmatizer.md
- website/meta/languages.json
Switch ru and uk lemmatizers to pymorphy3
?
> Switch ru and uk lemmatizers to pymorphy3

- website/src/templates/models.js
Improve floret vectors display in pipeline docs
Docs.
> Improve floret vectors display in pipeline docs

- extra/DEVELOPER_DOCS/Code Conventions.md
After internal discussion, add a section on numeric comparisons.
dev docs update
> dev docs: numeric comparators

- spacy/lang/ru/__init__.py
- spacy/lang/ru/lemmatizer.py
- spacy/lang/sl/__init__.py
- spacy/lang/sl/lex_attrs.py
- spacy/lang/sl/punctuation.py
- spacy/lang/sl/stop_words.py
- spacy/lang/sl/tokenizer_exceptions.py
- spacy/lang/uk/__init__.py
- spacy/lang/uk/lemmatizer.py
- spacy/tests/conftest.py
- spacy/tests/lang/sl/test_text.py
- website/docs/api/lemmatizer.md
- website/meta/languages.json
> Update v4 from develop

- setup.cfg
Some dependencies in setup.cfg are listed as "our libraries", but are not in the Explosion organization, so this moves them to "third-party deps". 
chore?
> Mark third-party deps in setup.cfg

- pyproject.toml
Remove `pathy` from `pyproject.toml`. (It was never needed. I think it was a carry-over from very early versions of `pyproject.toml` in the repo.)
Chore.
> Remove pathy from pyproject.toml

- setup.py
- spacy/ml/tb_framework.pyx
- spacy/pipeline/_parser_internals/_parser_utils.pxd
- spacy/pipeline/_parser_internals/_parser_utils.pyx
- spacy/pipeline/_parser_internals/transition_system.pyx
Move a couple of `argmax` functions used in the parser to a new `_parser_utils` Cython module.
Refactor
> New `_parser_utils` Cython module

- website/meta/universe.json
> Merge `master` into `develop`

- website/docs/usage/projects.md
This command doesn't have the project dir, but it's required, so it will throw an error. This just adds `[project_dir]` to the example.
> Fix DVC command example

- website/docs/api/top-level.md
Add missing docs for the `spacy.models_and_pipes_with_nvtx_range.v1` callback.
Docs
> Add docs for the `spacy.models_and_pipes_with_nvtx_range.v1` callback

- spacy/cli/templates/quickstart_training.jinja
- spacy/cli/templates/quickstart_training_recommendations.yml
Due to problems with the javascript conversion in the website quickstart, remove the `has_letters` setting to simplify generating `attrs` for the default `tok2vec`.
Additionally reduce `PREFIX` as in the trained pipelines.
Primarily docs.
> Remove has_letters in config template

- .gitignore
- licenses/3rd_party_licenses.txt
- setup.py
- spacy/matcher/__init__.py
- spacy/matcher/levenshtein.pyx
- spacy/matcher/polyleven.c
- spacy/tests/matcher/test_levenshtein.py
Add a simple levenshtein distance function using the implementation from the `polyleven` library as `spacy.matcher.levenshtein`.
Enhancement.
> Add levenshtein from polyleven

- website/docs/usage/v3-4.md
Release notes mistakenly refer to `en_core_news` pipelines; came up in #11541.
docs fix
> Fix English pipeline names in 3.4 release notes

- website/meta/universe.json
I added [spacy-partial-tagger](https://github.com/doccano/spacy-partial-tagger) to spaCy Universe. `spacy-partial-tagger` is a library to build a CRF tagger with a partially annotated dataset in spaCy.
This is a PR for adding a project to spaCy Universe.
> Add spacy-partial-tagger to spaCy Universe

- .github/ISSUE_TEMPLATE/01_bugs.md
It's rare to have anyone using v1 anymore, so the message in the issue template is no longer helpful.
> Remove mention of 1.7 from issue template

- website/docs/api/kb_in_memory.md
After the refactor of the `KnowledgeBase`, we forgot to update one occurrence in the docs.
docs "bug" fix
> Fix docs for refactored KB

- .pre-commit-config.yaml
- requirements.txt
Sync flake8 versions across requirements in pre-commit hooks and `requirements.txt`.
Chore.
> Sync flake8 version across requirements

- spacy/pipeline/edit_tree_lemmatizer.py
Follow up from https://github.com/explosion/spaCy/pull/11612
fix
> remove dtype

- spacy/lang/ru/lemmatizer.py
- spacy/lang/uk/lemmatizer.py
- spacy/tests/conftest.py
- spacy/tests/lang/ru/test_lemmatizer.py
- spacy/tests/lang/uk/test_lemmatizer.py
Fix initialization for `pymorphy2_lookup` lemmatizer mode.
Follow-up PR to #11627.
Bug fix.
> Fix init for pymorphy2_lookup lemmatizer mode

- requirements.txt
- setup.cfg
- spacy/schemas.py
* Update types to allow field defaults in schemas for updated pydantic+mypy
Mostly a chore.
> Extend to pydantic v1.10

- .github/azure-steps.yml
- azure-pipelines.yml
Add python 3.11.0rc2 to CI.
Chore.
> Add python 3.11.0rc2 to CI

- setup.py
* Plus minor linting / updating
Chore.
> Fix python 2.7 compat in setup.py

- spacy/about.py
> Set version to v3.4.2

- website/docs/usage/projects.md
This provides a detailed example of `env` usage in a project file and explains the motivations for it. It addresses #11135 and uses @adrianeboyd's example.
A tip block seems like the right place for this, but because of how the CSS for those works it ends up stacked, maybe there's a better way to format it? 
docs update
> Add detailed example of env dict usage

- spacy/tests/test_models.py
Rename test helper method with non-`test_` name since having a `test_` method that returns anything other than `None` will not be supported in pytest 8.
?
> Rename test helper method with non-test_ name

- README.md
- website/meta/languages.json
Update languages and version in README and website
Docs.
> Update languages and version in README and website

- azure-pipelines.yml
Reduce python 3.10 in CI to one OS.
?
> Reduce python 3.10 in CI to one OS

- spacy/pipeline/textcat.py
- spacy/pipeline/textcat_multilabel.py
* Use `NORM` instead of `ORTH`
* Remove `ID`
* Reduce rows for `PREFIX` and `SHAPE`
Enhancement.
> Adjust default attrs for textcat configs

- website/docs/usage/rule-based-matching.md
Changed `retokenize` to `retokenizer`
Fixing typo in docs
> Spelling mistake in rule-based-matching.md

- azure-pipelines.yml
Switch CI to Python 3.11.0
Chore.
> Switch CI to Python 3.11.0

- .github/azure-steps.yml
- azure-pipelines.yml
* Use `build` instead of `python setup.py sdist`
* Remove in-place build with `setup.py`
* Remove `gpu` parameter and GPU tests
* Keep `architecture` and `num_build_jobs` in azure steps with CI defaults
* Fix use of `num_build_jobs` parameter
* Remove now-unused `prefix` parameter
* Test imports and CLI before installing test requirements
* Remove `*.egg-info` directory in addition to source directory for a warning-free `import spacy`
* Switch `thinc-apple-ops` test to python 3.11 (as most recent python that is tested across platforms)
Chore.
> Modernize and simplify CI steps

- requirements.txt
- setup.cfg
This raises the maximum version limit for Typer, as requested in #11708, in order to run the tests. Note that even if the tests succeed there may be other things not check or other reasons to not raise the limit. In particular, we need to check if anything was deprecated or changed significantly in 0.5.0 or later. Looking at the [release notes](https://typer.tiangolo.com/release-notes/) this doesn't seem to be an issue.
dependency update
> Raise Typer limit

- spacy/cli/project/remote_storage.py
- spacy/errors.py
Patch related to CVE-2007-4559, extends original PR #11679.
Bug fix.
> Check for unsafe paths in tarfile.extractall (CVE-2007-4559)

- azure-pipelines.yml
Switch CI to python 3.11
Chore.
> Switch CI to python 3.11

- spacy/cli/project/run.py
The requirements check should only warn and never raise an error, so add a fallback for any requirements that can't be handled otherwise. In addition, add a flag to `project_run` so that the requirements check is only run once for the top-level `run` command rather than also for each subcommand in workflows.
Bug fix.
> Add fallback in requirements check, only check once

- .github/workflows/spacy_universe_alert.yml
Use python 3.10 for GHA universe alert
?
> Use python 3.10 for GHA universe alert

- spacy/cli/project/run.py
- spacy/tests/test_cli.py
* Make warning more general for differences between PEP 508 and pip
* Add tests for _check_requirements
?
> Update warning, add tests for project requirements check

- spacy/about.py
> Set version to v3.4.3

- website/meta/universe.json
Add greCy (ancient Greek models to spaCy universe)
Project description with links. 
- [X ] I confirm that I have the right to submit this contribution under the project's MIT license.
> Add greCy to Universe

- spacy/language.py
- spacy/tests/vocab_vectors/test_vectors.py
- spacy/vectors.pyx
This uses the check for vector equality from sourcing components as a defintion on the Vectors class. At the moment it's only used in the one place, but I recently had need of it when working on the [merging script](https://github.com/explosion/projects/pull/147). There are probably other contexts where it could be useful too.
Minor enhancement.
> Add equality definition for vectors

- requirements.txt
> Update to mypy 0.990

- spacy/cli/templates/quickstart_training_recommendations.yml
Model recommendation from @cayorodriguez.
Enhancement.
> Add transformer recommendation for ca

- website/meta/universe.json
This has no updates in over a year, and the pretrained models appear to have gone offline at some point (https://github.com/erre-quadro/spikex/issues/14).
Universe cleanup
> Remove spikex from Universe

- website/meta/universe.json
This is a course from 2017. As noted in #11842, the link to Safari Books Online doesn't work any more, and it doesn't seem to have been updated in over five years, so it's hard to still recommend it.
docs cleanup
> Remove Learning Path from Universe

- spacy/matcher/matcher.pyx
Fix `Matcher` cython `profile=True` header.
?
> Fix Matcher cython profile=True header

- requirements.txt
- setup.cfg
- spacy/cli/_util.py
- spacy/tests/test_cli.py
* Switch from deprecated `ignore_ext` to `compression`
* Add upload/download test for local files
?
> Add smart_open requirement, update deprecated options

- .github/azure-steps.yml
- spacy/about.py
- spacy/tests/test_cli.py
> Prepare for v3.5.0

- spacy/pipeline/textcat.py
- spacy/pipeline/textcat_multilabel.py
`cats_macro_auc_per_type` appears to have been added by mistake and never used. Removing it does not break validation.
Came up in #11824. 
cleanup
> Remove unused logging value from textcat defaults

- requirements.txt
- spacy/cli/debug_data.py
- spacy/language.py
- spacy/tests/pipeline/test_textcat.py
- spacy/util.py
Replace `Pipe` type with `Callable[[Doc], Doc]` in `Language`.
Requires mypy 0.990 with support for `hasattr`.
Types.
> Replace Pipe type with Callable in Language

- website/docs/api/vocab.md
> Fix typo in vocab.md table

- spacy/ml/extract_spans.py
- spacy/pipeline/spancat.py
- spacy/tests/pipeline/test_spancat.py
`spancat.predict` crashes on docs with zero suggestions.
Bug fix.
> Fix spancat for zero suggestions

- spacy/cli/project/run.py
Necessary for mypy with wasabi v1+.
Types.
> Refactor kwargs in CLI msg for future wasabi compatibility

- website/meta/universe.json
Going over Universe entries in #11916, I noticed this entry didn't actually link to the related Github repo, and then I noticed it hadn't been updated since 2018. 
https://github.com/tc64/spacyss
docs cleanup
> Remove spacy-sentence-segmenter from Universe

- README.md
- website/meta/sidebars.json
- website/meta/site.json
- website/src/widgets/landing.js
Making changes to the docs so that we point to the `/custom-solutions` page.
> Update custom solutions links

- spacy/errors.py
- spacy/language.py
- spacy/pipeline/pipe.pyx
- spacy/tests/pipeline/test_pipe_methods.py
- website/docs/api/dependencyparser.md
- website/docs/api/entitylinker.md
- website/docs/api/entityrecognizer.md
- website/docs/api/language.md
- website/docs/api/pipe.md
- website/docs/api/tagger.md
- website/docs/api/textcategorizer.md
When v3 was released, `begin_training` was renamed to `initialize`. There were warnings in the code and docs about that. This PR removes them.
cleanup
> Remove all references to "begin_training"

- azure-pipelines.yml
Update images and versions in CI.
Chore.
> Update images and versions in CI

- .github/azure-steps.yml
- spacy/tests/doc/test_array.py
- spacy/tokens/doc.pyx
- spacy/tokens/span.pyx
- spacy/training/example.pyx
Convert all individual values explicitly to uint64 for array-based doc representations.
Required for future numpy compatibility. Deprecation warnings will start in v1.24.0.
Bug fix.
> Cast to uint64 for all array-based doc representations

- .github/azure-steps.yml
Install `thinc-apple-ops` through extra so the correct compatible version is installed.
Chore.
> CI: Install thinc-apple-ops through extra

- .github/azure-steps.yml
- azure-pipelines.yml
- requirements.txt
- setup.cfg
- spacy/about.py
- spacy/cli/_util.py
- spacy/cli/templates/quickstart_training.jinja
- spacy/displacy/__init__.py
- spacy/errors.py
- spacy/pipeline/edit_tree_lemmatizer.py
- spacy/pipeline/spancat.py
- spacy/tests/doc/test_array.py
- spacy/tests/pipeline/test_edit_tree_lemmatizer.py
- spacy/tests/pipeline/test_spancat.py
- spacy/tests/test_cli.py
- spacy/tests/test_displacy.py
- spacy/tokens/doc.pyx
- spacy/tokens/span.pyx
- spacy/training/example.pyx
Backport bug fixes to v3.4.x.
Bug fix.
> Backport bug fixes to v3.4.x

- .github/azure-steps.yml
- .pre-commit-config.yaml
- azure-pipelines.yml
- requirements.txt
- setup.cfg
- spacy/about.py
- spacy/cli/_util.py
- spacy/displacy/__init__.py
- spacy/errors.py
- spacy/lang/ko/punctuation.py
- spacy/ml/_precomputable_affine.py
- spacy/pipeline/edit_tree_lemmatizer.py
- spacy/pipeline/spancat.py
- spacy/tests/doc/test_array.py
- spacy/tests/doc/test_doc_api.py
- spacy/tests/lang/ru/test_lemmatizer.py
- spacy/tests/lang/uk/test_lemmatizer.py
- spacy/tests/matcher/test_phrase_matcher.py
- spacy/tests/pipeline/test_edit_tree_lemmatizer.py
- spacy/tests/pipeline/test_entity_linker.py
- spacy/tests/pipeline/test_spancat.py
- spacy/tests/test_cli.py
- spacy/tests/test_displacy.py
- spacy/tests/test_models.py
- spacy/tests/vocab_vectors/test_similarity.py
- spacy/tokens/doc.pyx
- spacy/tokens/span.pyx
- spacy/training/example.pyx
- spacy/training/initialize.py
Backport bug fixes to v3.3.x.
Bug fix.
> Backport bug fixes to v3.3.x

- .github/azure-steps.yml
- .pre-commit-config.yaml
- azure-pipelines.yml
- requirements.txt
- setup.cfg
- spacy/about.py
- spacy/cli/_util.py
- spacy/cli/templates/quickstart_training.jinja
- spacy/errors.py
- spacy/pipeline/spancat.py
- spacy/tests/doc/test_array.py
- spacy/tests/doc/test_doc_api.py
- spacy/tests/lang/ru/test_lemmatizer.py
- spacy/tests/lang/uk/test_lemmatizer.py
- spacy/tests/matcher/test_phrase_matcher.py
- spacy/tests/pipeline/test_spancat.py
- spacy/tests/test_cli.py
- spacy/tests/test_models.py
- spacy/tests/vocab_vectors/test_similarity.py
- spacy/tokens/doc.pyx
- spacy/tokens/span.pyx
- spacy/training/example.pyx
- spacy/training/initialize.py
Backport bug fixes to v3.1.x.
Bug fix.
> Backport bug fixes to v3.1.x

- .github/azure-steps.yml
- azure-pipelines.yml
- requirements.txt
- setup.cfg
- spacy/about.py
- spacy/cli/_util.py
- spacy/cli/templates/quickstart_training.jinja
- spacy/errors.py
- spacy/ml/models/entity_linker.py
- spacy/pipeline/entity_linker.py
- spacy/schemas.py
- spacy/tests/doc/test_array.py
- spacy/tests/doc/test_doc_api.py
- spacy/tests/lang/ru/test_lemmatizer.py
- spacy/tests/lang/uk/test_lemmatizer.py
- spacy/tests/matcher/test_phrase_matcher.py
- spacy/tests/regression/test_issue5501-6000.py
- spacy/tests/serialize/test_serialize_kb.py
- spacy/tests/test_cli.py
- spacy/tests/test_models.py
- spacy/tokens/doc.pyx
- spacy/tokens/span.pyx
- spacy/training/example.pyx
- spacy/training/initialize.py
Backport bug fixes to v3.0.x
Bug fix.
> Backport bug fixes to v3.0.x

- spacy/tests/conftest.py
Allow conftest.py to run twice for build envs
Tests bug fix.
> Allow conftest.py to run twice for build envs

- build-constraints.txt
Update build constraints for aarch64 and python 3.10.
Chore.
> Update build constraints for aarch64 and python 3.10

- spacy/about.py
> Set version to v2.3.9

- spacy/lang/nl/stop_words.py
fix typo in "aangaande"
`aangaangde` is not a word but `aangaande` is
> Fix typo in Dutch stop words - stop_words.py

- setup.cfg
Add classifier for python 3.11
?
> Add classifier for python 3.11

- requirements.txt
- setup.cfg
- spacy/pipeline/textcat.py
- spacy/tests/pipeline/test_textcat.py
As a follow-up to #11696, rename the modified scorer to v2 and move the v1 scorer to `spacy-legacy`.
Bug fix.
> Rename modified textcat scorer to v2

- website/meta/universe.json
Add spacy-pythainlp project to universe
spacy-pythainlp: [https://github.com/PyThaiNLP/spaCy-PyThaiNLP](https://github.com/PyThaiNLP/spaCy-PyThaiNLP)
This package wraps the PyThaiNLP library to add support Thai for spaCy.
the universe documentation
> Add spacy-pythainlp

- requirements.txt
- setup.cfg
- spacy/cli/apply.py
- spacy/errors.py
- spacy/pipeline/span_ruler.py
- spacy/pipeline/textcat.py
- spacy/tests/pipeline/test_textcat.py
- spacy/training/loggers.py
- website/docs/api/top-level.md
- website/meta/universe.json
[Don't squash merge]
Syncing `v4` with the latest from `master`
chore
> Sync v4 with latest from master

- spacy/training/loop.py
The new `thinc.Schedule` class is a callable object that accepts a `step` argument. So, we need to pass `step=0` to get the initial learning rate.
Fix
> Update initial learning rate CLI output during training

- spacy/pipeline/edit_tree_lemmatizer.py
- spacy/tests/pipeline/test_edit_tree_lemmatizer.py
The losses/gradients of missing annotations were not correctly masked out. Fix this and check the masking in the partial data test.
Bugfix.
> Handle missing annotations in the edit tree lemmatizer

- website/docs/usage/saving-loading.mdx
This adds a few sentences to the docs to clarify how the `--code` argument works, including an explanation of how to load custom components in your own code.
small docs update
> Clarify how `--code` arg works

- spacy/matcher/levenshtein.pyx
- website/docs/usage/rule-based-matching.mdx
The comments and examples had gotten out-of-sync with modifications to `levenshtein_compare`.
Docs.
> Fix comments and examples for levenshtein_compare

- website/.dockerignore
- website/Dockerfile
- website/README.md
Update Dockerfile to work with Next.js
- Update to Node 18.
- Do not run as root, this also works better with Node privilege-dropping.
- Update README with new run instructions and adding the `--rm` flag to avoid leaving a bunch of unused Docker containers.
- Also change README to recommend building the image locally. Image builds are pretty fast and the uploaded images get outdated pretty quickly.
- Add .dockerignore to avoid sending large build contexts.
Maintenance
> Update Dockerfile to work with Next.js

- .gitignore
- website/.gitignore
Move all website gitignore settings to `website/.gitignore`
Meta.
> Move all website gitignore settings to website/.gitignore

- spacy/about.py
Set version of the `v4` branch to v4.0.0.dev0.
Maintenance
> Set version to v4.0.0.dev0

- website/pages/index.tsx
Update years in website landing page
Docs.
> Update years in website landing page

- README.md
> Update README for v3.5

- website/src/components/seo.js
Fixes broken social media preview images.
- updated link in meta tag to absolute URL
> Fix broken social media image

- website/src/components/copy.js
- website/src/widgets/project.js
Adds an `aria-label` to code copy component.
- Website frontend improvements
> Add missing label

- website/meta/universe.json
> Fix broken URL in docs

- azure-pipelines.yml
Add black formatting check to validation.
CI.
> CI: Add black formatting check to validation

- website/meta/site.json
Update binder version to v3.5. Merge following https://github.com/explosion/spacy-io-binder/pull/2
Docs.
> Update binder version to v3.5

- website/src/components/landing.js
- website/src/styles/code.module.sass
- website/src/styles/landing.module.sass
- Fixes two text color regressions in the docs
- some code blocks
- header on the front page
> Fix text color in docs

- website/pages/index.tsx
- Fixes missing image in docs frontpage
> Fix frontpage image

- azure-pipelines.yml
CI: Extend website excludes
CI.
> CI: Extend website excludes

- website/src/styles/aside.module.sass
- website/src/styles/quickstart.module.sass
- Fixes some remaining color problems introduced by #12178
- ~removes some dead code~
> Fix even more color problems

- website/docs/usage/v3-5.mdx
Explain how to change downstream code that call/use the `KnowledgeBase` directly.
docs fix
> Add KB breaking change to usage docs

- website/docs/api/cli.mdx
The `project assets` command has had an `--extra` flag for a while now, but it isn't in the docs. This adds it.
docs fix
> Add extra flag to assets docs

- spacy/language.py
- spacy/pipeline/trainable_pipe.pyx
- spacy/pipeline/transition_parser.pyx
- spacy/tests/test_language.py
- spacy/ty.py
- website/docs/api/dependencyparser.mdx
- website/docs/api/edittreelemmatizer.mdx
- website/docs/api/entityrecognizer.mdx
- website/docs/api/language.mdx
- website/docs/api/morphologizer.mdx
- website/docs/api/pipe.mdx
- website/docs/api/sentencerecognizer.mdx
- website/docs/api/tagger.mdx
This method is the distillation counterpart of `Language.update`.  It takes a teacher `Language` instance and distills the student pipes on the teacher pipes.
Feature
> Add `Language.distill`

- spacy/tests/test_cli_app.py
- spacy/tests/util.py
Depending on terminal settings, it looks like lines may be padded to the screen width so the comparison is too strict with only the command string replacement.
Tests.
> Normalize whitespace in evaluate CLI output test

- spacy/cli/init_config.py
- spacy/default_config_distillation.cfg
- spacy/language.py
- spacy/schemas.py
- spacy/tests/serialize/test_serialize_config.py
This change adds the configuration schema for distillation, as well as the default configuration and some tests. The schema will be used by the training loop and `distill` subcommand.
Enhancement
> Add the configuration schema for distillation

- spacy/language.py
In distillation we also modify the teacher docs (e.g. in tok2vec components), so we need to copy both the reference and predicted doc.
Problem caught by @shadeMe.
Bugfix
> Language.distill: copy both reference and predicted

- spacy/tests/test_cli.py
Removes remaining flaky assertions in `test_cli_find_threshold()` due to underlying models' behavior not being consistent across platforms. Related to https://github.com/explosion/spaCy/pull/12148.
> Remove flaky assertions in `test_cli_find_threshold()`

- .github/workflows/autoblack.yml
- azure-pipelines.yml
- requirements.txt
Use `black` version constraints from `requirements.txt`.
Does not yet handle pre-commit hooks.
Chore.
> Use black version constraints from requirements.txt

- website/docs/api/cli.mdx
Fixes a wrong negation in the docs for `spacy project pull`.
Docs fix.
> Remove wrong negation in `spacy project pull` docs 

- spacy/tokens/span.pyx
Use the same tuple in Span cmp and hash.
?
> Use the same tuple in Span cmp and hash

- requirements.txt
> Extend mypy to v1.0.x

- website/docs/usage/rule-based-matching.mdx
Fix wrong file name in docs for rule-based matcher. Resolves https://github.com/explosion/spaCy/issues/12259.
Docs fix.
> Fix wrong file name in docs for rule-based matcher

- spacy/cli/package.py
- spacy/util.py
Adjusts the return type of `registry.find` from `Callable` to `Dict[str, Optional[Union[str, int]]]` and code documentation so that it matches with `catalogue.registry.find`. 
bug fix
> Adjust return type of `registry.find`

- spacy/util.py
This changes `util.make_tempdir` to use `tempfile.TemporaryDirectory`. 
This function has been available for a long time, but there is one issue related to it. Git checkouts use read-only files, and the way that's handled on Windows is a little odd and can cause errors removing files normally. In Python 3.8, `tempfile.TemporaryDirectory`'s behavior was changed to handle that issue specifically, but on lower versions, there will be an error when attempting to delete the directory. 
This was previously discussed in https://github.com/explosion/spaCy/pull/12155#discussion_r1086466701. 
Behavior improvement?
> Use tempfile.TemporaryDirectory

- spacy/util.py
Add grc to langs with lexeme norms in `spacy-lookups-data`
?
> Add grc to langs with lexeme norms in spacy-lookups-data

- spacy/ml/tb_framework.pyx
- spacy/pipeline/transition_parser.pyx
- spacy/tests/parser/test_model.py
- spacy/tests/parser/test_ner.py
- spacy/tests/parser/test_parse.py
The code for distillation with an oracle cut size was not reimplemented after the parser refactor. We did not notice, because we did not have tests for this functionality. This change brings back the functionality and adds this to the parser tests.
Also add extra checks to `_parse_batch` to avoid segfaults that I encountered during implementation when feeding the function wrong inputs.
Enhancement or bugfix :)
> Reimplement distillation with oracle cut size

- spacy/tests/test_cli_app.py
- spacy/util.py
This is the same #12155, but based on the master branch.
The goal of this PR is to add tests to the projects functionality. The DVC command is deprecated and not covered. 
add tests
> Add tests for projects to master

- website/docs/usage/rule-based-matching.mdx
- website/docs/usage/v3-5.mdx
This reverts commit daedc45d050b15be8c5422aadff7b652439a562d.
The default length depends on the length of the pattern string and the original description was correct for these examples.
Docs.
> Revert "Fix FUZZY operator definition (#12318)"

- spacy/errors.py
Fix error message for displacy `auto_select_port`.
Bug fix.
> Fix error message for displacy auto_select_port

- website/docs/api/dependencymatcher.mdx
- website/docs/usage/rule-based-matching.mdx
Add new tags in docs for #12334.
Docs.
> Add new tags in docs for #12334

- website/docs/api/architectures.mdx
Update docs w.r.t. `spacy.CandidateBatchGenerator.v1` (missing in PR introducing the EL refactoring).
Docs update.
> Update docs w.r.t. `spacy.CandidateBatchGenerator.v1`

- spacy/tests/parser/test_ner.py
- spacy/tests/parser/test_parse.py
- spacy/tests/test_cli.py
Consistently use absolute imports in tests
Tests.
> Update to use absolute imports in tests

- website/package.json
Always run Python setup script for Jinja before starting dev mode.
- NPM Script
-
> Make sure to run Python setup before NPM dev mode

- README.md
- website/src/templates/index.js
Added links to the spaCy user survey in a bottom bar alert for the website and in the README. 
Enhancement, additional documentation
> Add links in website and readme for survey

- spacy/about.py
> Set version to v3.5.1

- spacy/tests/test_cli_app.py
Skip project clone tests if git is not available.
Tests.
> Skip project clone tests if git is not available

- spacy/tests/test_cli_app.py
Additional backport for v3.5.1.
?
> Skip project clone tests if git is not available (#12394)

- .github/workflows/tests.yml
Add GHA for CI tests
* Initially switch to `fail-fast: true` since each test job runs for a relatively long time and the linux instances run and therefore fail so much faster than the windows/macos instances.
CI
> Add GHA for CI tests

- .github/azure-steps.yml
- .github/workflows/tests.yml
- azure-pipelines.yml
Move universe validation to validate job.
CI.
> CI: Move universe validation to validate job

- .github/azure-steps.yml
- .github/workflows/tests.yml
Move CLI tests to ubuntu for speed
CI.
> CI: Move CLI tests to ubuntu for speed

- .github/workflows/tests.yml
Add all paths before excluding patterns for PRs. The default include was missed when switching from excludes to includes.
CI.
> CI: Add all paths before excluding patterns

- spacy/cli/find_threshold.py
- website/docs/api/cli.mdx
Fix `--verbose` definition for `spacy find-threshold`.
Bug fix, docs.
> Fix --verbose for spacy find-threshold

- .github/workflows/tests.yml
Switch PR tests back to paths-ignore but include changes to `.github` for all PRs rather than trying to figure out complicated includes+excludes.  Changes to `.github` are relatively rare and should not be a huge burden for the CI.
CI.
> CI: Switch PR back to paths-ignore

- .github/workflows/tests.yml
- .github/workflows/universe_validation.yml
Separate spacy universe validation into a separate workflow
CI.
> CI: Separate spacy universe validation into a separate workflow

- spacy/lang/sr/__init__.py
- spacy/lang/sr/punctuation.py
Update Serbian tokenization for UD Serbian SET.
`token_f` increases from 0.982 to 0.998.
Enhancement.
> Update Serbian tokenization for UD Serbian SET

- spacy/errors.py
- spacy/ml/models/multi_task.py
- spacy/tests/training/test_pretraining.py
Support floret for PretrainVectors
Enhancement.
> Support floret for PretrainVectors

- .github/workflows/explosionbot.yml
- .github/workflows/issue-manager.yml
- .github/workflows/lock.yml
- .github/workflows/spacy_universe_alert.yml
- .github/workflows/tests.yml
- .github/workflows/universe_validation.yml
Restrict github workflows to explosion.
Chore.
> Restrict github workflows to explosion

- spacy/displacy/__init__.py
- spacy/tests/test_displacy.py
- website/docs/api/top-level.mdx
Allow passing a Span to displacy.parse_deps. Resolves #12433.
Enhancement
> Allow passing a Span to displacy.parse_deps

- spacy/tests/pipeline/test_morphologizer.py
- spacy/tests/pipeline/test_tagger.py
Convert values to numpy for label smoothing tests.
Tests.
> Convert values to numpy for label smoothing tests

- spacy/pipeline/spancat.py
- spacy/tests/pipeline/test_spancat.py
Fix pickle for ngram suggester, required for multiprocessing with spawn.
Bug fix.
> Fix pickle for ngram suggester

- spacy/tokens/doc.pyx
Remove redundant `strings.add` for `Doc.char_span`.
?
> Remove redundant strings.add for Doc.char_span

- website/docs/api/top-level.mdx
Closes #12496 
Replace `progress_bar = "all_steps"` with `progress_bar = "eval"`, which is consistent with the default behavior for `spacy.ConsoleLogger.v1` and `spacy.ConsoleLogger.v2`.
> Fix invalid ConsoleLogger.v3 example config

- website/docs/api/top-level.mdx
- website/docs/usage/training.mdx
This `PR` adds a small section to the `usage/training` and `api/top-level` docs that mention that unpackaged models, trained with custom code, do not internally contain custom code but need to be imported into the script before loading in the models.
This `PR` is a duplicate of this https://github.com/explosion/spaCy/pull/12369 , but with the merge branch set to `master`
Documentation
> Add more information to custom code docs

- website/docs/usage/rule-based-matching.mdx
The executable example code was incorrectly ignoring `PERSON` entities that didn't have a preceding title. This PR fixes that oversight.
Resolves #12489. 
Docs
> `Docs`: Fix rule-based matching example that expands named entities

- spacy/about.py
> Set version to v3.5.2

- website/meta/universe.json
ScispaCy fits within biomedical domain. Consider adding this category.
Change to documentation
> Add category to spaCy project

- spacy/matcher/dependencymatcher.pyx
In some cases, not children at both the right and left side are relevant to the corresponding REL_OP. This PR limits the iteration range only to children on the required side.
Enhancement on the parsing speed of some REL_OPs
> perf(REL_OP): Replace token.children with token.rights or token.lefts

- website/src/templates/index.js
Remove user survey link
Remove user survey link in header and replace with 3.5 release, as it was before. 
Website update
> Remove user survey link

- spacy/language.py
- spacy/schemas.py
- spacy/tests/training/test_loop.py
- spacy/training/initialize.py
- spacy/training/loop.py
- spacy/util.py
- website/docs/api/language.mdx
This change adds the distillation loop. The loop is based on the training loop, but adjusted to do distillation. The change also introduces a new `init_nlp_student` function used to initialize the student pipe. Both are tested through a test that first trains a teacher model using the `train` loop and then distills a student using the `distill` loop.
Feature.
> Add distillation loop

- website/meta/universe.json
Add the spacy-wasm project to the Universe section. 
Enhancement
> Add spacy-wasm to universe

- spacy/lang/sr/lex_attrs.py
- spacy/lang/sr/tokenizer_exceptions.py
- spacy/tests/lang/sr/test_exceptions.py
- spacy/tests/lang/sr/test_lex_attrs.py
Use Latin normalization for Serbian `NORM`, `PREFIX`, and `SUFFIX`.
Enhancement.
> Use Latin normalization for Serbian attrs

- website/meta/universe.json
Add resource to spaCy Universe via universe.json, spec. trained pipelines (as well as floret vectors) for Latin.
New resource link/info
> Add LatinCy models to universe.json

- website/meta/universe.json
Add Parsigs project to the Universe section.
Enhancement
> parsigs universe

- website/docs/api/cli.mdx
Removed arguments which is no longer valid
> Removed invalid argument

- requirements.txt
- setup.cfg
This PR relaxes the constraints on the typer dependency, allowing user to
use a broader range of versions.
> build: bump typer version to accept >=0.3<0.10

- website/docs/usage/visualizers.mdx
This PR adds some documentation on displacy's `offset_x` option.
> docs: add comment on `offset_x` argument

- website/meta/languages.json
Add Malay to website languages
Docs.
> Add Malay to website languages

- .github/workflows/tests.yml
While the typing_extensions/pydantic `Literal` bugs are being sorted out, disable fail-fast so the rest of the CI is available for development purposes.
CI.
> CI: Disable fail-fast

- .github/workflows/tests.yml
This reverts commit 1f088cbf4ae5811ed4fbbd97b298db9f81aa4252.
CI.
> Revert "CI: Disable fail-fast (#12658)"

- .github/workflows/tests.yml
- spacy/tests/serialize/test_resource_warning.py
Address numpy 1.25 deprecations in test suite.
Tests.
> Address numpy 1.25 deprecations in test suite

- website/meta/universe.json
Hey all--
After [soliciting feedback](https://github.com/explosion/spaCy/discussions/12475) and incorporating spaCy support in a package I maintain, [vetiver](https://vetiver.rstudio.com/), I would love to have this project advertised with other spaCy tools!
Add new project (vetiver) to list of projects in spacy universe
Addition to website
> [DOCS] add vetiver to spacy universe

- spacy/language.py
- spacy/ty.py
This minor PR fixes the `InitializableComponent` type hint.
Since the `@runtime_checkable` decorator checks the presence of methods and not their signature, this change is non-breaking.
This is a (minor) fix.
> fix: `InitializableComponent` type hints

- spacy/about.py
Set version v3.6.0.dev1
Chore.
> Set version v3.6.0.dev1

- .github/workflows/tests.yml
CI: add `isort --check` to validate job.
Maintenance
> CI: add `isort --check` to validate job

- spacy/about.py
- spacy/tests/test_cli.py
> Set version to v3.6.0

- spacy/about.py
Set the `v4` branch version to `v4.0.0.dev1`.
> Set version to v4.0.0.dev1

- spacy/pipeline/span_finder.py
- spacy/tests/pipeline/test_span_finder.py
Use `spans_` prefix for default span finder scores.
The `scores` keys are intended to align with the doc/token attributes, not the component names, so that the focus on the final scores is on the doc annotation rather than which component produced the annotation.
Bug fix?
> Use spans_ prefix for default span finder scores

- website/docs/usage/v3-6.mdx
- website/meta/languages.json
- website/meta/sidebars.json
- website/src/templates/index.js
Website updates for for v3.6.0.
Docs.
> Docs for v3.6.0

- .github/workflows/tests.yml
- spacy/tests/test_cli.py
Reenable compat+models tests for v3.6.0.
Tests.
> Reenable compat+models tests for v3.6.0

- spacy/about.py
> Set version to `3.7.0.dev0`

- website/docs/api/spanfinder.mdx
Update `max_length` default for config in span finder docs.
Docs.
> Update max_length default in span finder docs

- website/meta/site.json
Update website binder version to v3.6
Docs.
> Update website binder version to v3.6

- Makefile
- website/docs/usage/index.mdx
Update pex Makefile defaults
- switch to python 3.8
- only install spacy-lookups-data for extra packages
?
> Update pex Makefile defaults

- spacy/tests/matcher/test_pattern_validation.py
Update matcher pattern validation tests
- parametrize over individual token patterns (as originally intended, as far as I can tell)
- add a test for lowercase `in` in patterns
Tests.
> Update matcher pattern validation tests

- spacy/language.py
> Clean up unused code in Language

- README.md
* Update most recent release
* Switch from azure to GHA CI tests badge
* Remove link to survey
* Format
Docs.
> Update README for v3.6, etc.

- website/docs/api/spancategorizer.mdx
As discussed in #12858.
The `threshold` argument is only valid for the multi-class SpanCat component.
Doc fix
> `SpanCat`: Remove invalid `threshold` config argument from example

- website/docs/api/spanruler.mdx
There was a missing " in one of the example code snippets
docs fix
> Small docs fix

- spacy/about.py
> Set version to v3.6.1

- website/docs/api/large-language-models.mdx
Update incorrect example config for LLM example (multi-line dict in .cfg can't be parsed).
Doc fix.
> Update incorrect LLM example config in docs

- requirements.txt
- setup.cfg
Extend to weasel v0.2.
Enhancement.
> Extend to weasel v0.2

- spacy/lang/tr/examples.py
Add: example sentences to improve the Turkish model. Let's get the tr_web_core_sm out in the the world yaa
> Update examples.py with Turkish sentences

- website/docs/api/top-level.mdx
- website/docs/usage/processing-pipelines.mdx
Docs: clarify abstract `spacy.load` examples.
Docs.
> Docs: clarify abstract spacy.load examples

- requirements.txt
- setup.cfg
- spacy/tests/test_cli.py
> Extend to weasel v0.3

- website/docs/api/spancategorizer.mdx
docs: fix `ngram_range_suggester` `max_size` description.
Docs
> docs: fix ngram_range_suggester max_size description

- website/docs/usage/large-language-models.mdx
The model factory was misspelled.
docs fix
> Fix LLM usage example

- website/docs/api/large-language-models.mdx
doc PR for https://github.com/explosion/spacy-llm/pull/236
docs update
> Document v2 OpenAI models

- website/docs/api/large-language-models.mdx
- website/docs/usage/large-language-models.mdx
Don't squash merge 
Consolidate spacy-llm docs for v0.5.0
branch sync
> Consolidate spacy-llm docs for v0.5.0

- website/docs/api/large-language-models.mdx
Further fixes for `spacy-llm` docs.
docs update
> Few spacy-llm doc fixes

- spacy/tests/test_cli_app.py
`weasel` (using `cloudpathlib`) does not currently support remote paths for python 3.12.
Tests.
> Skip project remotes test for python 3.12

- website/docs/usage/linguistic-features.mdx
If I understand the intended use correctly, this function registry should refer to the example `BertTokenizer` implementation from the section above it.
docs fix
> Fix in BertTokenizer docs

- website/docs/api/large-language-models.mdx
- website/docs/usage/linguistic-features.mdx
Synch `llm_main` with `master`.
Chore.
> Synch `llm_main` with `master`

- website/docs/api/large-language-models.mdx
- website/docs/usage/linguistic-features.mdx
Synch `llm_develop` with `llm_main`.
Chore.
> Synch `llm_develop` with `llm_main`

- spacy/lang/es/lemmatizer.py
> Fix typo in lemmatizer.py

- website/docs/api/cli.mdx
Follow-up to #12981 to add the new version info to the CLI docs.
Docs.
> Docs: add new tag for evaluate CLI --spans-keys

- .github/workflows/tests.yml
- README.md
- build-constraints.txt
- requirements.txt
- setup.cfg
- website/docs/usage/index.mdx
Drop support for python 3.6.
?
> Drop support for python 3.6

- website/docs/usage/rule-based-matching.mdx
The current version of `emojipedia` appears to have a regression that breaks our example code that fetches the descriptions of emojis. This PR replaces the `emojipedia` library with `emoji` that is more reliable.
Fixes #13010. Thanks to @igormorgado for identifying the issue and suggesting the fix!
Docs
> Update emoji library in rule-based matcher example

- website/meta/universe.json
Adding a model for processing noisy Romanian legal documents.
Created a new entry in the spacy universe json to add the rolegal package. The model is trained using floret embeddings and predicts legal entity types.
Extending the Universe page.
> Adding rolegal model to the spaCy universe

- spacy/about.py
> Set version to v3.7.0

- .github/workflows/tests.yml
- spacy/tests/test_cli.py
Set version to v3.7.0 and reenable model-related tests.
> Reenable model tests for v3.7.0

- README.md
- website/docs/usage/v3-7.mdx
- website/meta/sidebars.json
- website/src/templates/index.js
> Docs for v3.7.0

- website/meta/site.json
Update binder version to v3.7.
Docs.
> Update binder version to v3.7

- spacy/about.py
> Set version to v3.7.1

- website/docs/api/large-language-models.mdx
Add gpt-3.5-turbo-instruct to list of supported OpenAI models.
Docs update.
> Add `gpt-3.5-turbo-instruct` to list of supported OpenAI models

- requirements.txt
- setup.cfg
- spacy/cli/_util.py
- website/docs/api/cli.mdx
- website/docs/usage/projects.mdx
Remove pathy dependency, update docs for cloudpathlib in Weasel.
Docs, ?
> Remove pathy dependency, update docs for cloudpathlib in Weasel

- website/docs/api/large-language-models.mdx
- website/docs/usage/large-language-models.mdx
Add info on PaLM support in `spacy-llm`. See https://github.com/explosion/spacy-llm/pull/305.
> Add info on PaLM support in `spacy-llm`

- website/docs/api/large-language-models.mdx
- website/docs/usage/large-language-models.mdx
Mention Mistral in `spacy-llm` docs.
Docs update.
> Mention Mistral in `spacy-llm` docs

- website/docs/api/large-language-models.mdx
- website/docs/usage/large-language-models.mdx
- website/docs/usage/training.mdx
Sync `master` with `docs/llm_main`.
Chore/docs.
> Sync `master` with `docs/llm_main`

- website/docs/api/spancategorizer.mdx
Fix SpanCat typo in docs.
Doc fix.
> Fix SpanCat typo in docs

- website/docs/usage/linguistic-features.mdx
Fixes #13001
- Clarify that model is a custom trained one
- Add link to example project for more extensive example code
- prettier
docs update
> Clarify EL example in docs

- .github/workflows/tests.yml
Switch to stable python 3.12 and limit 3.11 runs.
CI.
> CI: Switch to stable python 3.12 and limit 3.11 runs

- licenses/3rd_party_licenses.txt
- spacy/scorer.py
- spacy/tokens/doc.pyi
- Replace `np.trapz` with vendored `trapezoid` from scipy
- Replace `np.float_` with `np.float64`
Chore.
> Update for numpy 2.0 deprecations

- spacy/tests/test_cli_app.py
Unskip python 3.12 remote tests since this is now supported in weasel/cloudpathlib.
Tests.
> Unskip python 3.12 remote tests

- spacy/lang/en/lex_attrs.py
- Adds extra lexical attributes
> feat: add extra lexical attributes

- website/docs/api/large-language-models.mdx
`spacy-llm`: mention custom endpoints for REST models. See https://github.com/explosion/spacy-llm/pull/390.
Docs update.
> `spacy-llm`: mention custom endpoints for REST models

- spacy/tests/test_misc.py
macOS now uses port 5000 for the AirPlay receiver functionality, so this test will always fail on a macOS desktop (unless AirPlay receiver functionality is disabled like in CI).
Bugfix
> test_find_available_port: use port 5001

- spacy/pipeline/_parser_internals/stateclass.pyx
> Fix typo in method name

- requirements.txt
- setup.cfg
This release is compatible with the parser refactor backout.
Maintenance
> Update `spacy-legacy` dependency to 4.0.0.dev1

- CONTRIBUTING.md
Quick fix to update mention of the universe.
docs update
> update universe description

- spacy/about.py
Increase version number to 3.7.3 in preparation for the release.
Maintenance.
> Set version to 3.7.3

- .github/workflows/gputests.yml
- .github/workflows/slowtests.yml
- CONTRIBUTING.md
- spacy/cli/benchmark_speed.py
- spacy/language.py
- spacy/tests/serialize/test_serialize_extension_attrs.py
- website/docs/api/cli.mdx
- website/docs/api/large-language-models.mdx
- website/docs/api/vocab.mdx
@svlandeg copied from your branch, still no failures after four rebuilds.
(If this indeed fixes the issue, we should cherry-pick 2d4067d021323e91ab80d40019f8e9792e2c8d36 in master.)
Maintenance.
> Sync main with latests changes from master (v3)

- .github/workflows/gputests.yml
- .github/workflows/slowtests.yml
- CONTRIBUTING.md
- spacy/cli/benchmark_speed.py
- spacy/tests/serialize/test_serialize_extension_attrs.py
- website/docs/api/cli.mdx
- website/docs/api/large-language-models.mdx
- website/docs/api/vocab.mdx
Don't squash merge
Sync main with latests changes from master
branch maintenance
> Sync main with latests changes from master (v2)

- website/docs/usage/models.mdx
See #13293.
Documentation update.
> Update example that shows model in requirements

- spacy/about.py
Set version to 3.7.4.
Maintenance.
> Set version to 3.7.4

- website/src/styles/code.module.sass
The filename / title for code listings scrolls along with the content, which may be undesirable. This PR makes the filename sticky. Tested on my machine.
Style enhancement
> Update code.module.sass to make code title sticky

- website/docs/api/architectures.mdx
- website/docs/api/curatedtransformer.mdx
- Update model constructors to v2 and add `dtype` argument.
- Update to `PyTorchCheckpointLoader` to `v2`.
- Add `transformer_discriminative.v1`.
Docs
> Update `spacy-curated-transformers` docs for spaCy 4

- .github/workflows/tests.yml
- extra/DEVELOPER_DOCS/Satellite Packages.md
- setup.cfg
- spacy/tests/package/test_requirements.py
- website/docs/usage/index.mdx
Account for merging of `thinc-apple-ops` into `thinc`.
Maintenance
> Remove `apple` from extras

- website/docs/api/pipe.mdx
Document `TrainablePipe.save_activations`
Documentation.
> Document `TrainablePipe.save_activations`

- LICENSE
Update LICENSE to include 2024
maintenance
> Update LICENSE to include 2024

- spacy/about.py
Set version to 3.7.5
maintenance
> Set version to 3.7.5

- spacy/lang/gd/__init__.py
- spacy/lang/gd/stop_words.py
- spacy/lang/gd/tokenizer_exceptions.py
Implemented a foundational Scottish Gaelic (gd) language option with tokenizer_exceptions and stop_words files.
> Add Scottish Gaelic Language

- spacy/lang/hr/lemma_lookup_license.txt
Fix misspelling in one of the license files.
Fix text in one of the license files.
> Fix misspelling (#13631) [ci skip]

- website/docs/usage/rule-based-matching.mdx
> docs: update rule-based-matching.mdx (#13665) [ci skip]

- CONTRIBUTING.md
- README.md
- website/docs/usage/processing-pipelines.mdx
- website/docs/usage/spacy-101.mdx
- website/meta/site.json
Change Twitter to X, in both the Connect area and the Contribution Guidelines.
> Change Twitter to X

- website/docs/usage/embeddings-transformers.mdx
Update trf_data examples info in Runtime usage
> Update embeddings-transformers.mdx, update trf_data examples info
